# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_jeeeztg2, v_1_a1ggonzy, v_2_ks264osx, v_3_wdacok75, v_4_xvv610ly, v_5_5sef8qyt):
        v_6_s4x7pdfl = torch.zeros((2, 1), dtype=torch.float32, device="cpu")
        v_7_1bu38c7a = (v_5_5sef8qyt if v_5_5sef8qyt.ndim >= 4 else torch.unsqueeze(v_5_5sef8qyt, 0))
        v_8_7l6jr5sy = (v_6_s4x7pdfl if v_6_s4x7pdfl.ndim >= 4 else torch.unsqueeze(v_6_s4x7pdfl, 0))
        v_9_01x8ddqv = (v_8_7l6jr5sy if v_8_7l6jr5sy.ndim >= 4 else torch.unsqueeze(v_8_7l6jr5sy, 0))
        v_10_rq54p1cg = torch.zeros((1, 3, 2, 1), dtype=torch.float32, device="cpu")
        v_7_yr3zydc8 = F.conv2d(v_7_1bu38c7a, torch.zeros(max(v_10_rq54p1cg.shape[0], 1), v_7_1bu38c7a.shape[1], min(v_10_rq54p1cg.shape[2], v_7_1bu38c7a.shape[2]), min(v_10_rq54p1cg.shape[3], v_7_1bu38c7a.shape[3])), stride=1, padding=0, dilation=1, groups=1)
        v_8_zgob6adt = torch.clamp(v_6_s4x7pdfl, min=-0.94, max=1.24)
        v_9_7zfcnq9o = torch.tanh(v_6_s4x7pdfl.float())
        v_10_k663m8vg = torch.log2(v_6_s4x7pdfl.float())
        v_11_anj2xry5 = torch.minimum(v_6_s4x7pdfl.float(), v_4_xvv610ly.float())
        v_12_f87ige14 = torch.neg(v_10_k663m8vg)
        v_13_tm1gl9zh = torch.argmin(v_10_k663m8vg, dim=-1).float()
        v_14_472f3yvg = torch.triu(v_12_f87ige14)
        v_15_dpoviois = F.layer_norm(v_12_f87ige14.float(), (v_12_f87ige14.shape[-1],))
        v_16_mmt9zwsw = torch.sum(v_14_472f3yvg, dim=-1, keepdim=False)
        v_17_jwyfo3ub = F.selu(v_14_472f3yvg.float())
        v_18_xad6aeyi = F.avg_pool2d(v_7_yr3zydc8, kernel_size=1, stride=1, padding=0)
        v_19_5frpx7ey = torch.max(v_14_472f3yvg, dim=-1, keepdim=False).values
        v_20_h4iim865 = F.max_pool2d(v_7_yr3zydc8, kernel_size=1, stride=1, padding=0)
        v_21_m5f2dd01 = torch.ones((4, 6, 3), dtype=torch.float32, device="cpu")
        v_22_b7k5bfx0 = torch.argmin(v_14_472f3yvg, dim=-1).float()
        v_23_xo5yx98z = torch.arange(0, 247, dtype=torch.float32, device="cpu")
        v_24_9xylf05s = torch.max(v_14_472f3yvg, dim=-1, keepdim=False).values
        v_25_krbk9nrg = torch.tile(v_23_xo5yx98z, [1] * 1)
        v_26_tw3rwe0g = v_8_zgob6adt[:max(1, v_8_zgob6adt.shape[0]//2)]
        v_27_1905lpxl = (v_25_krbk9nrg if v_25_krbk9nrg.ndim >= 4 else torch.unsqueeze(v_25_krbk9nrg, 0))
        v_28_pyax9g1w = torch.abs(v_26_tw3rwe0g)
        v_29_hjr6aggi = torch.rsqrt(v_27_1905lpxl.float())
        v_30_qbvr83gl = F.softmax(v_28_pyax9g1w.float(), dim=-1)
        v_31_vaqxjjtl = torch.ones((1, 1, 5, 3), dtype=torch.float32, device="cpu")
        v_32_olsqa7sc = torch.ceil(v_28_pyax9g1w)
        v_33_qv9qw79m = torch.round(v_28_pyax9g1w)
        v_34_42v3zqx4 = torch.maximum(v_28_pyax9g1w.float(), v_14_472f3yvg.float())
        v_35_7ogvcpfj = torch.mul(v_33_qv9qw79m.float(), v_9_7zfcnq9o.float())
        v_36_b528rof4 = torch.neg(v_33_qv9qw79m)
        v_37_sayzratx = torch.add(v_35_7ogvcpfj.float(), v_30_qbvr83gl.float())
        v_38_mrp9ng10 = torch.reciprocal(v_35_7ogvcpfj.float())
        v_39_ipsfrzvb = F.interpolate(v_20_h4iim865, scale_factor=2.0, mode='nearest')
        v_40_wzxvb7b0 = F.interpolate(v_31_vaqxjjtl, scale_factor=2.0, mode='nearest')
        v_41_8dt12b6p = torch.arange(0, 121, dtype=torch.float32, device="cpu")
        v_42_egz3zn2x = torch.tril(v_39_ipsfrzvb)
        v_43_ezvi7lhh = F.leaky_relu(v_41_8dt12b6p.float(), negative_slope=0.06)
        v_44_6baymwi3 = F.max_pool2d(v_7_yr3zydc8, kernel_size=1, stride=1, padding=0)
        v_45_4ir37jrg = torch.cumprod(v_41_8dt12b6p.float(), dim=-1)
        v_46_b2hliptq = F.batch_norm(v_21_m5f2dd01.float(), running_mean=torch.zeros(v_21_m5f2dd01.shape[1]), running_var=torch.ones(v_21_m5f2dd01.shape[1]), training=False)
        v_47_hiw2u21m = torch.mean(v_45_4ir37jrg, dim=-1, keepdim=False, dtype=torch.float32)
        v_48_cjdn1xgk = torch.clamp(v_45_4ir37jrg, min=-0.39, max=2.01)
        v_49_fdv18bhj = torch.sigmoid(v_47_hiw2u21m.float())
        v_50_wrbsuie7 = torch.sign(v_47_hiw2u21m)
        v_51_rfe1r37h = torch.full((6, 1), 0.0, dtype=torch.float32, device="cpu")
        v_52_10vl1pdl = torch.tile(v_5_5sef8qyt, [1] * 3)
        v_53_4yyhomdp = torch.cumprod(v_49_fdv18bhj.float(), dim=-1)
        v_54_vl7mhoe7 = F.interpolate(v_3_wdacok75, scale_factor=2.0, mode='nearest')
        v_55_vd9qky2e = torch.reciprocal(v_53_4yyhomdp.float())
        v_56_0l1sl4xr = F.selu(v_54_vl7mhoe7.float())
        v_57_l8l7fd2f = torch.round(v_55_vd9qky2e)
        v_58_goqwdlty = torch.abs(v_56_0l1sl4xr)
        v_59_92x0korp = torch.transpose(v_56_0l1sl4xr, 2, 3)
        v_60_ean1t5br = torch.minimum(v_56_0l1sl4xr.float(), v_26_tw3rwe0g.float())
        v_61_l3xofds6 = torch.triu(v_56_0l1sl4xr)
        v_62_ejto03kk = torch.zeros((6, 3, 2, 1), dtype=torch.float32, device="cpu")
        v_63_bgmv409m = F.max_pool2d(v_56_0l1sl4xr, kernel_size=1, stride=1, padding=0)
        v_64_p4lrys6i = F.selu(v_56_0l1sl4xr.float())
        v_65_vk3dwprz = torch.exp(v_63_bgmv409m.float())
        v_66_dj27n1qj = torch.log(v_63_bgmv409m.float())
        v_67_2ad55k1g = F.silu(v_63_bgmv409m.float())
        v_68_tc021vy5 = F.log_softmax(v_63_bgmv409m.float(), dim=-1)
        v_69_sin8gqg7 = torch.triu(v_67_2ad55k1g)
        v_70_3e6cgapn = torch.pow(v_67_2ad55k1g.float(), v_50_wrbsuie7.float())
        v_71_7fg9iwvk = F.avg_pool2d(v_69_sin8gqg7, kernel_size=2, stride=1, padding=0)
        v_72_ijsk4fn8 = F.gelu(v_69_sin8gqg7.float())
        v_73_lhfbc5xy = torch.ceil(v_71_7fg9iwvk)
        return (v_0_jeeeztg2, v_1_a1ggonzy, v_2_ks264osx, v_11_anj2xry5, v_13_tm1gl9zh, v_15_dpoviois, v_16_mmt9zwsw, v_17_jwyfo3ub, v_18_xad6aeyi, v_19_5frpx7ey, v_22_b7k5bfx0, v_24_9xylf05s, v_29_hjr6aggi, v_32_olsqa7sc, v_34_42v3zqx4, v_36_b528rof4, v_37_sayzratx, v_38_mrp9ng10, v_40_wzxvb7b0, v_42_egz3zn2x, v_43_ezvi7lhh, v_44_6baymwi3, v_46_b2hliptq, v_48_cjdn1xgk, v_51_rfe1r37h, v_52_10vl1pdl, v_57_l8l7fd2f, v_58_goqwdlty, v_59_92x0korp, v_60_ean1t5br, v_61_l3xofds6, v_62_ejto03kk, v_64_p4lrys6i, v_65_vk3dwprz, v_66_dj27n1qj, v_68_tc021vy5, v_70_3e6cgapn, v_72_ijsk4fn8, v_73_lhfbc5xy)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_jeeeztg2 = torch.randn(5, 5, 1, dtype=torch.float32, device="cpu")
v_1_a1ggonzy = torch.randn(4, 6, 5, 1, dtype=torch.float32, device="cpu")
v_2_ks264osx = torch.randn(1, 2, dtype=torch.float32, device="cpu")
v_3_wdacok75 = torch.randn(1, 6, 5, 6, dtype=torch.float32, device="cpu")
v_4_xvv610ly = torch.randn(5, 2, 5, dtype=torch.float32, device="cpu")
v_5_5sef8qyt = torch.randn(3, 2, 3, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_jeeeztg2, v_1_a1ggonzy, v_2_ks264osx, v_3_wdacok75, v_4_xvv610ly, v_5_5sef8qyt)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_jeeeztg2, v_1_a1ggonzy, v_2_ks264osx, v_3_wdacok75, v_4_xvv610ly, v_5_5sef8qyt)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise, cast to float for allclose compatibility
    all_match = all(torch.allclose(r.float(), c.float(), atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output.float(), cmp_output.float(), atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
