# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_b31ze8dc, v_1_r5pvt2dx, v_2_7yydmfsp, v_3_voorek3s, v_4_o4f5vc1k, v_5_rem89yxv, v_6_0uqciv2h, v_7_21vjhxyt, v_8_2g4liqr4, v_9_atc8p2lw, v_10_1sng2192, v_11_s2lgpodq):
        v_12_n37w9r7h = torch.cumsum(v_11_s2lgpodq, dim=-1, dtype=torch.float32)
        v_13_hmn7f4ue = F.relu(v_11_s2lgpodq)
        v_14_eck89b55 = torch.full((2, 6), 0.0, dtype=torch.float32, device="cpu")
        v_15_of6y2fbm = torch.log(v_12_n37w9r7h.float())
        v_16_11th95p9 = torch.mul(v_12_n37w9r7h.float(), v_13_hmn7f4ue.float())
        v_17_oc4ayqfp = torch.arange(0, 211, dtype=torch.float32, device="cpu")
        v_18_3n6cqzn9 = F.interpolate(v_15_of6y2fbm, scale_factor=2.0, mode='nearest')
        v_19_i175i8s9 = torch.sign(v_15_of6y2fbm)
        v_20_wrrul89b = F.log_softmax(v_15_of6y2fbm.float(), dim=-1)
        v_21_zm56hpsl = torch.add(v_15_of6y2fbm.float(), v_20_wrrul89b.float())
        v_22_5n2mnsj9 = torch.full((1, 1, 1, 2), 0.0, dtype=torch.float32, device="cpu")
        v_23_i208jz7n = F.conv2d(v_20_wrrul89b, torch.zeros(max(v_22_5n2mnsj9.shape[0], 1), v_20_wrrul89b.shape[1], min(v_22_5n2mnsj9.shape[2], v_20_wrrul89b.shape[2]), min(v_22_5n2mnsj9.shape[3], v_20_wrrul89b.shape[3])), stride=1, padding=0, dilation=1, groups=1)
        v_24_wdrajv4h = F.mish(v_20_wrrul89b.float())
        v_25_knogrqtj = torch.max(v_23_i208jz7n, dim=-1, keepdim=False).values
        v_26_k7ll9bef = torch.round(v_24_wdrajv4h)
        v_27_6txncplh = torch.cumprod(v_24_wdrajv4h.float(), dim=-1, dtype=torch.float32)
        v_28_dy1hkh6l = torch.tile(v_24_wdrajv4h, [1] * 4)
        v_29_z9aaahc4 = torch.div(v_24_wdrajv4h.float(), v_28_dy1hkh6l.float())
        v_30_twjubytr = torch.zeros((4, 2, 4, 5), dtype=torch.float32, device="cpu")
        v_31_z5nqmph8 = torch.reciprocal(v_24_wdrajv4h.float())
        v_32_pko0wco6 = torch.zeros((1), dtype=torch.float32, device="cpu")
        v_33_c8kthlgr = torch.pow(v_30_twjubytr.float(), v_32_pko0wco6.float())
        v_34_fag1kukt = torch.log2(v_32_pko0wco6.float())
        v_35_d0iiu328 = torch.reciprocal(v_32_pko0wco6.float())
        v_36_xx7o7z8b = torch.mean(v_32_pko0wco6.float(), dim=-1, keepdim=False)
        v_37_agtemq1u = torch.reciprocal(v_32_pko0wco6.float())
        v_38_hg14xz6z = torch.argmax(v_32_pko0wco6, dim=-1).float()
        v_39_asxcl1rq = v_10_1sng2192[:max(1, v_10_1sng2192.shape[0]//2)]
        v_40_3z874jvi = torch.transpose(v_39_asxcl1rq, 2, 3)
        v_41_1p8kxjok = torch.tile(v_3_voorek3s, [1] * 4)
        v_42_jmwjfi9k = torch.sign(v_38_hg14xz6z)
        v_43_knn7lj3s = F.gelu(v_38_hg14xz6z.float())
        v_44_a9833b86 = torch.exp(v_38_hg14xz6z.float())
        v_45_4fmy0k0d = torch.sub(v_43_knn7lj3s.float(), v_14_eck89b55.float())
        v_46_umx11gsi = torch.sqrt(v_44_a9833b86.float())
        v_47_9hwsiq73 = torch.pow(v_44_a9833b86.float(), v_5_rem89yxv.float())
        v_48_9v8ukohs = torch.cumsum(v_46_umx11gsi, dim=-1)
        v_49_heyr04je = torch.mul(v_46_umx11gsi.float(), v_48_9v8ukohs.float())
        v_50_i0n9enk1 = torch.ones((4, 6), dtype=torch.float32, device="cpu")
        v_51_oydl0u8g = F.log_softmax(v_49_heyr04je.float(), dim=-1)
        v_52_8mf6kxng = torch.sqrt(v_50_i0n9enk1.float())
        v_53_xttld7z5 = torch.round(v_50_i0n9enk1)
        v_54_3pbviqb3 = torch.gather(v_50_i0n9enk1, 0, torch.zeros([1]*v_50_i0n9enk1.ndim, dtype=torch.int64, device=v_50_i0n9enk1.device))
        v_55_mh5c6aoc = torch.full((3, 3), 0.0, dtype=torch.float32, device="cpu")
        v_56_niz8iv46 = torch.argmax(v_50_i0n9enk1, dim=-1).float()
        v_57_v6j7agvr = torch.floor(v_50_i0n9enk1)
        v_58_5941l2bn = F.log_softmax(v_50_i0n9enk1.float(), dim=-1)
        v_59_5jmc9a5a = torch.triu(v_50_i0n9enk1)
        v_60_1vcl6iny = F.relu(v_50_i0n9enk1)
        v_61_fjce0mep = torch.gather(v_59_5jmc9a5a, 0, torch.zeros([1]*v_59_5jmc9a5a.ndim, dtype=torch.int64, device=v_59_5jmc9a5a.device))
        v_62_1ewu1af5 = F.silu(v_59_5jmc9a5a.float())
        v_63_ulghd16d = F.silu(v_59_5jmc9a5a.float())
        v_64_y24203u0 = torch.minimum(v_62_1ewu1af5.float(), v_21_zm56hpsl.float())
        v_65_mw3lhrup = torch.min(v_62_1ewu1af5, dim=-1, keepdim=False).values
        v_66_njy5miol = F.mish(v_64_y24203u0.float())
        v_67_ldhosgaq = F.silu(v_64_y24203u0.float())
        v_68_dx5a13uz = torch.reciprocal(v_66_njy5miol.float())
        v_69_u053b3um = torch.cumprod(v_66_njy5miol.float(), dim=-1)
        v_70_lpl740y7 = F.mish(v_66_njy5miol.float())
        v_71_w9q5adc7 = F.interpolate(v_66_njy5miol, scale_factor=2.0, mode='nearest')
        v_72_yofvqwob = torch.floor(v_66_njy5miol)
        v_73_4qy0t37a = F.log_softmax(v_66_njy5miol.float(), dim=-1)
        v_74_9qvihlth = F.mish(v_72_yofvqwob.float())
        v_75_bjblhoqd = torch.ceil(v_72_yofvqwob)
        v_76_svzosqdf = torch.zeros((4, 4, 2), dtype=torch.float32, device="cpu")
        v_77_89a1emq1 = F.mish(v_72_yofvqwob.float())
        v_78_0t8unh4x = F.elu(v_76_svzosqdf.float(), alpha=0.9)
        v_79_l3cx5eah = torch.tile(v_76_svzosqdf, [1] * 3)
        return (v_0_b31ze8dc, v_1_r5pvt2dx, v_2_7yydmfsp, v_4_o4f5vc1k, v_6_0uqciv2h, v_7_21vjhxyt, v_8_2g4liqr4, v_9_atc8p2lw, v_16_11th95p9, v_17_oc4ayqfp, v_18_3n6cqzn9, v_19_i175i8s9, v_25_knogrqtj, v_26_k7ll9bef, v_27_6txncplh, v_29_z9aaahc4, v_31_z5nqmph8, v_33_c8kthlgr, v_34_fag1kukt, v_35_d0iiu328, v_36_xx7o7z8b, v_37_agtemq1u, v_40_3z874jvi, v_41_1p8kxjok, v_42_jmwjfi9k, v_45_4fmy0k0d, v_47_9hwsiq73, v_51_oydl0u8g, v_52_8mf6kxng, v_53_xttld7z5, v_54_3pbviqb3, v_55_mh5c6aoc, v_56_niz8iv46, v_57_v6j7agvr, v_58_5941l2bn, v_60_1vcl6iny, v_61_fjce0mep, v_63_ulghd16d, v_65_mw3lhrup, v_67_ldhosgaq, v_68_dx5a13uz, v_69_u053b3um, v_70_lpl740y7, v_71_w9q5adc7, v_73_4qy0t37a, v_74_9qvihlth, v_75_bjblhoqd, v_77_89a1emq1, v_78_0t8unh4x, v_79_l3cx5eah)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_b31ze8dc = torch.randn(1, 6, 6, 4, dtype=torch.float32, device="cpu")
v_1_r5pvt2dx = torch.randn(4, 4, dtype=torch.float32, device="cpu")
v_2_7yydmfsp = torch.randn(1, 5, 1, dtype=torch.float32, device="cpu")
v_3_voorek3s = torch.randn(3, 2, 2, 3, dtype=torch.float32, device="cpu")
v_4_o4f5vc1k = torch.randn(4, 4, dtype=torch.float32, device="cpu")
v_5_rem89yxv = torch.randn(2, 6, dtype=torch.float32, device="cpu")
v_6_0uqciv2h = torch.randn(5, 3, dtype=torch.float32, device="cpu")
v_7_21vjhxyt = torch.randn(6, 5, 3, dtype=torch.float32, device="cpu")
v_8_2g4liqr4 = torch.randn(5, 3, dtype=torch.float32, device="cpu")
v_9_atc8p2lw = torch.randn(2, 5, 6, dtype=torch.float32, device="cpu")
v_10_1sng2192 = torch.randn(1, 6, 6, 2, dtype=torch.float32, device="cpu")
v_11_s2lgpodq = torch.randn(5, 1, 4, 6, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_b31ze8dc, v_1_r5pvt2dx, v_2_7yydmfsp, v_3_voorek3s, v_4_o4f5vc1k, v_5_rem89yxv, v_6_0uqciv2h, v_7_21vjhxyt, v_8_2g4liqr4, v_9_atc8p2lw, v_10_1sng2192, v_11_s2lgpodq)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_b31ze8dc, v_1_r5pvt2dx, v_2_7yydmfsp, v_3_voorek3s, v_4_o4f5vc1k, v_5_rem89yxv, v_6_0uqciv2h, v_7_21vjhxyt, v_8_2g4liqr4, v_9_atc8p2lw, v_10_1sng2192, v_11_s2lgpodq)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise, cast to float for allclose compatibility
    all_match = all(torch.allclose(r.float(), c.float(), atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output.float(), cmp_output.float(), atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
