# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_17_it2n9tx2_var = relax.Var("v_17_it2n9tx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1]), dtype="float32"))
    with bb.function("graph_2", [v_17_it2n9tx2_var]):
        # input: [1]
        # output: []
        v_18_b6lcx44f = bb.emit(relax.op.astype(relax.op.argmin(v_17_it2n9tx2_var, axis=-1), dtype="float32"))
        assert str(v_18_b6lcx44f.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_18_b6lcx44f.struct_info.shape}"
        bb.emit_func_output(v_18_b6lcx44f)

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_2
np_v_17_it2n9tx2 = np.random.uniform(0.0, 1.0, size=(1)).astype(np.float32)
v_17_it2n9tx2 = tvm.runtime.tensor(np_v_17_it2n9tx2, device=tvm.cuda())

tvm_result_0 = vm["graph_2"](v_17_it2n9tx2)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
