# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_7r2arbmg_var = relax.Var("v_0_7r2arbmg", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2]), dtype="float32"))
    v_1_vpmbugfg_var = relax.Var("v_1_vpmbugfg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_3d2a8c4s_var = relax.Var("v_2_3d2a8c4s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 5]), dtype="float32"))
    v_3_45wfib3u_var = relax.Var("v_3_45wfib3u", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6]), dtype="float32"))
    v_4_hr5bpypw_var = relax.Var("v_4_hr5bpypw", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_5_3cbxpfet_var = relax.Var("v_5_3cbxpfet", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2, 3]), dtype="float32"))
    with bb.function("graph_0", [v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_4_hr5bpypw_var, v_5_3cbxpfet_var]):
        # input: 
        # output: [1, 6]
        v_6_sbjo3p4a = bb.emit(relax.op.full(relax.ShapeExpr([1, 6]), relax.const(0, dtype="float32")))
        assert str(v_6_sbjo3p4a.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_6_sbjo3p4a.struct_info.shape}"
        # input: [6, 2, 3]
        # output: [6, 2, 3]
        v_7_duz9zv74 = bb.emit(relax.op.tile(v_5_3cbxpfet_var, [1, 1, 1]))
        assert str(v_7_duz9zv74.struct_info.shape) == "R.shape([6, 2, 3])", f"Shape mismatch: expected R.shape([6, 2, 3]), got {v_7_duz9zv74.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_8_st5viri8 = bb.emit(relax.op.abs(v_6_sbjo3p4a))
        assert str(v_8_st5viri8.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_8_st5viri8.struct_info.shape}"
        # input: [1, 6], [1, 6]
        # output: [1, 6]
        v_9_u485czx2 = bb.emit(relax.op.minimum(relax.op.astype(v_6_sbjo3p4a, dtype="float32"), relax.op.astype(v_8_st5viri8, dtype="float32")))
        assert str(v_9_u485czx2.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_9_u485czx2.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_10_pj1kq3oj = bb.emit(relax.op.nn.avg_pool2d(v_4_hr5bpypw_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_10_pj1kq3oj.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_10_pj1kq3oj.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_11_g91lb1jv = bb.emit(relax.op.nn.max_pool2d(v_4_hr5bpypw_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_11_g91lb1jv.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_11_g91lb1jv.struct_info.shape}"
        bb.emit_func_output((v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_7_duz9zv74, v_9_u485czx2, v_10_pj1kq3oj, v_11_g91lb1jv))

    v_0_7r2arbmg_var = relax.Var("v_0_7r2arbmg", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2]), dtype="float32"))
    v_1_vpmbugfg_var = relax.Var("v_1_vpmbugfg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_3d2a8c4s_var = relax.Var("v_2_3d2a8c4s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 5]), dtype="float32"))
    v_3_45wfib3u_var = relax.Var("v_3_45wfib3u", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6]), dtype="float32"))
    v_7_duz9zv74_var = relax.Var("v_7_duz9zv74", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2, 3]), dtype="float32"))
    v_9_u485czx2_var = relax.Var("v_9_u485czx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_10_pj1kq3oj_var = relax.Var("v_10_pj1kq3oj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_11_g91lb1jv_var = relax.Var("v_11_g91lb1jv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    with bb.function("graph_1", [v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_7_duz9zv74_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_11_g91lb1jv_var]):
        # input: [5, 6, 5, 6]
        # output: [5, 6, 10, 12]
        v_12_9wfuy2n1 = bb.emit(relax.op.image.resize2d(v_11_g91lb1jv_var, relax.ShapeExpr([10, 12]), layout="NCHW"))
        assert str(v_12_9wfuy2n1.struct_info.shape) == "R.shape([5, 6, 10, 12])", f"Shape mismatch: expected R.shape([5, 6, 10, 12]), got {v_12_9wfuy2n1.struct_info.shape}"
        # input: 
        # output: [229]
        v_13_qni84nxx = bb.emit(relax.op.arange(0, 229, dtype="float32"))
        assert str(v_13_qni84nxx.struct_info.shape) == "R.shape([229])", f"Shape mismatch: expected R.shape([229]), got {v_13_qni84nxx.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_14_1vlq7grt = bb.emit(relax.op.nn.silu(v_11_g91lb1jv_var))
        assert str(v_14_1vlq7grt.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_14_1vlq7grt.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_15_tyo6psxs = bb.emit(relax.op.astype(v_11_g91lb1jv_var, dtype="float32"))
        assert str(v_15_tyo6psxs.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_15_tyo6psxs.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_16_qylh6us1 = bb.emit(relax.op.clip(v_14_1vlq7grt, -0.56, 1.38))
        assert str(v_16_qylh6us1.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_16_qylh6us1.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 10, 12]
        v_17_51rsn1ub = bb.emit(relax.op.image.resize2d(v_15_tyo6psxs, relax.ShapeExpr([10, 12]), layout="NCHW"))
        assert str(v_17_51rsn1ub.struct_info.shape) == "R.shape([5, 6, 10, 12])", f"Shape mismatch: expected R.shape([5, 6, 10, 12]), got {v_17_51rsn1ub.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_18_41njmvhi = bb.emit(relax.op.triu(v_15_tyo6psxs))
        assert str(v_18_41njmvhi.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_18_41njmvhi.struct_info.shape}"
        # input: [5, 6, 10, 12]
        # output: [5, 6, 10, 12]
        v_19_rh3ku3xu = bb.emit(relax.op.where(relax.op.greater_equal(v_17_51rsn1ub, relax.const(0, dtype="float32")), v_17_51rsn1ub, relax.op.multiply(relax.const(1.48, dtype="float32"), relax.op.subtract(relax.op.exp(v_17_51rsn1ub), relax.const(1.0, dtype="float32")))))
        assert str(v_19_rh3ku3xu.struct_info.shape) == "R.shape([5, 6, 10, 12])", f"Shape mismatch: expected R.shape([5, 6, 10, 12]), got {v_19_rh3ku3xu.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_20_wfk414qz = bb.emit(relax.op.nn.silu(v_18_41njmvhi))
        assert str(v_20_wfk414qz.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_20_wfk414qz.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [2, 6, 5, 6]
        v_21_k6ln1v56 = bb.emit(relax.op.strided_slice(v_18_41njmvhi, axes=[0], begin=[0], end=[2]))
        assert str(v_21_k6ln1v56.struct_info.shape) == "R.shape([2, 6, 5, 6])", f"Shape mismatch: expected R.shape([2, 6, 5, 6]), got {v_21_k6ln1v56.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_22_mzxbu99v = bb.emit(relax.op.nn.softmax(relax.op.astype(v_18_41njmvhi, dtype="float32"), axis=-1))
        assert str(v_22_mzxbu99v.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_22_mzxbu99v.struct_info.shape}"
        # input: 
        # output: [4, 6, 3, 1]
        v_23_paupgeld = bb.emit(relax.op.full(relax.ShapeExpr([4, 6, 3, 1]), relax.const(0, dtype="float32")))
        assert str(v_23_paupgeld.struct_info.shape) == "R.shape([4, 6, 3, 1])", f"Shape mismatch: expected R.shape([4, 6, 3, 1]), got {v_23_paupgeld.struct_info.shape}"
        # input: [5, 6, 5, 6], [4, 6, 3, 1]
        # output: [5, 4, 3, 6]
        v_24_eqd4jdtq = bb.emit(relax.op.nn.conv2d(v_18_41njmvhi, v_23_paupgeld, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_24_eqd4jdtq.struct_info.shape) == "R.shape([5, 4, 3, 6])", f"Shape mismatch: expected R.shape([5, 4, 3, 6]), got {v_24_eqd4jdtq.struct_info.shape}"
        # input: 
        # output: [4, 6, 3, 1]
        v_25_vkyuq5if = bb.emit(relax.op.full(relax.ShapeExpr([4, 6, 3, 1]), relax.const(0, dtype="float32")))
        assert str(v_25_vkyuq5if.struct_info.shape) == "R.shape([4, 6, 3, 1])", f"Shape mismatch: expected R.shape([4, 6, 3, 1]), got {v_25_vkyuq5if.struct_info.shape}"
        # input: [5, 6, 5, 6], [4, 6, 3, 1]
        # output: [5, 4, 3, 6]
        v_26_hvu5q99i = bb.emit(relax.op.nn.conv2d(v_18_41njmvhi, v_25_vkyuq5if, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_26_hvu5q99i.struct_info.shape) == "R.shape([5, 4, 3, 6])", f"Shape mismatch: expected R.shape([5, 4, 3, 6]), got {v_26_hvu5q99i.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [2, 6, 5, 6]
        v_27_66u8tr3g = bb.emit(relax.op.strided_slice(v_18_41njmvhi, axes=[0], begin=[0], end=[2]))
        assert str(v_27_66u8tr3g.struct_info.shape) == "R.shape([2, 6, 5, 6])", f"Shape mismatch: expected R.shape([2, 6, 5, 6]), got {v_27_66u8tr3g.struct_info.shape}"
        # input: [5, 4, 3, 6], [5, 4, 3, 6]
        # output: [5, 4, 3, 6]
        v_28_fqr2v4zn = bb.emit(relax.op.add(relax.op.astype(v_26_hvu5q99i, dtype="float32"), relax.op.astype(v_24_eqd4jdtq, dtype="float32")))
        assert str(v_28_fqr2v4zn.struct_info.shape) == "R.shape([5, 4, 3, 6])", f"Shape mismatch: expected R.shape([5, 4, 3, 6]), got {v_28_fqr2v4zn.struct_info.shape}"
        # input: [6, 2, 3]
        # output: [1, 6, 2, 3]
        v_29_g9kntm6y = bb.emit(relax.op.expand_dims(v_7_duz9zv74_var, axis=0))
        assert str(v_29_g9kntm6y.struct_info.shape) == "R.shape([1, 6, 2, 3])", f"Shape mismatch: expected R.shape([1, 6, 2, 3]), got {v_29_g9kntm6y.struct_info.shape}"
        # input: [5, 4, 3, 6]
        # output: [5, 4, 3, 6]
        v_30_wehyi3np = bb.emit(relax.op.triu(v_28_fqr2v4zn))
        assert str(v_30_wehyi3np.struct_info.shape) == "R.shape([5, 4, 3, 6])", f"Shape mismatch: expected R.shape([5, 4, 3, 6]), got {v_30_wehyi3np.struct_info.shape}"
        # input: [5, 4, 3, 6]
        # output: [5, 4, 3]
        v_31_rqfxsnl9 = bb.emit(relax.op.min(v_28_fqr2v4zn, axis=[-1], keepdims=False))
        assert str(v_31_rqfxsnl9.struct_info.shape) == "R.shape([5, 4, 3])", f"Shape mismatch: expected R.shape([5, 4, 3]), got {v_31_rqfxsnl9.struct_info.shape}"
        bb.emit_func_output((v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1, v_13_qni84nxx, v_16_qylh6us1, v_19_rh3ku3xu, v_20_wfk414qz, v_21_k6ln1v56, v_22_mzxbu99v, v_27_66u8tr3g, v_29_g9kntm6y, v_30_wehyi3np, v_31_rqfxsnl9))

    v_0_7r2arbmg_var = relax.Var("v_0_7r2arbmg", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2]), dtype="float32"))
    v_1_vpmbugfg_var = relax.Var("v_1_vpmbugfg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_3d2a8c4s_var = relax.Var("v_2_3d2a8c4s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 5]), dtype="float32"))
    v_3_45wfib3u_var = relax.Var("v_3_45wfib3u", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6]), dtype="float32"))
    v_9_u485czx2_var = relax.Var("v_9_u485czx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_10_pj1kq3oj_var = relax.Var("v_10_pj1kq3oj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_12_9wfuy2n1_var = relax.Var("v_12_9wfuy2n1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_13_qni84nxx_var = relax.Var("v_13_qni84nxx", relax.TensorStructInfo(shape=relax.ShapeExpr([229]), dtype="float32"))
    v_16_qylh6us1_var = relax.Var("v_16_qylh6us1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_19_rh3ku3xu_var = relax.Var("v_19_rh3ku3xu", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_20_wfk414qz_var = relax.Var("v_20_wfk414qz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_21_k6ln1v56_var = relax.Var("v_21_k6ln1v56", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_22_mzxbu99v_var = relax.Var("v_22_mzxbu99v", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_27_66u8tr3g_var = relax.Var("v_27_66u8tr3g", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_29_g9kntm6y_var = relax.Var("v_29_g9kntm6y", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 2, 3]), dtype="float32"))
    v_30_wehyi3np_var = relax.Var("v_30_wehyi3np", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3, 6]), dtype="float32"))
    v_31_rqfxsnl9_var = relax.Var("v_31_rqfxsnl9", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3]), dtype="float32"))
    with bb.function("graph_2", [v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_20_wfk414qz_var, v_21_k6ln1v56_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_31_rqfxsnl9_var]):
        # input: [5, 4, 3]
        # output: [5, 4, 3]
        v_32_2taa9v6y = bb.emit(relax.op.clip(v_31_rqfxsnl9_var, -1, 1))
        assert str(v_32_2taa9v6y.struct_info.shape) == "R.shape([5, 4, 3])", f"Shape mismatch: expected R.shape([5, 4, 3]), got {v_32_2taa9v6y.struct_info.shape}"
        # input: [5, 4, 3]
        # output: [5, 4, 3]
        v_33_bte52emv = bb.emit(relax.op.clip(v_31_rqfxsnl9_var, 0, 1))
        assert str(v_33_bte52emv.struct_info.shape) == "R.shape([5, 4, 3])", f"Shape mismatch: expected R.shape([5, 4, 3]), got {v_33_bte52emv.struct_info.shape}"
        # input: [5, 4, 3]
        # output: [1, 5, 4, 3]
        v_34_v5rsgmrm = bb.emit(relax.op.expand_dims(v_32_2taa9v6y, axis=0))
        assert str(v_34_v5rsgmrm.struct_info.shape) == "R.shape([1, 5, 4, 3])", f"Shape mismatch: expected R.shape([1, 5, 4, 3]), got {v_34_v5rsgmrm.struct_info.shape}"
        # input: [5, 4, 3]
        # output: [5, 4, 3]
        v_35_gkl9j3b9 = bb.emit(relax.op.nn.silu(v_32_2taa9v6y))
        assert str(v_35_gkl9j3b9.struct_info.shape) == "R.shape([5, 4, 3])", f"Shape mismatch: expected R.shape([5, 4, 3]), got {v_35_gkl9j3b9.struct_info.shape}"
        # input: [1, 5, 4, 3]
        # output: [1, 5, 4, 3]
        v_36_fuez9nkx = bb.emit(relax.op.nn.selu(v_34_v5rsgmrm))
        assert str(v_36_fuez9nkx.struct_info.shape) == "R.shape([1, 5, 4, 3])", f"Shape mismatch: expected R.shape([1, 5, 4, 3]), got {v_36_fuez9nkx.struct_info.shape}"
        # input: [5, 4, 3]
        # output: [5, 4, 3]
        v_37_08wuac4g = bb.emit(relax.op.astype(v_35_gkl9j3b9, dtype="float32"))
        assert str(v_37_08wuac4g.struct_info.shape) == "R.shape([5, 4, 3])", f"Shape mismatch: expected R.shape([5, 4, 3]), got {v_37_08wuac4g.struct_info.shape}"
        # input: [2, 6, 5, 6]
        # output: [2, 6, 5, 6]
        v_38_g9qeaj9p = bb.emit(relax.op.nn.max_pool2d(v_21_k6ln1v56_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_38_g9qeaj9p.struct_info.shape) == "R.shape([2, 6, 5, 6])", f"Shape mismatch: expected R.shape([2, 6, 5, 6]), got {v_38_g9qeaj9p.struct_info.shape}"
        # input: 
        # output: [3, 5, 2, 3]
        v_39_6izrvgoc = bb.emit(relax.op.ones(relax.ShapeExpr([3, 5, 2, 3]), dtype="float32"))
        assert str(v_39_6izrvgoc.struct_info.shape) == "R.shape([3, 5, 2, 3])", f"Shape mismatch: expected R.shape([3, 5, 2, 3]), got {v_39_6izrvgoc.struct_info.shape}"
        # input: [3, 5, 2, 3]
        # output: [3, 5, 1, 1]
        v_40_nahpz7au = bb.emit(relax.op.nn.avg_pool2d(v_39_6izrvgoc, pool_size=[2, 2], strides=[2, 2], padding=[0, 0]))
        assert str(v_40_nahpz7au.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_40_nahpz7au.struct_info.shape}"
        # input: [3, 5, 2, 3]
        # output: [3, 5, 2, 3]
        v_41_mqil414w = bb.emit(relax.op.nn.gelu(v_39_6izrvgoc))
        assert str(v_41_mqil414w.struct_info.shape) == "R.shape([3, 5, 2, 3])", f"Shape mismatch: expected R.shape([3, 5, 2, 3]), got {v_41_mqil414w.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_42_7cmn7xvz = bb.emit(relax.op.sigmoid(v_40_nahpz7au))
        assert str(v_42_7cmn7xvz.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_42_7cmn7xvz.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [1, 5, 1, 1]
        v_43_g3lzv8dn = bb.emit(relax.op.strided_slice(v_40_nahpz7au, axes=[0], begin=[0], end=[1]))
        assert str(v_43_g3lzv8dn.struct_info.shape) == "R.shape([1, 5, 1, 1])", f"Shape mismatch: expected R.shape([1, 5, 1, 1]), got {v_43_g3lzv8dn.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_44_rux3rvwk = bb.emit(relax.op.clip(v_40_nahpz7au, -1, 2))
        assert str(v_44_rux3rvwk.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_44_rux3rvwk.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_45_m34m0081 = bb.emit(relax.op.nn.relu(v_40_nahpz7au))
        assert str(v_45_m34m0081.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_45_m34m0081.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_46_og8dv4f7 = bb.emit(relax.op.nn.layer_norm(v_44_rux3rvwk, gamma=relax.op.ones(relax.ShapeExpr([1]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"), axes=[-1]))
        assert str(v_46_og8dv4f7.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_46_og8dv4f7.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_47_qth0qtx5 = bb.emit(relax.op.permute_dims(v_44_rux3rvwk, axes=[0, 1, 3, 2]))
        assert str(v_47_qth0qtx5.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_47_qth0qtx5.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_48_n6fy6a9d = bb.emit(relax.op.negative(v_46_og8dv4f7))
        assert str(v_48_n6fy6a9d.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_48_n6fy6a9d.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_49_dzf74hph = bb.emit(relax.op.tile(v_46_og8dv4f7, [1, 1, 1, 1]))
        assert str(v_49_dzf74hph.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_49_dzf74hph.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_50_j7bl4ss6 = bb.emit(relax.op.nn.gelu(v_46_og8dv4f7))
        assert str(v_50_j7bl4ss6.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_50_j7bl4ss6.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_51_sjv1ruso = bb.emit(relax.op.nn.softmax(relax.op.astype(v_46_og8dv4f7, dtype="float32"), axis=-1))
        assert str(v_51_sjv1ruso.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_51_sjv1ruso.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_52_9ocst2f2 = bb.emit(relax.op.nn.avg_pool2d(v_46_og8dv4f7, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_52_9ocst2f2.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_52_9ocst2f2.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [5, 1, 1]
        v_53_17abqysz = bb.emit(relax.op.take(v_51_sjv1ruso, relax.const(0, dtype="int64"), axis=0))
        assert str(v_53_17abqysz.struct_info.shape) == "R.shape([5, 1, 1])", f"Shape mismatch: expected R.shape([5, 1, 1]), got {v_53_17abqysz.struct_info.shape}"
        # input: 
        # output: [3, 6]
        v_54_2ifvorj6 = bb.emit(relax.op.zeros(relax.ShapeExpr([3, 6]), dtype="float32"))
        assert str(v_54_2ifvorj6.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_54_2ifvorj6.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1]
        v_55_fp74y78n = bb.emit(relax.op.max(v_51_sjv1ruso, axis=[-1], keepdims=False))
        assert str(v_55_fp74y78n.struct_info.shape) == "R.shape([3, 5, 1])", f"Shape mismatch: expected R.shape([3, 5, 1]), got {v_55_fp74y78n.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_56_mtyyvls1 = bb.emit(relax.op.nn.layer_norm(v_51_sjv1ruso, gamma=relax.op.ones(relax.ShapeExpr([1]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"), axes=[-1]))
        assert str(v_56_mtyyvls1.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_56_mtyyvls1.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_57_4la34q8b = bb.emit(relax.op.nn.avg_pool2d(v_51_sjv1ruso, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_57_4la34q8b.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_57_4la34q8b.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_58_2wq59alx = bb.emit(relax.op.abs(v_51_sjv1ruso))
        assert str(v_58_2wq59alx.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_58_2wq59alx.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_59_4ig4zr9p_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_51_sjv1ruso, gamma=relax.op.ones(relax.ShapeExpr([5]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([5]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([5]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([5]), dtype="float32"), axis=1))
        v_59_4ig4zr9p = bb.emit(relax.TupleGetItem(v_59_4ig4zr9p_bn_tuple, 0))
        assert str(v_59_4ig4zr9p.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_59_4ig4zr9p.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_60_e671cxqj = bb.emit(relax.op.triu(v_58_2wq59alx))
        assert str(v_60_e671cxqj.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_60_e671cxqj.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_61_0lqo5vn8 = bb.emit(relax.op.astype(v_58_2wq59alx, dtype="float32"))
        assert str(v_61_0lqo5vn8.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_61_0lqo5vn8.struct_info.shape}"
        bb.emit_func_output((v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_20_wfk414qz_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_33_bte52emv, v_36_fuez9nkx, v_37_08wuac4g, v_38_g9qeaj9p, v_41_mqil414w, v_42_7cmn7xvz, v_43_g3lzv8dn, v_45_m34m0081, v_47_qth0qtx5, v_48_n6fy6a9d, v_49_dzf74hph, v_50_j7bl4ss6, v_52_9ocst2f2, v_53_17abqysz, v_54_2ifvorj6, v_55_fp74y78n, v_56_mtyyvls1, v_57_4la34q8b, v_59_4ig4zr9p, v_60_e671cxqj, v_61_0lqo5vn8))

    v_0_7r2arbmg_var = relax.Var("v_0_7r2arbmg", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2]), dtype="float32"))
    v_1_vpmbugfg_var = relax.Var("v_1_vpmbugfg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_3d2a8c4s_var = relax.Var("v_2_3d2a8c4s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 5]), dtype="float32"))
    v_3_45wfib3u_var = relax.Var("v_3_45wfib3u", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6]), dtype="float32"))
    v_9_u485czx2_var = relax.Var("v_9_u485czx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_10_pj1kq3oj_var = relax.Var("v_10_pj1kq3oj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_12_9wfuy2n1_var = relax.Var("v_12_9wfuy2n1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_13_qni84nxx_var = relax.Var("v_13_qni84nxx", relax.TensorStructInfo(shape=relax.ShapeExpr([229]), dtype="float32"))
    v_16_qylh6us1_var = relax.Var("v_16_qylh6us1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_19_rh3ku3xu_var = relax.Var("v_19_rh3ku3xu", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_20_wfk414qz_var = relax.Var("v_20_wfk414qz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_22_mzxbu99v_var = relax.Var("v_22_mzxbu99v", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_27_66u8tr3g_var = relax.Var("v_27_66u8tr3g", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_29_g9kntm6y_var = relax.Var("v_29_g9kntm6y", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 2, 3]), dtype="float32"))
    v_30_wehyi3np_var = relax.Var("v_30_wehyi3np", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3, 6]), dtype="float32"))
    v_33_bte52emv_var = relax.Var("v_33_bte52emv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3]), dtype="float32"))
    v_36_fuez9nkx_var = relax.Var("v_36_fuez9nkx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 4, 3]), dtype="float32"))
    v_37_08wuac4g_var = relax.Var("v_37_08wuac4g", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3]), dtype="float32"))
    v_38_g9qeaj9p_var = relax.Var("v_38_g9qeaj9p", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_41_mqil414w_var = relax.Var("v_41_mqil414w", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 2, 3]), dtype="float32"))
    v_42_7cmn7xvz_var = relax.Var("v_42_7cmn7xvz", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_43_g3lzv8dn_var = relax.Var("v_43_g3lzv8dn", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 1, 1]), dtype="float32"))
    v_45_m34m0081_var = relax.Var("v_45_m34m0081", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_47_qth0qtx5_var = relax.Var("v_47_qth0qtx5", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_48_n6fy6a9d_var = relax.Var("v_48_n6fy6a9d", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_49_dzf74hph_var = relax.Var("v_49_dzf74hph", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_50_j7bl4ss6_var = relax.Var("v_50_j7bl4ss6", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_52_9ocst2f2_var = relax.Var("v_52_9ocst2f2", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_53_17abqysz_var = relax.Var("v_53_17abqysz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 1, 1]), dtype="float32"))
    v_54_2ifvorj6_var = relax.Var("v_54_2ifvorj6", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_55_fp74y78n_var = relax.Var("v_55_fp74y78n", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1]), dtype="float32"))
    v_56_mtyyvls1_var = relax.Var("v_56_mtyyvls1", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_57_4la34q8b_var = relax.Var("v_57_4la34q8b", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_59_4ig4zr9p_var = relax.Var("v_59_4ig4zr9p", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_60_e671cxqj_var = relax.Var("v_60_e671cxqj", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_61_0lqo5vn8_var = relax.Var("v_61_0lqo5vn8", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    with bb.function("graph_3", [v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_20_wfk414qz_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_33_bte52emv_var, v_36_fuez9nkx_var, v_37_08wuac4g_var, v_38_g9qeaj9p_var, v_41_mqil414w_var, v_42_7cmn7xvz_var, v_43_g3lzv8dn_var, v_45_m34m0081_var, v_47_qth0qtx5_var, v_48_n6fy6a9d_var, v_49_dzf74hph_var, v_50_j7bl4ss6_var, v_52_9ocst2f2_var, v_53_17abqysz_var, v_54_2ifvorj6_var, v_55_fp74y78n_var, v_56_mtyyvls1_var, v_57_4la34q8b_var, v_59_4ig4zr9p_var, v_60_e671cxqj_var, v_61_0lqo5vn8_var]):
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_62_f3qeorhx_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_61_0lqo5vn8_var, gamma=relax.op.ones(relax.ShapeExpr([5]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([5]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([5]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([5]), dtype="float32"), axis=1))
        v_62_f3qeorhx = bb.emit(relax.TupleGetItem(v_62_f3qeorhx_bn_tuple, 0))
        assert str(v_62_f3qeorhx.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_62_f3qeorhx.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_63_jlexkd0a = bb.emit(relax.op.tanh(v_61_0lqo5vn8_var))
        assert str(v_63_jlexkd0a.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_63_jlexkd0a.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_64_fwjojhp0 = bb.emit(relax.op.where(relax.op.greater_equal(v_61_0lqo5vn8_var, relax.const(0, dtype="float32")), v_61_0lqo5vn8_var, relax.op.multiply(relax.const(1.98, dtype="float32"), relax.op.subtract(relax.op.exp(v_61_0lqo5vn8_var), relax.const(1.0, dtype="float32")))))
        assert str(v_64_fwjojhp0.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_64_fwjojhp0.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_65_w6haru9z = bb.emit(relax.op.tril(v_61_0lqo5vn8_var))
        assert str(v_65_w6haru9z.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_65_w6haru9z.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_66_zgdebfez = bb.emit(relax.op.clip(v_64_fwjojhp0, 0, 0))
        assert str(v_66_zgdebfez.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_66_zgdebfez.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_67_6r5her4x = bb.emit(relax.op.tile(v_64_fwjojhp0, [1, 1, 1, 1]))
        assert str(v_67_6r5her4x.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_67_6r5her4x.struct_info.shape}"
        # input: 
        # output: [112]
        v_68_zveekr3u = bb.emit(relax.op.arange(0, 112, dtype="float32"))
        assert str(v_68_zveekr3u.struct_info.shape) == "R.shape([112])", f"Shape mismatch: expected R.shape([112]), got {v_68_zveekr3u.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_69_cepsqnv4 = bb.emit(relax.op.nn.selu(v_64_fwjojhp0))
        assert str(v_69_cepsqnv4.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_69_cepsqnv4.struct_info.shape}"
        # input: [112]
        # output: [112]
        v_70_230vhzys = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_68_zveekr3u, dtype="float32"), axis=-1))
        assert str(v_70_230vhzys.struct_info.shape) == "R.shape([112])", f"Shape mismatch: expected R.shape([112]), got {v_70_230vhzys.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_71_qbfhdyx6 = bb.emit(relax.op.nn.silu(v_69_cepsqnv4))
        assert str(v_71_qbfhdyx6.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_71_qbfhdyx6.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_72_2cysf28h = bb.emit(relax.op.tril(v_69_cepsqnv4))
        assert str(v_72_2cysf28h.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_72_2cysf28h.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_73_7u0nzl6e = bb.emit(relax.op.where(relax.op.greater_equal(v_71_qbfhdyx6, relax.const(0, dtype="float32")), v_71_qbfhdyx6, relax.op.multiply(relax.const(1.67, dtype="float32"), relax.op.subtract(relax.op.exp(v_71_qbfhdyx6), relax.const(1.0, dtype="float32")))))
        assert str(v_73_7u0nzl6e.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_73_7u0nzl6e.struct_info.shape}"
        # input: [3, 5, 1, 1], [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_74_sg11v2p5 = bb.emit(relax.op.minimum(relax.op.astype(v_72_2cysf28h, dtype="float32"), relax.op.astype(v_66_zgdebfez, dtype="float32")))
        assert str(v_74_sg11v2p5.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_74_sg11v2p5.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_75_snnkmetr = bb.emit(relax.op.tril(v_72_2cysf28h))
        assert str(v_75_snnkmetr.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_75_snnkmetr.struct_info.shape}"
        # input: [3, 5, 1, 1], [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_76_u5qjx04f = bb.emit(relax.op.multiply(relax.op.astype(v_72_2cysf28h, dtype="float32"), relax.op.astype(v_49_dzf74hph_var, dtype="float32")))
        assert str(v_76_u5qjx04f.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_76_u5qjx04f.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_77_w7v1aztq = bb.emit(relax.op.where(relax.op.greater_equal(v_72_2cysf28h, relax.const(0, dtype="float32")), v_72_2cysf28h, relax.op.multiply(relax.const(1.99, dtype="float32"), relax.op.subtract(relax.op.exp(v_72_2cysf28h), relax.const(1.0, dtype="float32")))))
        assert str(v_77_w7v1aztq.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_77_w7v1aztq.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_78_nl88di4l = bb.emit(relax.op.nn.max_pool2d(v_72_2cysf28h, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_78_nl88di4l.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_78_nl88di4l.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_79_dh7xsiwu = bb.emit(relax.op.permute_dims(v_72_2cysf28h, axes=[0, 1, 3, 2]))
        assert str(v_79_dh7xsiwu.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_79_dh7xsiwu.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 2, 2]
        v_80_uaz3rh9a = bb.emit(relax.op.image.resize2d(v_72_2cysf28h, relax.ShapeExpr([2, 2]), layout="NCHW"))
        assert str(v_80_uaz3rh9a.struct_info.shape) == "R.shape([3, 5, 2, 2])", f"Shape mismatch: expected R.shape([3, 5, 2, 2]), got {v_80_uaz3rh9a.struct_info.shape}"
        # input: [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_81_uzkezku0 = bb.emit(relax.op.permute_dims(v_72_2cysf28h, axes=[0, 1, 3, 2]))
        assert str(v_81_uzkezku0.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_81_uzkezku0.struct_info.shape}"
        # input: [3, 5, 2, 2]
        # output: [3, 5, 2, 2]
        v_82_icmdsn01 = bb.emit(relax.op.abs(v_80_uaz3rh9a))
        assert str(v_82_icmdsn01.struct_info.shape) == "R.shape([3, 5, 2, 2])", f"Shape mismatch: expected R.shape([3, 5, 2, 2]), got {v_82_icmdsn01.struct_info.shape}"
        # input: [3, 5, 1, 1], [3, 5, 2, 2]
        # output: [3, 5, 2, 2]
        v_83_w94n7fuh = bb.emit(relax.op.add(relax.op.astype(v_81_uzkezku0, dtype="float32"), relax.op.astype(v_82_icmdsn01, dtype="float32")))
        assert str(v_83_w94n7fuh.struct_info.shape) == "R.shape([3, 5, 2, 2])", f"Shape mismatch: expected R.shape([3, 5, 2, 2]), got {v_83_w94n7fuh.struct_info.shape}"
        # input: [3, 5, 1, 1], [3, 6]
        # output: [3, 5, 3, 6]
        v_84_o3ksolon = bb.emit(relax.op.subtract(relax.op.astype(v_81_uzkezku0, dtype="float32"), relax.op.astype(v_54_2ifvorj6_var, dtype="float32")))
        assert str(v_84_o3ksolon.struct_info.shape) == "R.shape([3, 5, 3, 6])", f"Shape mismatch: expected R.shape([3, 5, 3, 6]), got {v_84_o3ksolon.struct_info.shape}"
        # input: [3, 5, 1, 1], [3, 5, 1, 1]
        # output: [3, 5, 1, 1]
        v_85_kjaeg8z2 = bb.emit(relax.op.multiply(relax.op.astype(v_81_uzkezku0, dtype="float32"), relax.op.astype(v_77_w7v1aztq, dtype="float32")))
        assert str(v_85_kjaeg8z2.struct_info.shape) == "R.shape([3, 5, 1, 1])", f"Shape mismatch: expected R.shape([3, 5, 1, 1]), got {v_85_kjaeg8z2.struct_info.shape}"
        # input: [3, 5, 3, 6]
        # output: [5, 3, 6]
        v_86_wcvz941k = bb.emit(relax.op.take(v_84_o3ksolon, relax.const(0, dtype="int64"), axis=0))
        assert str(v_86_wcvz941k.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_86_wcvz941k.struct_info.shape}"
        bb.emit_func_output((v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_20_wfk414qz_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_33_bte52emv_var, v_36_fuez9nkx_var, v_37_08wuac4g_var, v_38_g9qeaj9p_var, v_41_mqil414w_var, v_42_7cmn7xvz_var, v_43_g3lzv8dn_var, v_45_m34m0081_var, v_47_qth0qtx5_var, v_48_n6fy6a9d_var, v_50_j7bl4ss6_var, v_52_9ocst2f2_var, v_53_17abqysz_var, v_55_fp74y78n_var, v_56_mtyyvls1_var, v_57_4la34q8b_var, v_59_4ig4zr9p_var, v_60_e671cxqj_var, v_62_f3qeorhx, v_63_jlexkd0a, v_65_w6haru9z, v_67_6r5her4x, v_70_230vhzys, v_73_7u0nzl6e, v_74_sg11v2p5, v_75_snnkmetr, v_76_u5qjx04f, v_78_nl88di4l, v_79_dh7xsiwu, v_83_w94n7fuh, v_85_kjaeg8z2, v_86_wcvz941k))

    v_0_7r2arbmg_var = relax.Var("v_0_7r2arbmg", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 2]), dtype="float32"))
    v_1_vpmbugfg_var = relax.Var("v_1_vpmbugfg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_3d2a8c4s_var = relax.Var("v_2_3d2a8c4s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 5]), dtype="float32"))
    v_3_45wfib3u_var = relax.Var("v_3_45wfib3u", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6]), dtype="float32"))
    v_9_u485czx2_var = relax.Var("v_9_u485czx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_10_pj1kq3oj_var = relax.Var("v_10_pj1kq3oj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_12_9wfuy2n1_var = relax.Var("v_12_9wfuy2n1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_13_qni84nxx_var = relax.Var("v_13_qni84nxx", relax.TensorStructInfo(shape=relax.ShapeExpr([229]), dtype="float32"))
    v_16_qylh6us1_var = relax.Var("v_16_qylh6us1", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_19_rh3ku3xu_var = relax.Var("v_19_rh3ku3xu", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 10, 12]), dtype="float32"))
    v_20_wfk414qz_var = relax.Var("v_20_wfk414qz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_22_mzxbu99v_var = relax.Var("v_22_mzxbu99v", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 6]), dtype="float32"))
    v_27_66u8tr3g_var = relax.Var("v_27_66u8tr3g", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_29_g9kntm6y_var = relax.Var("v_29_g9kntm6y", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 2, 3]), dtype="float32"))
    v_30_wehyi3np_var = relax.Var("v_30_wehyi3np", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3, 6]), dtype="float32"))
    v_33_bte52emv_var = relax.Var("v_33_bte52emv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3]), dtype="float32"))
    v_36_fuez9nkx_var = relax.Var("v_36_fuez9nkx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 4, 3]), dtype="float32"))
    v_37_08wuac4g_var = relax.Var("v_37_08wuac4g", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4, 3]), dtype="float32"))
    v_38_g9qeaj9p_var = relax.Var("v_38_g9qeaj9p", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6, 5, 6]), dtype="float32"))
    v_41_mqil414w_var = relax.Var("v_41_mqil414w", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 2, 3]), dtype="float32"))
    v_42_7cmn7xvz_var = relax.Var("v_42_7cmn7xvz", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_43_g3lzv8dn_var = relax.Var("v_43_g3lzv8dn", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 1, 1]), dtype="float32"))
    v_45_m34m0081_var = relax.Var("v_45_m34m0081", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_47_qth0qtx5_var = relax.Var("v_47_qth0qtx5", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_48_n6fy6a9d_var = relax.Var("v_48_n6fy6a9d", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_50_j7bl4ss6_var = relax.Var("v_50_j7bl4ss6", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_52_9ocst2f2_var = relax.Var("v_52_9ocst2f2", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_53_17abqysz_var = relax.Var("v_53_17abqysz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 1, 1]), dtype="float32"))
    v_55_fp74y78n_var = relax.Var("v_55_fp74y78n", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1]), dtype="float32"))
    v_56_mtyyvls1_var = relax.Var("v_56_mtyyvls1", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_57_4la34q8b_var = relax.Var("v_57_4la34q8b", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_59_4ig4zr9p_var = relax.Var("v_59_4ig4zr9p", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_60_e671cxqj_var = relax.Var("v_60_e671cxqj", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_62_f3qeorhx_var = relax.Var("v_62_f3qeorhx", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_63_jlexkd0a_var = relax.Var("v_63_jlexkd0a", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_65_w6haru9z_var = relax.Var("v_65_w6haru9z", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_67_6r5her4x_var = relax.Var("v_67_6r5her4x", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_70_230vhzys_var = relax.Var("v_70_230vhzys", relax.TensorStructInfo(shape=relax.ShapeExpr([112]), dtype="float32"))
    v_73_7u0nzl6e_var = relax.Var("v_73_7u0nzl6e", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_74_sg11v2p5_var = relax.Var("v_74_sg11v2p5", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_75_snnkmetr_var = relax.Var("v_75_snnkmetr", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_76_u5qjx04f_var = relax.Var("v_76_u5qjx04f", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_78_nl88di4l_var = relax.Var("v_78_nl88di4l", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_79_dh7xsiwu_var = relax.Var("v_79_dh7xsiwu", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_83_w94n7fuh_var = relax.Var("v_83_w94n7fuh", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 2, 2]), dtype="float32"))
    v_85_kjaeg8z2_var = relax.Var("v_85_kjaeg8z2", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5, 1, 1]), dtype="float32"))
    v_86_wcvz941k_var = relax.Var("v_86_wcvz941k", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    with bb.function("graph_4", [v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_10_pj1kq3oj_var, v_12_9wfuy2n1_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_20_wfk414qz_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_33_bte52emv_var, v_36_fuez9nkx_var, v_37_08wuac4g_var, v_38_g9qeaj9p_var, v_41_mqil414w_var, v_42_7cmn7xvz_var, v_43_g3lzv8dn_var, v_45_m34m0081_var, v_47_qth0qtx5_var, v_48_n6fy6a9d_var, v_50_j7bl4ss6_var, v_52_9ocst2f2_var, v_53_17abqysz_var, v_55_fp74y78n_var, v_56_mtyyvls1_var, v_57_4la34q8b_var, v_59_4ig4zr9p_var, v_60_e671cxqj_var, v_62_f3qeorhx_var, v_63_jlexkd0a_var, v_65_w6haru9z_var, v_67_6r5her4x_var, v_70_230vhzys_var, v_73_7u0nzl6e_var, v_74_sg11v2p5_var, v_75_snnkmetr_var, v_76_u5qjx04f_var, v_78_nl88di4l_var, v_79_dh7xsiwu_var, v_83_w94n7fuh_var, v_85_kjaeg8z2_var, v_86_wcvz941k_var]):
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_87_7mvvoavt = bb.emit(relax.op.triu(v_86_wcvz941k_var))
        assert str(v_87_7mvvoavt.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_87_7mvvoavt.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [3, 6]
        v_88_8qb38zcf = bb.emit(relax.op.take(v_86_wcvz941k_var, relax.const(0, dtype="int64"), axis=0))
        assert str(v_88_8qb38zcf.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_88_8qb38zcf.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_89_jb6m3whc = bb.emit(relax.op.nn.leakyrelu(v_86_wcvz941k_var, alpha=0.24))
        assert str(v_89_jb6m3whc.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_89_jb6m3whc.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_90_6j33sz90 = bb.emit(relax.op.nn.gelu(v_86_wcvz941k_var))
        assert str(v_90_6j33sz90.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_90_6j33sz90.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_91_mnmd7jhc = bb.emit(relax.op.nn.avg_pool2d(v_10_pj1kq3oj_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_91_mnmd7jhc.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_91_mnmd7jhc.struct_info.shape}"
        # input: 
        # output: [4, 3, 5]
        v_92_08rnmu0b = bb.emit(relax.op.zeros(relax.ShapeExpr([4, 3, 5]), dtype="float32"))
        assert str(v_92_08rnmu0b.struct_info.shape) == "R.shape([4, 3, 5])", f"Shape mismatch: expected R.shape([4, 3, 5]), got {v_92_08rnmu0b.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_93_4j8s3qw9 = bb.emit(relax.op.tile(v_90_6j33sz90, [1, 1, 1]))
        assert str(v_93_4j8s3qw9.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_93_4j8s3qw9.struct_info.shape}"
        # input: [5, 6, 5, 6]
        # output: [5, 6, 5, 6]
        v_94_o9lb9q3g = bb.emit(relax.op.nn.avg_pool2d(v_20_wfk414qz_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_94_o9lb9q3g.struct_info.shape) == "R.shape([5, 6, 5, 6])", f"Shape mismatch: expected R.shape([5, 6, 5, 6]), got {v_94_o9lb9q3g.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_95_3jneijzt = bb.emit(relax.op.tanh(v_93_4j8s3qw9))
        assert str(v_95_3jneijzt.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_95_3jneijzt.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_96_2racrpi6 = bb.emit(relax.op.clip(v_93_4j8s3qw9, 0, 1))
        assert str(v_96_2racrpi6.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_96_2racrpi6.struct_info.shape}"
        # input: [5, 3, 6], [3, 5, 1, 1]
        # output: [3, 5, 3, 6]
        v_97_uqhv1h1i = bb.emit(relax.op.minimum(relax.op.astype(v_95_3jneijzt, dtype="float32"), relax.op.astype(v_48_n6fy6a9d_var, dtype="float32")))
        assert str(v_97_uqhv1h1i.struct_info.shape) == "R.shape([3, 5, 3, 6])", f"Shape mismatch: expected R.shape([3, 5, 3, 6]), got {v_97_uqhv1h1i.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_98_frg2dh18 = bb.emit(relax.op.nn.layer_norm(v_95_3jneijzt, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), axes=[-1]))
        assert str(v_98_frg2dh18.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_98_frg2dh18.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_99_quqfl1kv = bb.emit(relax.op.tile(v_95_3jneijzt, [1, 1, 1]))
        assert str(v_99_quqfl1kv.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_99_quqfl1kv.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_100_zc12qds2 = bb.emit(relax.op.nn.softmax(relax.op.astype(v_98_frg2dh18, dtype="float32"), axis=-1))
        assert str(v_100_zc12qds2.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_100_zc12qds2.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [1, 5, 3, 6]
        v_101_rdhar0ek = bb.emit(relax.op.expand_dims(v_98_frg2dh18, axis=0))
        assert str(v_101_rdhar0ek.struct_info.shape) == "R.shape([1, 5, 3, 6])", f"Shape mismatch: expected R.shape([1, 5, 3, 6]), got {v_101_rdhar0ek.struct_info.shape}"
        # input: [5, 6, 10, 12]
        # output: [5, 6, 20, 24]
        v_102_j5dmvmui = bb.emit(relax.op.image.resize2d(v_12_9wfuy2n1_var, relax.ShapeExpr([20, 24]), layout="NCHW"))
        assert str(v_102_j5dmvmui.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_102_j5dmvmui.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_103_zg2ck0pp = bb.emit(relax.op.nn.selu(v_100_zc12qds2))
        assert str(v_103_zg2ck0pp.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_103_zg2ck0pp.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_104_qx4pkuj5 = bb.emit(relax.op.sigmoid(v_102_j5dmvmui))
        assert str(v_104_qx4pkuj5.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_104_qx4pkuj5.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 40, 48]
        v_105_96h4gett = bb.emit(relax.op.image.resize2d(v_102_j5dmvmui, relax.ShapeExpr([40, 48]), layout="NCHW"))
        assert str(v_105_96h4gett.struct_info.shape) == "R.shape([5, 6, 40, 48])", f"Shape mismatch: expected R.shape([5, 6, 40, 48]), got {v_105_96h4gett.struct_info.shape}"
        # input: [5, 6, 20, 24], [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_106_j1jtnvu2 = bb.emit(relax.op.minimum(relax.op.astype(v_104_qx4pkuj5, dtype="float32"), relax.op.astype(v_102_j5dmvmui, dtype="float32")))
        assert str(v_106_j1jtnvu2.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_106_j1jtnvu2.struct_info.shape}"
        # input: [5, 6, 20, 24], [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_107_l5d3o78k = bb.emit(relax.op.minimum(relax.op.astype(v_104_qx4pkuj5, dtype="float32"), relax.op.astype(v_102_j5dmvmui, dtype="float32")))
        assert str(v_107_l5d3o78k.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_107_l5d3o78k.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [2, 6, 20, 24]
        v_108_5tjerdmd = bb.emit(relax.op.strided_slice(v_106_j1jtnvu2, axes=[0], begin=[0], end=[2]))
        assert str(v_108_5tjerdmd.struct_info.shape) == "R.shape([2, 6, 20, 24])", f"Shape mismatch: expected R.shape([2, 6, 20, 24]), got {v_108_5tjerdmd.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_109_klgtqpii = bb.emit(relax.op.nn.relu(v_107_l5d3o78k))
        assert str(v_109_klgtqpii.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_109_klgtqpii.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_110_wh6om9b1 = bb.emit(relax.op.nn.max_pool2d(v_107_l5d3o78k, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_110_wh6om9b1.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_110_wh6om9b1.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_111_gopc3srt = bb.emit(relax.op.sigmoid(v_109_klgtqpii))
        assert str(v_111_gopc3srt.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_111_gopc3srt.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 20, 24]
        v_112_zcjm84f0 = bb.emit(relax.op.multiply(v_109_klgtqpii, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_109_klgtqpii))))))
        assert str(v_112_zcjm84f0.struct_info.shape) == "R.shape([5, 6, 20, 24])", f"Shape mismatch: expected R.shape([5, 6, 20, 24]), got {v_112_zcjm84f0.struct_info.shape}"
        # input: 
        # output: [1, 6, 3, 1]
        v_113_at9yudga = bb.emit(relax.op.full(relax.ShapeExpr([1, 6, 3, 1]), relax.const(0, dtype="float32")))
        assert str(v_113_at9yudga.struct_info.shape) == "R.shape([1, 6, 3, 1])", f"Shape mismatch: expected R.shape([1, 6, 3, 1]), got {v_113_at9yudga.struct_info.shape}"
        # input: [5, 6, 20, 24], [1, 6, 3, 1]
        # output: [5, 1, 18, 24]
        v_114_55aesmxr = bb.emit(relax.op.nn.conv2d(v_109_klgtqpii, v_113_at9yudga, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_114_55aesmxr.struct_info.shape) == "R.shape([5, 1, 18, 24])", f"Shape mismatch: expected R.shape([5, 1, 18, 24]), got {v_114_55aesmxr.struct_info.shape}"
        # input: [5, 6, 20, 24]
        # output: [5, 6, 40, 48]
        v_115_2c5a4yv9 = bb.emit(relax.op.image.resize2d(v_109_klgtqpii, relax.ShapeExpr([40, 48]), layout="NCHW"))
        assert str(v_115_2c5a4yv9.struct_info.shape) == "R.shape([5, 6, 40, 48])", f"Shape mismatch: expected R.shape([5, 6, 40, 48]), got {v_115_2c5a4yv9.struct_info.shape}"
        bb.emit_func_output((v_0_7r2arbmg_var, v_1_vpmbugfg_var, v_2_3d2a8c4s_var, v_3_45wfib3u_var, v_9_u485czx2_var, v_13_qni84nxx_var, v_16_qylh6us1_var, v_19_rh3ku3xu_var, v_22_mzxbu99v_var, v_27_66u8tr3g_var, v_29_g9kntm6y_var, v_30_wehyi3np_var, v_33_bte52emv_var, v_36_fuez9nkx_var, v_37_08wuac4g_var, v_38_g9qeaj9p_var, v_41_mqil414w_var, v_42_7cmn7xvz_var, v_43_g3lzv8dn_var, v_45_m34m0081_var, v_47_qth0qtx5_var, v_50_j7bl4ss6_var, v_52_9ocst2f2_var, v_53_17abqysz_var, v_55_fp74y78n_var, v_56_mtyyvls1_var, v_57_4la34q8b_var, v_59_4ig4zr9p_var, v_60_e671cxqj_var, v_62_f3qeorhx_var, v_63_jlexkd0a_var, v_65_w6haru9z_var, v_67_6r5her4x_var, v_70_230vhzys_var, v_73_7u0nzl6e_var, v_74_sg11v2p5_var, v_75_snnkmetr_var, v_76_u5qjx04f_var, v_78_nl88di4l_var, v_79_dh7xsiwu_var, v_83_w94n7fuh_var, v_85_kjaeg8z2_var, v_87_7mvvoavt, v_88_8qb38zcf, v_89_jb6m3whc, v_91_mnmd7jhc, v_92_08rnmu0b, v_94_o9lb9q3g, v_96_2racrpi6, v_97_uqhv1h1i, v_99_quqfl1kv, v_101_rdhar0ek, v_103_zg2ck0pp, v_105_96h4gett, v_108_5tjerdmd, v_110_wh6om9b1, v_111_gopc3srt, v_112_zcjm84f0, v_114_55aesmxr, v_115_2c5a4yv9))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_7r2arbmg = np.random.uniform(0.0, 1.0, size=(6, 2)).astype(np.float32)
v_0_7r2arbmg = tvm.runtime.tensor(np_v_0_7r2arbmg, device=tvm.cuda())
np_v_1_vpmbugfg = np.random.uniform(0.0, 1.0, size=(3, 6)).astype(np.float32)
v_1_vpmbugfg = tvm.runtime.tensor(np_v_1_vpmbugfg, device=tvm.cuda())
np_v_2_3d2a8c4s = np.random.uniform(0.0, 1.0, size=(1, 2, 5)).astype(np.float32)
v_2_3d2a8c4s = tvm.runtime.tensor(np_v_2_3d2a8c4s, device=tvm.cuda())
np_v_3_45wfib3u = np.random.uniform(0.0, 1.0, size=(4, 6)).astype(np.float32)
v_3_45wfib3u = tvm.runtime.tensor(np_v_3_45wfib3u, device=tvm.cuda())
np_v_4_hr5bpypw = np.random.uniform(0.0, 1.0, size=(5, 6, 5, 6)).astype(np.float32)
v_4_hr5bpypw = tvm.runtime.tensor(np_v_4_hr5bpypw, device=tvm.cuda())
np_v_5_3cbxpfet = np.random.uniform(0.0, 1.0, size=(6, 2, 3)).astype(np.float32)
v_5_3cbxpfet = tvm.runtime.tensor(np_v_5_3cbxpfet, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_0_7r2arbmg, v_1_vpmbugfg, v_2_3d2a8c4s, v_3_45wfib3u, v_4_hr5bpypw, v_5_3cbxpfet)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_0 -> graph_1
_prev_out = tvm_result_0 if not hasattr(tvm_result_0, 'numpy') else [tvm_result_0]
v_0_7r2arbmg = _prev_out[0]
v_1_vpmbugfg = _prev_out[1]
v_2_3d2a8c4s = _prev_out[2]
v_3_45wfib3u = _prev_out[3]
v_7_duz9zv74 = _prev_out[4]
v_9_u485czx2 = _prev_out[5]
v_10_pj1kq3oj = _prev_out[6]
v_11_g91lb1jv = _prev_out[7]

tvm_result_1 = vm["graph_1"](v_0_7r2arbmg, v_1_vpmbugfg, v_2_3d2a8c4s, v_3_45wfib3u, v_7_duz9zv74, v_9_u485czx2, v_10_pj1kq3oj, v_11_g91lb1jv)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_1 -> graph_2
_prev_out = tvm_result_1 if not hasattr(tvm_result_1, 'numpy') else [tvm_result_1]
v_0_7r2arbmg = _prev_out[0]
v_1_vpmbugfg = _prev_out[1]
v_2_3d2a8c4s = _prev_out[2]
v_3_45wfib3u = _prev_out[3]
v_9_u485czx2 = _prev_out[4]
v_10_pj1kq3oj = _prev_out[5]
v_12_9wfuy2n1 = _prev_out[6]
v_13_qni84nxx = _prev_out[7]
v_16_qylh6us1 = _prev_out[8]
v_19_rh3ku3xu = _prev_out[9]
v_20_wfk414qz = _prev_out[10]
v_21_k6ln1v56 = _prev_out[11]
v_22_mzxbu99v = _prev_out[12]
v_27_66u8tr3g = _prev_out[13]
v_29_g9kntm6y = _prev_out[14]
v_30_wehyi3np = _prev_out[15]
v_31_rqfxsnl9 = _prev_out[16]

tvm_result_2 = vm["graph_2"](v_0_7r2arbmg, v_1_vpmbugfg, v_2_3d2a8c4s, v_3_45wfib3u, v_9_u485czx2, v_10_pj1kq3oj, v_12_9wfuy2n1, v_13_qni84nxx, v_16_qylh6us1, v_19_rh3ku3xu, v_20_wfk414qz, v_21_k6ln1v56, v_22_mzxbu99v, v_27_66u8tr3g, v_29_g9kntm6y, v_30_wehyi3np, v_31_rqfxsnl9)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_2 -> graph_3
_prev_out = tvm_result_2 if not hasattr(tvm_result_2, 'numpy') else [tvm_result_2]
v_0_7r2arbmg = _prev_out[0]
v_1_vpmbugfg = _prev_out[1]
v_2_3d2a8c4s = _prev_out[2]
v_3_45wfib3u = _prev_out[3]
v_9_u485czx2 = _prev_out[4]
v_10_pj1kq3oj = _prev_out[5]
v_12_9wfuy2n1 = _prev_out[6]
v_13_qni84nxx = _prev_out[7]
v_16_qylh6us1 = _prev_out[8]
v_19_rh3ku3xu = _prev_out[9]
v_20_wfk414qz = _prev_out[10]
v_22_mzxbu99v = _prev_out[11]
v_27_66u8tr3g = _prev_out[12]
v_29_g9kntm6y = _prev_out[13]
v_30_wehyi3np = _prev_out[14]
v_33_bte52emv = _prev_out[15]
v_36_fuez9nkx = _prev_out[16]
v_37_08wuac4g = _prev_out[17]
v_38_g9qeaj9p = _prev_out[18]
v_41_mqil414w = _prev_out[19]
v_42_7cmn7xvz = _prev_out[20]
v_43_g3lzv8dn = _prev_out[21]
v_45_m34m0081 = _prev_out[22]
v_47_qth0qtx5 = _prev_out[23]
v_48_n6fy6a9d = _prev_out[24]
v_49_dzf74hph = _prev_out[25]
v_50_j7bl4ss6 = _prev_out[26]
v_52_9ocst2f2 = _prev_out[27]
v_53_17abqysz = _prev_out[28]
v_54_2ifvorj6 = _prev_out[29]
v_55_fp74y78n = _prev_out[30]
v_56_mtyyvls1 = _prev_out[31]
v_57_4la34q8b = _prev_out[32]
v_59_4ig4zr9p = _prev_out[33]
v_60_e671cxqj = _prev_out[34]
v_61_0lqo5vn8 = _prev_out[35]

tvm_result_3 = vm["graph_3"](v_0_7r2arbmg, v_1_vpmbugfg, v_2_3d2a8c4s, v_3_45wfib3u, v_9_u485czx2, v_10_pj1kq3oj, v_12_9wfuy2n1, v_13_qni84nxx, v_16_qylh6us1, v_19_rh3ku3xu, v_20_wfk414qz, v_22_mzxbu99v, v_27_66u8tr3g, v_29_g9kntm6y, v_30_wehyi3np, v_33_bte52emv, v_36_fuez9nkx, v_37_08wuac4g, v_38_g9qeaj9p, v_41_mqil414w, v_42_7cmn7xvz, v_43_g3lzv8dn, v_45_m34m0081, v_47_qth0qtx5, v_48_n6fy6a9d, v_49_dzf74hph, v_50_j7bl4ss6, v_52_9ocst2f2, v_53_17abqysz, v_54_2ifvorj6, v_55_fp74y78n, v_56_mtyyvls1, v_57_4la34q8b, v_59_4ig4zr9p, v_60_e671cxqj, v_61_0lqo5vn8)
# Print output
if hasattr(tvm_result_3, 'numpy'):
    _arr = tvm_result_3.numpy()
    print(f"[TVM-OUT] graph_3: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_3)):
        _arr = tvm_result_3[_tvmi].numpy()
        print(f"[TVM-OUT] graph_3[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_3 -> graph_4
_prev_out = tvm_result_3 if not hasattr(tvm_result_3, 'numpy') else [tvm_result_3]
v_0_7r2arbmg = _prev_out[0]
v_1_vpmbugfg = _prev_out[1]
v_2_3d2a8c4s = _prev_out[2]
v_3_45wfib3u = _prev_out[3]
v_9_u485czx2 = _prev_out[4]
v_10_pj1kq3oj = _prev_out[5]
v_12_9wfuy2n1 = _prev_out[6]
v_13_qni84nxx = _prev_out[7]
v_16_qylh6us1 = _prev_out[8]
v_19_rh3ku3xu = _prev_out[9]
v_20_wfk414qz = _prev_out[10]
v_22_mzxbu99v = _prev_out[11]
v_27_66u8tr3g = _prev_out[12]
v_29_g9kntm6y = _prev_out[13]
v_30_wehyi3np = _prev_out[14]
v_33_bte52emv = _prev_out[15]
v_36_fuez9nkx = _prev_out[16]
v_37_08wuac4g = _prev_out[17]
v_38_g9qeaj9p = _prev_out[18]
v_41_mqil414w = _prev_out[19]
v_42_7cmn7xvz = _prev_out[20]
v_43_g3lzv8dn = _prev_out[21]
v_45_m34m0081 = _prev_out[22]
v_47_qth0qtx5 = _prev_out[23]
v_48_n6fy6a9d = _prev_out[24]
v_50_j7bl4ss6 = _prev_out[25]
v_52_9ocst2f2 = _prev_out[26]
v_53_17abqysz = _prev_out[27]
v_55_fp74y78n = _prev_out[28]
v_56_mtyyvls1 = _prev_out[29]
v_57_4la34q8b = _prev_out[30]
v_59_4ig4zr9p = _prev_out[31]
v_60_e671cxqj = _prev_out[32]
v_62_f3qeorhx = _prev_out[33]
v_63_jlexkd0a = _prev_out[34]
v_65_w6haru9z = _prev_out[35]
v_67_6r5her4x = _prev_out[36]
v_70_230vhzys = _prev_out[37]
v_73_7u0nzl6e = _prev_out[38]
v_74_sg11v2p5 = _prev_out[39]
v_75_snnkmetr = _prev_out[40]
v_76_u5qjx04f = _prev_out[41]
v_78_nl88di4l = _prev_out[42]
v_79_dh7xsiwu = _prev_out[43]
v_83_w94n7fuh = _prev_out[44]
v_85_kjaeg8z2 = _prev_out[45]
v_86_wcvz941k = _prev_out[46]

tvm_result_4 = vm["graph_4"](v_0_7r2arbmg, v_1_vpmbugfg, v_2_3d2a8c4s, v_3_45wfib3u, v_9_u485czx2, v_10_pj1kq3oj, v_12_9wfuy2n1, v_13_qni84nxx, v_16_qylh6us1, v_19_rh3ku3xu, v_20_wfk414qz, v_22_mzxbu99v, v_27_66u8tr3g, v_29_g9kntm6y, v_30_wehyi3np, v_33_bte52emv, v_36_fuez9nkx, v_37_08wuac4g, v_38_g9qeaj9p, v_41_mqil414w, v_42_7cmn7xvz, v_43_g3lzv8dn, v_45_m34m0081, v_47_qth0qtx5, v_48_n6fy6a9d, v_50_j7bl4ss6, v_52_9ocst2f2, v_53_17abqysz, v_55_fp74y78n, v_56_mtyyvls1, v_57_4la34q8b, v_59_4ig4zr9p, v_60_e671cxqj, v_62_f3qeorhx, v_63_jlexkd0a, v_65_w6haru9z, v_67_6r5her4x, v_70_230vhzys, v_73_7u0nzl6e, v_74_sg11v2p5, v_75_snnkmetr, v_76_u5qjx04f, v_78_nl88di4l, v_79_dh7xsiwu, v_83_w94n7fuh, v_85_kjaeg8z2, v_86_wcvz941k)
# Print output
if hasattr(tvm_result_4, 'numpy'):
    _arr = tvm_result_4.numpy()
    print(f"[TVM-OUT] graph_4: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_4)):
        _arr = tvm_result_4[_tvmi].numpy()
        print(f"[TVM-OUT] graph_4[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
