# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_084tnf5t, v_1_7upuje1u, v_2_khzc2fu6, v_3_hv5rylru, v_4_4hzo2pdb, v_5_u86k21ej, v_6_pvfq4mmr):
        v_7_1jbiclbl = F.elu(v_6_pvfq4mmr, alpha=1.24)
        v_8_u9vs1n5c = torch.log(v_6_pvfq4mmr)
        v_9_2ir05z7f = torch.tanh(v_7_1jbiclbl)
        v_10_alcjvek0 = torch.triu(v_7_1jbiclbl)
        v_11_c9iotx6v = torch.exp(v_7_1jbiclbl)
        v_12_upv83is1 = F.silu(v_7_1jbiclbl)
        v_13_joqulehl = F.mish(v_7_1jbiclbl)
        v_14_yohqdfyh = torch.add(v_7_1jbiclbl, v_11_c9iotx6v)
        v_15_const = torch.zeros((24, 57, 37), dtype=torch.float32, device="cpu")
        v_15_8jtovdkg = torch.maximum(v_13_joqulehl, v_15_const)
        v_16_dth56jg4 = F.softmax(v_14_yohqdfyh, dim=-1)
        v_17_xbgxhgyw = F.relu(v_14_yohqdfyh)
        v_18_bbnjyzgd = torch.reciprocal(v_14_yohqdfyh)
        v_19_zgn43bgi = F.mish(v_14_yohqdfyh)
        v_20_bt1gqf0h = v_14_yohqdfyh.to(torch.float32)
        v_21_t7mv1xch = torch.transpose(v_14_yohqdfyh, 1, 2)
        v_22_s3uujgih = F.elu(v_14_yohqdfyh, alpha=0.57)
        v_23_ncj9xp67 = F.hardtanh(v_14_yohqdfyh, min_val=-0.79, max_val=2.01)
        v_24_whpz7u9e = torch.arange(0, 110, dtype=torch.float32, device="cpu")
        v_25_vdr0wwwx = F.silu(v_14_yohqdfyh)
        v_26_qk6hnmdm = torch.sum(v_14_yohqdfyh, dim=-1, keepdim=False)
        v_27_t59doisz = torch.floor(v_14_yohqdfyh)
        v_28_const = torch.zeros((24, 57), dtype=torch.float32, device="cpu")
        v_28_emht5gqc = torch.div(v_26_qk6hnmdm, v_28_const)
        v_29_mn5g2wt6 = torch.log2(v_26_qk6hnmdm)
        v_30_kvim7tg0 = torch.min(v_26_qk6hnmdm, dim=-1, keepdim=False).values
        v_31_udvjl3oy = torch.triu(v_26_qk6hnmdm)
        v_32_const = torch.zeros((24, 57), dtype=torch.float32, device="cpu")
        v_32_lbwiq51r = torch.add(v_26_qk6hnmdm, v_32_const)
        v_33_8yzpzcq8 = torch.abs(v_26_qk6hnmdm)
        v_34_lss6orq3 = torch.log2(v_26_qk6hnmdm)
        v_35_26gvuie7 = torch.sum(v_26_qk6hnmdm, dim=-1, keepdim=False)
        v_36_muyr8wg4 = torch.abs(v_26_qk6hnmdm)
        v_37_fd9052zc = torch.log(v_26_qk6hnmdm)
        v_38_rn0nffhn = torch.transpose(v_26_qk6hnmdm, 0, 1)
        v_39_7dt920ix = torch.clamp(v_26_qk6hnmdm, min=-0.07, max=1.75)
        v_40_unl54rp2 = torch.sub(v_26_qk6hnmdm, v_39_7dt920ix)
        v_41_const = torch.zeros((24, 57), dtype=torch.float32, device="cpu")
        v_41_sg9qy0q1 = torch.maximum(v_26_qk6hnmdm, v_41_const)
        v_42_3p29mkig = torch.exp(v_26_qk6hnmdm)
        v_43_zz1dtanh = torch.exp(v_26_qk6hnmdm)
        v_44_o8zy8h7c = v_42_3p29mkig.to(torch.float32)
        v_45_9sk3v9jo = torch.tile(v_43_zz1dtanh, [1] * 2)
        v_46_bujzcidp = torch.ones((16, 4, 27, 29), dtype=torch.float32, device="cpu")
        v_47_2hd2xp3p = torch.reciprocal(v_44_o8zy8h7c)
        v_48_kb5ece80 = torch.abs(v_44_o8zy8h7c)
        v_49_wpb6nrbo = torch.arange(0, 64, dtype=torch.float32, device="cpu")
        v_50_hxh8squh = torch.arange(0, 238, dtype=torch.float32, device="cpu")
        v_51_u96b7jr2 = torch.max(v_48_kb5ece80, dim=-1, keepdim=False).values
        v_52_zms460a7 = torch.unsqueeze(v_48_kb5ece80, 0)
        v_53_mfdh22sm = v_48_kb5ece80.to(torch.float32)
        return (v_0_084tnf5t, v_1_7upuje1u, v_2_khzc2fu6, v_3_hv5rylru, v_4_4hzo2pdb, v_5_u86k21ej, v_8_u9vs1n5c, v_9_2ir05z7f, v_10_alcjvek0, v_12_upv83is1, v_15_8jtovdkg, v_16_dth56jg4, v_17_xbgxhgyw, v_18_bbnjyzgd, v_19_zgn43bgi, v_20_bt1gqf0h, v_21_t7mv1xch, v_22_s3uujgih, v_23_ncj9xp67, v_24_whpz7u9e, v_25_vdr0wwwx, v_27_t59doisz, v_28_emht5gqc, v_29_mn5g2wt6, v_30_kvim7tg0, v_31_udvjl3oy, v_32_lbwiq51r, v_33_8yzpzcq8, v_34_lss6orq3, v_35_26gvuie7, v_36_muyr8wg4, v_37_fd9052zc, v_38_rn0nffhn, v_40_unl54rp2, v_41_sg9qy0q1, v_45_9sk3v9jo, v_46_bujzcidp, v_47_2hd2xp3p, v_49_wpb6nrbo, v_50_hxh8squh, v_51_u96b7jr2, v_52_zms460a7, v_53_mfdh22sm)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_084tnf5t = torch.randn(14, 14, 27, 16, dtype=torch.float32, device="cpu")
v_1_7upuje1u = torch.randn(29, 19, dtype=torch.float32, device="cpu")
v_2_khzc2fu6 = torch.randn(6, 48, 18, dtype=torch.float32, device="cpu")
v_3_hv5rylru = torch.randn(12, 38, 15, dtype=torch.float32, device="cpu")
v_4_4hzo2pdb = torch.randn(8, 43, dtype=torch.float32, device="cpu")
v_5_u86k21ej = torch.randn(24, 56, dtype=torch.float32, device="cpu")
v_6_pvfq4mmr = torch.randn(24, 57, 37, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_084tnf5t, v_1_7upuje1u, v_2_khzc2fu6, v_3_hv5rylru, v_4_4hzo2pdb, v_5_u86k21ej, v_6_pvfq4mmr)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_084tnf5t, v_1_7upuje1u, v_2_khzc2fu6, v_3_hv5rylru, v_4_4hzo2pdb, v_5_u86k21ej, v_6_pvfq4mmr)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
