# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_hcn4s4yt, v_1_ad1rfz5p, v_2_v1xvx5h0, v_3_xtruwrpo, v_4_23r2m7ap, v_5_tgh3c1j3, v_6_tk25764x):
        v_7_hha5scr1 = torch.mean(v_6_tk25764x.float(), dim=-1, keepdim=False)
        v_8_ta67w3hv = F.silu(v_6_tk25764x)
        v_9_99leehkd = torch.log(v_6_tk25764x)
        v_10_9pm2u7no = torch.sub(v_6_tk25764x, v_8_ta67w3hv)
        v_11_const = torch.zeros((16, 15, 28, 11), dtype=torch.float32, device="cpu")
        v_11_ttwlz2v8 = torch.minimum(v_9_99leehkd, v_11_const)
        v_12_const = torch.zeros((16, 15, 28, 11), dtype=torch.float32, device="cpu")
        v_12_s8zf4o8r = torch.sub(v_9_99leehkd, v_12_const)
        v_13_qdtksd5p = torch.log(v_9_99leehkd)
        v_14_t03o0uui = v_9_99leehkd.to(torch.float32)
        v_15_njwgsksh = torch.zeros((14, 53), dtype=torch.float32, device="cpu")
        v_16_x6f49gz6 = torch.ceil(v_13_qdtksd5p)
        v_17_yk4uljun = torch.full((47, 35), 0.0, dtype=torch.float32, device="cpu")
        v_18_ja6rl09a = torch.unsqueeze(v_13_qdtksd5p, 0)
        v_19_tohorisf = torch.ceil(v_13_qdtksd5p)
        v_20_t0dre5tm = torch.pow(v_13_qdtksd5p, v_8_ta67w3hv)
        v_21_u1spci2i = v_19_tohorisf[:max(1, v_19_tohorisf.shape[0]//2)]
        v_22_9ekm7xm5 = torch.zeros((18, 14, 11, 20), dtype=torch.float32, device="cpu")
        v_23_x0d4tkxf = torch.abs(v_19_tohorisf)
        v_24_w7pl0avk = torch.max(v_22_9ekm7xm5, dim=-1, keepdim=False).values
        v_25_o2wb4q9a = torch.triu(v_23_x0d4tkxf)
        v_26_5hd57qdd = torch.tile(v_24_w7pl0avk, [1] * 3)
        v_27_e68816hk = torch.gather(v_24_w7pl0avk, 0, torch.zeros((min(18, 1), min(14, 1), min(11, 1)), dtype=torch.int64, device=v_24_w7pl0avk.device))
        v_28_fxhq2etj = F.silu(v_24_w7pl0avk)
        v_29_468m34xd = F.softmax(v_27_e68816hk, dim=-1)
        v_30_z2xqqex7 = torch.pow(v_27_e68816hk, v_1_ad1rfz5p)
        v_31_dwqklijz = torch.tanh(v_27_e68816hk)
        v_32_t72jwwz1 = torch.ceil(v_30_z2xqqex7)
        v_33_1wl4r35g = F.gelu(v_30_z2xqqex7)
        v_34_5188uhfl = torch.exp(v_30_z2xqqex7)
        v_35_pduv2eeb = v_30_z2xqqex7.to(torch.float32)
        v_36_4byqwffc = v_30_z2xqqex7.to(torch.float32)
        v_37_ceudm8ec = torch.ceil(v_35_pduv2eeb)
        v_38_7ru8pdx5 = F.silu(v_36_4byqwffc)
        v_39_8202lgfg = torch.tanh(v_36_4byqwffc)
        v_40_lfzw24ey = F.silu(v_36_4byqwffc)
        v_41_3bcvy940 = v_36_4byqwffc.to(torch.float32)
        v_42_xyautqdb = torch.sigmoid(v_36_4byqwffc)
        v_43_lmkvztlf = torch.abs(v_36_4byqwffc)
        v_44_6dui5wdx = torch.sigmoid(v_42_xyautqdb)
        v_45_ltpozks3 = torch.tanh(v_42_xyautqdb)
        v_46_const = torch.zeros((1, 2, 50), dtype=torch.float32, device="cpu")
        v_46_qf3q5bre = torch.div(v_42_xyautqdb, v_46_const)
        v_47_const = torch.zeros((1, 2, 50), dtype=torch.float32, device="cpu")
        v_47_ugsrcdc6 = torch.add(v_42_xyautqdb, v_47_const)
        v_48_jmbtqd7c = torch.triu(v_42_xyautqdb)
        v_49_jtwozt9b = torch.exp(v_42_xyautqdb)
        v_50_j0u6o2wp = torch.zeros((14, 16, 20, 13), dtype=torch.float32, device="cpu")
        v_51_oeegwegx = torch.sum(v_49_jtwozt9b, dim=-1, keepdim=False)
        v_52_const = torch.zeros((1, 2, 50), dtype=torch.float32, device="cpu")
        v_52_c87q2b9q = torch.sub(v_49_jtwozt9b, v_52_const)
        v_53_j6mdoreh = torch.neg(v_51_oeegwegx)
        v_54_yxylger0 = torch.sqrt(v_51_oeegwegx)
        v_55_smp1f8wu = torch.transpose(v_51_oeegwegx, 0, 1)
        v_56_x64xhdjy = torch.max(v_51_oeegwegx, dim=-1, keepdim=False).values
        v_57_5l0a64us = v_51_oeegwegx[:max(1, v_51_oeegwegx.shape[0]//2)]
        v_58_e6ztp11b = torch.tril(v_51_oeegwegx)
        v_59_const = torch.zeros((1, 2), dtype=torch.float32, device="cpu")
        v_59_odx8z0uu = torch.div(v_51_oeegwegx, v_59_const)
        v_60_wgd9ky64 = F.gelu(v_58_e6ztp11b)
        v_61_mj72ni4w = torch.arange(0, 232, dtype=torch.float32, device="cpu")
        v_62_c66n1eem = torch.unsqueeze(v_58_e6ztp11b, 0)
        v_63_7oubqjbz = torch.exp(v_58_e6ztp11b)
        v_64_const = torch.zeros((1, 2), dtype=torch.float32, device="cpu")
        v_64_zg4h2d02 = torch.pow(v_58_e6ztp11b, v_64_const)
        v_65_o8ml1l9t = v_63_7oubqjbz[:max(1, v_63_7oubqjbz.shape[0]//2)]
        v_66_14sxcqaw = torch.ceil(v_63_7oubqjbz)
        v_67_stxvc56q = torch.min(v_63_7oubqjbz, dim=-1, keepdim=False).values
        v_68_gnlamkth = torch.arange(0, 85, dtype=torch.float32, device="cpu")
        v_69_const = torch.zeros((1, 2), dtype=torch.float32, device="cpu")
        v_69_rzn0b1cj = torch.minimum(v_66_14sxcqaw, v_69_const)
        return (v_0_hcn4s4yt, v_2_v1xvx5h0, v_3_xtruwrpo, v_4_23r2m7ap, v_5_tgh3c1j3, v_7_hha5scr1, v_10_9pm2u7no, v_11_ttwlz2v8, v_12_s8zf4o8r, v_14_t03o0uui, v_15_njwgsksh, v_16_x6f49gz6, v_17_yk4uljun, v_18_ja6rl09a, v_20_t0dre5tm, v_21_u1spci2i, v_25_o2wb4q9a, v_26_5hd57qdd, v_28_fxhq2etj, v_29_468m34xd, v_31_dwqklijz, v_32_t72jwwz1, v_33_1wl4r35g, v_34_5188uhfl, v_37_ceudm8ec, v_38_7ru8pdx5, v_39_8202lgfg, v_40_lfzw24ey, v_41_3bcvy940, v_43_lmkvztlf, v_44_6dui5wdx, v_45_ltpozks3, v_46_qf3q5bre, v_47_ugsrcdc6, v_48_jmbtqd7c, v_50_j0u6o2wp, v_52_c87q2b9q, v_53_j6mdoreh, v_54_yxylger0, v_55_smp1f8wu, v_56_x64xhdjy, v_57_5l0a64us, v_59_odx8z0uu, v_60_wgd9ky64, v_61_mj72ni4w, v_62_c66n1eem, v_64_zg4h2d02, v_65_o8ml1l9t, v_67_stxvc56q, v_68_gnlamkth, v_69_rzn0b1cj)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_hcn4s4yt = torch.randn(36, 61, 32, dtype=torch.float32, device="cpu")
v_1_ad1rfz5p = torch.randn(2, 50, dtype=torch.float32, device="cpu")
v_2_v1xvx5h0 = torch.randn(59, 2, 27, dtype=torch.float32, device="cpu")
v_3_xtruwrpo = torch.randn(47, 3, 8, dtype=torch.float32, device="cpu")
v_4_23r2m7ap = torch.randn(14, 16, 14, 18, dtype=torch.float32, device="cpu")
v_5_tgh3c1j3 = torch.randn(25, 35, 30, dtype=torch.float32, device="cpu")
v_6_tk25764x = torch.randn(16, 15, 28, 11, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_hcn4s4yt, v_1_ad1rfz5p, v_2_v1xvx5h0, v_3_xtruwrpo, v_4_23r2m7ap, v_5_tgh3c1j3, v_6_tk25764x)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_hcn4s4yt, v_1_ad1rfz5p, v_2_v1xvx5h0, v_3_xtruwrpo, v_4_23r2m7ap, v_5_tgh3c1j3, v_6_tk25764x)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
