# Auto-generated by aiFuzzer
# Source: generated

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_oyecu90g_var = relax.Var("v_0_oyecu90g", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 8, 3]), dtype="float32"))
    v_1_w35jct7h_var = relax.Var("v_1_w35jct7h", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 4]), dtype="float32"))
    v_2_83tsnspu_var = relax.Var("v_2_83tsnspu", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 7, 6]), dtype="float32"))
    v_3_y3gm1rr5_var = relax.Var("v_3_y3gm1rr5", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 7, 8, 2]), dtype="float32"))
    with bb.function("graph_0", [v_0_oyecu90g_var, v_1_w35jct7h_var, v_2_83tsnspu_var, v_3_y3gm1rr5_var]):
        # input: [6, 7, 8, 2]
        # output: [6, 7, 1, 2]
        v_4_7e3dqaqw = bb.emit(relax.op.min(v_3_y3gm1rr5_var, axis=[2], keepdims=True))
        assert str(v_4_7e3dqaqw.struct_info.shape) == "R.shape([6, 7, 1, 2])", f"Shape mismatch: expected R.shape([6, 7, 1, 2]), got {v_4_7e3dqaqw.struct_info.shape}"
        # input: [6, 7, 8, 2]
        # output: [6, 7, 8, 2]
        v_5_eu7yjrqs = bb.emit(relax.op.negative(v_3_y3gm1rr5_var))
        assert str(v_5_eu7yjrqs.struct_info.shape) == "R.shape([6, 7, 8, 2])", f"Shape mismatch: expected R.shape([6, 7, 8, 2]), got {v_5_eu7yjrqs.struct_info.shape}"
        # input: [6, 7, 8, 2]
        # output: [24, 4, 7, 1]
        v_6_ztn1x0d5 = bb.emit(relax.op.reshape(v_5_eu7yjrqs, relax.ShapeExpr([24, 4, 7, 1])))
        assert str(v_6_ztn1x0d5.struct_info.shape) == "R.shape([24, 4, 7, 1])", f"Shape mismatch: expected R.shape([24, 4, 7, 1]), got {v_6_ztn1x0d5.struct_info.shape}"
        # input: [4, 5, 7, 6]
        # output: [840]
        v_7_1sagu2fk = bb.emit(relax.op.reshape(v_2_83tsnspu_var, relax.ShapeExpr([840])))
        assert str(v_7_1sagu2fk.struct_info.shape) == "R.shape([840])", f"Shape mismatch: expected R.shape([840]), got {v_7_1sagu2fk.struct_info.shape}"
        # input: [840]
        # output: [16]
        v_8_2sfyzfdf = bb.emit(relax.op.strided_slice(v_7_1sagu2fk, axes=[0], begin=[0], end=[16]))
        assert str(v_8_2sfyzfdf.struct_info.shape) == "R.shape([16])", f"Shape mismatch: expected R.shape([16]), got {v_8_2sfyzfdf.struct_info.shape}"
        # input: [16]
        # output: [4, 4]
        v_9_4l331ta9 = bb.emit(relax.op.reshape(v_8_2sfyzfdf, relax.ShapeExpr([4, 4])))
        assert str(v_9_4l331ta9.struct_info.shape) == "R.shape([4, 4])", f"Shape mismatch: expected R.shape([4, 4]), got {v_9_4l331ta9.struct_info.shape}"
        # input: [4, 4], [4, 4]
        # output: [4, 4]
        v_7_l9kq2m39 = bb.emit(relax.op.power(relax.op.astype(v_1_w35jct7h_var, dtype="float32"), relax.op.astype(v_9_4l331ta9, dtype="float32")))
        assert str(v_7_l9kq2m39.struct_info.shape) == "R.shape([4, 4])", f"Shape mismatch: expected R.shape([4, 4]), got {v_7_l9kq2m39.struct_info.shape}"
        # input: [4, 4]
        # output: [4, 4]
        v_8_vq72dr13 = bb.emit(relax.op.clip(v_7_l9kq2m39, 0, 1))
        assert str(v_8_vq72dr13.struct_info.shape) == "R.shape([4, 4])", f"Shape mismatch: expected R.shape([4, 4]), got {v_8_vq72dr13.struct_info.shape}"
        # input: [4, 4]
        # output: [1, 4, 4]
        v_9_ckwnm871 = bb.emit(relax.op.expand_dims(v_8_vq72dr13, axis=0))
        assert str(v_9_ckwnm871.struct_info.shape) == "R.shape([1, 4, 4])", f"Shape mismatch: expected R.shape([1, 4, 4]), got {v_9_ckwnm871.struct_info.shape}"
        # input: [1, 4, 4]
        # output: [1, 1, 4, 4]
        v_10_79xjbjww = bb.emit(relax.op.expand_dims(v_9_ckwnm871, axis=0))
        assert str(v_10_79xjbjww.struct_info.shape) == "R.shape([1, 1, 4, 4])", f"Shape mismatch: expected R.shape([1, 1, 4, 4]), got {v_10_79xjbjww.struct_info.shape}"
        # input: [4, 4]
        # output: [1, 4, 4]
        v_11_bm5g97lz = bb.emit(relax.op.expand_dims(v_1_w35jct7h_var, axis=0))
        assert str(v_11_bm5g97lz.struct_info.shape) == "R.shape([1, 4, 4])", f"Shape mismatch: expected R.shape([1, 4, 4]), got {v_11_bm5g97lz.struct_info.shape}"
        # input: [1, 4, 4]
        # output: [1, 1, 4, 4]
        v_12_qn0glstp = bb.emit(relax.op.expand_dims(v_11_bm5g97lz, axis=0))
        assert str(v_12_qn0glstp.struct_info.shape) == "R.shape([1, 1, 4, 4])", f"Shape mismatch: expected R.shape([1, 1, 4, 4]), got {v_12_qn0glstp.struct_info.shape}"
        # input: [1, 1, 4, 4], [1, 1, 4, 4]
        # output: [1, 1, 3, 3]
        v_9_yjvsu8a0 = bb.emit(relax.op.nn.conv2d(v_10_79xjbjww, v_12_qn0glstp, strides=[2, 2], padding=[2, 2], dilation=[1, 1], groups=1))
        assert str(v_9_yjvsu8a0.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_9_yjvsu8a0.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_10_7xn43daa = bb.emit(relax.op.nn.avg_pool2d(v_9_yjvsu8a0, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_10_7xn43daa.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_10_7xn43daa.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_11_cwd76xq1 = bb.emit(relax.op.nn.relu(v_10_7xn43daa))
        assert str(v_11_cwd76xq1.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_11_cwd76xq1.struct_info.shape}"
        bb.emit_func_output((v_0_oyecu90g_var, v_4_7e3dqaqw, v_6_ztn1x0d5, v_11_cwd76xq1))

    v_0_oyecu90g_var = relax.Var("v_0_oyecu90g", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 8, 3]), dtype="float32"))
    v_4_7e3dqaqw_var = relax.Var("v_4_7e3dqaqw", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 7, 1, 2]), dtype="float32"))
    v_6_ztn1x0d5_var = relax.Var("v_6_ztn1x0d5", relax.TensorStructInfo(shape=relax.ShapeExpr([24, 4, 7, 1]), dtype="float32"))
    v_11_cwd76xq1_var = relax.Var("v_11_cwd76xq1", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 3]), dtype="float32"))
    v_12_8osve105_var = relax.Var("v_12_8osve105", relax.TensorStructInfo(shape=relax.ShapeExpr([7, 4, 6]), dtype="float32"))
    with bb.function("graph_1", [v_0_oyecu90g_var, v_4_7e3dqaqw_var, v_6_ztn1x0d5_var, v_11_cwd76xq1_var, v_12_8osve105_var]):
        # input: [7, 4, 6]
        # output: [7, 4, 6]
        v_13_im14vqzm = bb.emit(relax.op.round(v_12_8osve105_var))
        assert str(v_13_im14vqzm.struct_info.shape) == "R.shape([7, 4, 6])", f"Shape mismatch: expected R.shape([7, 4, 6]), got {v_13_im14vqzm.struct_info.shape}"
        # input: [7, 4, 6]
        # output: [1, 7, 4, 6]
        v_14_coxrchf5 = bb.emit(relax.op.expand_dims(v_13_im14vqzm, axis=0))
        assert str(v_14_coxrchf5.struct_info.shape) == "R.shape([1, 7, 4, 6])", f"Shape mismatch: expected R.shape([1, 7, 4, 6]), got {v_14_coxrchf5.struct_info.shape}"
        # input: [7, 4, 6]
        # output: [1, 7, 4, 6]
        v_15_hv20cfec = bb.emit(relax.op.expand_dims(v_12_8osve105_var, axis=0))
        assert str(v_15_hv20cfec.struct_info.shape) == "R.shape([1, 7, 4, 6])", f"Shape mismatch: expected R.shape([1, 7, 4, 6]), got {v_15_hv20cfec.struct_info.shape}"
        # input: [1, 7, 4, 6], [1, 7, 4, 6]
        # output: [1, 1, 2, 2]
        v_14_q8kxp1t0 = bb.emit(relax.op.nn.conv2d(v_14_coxrchf5, v_15_hv20cfec, strides=[3, 3], padding=[2, 2], dilation=[1, 1], groups=1))
        assert str(v_14_q8kxp1t0.struct_info.shape) == "R.shape([1, 1, 2, 2])", f"Shape mismatch: expected R.shape([1, 1, 2, 2]), got {v_14_q8kxp1t0.struct_info.shape}"
        # input: [1, 1, 2, 2]
        # output: [1, 1, 2, 2]
        v_15_9wuvlcts = bb.emit(relax.op.nn.silu(v_14_q8kxp1t0))
        assert str(v_15_9wuvlcts.struct_info.shape) == "R.shape([1, 1, 2, 2])", f"Shape mismatch: expected R.shape([1, 1, 2, 2]), got {v_15_9wuvlcts.struct_info.shape}"
        # input: 
        # output: [146]
        v_16_y4tubzx5 = bb.emit(relax.op.arange(0, 146, dtype="float32"))
        assert str(v_16_y4tubzx5.struct_info.shape) == "R.shape([146])", f"Shape mismatch: expected R.shape([146]), got {v_16_y4tubzx5.struct_info.shape}"
        # input: 
        # output: [150]
        v_17_prrna8ce = bb.emit(relax.op.arange(0, 150, dtype="float32"))
        assert str(v_17_prrna8ce.struct_info.shape) == "R.shape([150])", f"Shape mismatch: expected R.shape([150]), got {v_17_prrna8ce.struct_info.shape}"
        # input: [24, 4, 7, 1]
        # output: [24, 4, 14, 2]
        v_18_v3yiiydo = bb.emit(relax.op.image.resize2d(v_6_ztn1x0d5_var, relax.ShapeExpr([14, 2]), layout="NCHW"))
        assert str(v_18_v3yiiydo.struct_info.shape) == "R.shape([24, 4, 14, 2])", f"Shape mismatch: expected R.shape([24, 4, 14, 2]), got {v_18_v3yiiydo.struct_info.shape}"
        # input: [24, 4, 14, 2]
        # output: [24, 4, 14, 2]
        v_19_5o1b4imt = bb.emit(relax.op.nn.selu(v_18_v3yiiydo))
        assert str(v_19_5o1b4imt.struct_info.shape) == "R.shape([24, 4, 14, 2])", f"Shape mismatch: expected R.shape([24, 4, 14, 2]), got {v_19_5o1b4imt.struct_info.shape}"
        # input: [150], [24, 4, 7, 1]
        # output: [24, 4, 7, 150]
        v_20_9lrzn686 = bb.emit(relax.op.add(relax.op.astype(v_17_prrna8ce, dtype="float32"), relax.op.astype(v_6_ztn1x0d5_var, dtype="float32")))
        assert str(v_20_9lrzn686.struct_info.shape) == "R.shape([24, 4, 7, 150])", f"Shape mismatch: expected R.shape([24, 4, 7, 150]), got {v_20_9lrzn686.struct_info.shape}"
        # input: 
        # output: [8, 6, 4, 5]
        v_21_qgsna1eq = bb.emit(relax.op.ones(relax.ShapeExpr([8, 6, 4, 5]), dtype="float32"))
        assert str(v_21_qgsna1eq.struct_info.shape) == "R.shape([8, 6, 4, 5])", f"Shape mismatch: expected R.shape([8, 6, 4, 5]), got {v_21_qgsna1eq.struct_info.shape}"
        # input: [24, 4, 7, 150]
        # output: [24, 4, 14, 300]
        v_22_ycwbus4a = bb.emit(relax.op.image.resize2d(v_20_9lrzn686, relax.ShapeExpr([14, 300]), layout="NCHW"))
        assert str(v_22_ycwbus4a.struct_info.shape) == "R.shape([24, 4, 14, 300])", f"Shape mismatch: expected R.shape([24, 4, 14, 300]), got {v_22_ycwbus4a.struct_info.shape}"
        # input: [24, 4, 14, 300]
        # output: [24, 4, 14, 300]
        v_23_2l7qjxh0 = bb.emit(relax.op.cumprod(v_22_ycwbus4a, axis=1))
        assert str(v_23_2l7qjxh0.struct_info.shape) == "R.shape([24, 4, 14, 300])", f"Shape mismatch: expected R.shape([24, 4, 14, 300]), got {v_23_2l7qjxh0.struct_info.shape}"
        bb.emit_func_output((v_0_oyecu90g_var, v_4_7e3dqaqw_var, v_11_cwd76xq1_var, v_15_9wuvlcts, v_16_y4tubzx5, v_19_5o1b4imt, v_21_qgsna1eq, v_23_2l7qjxh0))

    v_0_oyecu90g_var = relax.Var("v_0_oyecu90g", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 8, 3]), dtype="float32"))
    v_4_7e3dqaqw_var = relax.Var("v_4_7e3dqaqw", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 7, 1, 2]), dtype="float32"))
    v_11_cwd76xq1_var = relax.Var("v_11_cwd76xq1", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 3]), dtype="float32"))
    v_15_9wuvlcts_var = relax.Var("v_15_9wuvlcts", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 2, 2]), dtype="float32"))
    v_16_y4tubzx5_var = relax.Var("v_16_y4tubzx5", relax.TensorStructInfo(shape=relax.ShapeExpr([146]), dtype="float32"))
    v_19_5o1b4imt_var = relax.Var("v_19_5o1b4imt", relax.TensorStructInfo(shape=relax.ShapeExpr([24, 4, 14, 2]), dtype="float32"))
    v_21_qgsna1eq_var = relax.Var("v_21_qgsna1eq", relax.TensorStructInfo(shape=relax.ShapeExpr([8, 6, 4, 5]), dtype="float32"))
    v_23_2l7qjxh0_var = relax.Var("v_23_2l7qjxh0", relax.TensorStructInfo(shape=relax.ShapeExpr([24, 4, 14, 300]), dtype="float32"))
    v_24_2wuqvra2_var = relax.Var("v_24_2wuqvra2", relax.TensorStructInfo(shape=relax.ShapeExpr([8, 2, 7, 8]), dtype="float32"))
    with bb.function("graph_2", [v_0_oyecu90g_var, v_4_7e3dqaqw_var, v_11_cwd76xq1_var, v_15_9wuvlcts_var, v_16_y4tubzx5_var, v_19_5o1b4imt_var, v_21_qgsna1eq_var, v_23_2l7qjxh0_var, v_24_2wuqvra2_var]):
        # input: [8, 2, 7, 8]
        # output: [8, 2, 7, 8]
        v_25_bzlcaek6 = bb.emit(relax.op.abs(v_24_2wuqvra2_var))
        assert str(v_25_bzlcaek6.struct_info.shape) == "R.shape([8, 2, 7, 8])", f"Shape mismatch: expected R.shape([8, 2, 7, 8]), got {v_25_bzlcaek6.struct_info.shape}"
        # input: [24, 4, 14, 300]
        # output: [403200]
        v_26_4w2x0yqu = bb.emit(relax.op.reshape(v_23_2l7qjxh0_var, relax.ShapeExpr([403200])))
        assert str(v_26_4w2x0yqu.struct_info.shape) == "R.shape([403200])", f"Shape mismatch: expected R.shape([403200]), got {v_26_4w2x0yqu.struct_info.shape}"
        # input: [403200]
        # output: [146]
        v_27_eh1lx9yc = bb.emit(relax.op.strided_slice(v_26_4w2x0yqu, axes=[0], begin=[0], end=[146]))
        assert str(v_27_eh1lx9yc.struct_info.shape) == "R.shape([146])", f"Shape mismatch: expected R.shape([146]), got {v_27_eh1lx9yc.struct_info.shape}"
        # input: [146]
        # output: [146]
        v_28_8oeyx36x = bb.emit(relax.op.reshape(v_27_eh1lx9yc, relax.ShapeExpr([146])))
        assert str(v_28_8oeyx36x.struct_info.shape) == "R.shape([146])", f"Shape mismatch: expected R.shape([146]), got {v_28_8oeyx36x.struct_info.shape}"
        # input: [146], [146]
        # output: [146]
        v_26_r1qj42ok = bb.emit(relax.op.minimum(relax.op.astype(v_16_y4tubzx5_var, dtype="float32"), relax.op.astype(v_28_8oeyx36x, dtype="float32")))
        assert str(v_26_r1qj42ok.struct_info.shape) == "R.shape([146])", f"Shape mismatch: expected R.shape([146]), got {v_26_r1qj42ok.struct_info.shape}"
        # input: 
        # output: [7, 5]
        v_27_x50sv2i6 = bb.emit(relax.op.full(relax.ShapeExpr([7, 5]), relax.const(0, dtype="float32")))
        assert str(v_27_x50sv2i6.struct_info.shape) == "R.shape([7, 5])", f"Shape mismatch: expected R.shape([7, 5]), got {v_27_x50sv2i6.struct_info.shape}"
        # input: [7, 5]
        # output: [7, 5]
        v_28_q8yp81of = bb.emit(relax.op.divide(relax.op.log(relax.op.astype(v_27_x50sv2i6, dtype="float32")), relax.const(0.6931471805599453, dtype="float32")))
        assert str(v_28_q8yp81of.struct_info.shape) == "R.shape([7, 5])", f"Shape mismatch: expected R.shape([7, 5]), got {v_28_q8yp81of.struct_info.shape}"
        # input: [6, 7, 1, 2]
        # output: [84]
        v_29_vhven9tg = bb.emit(relax.op.reshape(v_4_7e3dqaqw_var, relax.ShapeExpr([84])))
        assert str(v_29_vhven9tg.struct_info.shape) == "R.shape([84])", f"Shape mismatch: expected R.shape([84]), got {v_29_vhven9tg.struct_info.shape}"
        # input: [84]
        # output: [9]
        v_30_zufailh7 = bb.emit(relax.op.strided_slice(v_29_vhven9tg, axes=[0], begin=[0], end=[9]))
        assert str(v_30_zufailh7.struct_info.shape) == "R.shape([9])", f"Shape mismatch: expected R.shape([9]), got {v_30_zufailh7.struct_info.shape}"
        # input: [9]
        # output: [1, 1, 3, 3]
        v_31_78pp1wch = bb.emit(relax.op.reshape(v_30_zufailh7, relax.ShapeExpr([1, 1, 3, 3])))
        assert str(v_31_78pp1wch.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_31_78pp1wch.struct_info.shape}"
        # input: [1, 1, 3, 3], [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_29_08qlexoc = bb.emit(relax.op.minimum(relax.op.astype(v_11_cwd76xq1_var, dtype="float32"), relax.op.astype(v_31_78pp1wch, dtype="float32")))
        assert str(v_29_08qlexoc.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_29_08qlexoc.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_30_d4cyocel = bb.emit(relax.op.log(relax.op.astype(v_29_08qlexoc, dtype="float32")))
        assert str(v_30_d4cyocel.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_30_d4cyocel.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3]
        v_31_fst8bqww = bb.emit(relax.op.astype(relax.op.argmax(v_29_08qlexoc, axis=3), dtype="float32"))
        assert str(v_31_fst8bqww.struct_info.shape) == "R.shape([1, 1, 3])", f"Shape mismatch: expected R.shape([1, 1, 3]), got {v_31_fst8bqww.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_32_5r3ammiv = bb.emit(relax.op.where(relax.op.greater_equal(v_30_d4cyocel, relax.const(0, dtype="float32")), v_30_d4cyocel, relax.op.multiply(relax.const(1.65, dtype="float32"), relax.op.subtract(relax.op.exp(v_30_d4cyocel), relax.const(1.0, dtype="float32")))))
        assert str(v_32_5r3ammiv.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_32_5r3ammiv.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 3]
        v_33_g529w21r = bb.emit(relax.op.divide(relax.op.log(relax.op.astype(v_32_5r3ammiv, dtype="float32")), relax.const(0.6931471805599453, dtype="float32")))
        assert str(v_33_g529w21r.struct_info.shape) == "R.shape([1, 1, 3, 3])", f"Shape mismatch: expected R.shape([1, 1, 3, 3]), got {v_33_g529w21r.struct_info.shape}"
        # input: [1, 1, 3, 3]
        # output: [1, 1, 3, 1]
        v_34_l32fu24z = bb.emit(relax.op.mean(v_33_g529w21r, axis=[3], keepdims=True))
        assert str(v_34_l32fu24z.struct_info.shape) == "R.shape([1, 1, 3, 1])", f"Shape mismatch: expected R.shape([1, 1, 3, 1]), got {v_34_l32fu24z.struct_info.shape}"
        # input: [1, 1, 3, 1]
        # output: [1, 1, 3, 1]
        v_35_zqeumf0f = bb.emit(relax.op.nn.gelu(v_34_l32fu24z))
        assert str(v_35_zqeumf0f.struct_info.shape) == "R.shape([1, 1, 3, 1])", f"Shape mismatch: expected R.shape([1, 1, 3, 1]), got {v_35_zqeumf0f.struct_info.shape}"
        # input: [1, 1, 3, 1]
        # output: [1, 1, 1]
        v_36_5evzjg9k = bb.emit(relax.op.mean(v_35_zqeumf0f, axis=[2], keepdims=False))
        assert str(v_36_5evzjg9k.struct_info.shape) == "R.shape([1, 1, 1])", f"Shape mismatch: expected R.shape([1, 1, 1]), got {v_36_5evzjg9k.struct_info.shape}"
        # input: [1, 1, 1]
        # output: [1, 1]
        v_37_epdziad6 = bb.emit(relax.op.astype(relax.op.argmax(v_36_5evzjg9k, axis=0), dtype="float32"))
        assert str(v_37_epdziad6.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_37_epdziad6.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_38_9vphxiht = bb.emit(relax.op.negative(v_37_epdziad6))
        assert str(v_38_9vphxiht.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_38_9vphxiht.struct_info.shape}"
        bb.emit_func_output((v_0_oyecu90g_var, v_15_9wuvlcts_var, v_19_5o1b4imt_var, v_21_qgsna1eq_var, v_25_bzlcaek6, v_26_r1qj42ok, v_28_q8yp81of, v_31_fst8bqww, v_38_9vphxiht))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_oyecu90g = np.random.uniform(0.0, 1.0, size=(3, 8, 3)).astype(np.float32)
v_0_oyecu90g = tvm.runtime.tensor(np_v_0_oyecu90g, device=tvm.cuda())
np_v_1_w35jct7h = np.random.uniform(0.0, 1.0, size=(4, 4)).astype(np.float32)
v_1_w35jct7h = tvm.runtime.tensor(np_v_1_w35jct7h, device=tvm.cuda())
np_v_2_83tsnspu = np.random.uniform(0.0, 1.0, size=(4, 5, 7, 6)).astype(np.float32)
v_2_83tsnspu = tvm.runtime.tensor(np_v_2_83tsnspu, device=tvm.cuda())
np_v_3_y3gm1rr5 = np.random.uniform(0.0, 1.0, size=(6, 7, 8, 2)).astype(np.float32)
v_3_y3gm1rr5 = tvm.runtime.tensor(np_v_3_y3gm1rr5, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_0_oyecu90g, v_1_w35jct7h, v_2_83tsnspu, v_3_y3gm1rr5)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Generate fresh inputs for graph_1
np_v_12_8osve105 = np.random.uniform(0.0, 1.0, size=(7, 4, 6)).astype(np.float32)
v_12_8osve105 = tvm.runtime.tensor(np_v_12_8osve105, device=tvm.cuda())

# Chained: graph_0 -> graph_1
_prev_out = tvm_result_0 if not hasattr(tvm_result_0, 'numpy') else [tvm_result_0]
v_0_oyecu90g = _prev_out[0]
v_4_7e3dqaqw = _prev_out[1]
v_6_ztn1x0d5 = _prev_out[2]
v_11_cwd76xq1 = _prev_out[3]

tvm_result_1 = vm["graph_1"](v_0_oyecu90g, v_4_7e3dqaqw, v_6_ztn1x0d5, v_11_cwd76xq1, v_12_8osve105)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Generate fresh inputs for graph_2
np_v_24_2wuqvra2 = np.random.uniform(0.0, 1.0, size=(8, 2, 7, 8)).astype(np.float32)
v_24_2wuqvra2 = tvm.runtime.tensor(np_v_24_2wuqvra2, device=tvm.cuda())

# Chained: graph_1 -> graph_2
_prev_out = tvm_result_1 if not hasattr(tvm_result_1, 'numpy') else [tvm_result_1]
v_0_oyecu90g = _prev_out[0]
v_4_7e3dqaqw = _prev_out[1]
v_11_cwd76xq1 = _prev_out[2]
v_15_9wuvlcts = _prev_out[3]
v_16_y4tubzx5 = _prev_out[4]
v_19_5o1b4imt = _prev_out[5]
v_21_qgsna1eq = _prev_out[6]
v_23_2l7qjxh0 = _prev_out[7]

tvm_result_2 = vm["graph_2"](v_0_oyecu90g, v_4_7e3dqaqw, v_11_cwd76xq1, v_15_9wuvlcts, v_16_y4tubzx5, v_19_5o1b4imt, v_21_qgsna1eq, v_23_2l7qjxh0, v_24_2wuqvra2)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
