# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_yrmkhxr9_var = relax.Var("v_0_yrmkhxr9", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 4]), dtype="float32"))
    v_1_r9tc2ef0_var = relax.Var("v_1_r9tc2ef0", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 5]), dtype="float32"))
    v_2_7puitm84_var = relax.Var("v_2_7puitm84", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_3_mfoobwcu_var = relax.Var("v_3_mfoobwcu", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 6, 3]), dtype="float32"))
    with bb.function("graph_0", [v_0_yrmkhxr9_var, v_1_r9tc2ef0_var, v_2_7puitm84_var, v_3_mfoobwcu_var]):
        # input: [4, 6, 3]
        # output: [4, 6]
        v_4_ib9vhlul = bb.emit(relax.op.max(v_3_mfoobwcu_var, axis=[-1], keepdims=False))
        assert str(v_4_ib9vhlul.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_4_ib9vhlul.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_5_evmcft2a_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_3_mfoobwcu_var, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), axis=1))
        v_5_evmcft2a = bb.emit(relax.TupleGetItem(v_5_evmcft2a_bn_tuple, 0))
        assert str(v_5_evmcft2a.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_5_evmcft2a.struct_info.shape}"
        # input: 
        # output: [4, 1]
        v_6_7zgn0xg1 = bb.emit(relax.op.full(relax.ShapeExpr([4, 1]), relax.const(0, dtype="float32")))
        assert str(v_6_7zgn0xg1.struct_info.shape) == "R.shape([4, 1])", f"Shape mismatch: expected R.shape([4, 1]), got {v_6_7zgn0xg1.struct_info.shape}"
        # input: [4, 6, 3], [4, 6, 3]
        # output: [4, 6, 3]
        v_7_ibn5jp0z = bb.emit(relax.op.subtract(relax.op.astype(v_3_mfoobwcu_var, dtype="float32"), relax.op.astype(v_5_evmcft2a, dtype="float32")))
        assert str(v_7_ibn5jp0z.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_7_ibn5jp0z.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 3, 6]
        v_8_5w9widwh = bb.emit(relax.op.permute_dims(v_3_mfoobwcu_var, axes=[0, 2, 1]))
        assert str(v_8_5w9widwh.struct_info.shape) == "R.shape([4, 3, 6])", f"Shape mismatch: expected R.shape([4, 3, 6]), got {v_8_5w9widwh.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_9_t2o2jsr5 = bb.emit(relax.op.nn.relu(v_3_mfoobwcu_var))
        assert str(v_9_t2o2jsr5.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_9_t2o2jsr5.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_10_kel43di7 = bb.emit(relax.op.sqrt(relax.op.astype(v_3_mfoobwcu_var, dtype="float32")))
        assert str(v_10_kel43di7.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_10_kel43di7.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_11_0if353qf = bb.emit(relax.op.nn.gelu(v_9_t2o2jsr5))
        assert str(v_11_0if353qf.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_11_0if353qf.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_12_xczmksx9_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_10_kel43di7, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), axis=1))
        v_12_xczmksx9 = bb.emit(relax.TupleGetItem(v_12_xczmksx9_bn_tuple, 0))
        assert str(v_12_xczmksx9.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_12_xczmksx9.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_13_zn4yq4lo_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_11_0if353qf, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), axis=1))
        v_13_zn4yq4lo = bb.emit(relax.TupleGetItem(v_13_zn4yq4lo_bn_tuple, 0))
        assert str(v_13_zn4yq4lo.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_13_zn4yq4lo.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_14_m2vcibw4 = bb.emit(relax.op.sqrt(relax.op.astype(v_12_xczmksx9, dtype="float32")))
        assert str(v_14_m2vcibw4.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_14_m2vcibw4.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6, 3]
        v_15_wvhhn7vs = bb.emit(relax.op.tile(v_12_xczmksx9, [1, 1, 1]))
        assert str(v_15_wvhhn7vs.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_15_wvhhn7vs.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [1, 4, 6, 3]
        v_16_9eikxzsi = bb.emit(relax.op.expand_dims(v_12_xczmksx9, axis=0))
        assert str(v_16_9eikxzsi.struct_info.shape) == "R.shape([1, 4, 6, 3])", f"Shape mismatch: expected R.shape([1, 4, 6, 3]), got {v_16_9eikxzsi.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6]
        v_17_4uwwtdv1 = bb.emit(relax.op.astype(relax.op.argmax(v_12_xczmksx9, axis=-1), dtype="float32"))
        assert str(v_17_4uwwtdv1.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_17_4uwwtdv1.struct_info.shape}"
        # input: [4, 6, 3]
        # output: [4, 6]
        v_18_5qg6n2ni = bb.emit(relax.op.astype(relax.op.argmax(v_12_xczmksx9, axis=-1), dtype="float32"))
        assert str(v_18_5qg6n2ni.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_18_5qg6n2ni.struct_info.shape}"
        # input: [4, 6]
        # output: [4, 6]
        v_19_sal5eqrx = bb.emit(relax.op.triu(v_17_4uwwtdv1))
        assert str(v_19_sal5eqrx.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_19_sal5eqrx.struct_info.shape}"
        # input: [4, 6]
        # output: [4, 6]
        v_20_u0qzzpex = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_17_4uwwtdv1, dtype="float32"), axis=-1))
        assert str(v_20_u0qzzpex.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_20_u0qzzpex.struct_info.shape}"
        # input: [1, 4, 6, 3]
        # output: [1, 4, 6, 3]
        v_21_fckkf4k4 = bb.emit(relax.op.nn.max_pool2d(v_16_9eikxzsi, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_21_fckkf4k4.struct_info.shape) == "R.shape([1, 4, 6, 3])", f"Shape mismatch: expected R.shape([1, 4, 6, 3]), got {v_21_fckkf4k4.struct_info.shape}"
        # input: [4, 6], [4, 6]
        # output: [4, 6]
        v_22_migeqpye = bb.emit(relax.op.minimum(relax.op.astype(v_17_4uwwtdv1, dtype="float32"), relax.op.astype(v_20_u0qzzpex, dtype="float32")))
        assert str(v_22_migeqpye.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_22_migeqpye.struct_info.shape}"
        # input: 
        # output: [1, 6, 1]
        v_23_7kzmshgn = bb.emit(relax.op.ones(relax.ShapeExpr([1, 6, 1]), dtype="float32"))
        assert str(v_23_7kzmshgn.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_23_7kzmshgn.struct_info.shape}"
        # input: [4, 6]
        # output: [4, 6]
        v_24_rn32n021 = bb.emit(relax.op.nn.gelu(v_17_4uwwtdv1))
        assert str(v_24_rn32n021.struct_info.shape) == "R.shape([4, 6])", f"Shape mismatch: expected R.shape([4, 6]), got {v_24_rn32n021.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_25_63689jba = bb.emit(relax.op.nn.leakyrelu(v_23_7kzmshgn, alpha=0.3))
        assert str(v_25_63689jba.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_25_63689jba.struct_info.shape}"
        # input: 
        # output: [3, 2, 3]
        v_26_gglfybp7 = bb.emit(relax.op.full(relax.ShapeExpr([3, 2, 3]), relax.const(0, dtype="float32")))
        assert str(v_26_gglfybp7.struct_info.shape) == "R.shape([3, 2, 3])", f"Shape mismatch: expected R.shape([3, 2, 3]), got {v_26_gglfybp7.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_27_j9yngjl4 = bb.emit(relax.op.nn.layer_norm(v_25_63689jba, gamma=relax.op.ones(relax.ShapeExpr([1]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"), axes=[-1]))
        assert str(v_27_j9yngjl4.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_27_j9yngjl4.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_28_3ybmfwwd = bb.emit(relax.op.nn.relu(v_25_63689jba))
        assert str(v_28_3ybmfwwd.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_28_3ybmfwwd.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 1, 6, 1]
        v_29_9zdi2g89 = bb.emit(relax.op.expand_dims(v_27_j9yngjl4, axis=0))
        assert str(v_29_9zdi2g89.struct_info.shape) == "R.shape([1, 1, 6, 1])", f"Shape mismatch: expected R.shape([1, 1, 6, 1]), got {v_29_9zdi2g89.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 1, 6, 1]
        v_30_lfysko8z = bb.emit(relax.op.expand_dims(v_23_7kzmshgn, axis=0))
        assert str(v_30_lfysko8z.struct_info.shape) == "R.shape([1, 1, 6, 1])", f"Shape mismatch: expected R.shape([1, 1, 6, 1]), got {v_30_lfysko8z.struct_info.shape}"
        # input: [1, 1, 6, 1], [1, 1, 6, 1]
        # output: [1, 1, 1, 1]
        v_29_yong7e6j = bb.emit(relax.op.nn.conv2d(v_29_9zdi2g89, v_30_lfysko8z, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_29_yong7e6j.struct_info.shape) == "R.shape([1, 1, 1, 1])", f"Shape mismatch: expected R.shape([1, 1, 1, 1]), got {v_29_yong7e6j.struct_info.shape}"
        # input: [1, 4, 6, 3]
        # output: [1, 4, 5, 2]
        v_30_gwisbzta = bb.emit(relax.op.nn.avg_pool2d(v_21_fckkf4k4, pool_size=[2, 2], strides=[1, 1], padding=[0, 0]))
        assert str(v_30_gwisbzta.struct_info.shape) == "R.shape([1, 4, 5, 2])", f"Shape mismatch: expected R.shape([1, 4, 5, 2]), got {v_30_gwisbzta.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_31_c1440kq6 = bb.emit(relax.op.nn.layer_norm(v_27_j9yngjl4, gamma=relax.op.ones(relax.ShapeExpr([1]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"), axes=[-1]))
        assert str(v_31_c1440kq6.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_31_c1440kq6.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_32_m24y0w3e = bb.emit(relax.op.divide(relax.op.log(relax.op.astype(v_27_j9yngjl4, dtype="float32")), relax.const(0.6931471805599453, dtype="float32")))
        assert str(v_32_m24y0w3e.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_32_m24y0w3e.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [6, 1]
        v_33_4bdn2373 = bb.emit(relax.op.take(v_27_j9yngjl4, relax.const(0, dtype="int64"), axis=0))
        assert str(v_33_4bdn2373.struct_info.shape) == "R.shape([6, 1])", f"Shape mismatch: expected R.shape([6, 1]), got {v_33_4bdn2373.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [6, 1]
        v_34_9tef20gh = bb.emit(relax.op.take(v_27_j9yngjl4, relax.const(0, dtype="int64"), axis=0))
        assert str(v_34_9tef20gh.struct_info.shape) == "R.shape([6, 1])", f"Shape mismatch: expected R.shape([6, 1]), got {v_34_9tef20gh.struct_info.shape}"
        # input: [1, 6, 1]
        # output: [1, 6, 1]
        v_35_lulpl1kx = bb.emit(relax.op.triu(v_27_j9yngjl4))
        assert str(v_35_lulpl1kx.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_35_lulpl1kx.struct_info.shape}"
        # input: [6, 1], [1, 6, 1]
        # output: [1, 6, 1]
        v_36_1s3cx2ky = bb.emit(relax.op.multiply(relax.op.astype(v_34_9tef20gh, dtype="float32"), relax.op.astype(v_35_lulpl1kx, dtype="float32")))
        assert str(v_36_1s3cx2ky.struct_info.shape) == "R.shape([1, 6, 1])", f"Shape mismatch: expected R.shape([1, 6, 1]), got {v_36_1s3cx2ky.struct_info.shape}"
        # input: [6, 1]
        # output: [6, 1]
        v_37_1rm53sqs = bb.emit(relax.op.nn.selu(v_34_9tef20gh))
        assert str(v_37_1rm53sqs.struct_info.shape) == "R.shape([6, 1])", f"Shape mismatch: expected R.shape([6, 1]), got {v_37_1rm53sqs.struct_info.shape}"
        # input: [6, 1]
        # output: [6, 1]
        v_38_mz4l1z2g = bb.emit(relax.op.tile(v_34_9tef20gh, [1, 1]))
        assert str(v_38_mz4l1z2g.struct_info.shape) == "R.shape([6, 1])", f"Shape mismatch: expected R.shape([6, 1]), got {v_38_mz4l1z2g.struct_info.shape}"
        # input: [6, 1], [4, 6, 3]
        # output: [4, 6, 3]
        v_39_scuvzgk0 = bb.emit(relax.op.add(relax.op.astype(v_34_9tef20gh, dtype="float32"), relax.op.astype(v_13_zn4yq4lo, dtype="float32")))
        assert str(v_39_scuvzgk0.struct_info.shape) == "R.shape([4, 6, 3])", f"Shape mismatch: expected R.shape([4, 6, 3]), got {v_39_scuvzgk0.struct_info.shape}"
        bb.emit_func_output((v_0_yrmkhxr9_var, v_1_r9tc2ef0_var, v_2_7puitm84_var, v_4_ib9vhlul, v_6_7zgn0xg1, v_7_ibn5jp0z, v_8_5w9widwh, v_14_m2vcibw4, v_15_wvhhn7vs, v_18_5qg6n2ni, v_19_sal5eqrx, v_22_migeqpye, v_24_rn32n021, v_26_gglfybp7, v_28_3ybmfwwd, v_29_yong7e6j, v_30_gwisbzta, v_31_c1440kq6, v_32_m24y0w3e, v_33_4bdn2373, v_36_1s3cx2ky, v_37_1rm53sqs, v_38_mz4l1z2g, v_39_scuvzgk0))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module ===
np.random.seed(42)
ex = relax.build(mod, target="llvm")
vm = relax.VirtualMachine(ex, tvm.cpu())

# Generate inputs for graph_0
np_v_0_yrmkhxr9 = np.random.randn(1, 4).astype(np.float32)
np_v_1_r9tc2ef0 = np.random.randn(3, 5).astype(np.float32)
np_v_2_7puitm84 = np.random.randn(2, 6).astype(np.float32)
np_v_3_mfoobwcu = np.random.randn(4, 6, 3).astype(np.float32)

tvm_result_0 = vm["graph_0"](np_v_0_yrmkhxr9, np_v_1_r9tc2ef0, np_v_2_7puitm84, np_v_3_mfoobwcu)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
