# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_um31e247, v_1_2437orqc, v_2_hwfh5jmi, v_3_wckt9vw3):
        v_4_rtfm1jrm = torch.tile(v_3_wckt9vw3, [1] * 4)
        v_5_const = torch.zeros((8, 18, 17, 22), dtype=torch.float32, device="cpu")
        v_5_dt86xbpb = torch.minimum(v_3_wckt9vw3, v_5_const)
        v_6_19w4tli3 = torch.tile(v_3_wckt9vw3, [1] * 4)
        v_7_4mme08sk = torch.tanh(v_3_wckt9vw3)
        v_8_986wcuyr = v_3_wckt9vw3.to(torch.float32)
        v_9_p7bf6h1n = torch.exp(v_3_wckt9vw3)
        v_10_7z4qd8lt = torch.mul(v_8_986wcuyr, v_5_dt86xbpb)
        v_11_9r580at1 = torch.sum(v_8_986wcuyr, dim=-1, keepdim=False)
        v_12_tfftjohs = torch.tile(v_8_986wcuyr, [1] * 4)
        v_13_y5oq1kzh = torch.tanh(v_11_9r580at1)
        v_14_groco4zg = torch.mean(v_12_tfftjohs.float(), dim=-1, keepdim=False)
        v_15_fdxa1b96 = torch.gather(v_13_y5oq1kzh, 0, torch.zeros((min(8, 1), min(18, 1), min(17, 1)), dtype=torch.int64, device=v_13_y5oq1kzh.device))
        v_16_const = torch.zeros((8, 18, 17), dtype=torch.float32, device="cpu")
        v_16_vr0okh7e = torch.maximum(v_13_y5oq1kzh, v_16_const)
        v_17_f5dl9zy6 = torch.tril(v_13_y5oq1kzh)
        v_18_mp0xu1dq = torch.arange(0, 27, dtype=torch.float32, device="cpu")
        v_19_3io3effj = F.silu(v_13_y5oq1kzh)
        v_20_glw6dsy1 = torch.sum(v_13_y5oq1kzh, dim=-1, keepdim=False)
        v_21_const = torch.zeros((8, 18, 17), dtype=torch.float32, device="cpu")
        v_21_ncuacvro = torch.add(v_13_y5oq1kzh, v_21_const)
        v_22_9bwscmdm = torch.exp(v_20_glw6dsy1)
        v_23_const = torch.zeros((8, 18, 17), dtype=torch.float32, device="cpu")
        v_23_a8l81b6w = torch.add(v_21_ncuacvro, v_23_const)
        v_24_o9haw5fn = torch.minimum(v_21_ncuacvro, v_13_y5oq1kzh)
        v_25_xbyzy2wy = torch.min(v_21_ncuacvro, dim=-1, keepdim=False).values
        v_26_m79n53l1 = torch.abs(v_21_ncuacvro)
        v_27_hqhco35d = torch.gather(v_21_ncuacvro, 0, torch.zeros((min(8, 1), min(18, 1), min(17, 1)), dtype=torch.int64, device=v_21_ncuacvro.device))
        v_28_h0gtrlmu = torch.add(v_21_ncuacvro, v_24_o9haw5fn)
        v_29_5hoq3jzr = torch.floor(v_21_ncuacvro)
        v_30_yoltna1m = torch.log(v_28_h0gtrlmu)
        v_31_snk1o28g = torch.zeros((60, 15, 63), dtype=torch.float32, device="cpu")
        v_32_ou2dkocq = torch.abs(v_28_h0gtrlmu)
        v_33_tynzij40 = torch.tril(v_28_h0gtrlmu)
        v_34_s0kc5b8c = torch.min(v_32_ou2dkocq, dim=-1, keepdim=False).values
        v_35_svf1qbs2 = F.relu(v_32_ou2dkocq)
        v_36_9pb1rxga = torch.add(v_32_ou2dkocq, v_29_5hoq3jzr)
        v_37_60vx3k1v = torch.transpose(v_35_svf1qbs2, 1, 2)
        v_38_const = torch.zeros((8, 18, 17), dtype=torch.float32, device="cpu")
        v_38_ebmeynfe = torch.sub(v_35_svf1qbs2, v_38_const)
        v_39_orgouwc1 = torch.tanh(v_37_60vx3k1v)
        v_40_04pu0tl6 = torch.tril(v_38_ebmeynfe)
        v_41_const = torch.zeros((8, 17, 18), dtype=torch.float32, device="cpu")
        v_41_6yszo5er = torch.div(v_39_orgouwc1, v_41_const)
        v_42_76ipa4ct = v_39_orgouwc1[:max(1, v_39_orgouwc1.shape[0]//2)]
        v_43_0olyvzyv = torch.max(v_39_orgouwc1, dim=-1, keepdim=False).values
        v_44_bxlwr4uk = torch.min(v_39_orgouwc1, dim=-1, keepdim=False).values
        v_45_19vj9ihx = torch.tile(v_39_orgouwc1, [1] * 3)
        v_46_sk4ydplt = torch.transpose(v_39_orgouwc1, 1, 2)
        v_47_7jyg4kgk = torch.sigmoid(v_39_orgouwc1)
        v_48_dp8ffdka = torch.max(v_39_orgouwc1, dim=-1, keepdim=False).values
        return (v_0_um31e247, v_1_2437orqc, v_2_hwfh5jmi, v_4_rtfm1jrm, v_6_19w4tli3, v_7_4mme08sk, v_9_p7bf6h1n, v_10_7z4qd8lt, v_14_groco4zg, v_15_fdxa1b96, v_16_vr0okh7e, v_17_f5dl9zy6, v_18_mp0xu1dq, v_19_3io3effj, v_22_9bwscmdm, v_23_a8l81b6w, v_25_xbyzy2wy, v_26_m79n53l1, v_27_hqhco35d, v_30_yoltna1m, v_31_snk1o28g, v_33_tynzij40, v_34_s0kc5b8c, v_36_9pb1rxga, v_40_04pu0tl6, v_41_6yszo5er, v_42_76ipa4ct, v_43_0olyvzyv, v_44_bxlwr4uk, v_45_19vj9ihx, v_46_sk4ydplt, v_47_7jyg4kgk, v_48_dp8ffdka)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_um31e247 = torch.randn(63, 21, dtype=torch.float32, device="cpu")
v_1_2437orqc = torch.randn(34, 5, 27, 18, dtype=torch.float32, device="cpu")
v_2_hwfh5jmi = torch.randn(24, 46, 6, 11, dtype=torch.float32, device="cpu")
v_3_wckt9vw3 = torch.randn(8, 18, 17, 22, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_um31e247, v_1_2437orqc, v_2_hwfh5jmi, v_3_wckt9vw3)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_um31e247, v_1_2437orqc, v_2_hwfh5jmi, v_3_wckt9vw3)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
