# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_y0o8eye2, v_1_87j1sldm):
        v_2_const = torch.zeros((24, 23, 13), dtype=torch.float32, device="cpu")
        v_2_6rj7liml = torch.add(v_1_87j1sldm, v_2_const)
        v_3_jtmz0zkf = F.log_softmax(v_1_87j1sldm, dim=-1)
        v_4_ro2mycmw = torch.sqrt(v_2_6rj7liml)
        v_5_5a5f4tj8 = torch.div(v_3_jtmz0zkf, v_2_6rj7liml)
        v_6_ns7si8hh = torch.transpose(v_3_jtmz0zkf, 1, 2)
        v_7_cnwab493 = F.silu(v_5_5a5f4tj8)
        v_8_hunebc17 = torch.ceil(v_5_5a5f4tj8)
        v_9_adxpztzs = torch.log(v_5_5a5f4tj8)
        v_10_g1ncz617 = torch.max(v_5_5a5f4tj8, dim=-1, keepdim=False).values
        v_11_qska94tq = F.relu(v_5_5a5f4tj8)
        v_12_k3r9y6ww = torch.triu(v_5_5a5f4tj8)
        v_13_we25uf5j = torch.tril(v_5_5a5f4tj8)
        v_14_msvh6pcb = torch.arange(0, 108, dtype=torch.float32, device="cpu")
        v_15_fcyfvkd3 = torch.transpose(v_5_5a5f4tj8, 1, 2)
        v_16_ireepyjg = torch.sub(v_5_5a5f4tj8, v_4_ro2mycmw)
        v_17_8tvm8z09 = torch.ones((27, 17, 16, 7), dtype=torch.float32, device="cpu")
        v_18_gjw0e1ub = torch.rsqrt(v_16_ireepyjg)
        v_19_7stig1xz = torch.ceil(v_16_ireepyjg)
        v_20_m6d7t2yj = torch.transpose(v_16_ireepyjg, 1, 2)
        v_21_5bzwr2k6 = F.gelu(v_16_ireepyjg)
        v_22_98g3pmot = torch.transpose(v_20_m6d7t2yj, 1, 2)
        v_23_5312w0vb = torch.tanh(v_21_5bzwr2k6)
        v_24_pxvwju8c = F.relu(v_21_5bzwr2k6)
        v_25_arh0fs55 = torch.log(v_23_5312w0vb)
        v_26_iauou8av = F.relu(v_23_5312w0vb)
        v_27_khlpe16z = F.gelu(v_25_arh0fs55)
        v_28_e49mwy2u = F.elu(v_25_arh0fs55, alpha=1.24)
        v_29_qmnx31d6 = torch.min(v_25_arh0fs55, dim=-1, keepdim=False).values
        v_30_w17scz1q = torch.ceil(v_25_arh0fs55)
        v_31_1buq82tq = torch.transpose(v_25_arh0fs55, 1, 2)
        v_32_atzpj1lu = torch.pow(v_25_arh0fs55, v_7_cnwab493)
        v_33_zs0bjwdh = F.mish(v_25_arh0fs55)
        v_34_63eduh2r = torch.round(v_32_atzpj1lu)
        v_35_won38n3i = F.softmax(v_32_atzpj1lu, dim=-1)
        v_36_x4jhm7s0 = F.selu(v_34_63eduh2r)
        v_37_zo7g4kpm = torch.neg(v_35_won38n3i)
        v_38_el0mc47n = torch.tanh(v_35_won38n3i)
        v_39_7ktowd1v = torch.sqrt(v_35_won38n3i)
        v_40_8vgdreek = torch.tanh(v_35_won38n3i)
        v_41_vdl3bfcg = torch.triu(v_39_7ktowd1v)
        v_42_9ramarca = torch.tile(v_39_7ktowd1v, [1] * 3)
        return (v_0_y0o8eye2, v_6_ns7si8hh, v_8_hunebc17, v_9_adxpztzs, v_10_g1ncz617, v_11_qska94tq, v_12_k3r9y6ww, v_13_we25uf5j, v_14_msvh6pcb, v_15_fcyfvkd3, v_17_8tvm8z09, v_18_gjw0e1ub, v_19_7stig1xz, v_22_98g3pmot, v_24_pxvwju8c, v_26_iauou8av, v_27_khlpe16z, v_28_e49mwy2u, v_29_qmnx31d6, v_30_w17scz1q, v_31_1buq82tq, v_33_zs0bjwdh, v_36_x4jhm7s0, v_37_zo7g4kpm, v_38_el0mc47n, v_40_8vgdreek, v_41_vdl3bfcg, v_42_9ramarca)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_y0o8eye2 = torch.randn(38, 26, 3, 32, dtype=torch.float32, device="cpu")
v_1_87j1sldm = torch.randn(24, 23, 13, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_y0o8eye2, v_1_87j1sldm)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_y0o8eye2, v_1_87j1sldm)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
