# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_ke661yvd, v_1_im9x4h3r, v_2_mkc3rqy9, v_3_d1jg8oyv, v_4_8vbbyyel, v_5_ph51o0dz, v_6_xbrd8khr, v_7_at92q8xi, v_8_bat8j9ae):
        v_9_w9ocw0t3 = torch.sqrt(v_8_bat8j9ae)
        v_10_e4hg00lr = torch.full((15, 14, 27, 17), 0.0, dtype=torch.float32, device="cpu")
        v_11_l392f3f8 = torch.zeros((22, 60), dtype=torch.float32, device="cpu")
        v_12_uz3bnv4t = torch.neg(v_10_e4hg00lr)
        v_13_noh8izm1 = torch.full((33, 63, 36), 0.0, dtype=torch.float32, device="cpu")
        v_14_2mijmtw4 = torch.unsqueeze(v_10_e4hg00lr, 0)
        v_15_xd1d3n05 = torch.exp(v_10_e4hg00lr)
        v_16_bg2yf3v7 = v_14_2mijmtw4.to(torch.float32)
        v_17_dvxthvli = torch.tril(v_14_2mijmtw4)
        v_18_lbafn7hw = torch.ceil(v_16_bg2yf3v7)
        v_19_g7nj23ze = torch.tile(v_17_dvxthvli, [1] * 5)
        v_20_88gut2i7 = torch.ceil(v_17_dvxthvli)
        v_21_1gdum856 = v_17_dvxthvli[:max(1, v_17_dvxthvli.shape[0]//2)]
        v_22_const = torch.zeros((1, 15, 14, 27, 17), dtype=torch.float32, device="cpu")
        v_22_q1rzt12h = torch.minimum(v_17_dvxthvli, v_22_const)
        v_23_u8xplqkg = v_17_dvxthvli.to(torch.float32)
        v_24_p8oqa8i8 = torch.sqrt(v_17_dvxthvli)
        v_25_rrwuz7ff = F.silu(v_17_dvxthvli)
        v_26_05o8zeg0 = torch.zeros((32, 56), dtype=torch.float32, device="cpu")
        v_27_p3m3hwpn = torch.full((13, 63, 62), 0.0, dtype=torch.float32, device="cpu")
        v_28_c5idaa05 = torch.tile(v_25_rrwuz7ff, [1] * 5)
        v_29_qvbqgfna = torch.exp(v_27_p3m3hwpn)
        v_30_const = torch.zeros((13, 63, 62), dtype=torch.float32, device="cpu")
        v_30_leta58us = torch.pow(v_27_p3m3hwpn, v_30_const)
        v_31_o7spnsx3 = torch.abs(v_27_p3m3hwpn)
        v_32_apf6k8dj = torch.triu(v_30_leta58us)
        v_33_cy7akc18 = torch.sqrt(v_31_o7spnsx3)
        v_34_kdnwresy = torch.exp(v_31_o7spnsx3)
        v_35_cbwru6vo = torch.mean(v_33_cy7akc18.float(), dim=-1, keepdim=False)
        v_36_const = torch.zeros((13, 63, 62), dtype=torch.float32, device="cpu")
        v_36_pdkbsff4 = torch.maximum(v_33_cy7akc18, v_36_const)
        v_37_j9matn6m = torch.transpose(v_33_cy7akc18, 1, 2)
        v_38_dxwxuvjl = v_36_pdkbsff4[:max(1, v_36_pdkbsff4.shape[0]//2)]
        v_39_hnf56hyr = torch.log(v_36_pdkbsff4)
        v_40_jedksvku = torch.tile(v_38_dxwxuvjl, [1] * 3)
        v_41_7dfkm863 = torch.full((14, 23, 13, 15), 0.0, dtype=torch.float32, device="cpu")
        v_42_18rqqeyf = F.softmax(v_38_dxwxuvjl, dim=-1)
        v_43_357g2c10 = torch.log(v_41_7dfkm863)
        v_44_4qhmr9n4 = torch.tile(v_41_7dfkm863, [1] * 4)
        v_45_1sqqhkcc = torch.exp(v_41_7dfkm863)
        v_46_kpof3xrz = F.silu(v_41_7dfkm863)
        v_47_bpnakg6n = torch.floor(v_41_7dfkm863)
        v_48_xtclz0w5 = torch.tile(v_46_kpof3xrz, [1] * 4)
        v_49_yt8h67ry = torch.ceil(v_46_kpof3xrz)
        v_50_siijvphv = torch.log(v_46_kpof3xrz)
        v_51_xbtyd8dl = torch.tanh(v_46_kpof3xrz)
        v_52_xri3ex9z = torch.unsqueeze(v_50_siijvphv, 0)
        v_53_const = torch.zeros((14, 23, 13, 15), dtype=torch.float32, device="cpu")
        v_53_fud4eoza = torch.sub(v_50_siijvphv, v_53_const)
        v_54_ccm0w41p = torch.abs(v_50_siijvphv)
        v_55_const = torch.zeros((14, 23, 13, 15), dtype=torch.float32, device="cpu")
        v_55_usa0hnig = torch.sub(v_50_siijvphv, v_55_const)
        v_56_9yjk3wnb = torch.unsqueeze(v_54_ccm0w41p, 0)
        v_57_sd5gqsro = torch.triu(v_54_ccm0w41p)
        v_58_ec9xfq8f = torch.sub(v_54_ccm0w41p, v_49_yt8h67ry)
        v_59_c6122vlo = torch.sum(v_54_ccm0w41p, dim=-1, keepdim=False)
        v_60_d7y3pwr6 = torch.full((36, 54, 31), 0.0, dtype=torch.float32, device="cpu")
        v_61_48zeqgoj = F.gelu(v_59_c6122vlo)
        v_62_5d34075m = torch.max(v_59_c6122vlo, dim=-1, keepdim=False).values
        v_63_shbvixls = torch.sum(v_59_c6122vlo, dim=-1, keepdim=False)
        v_64_const = torch.zeros((14, 23, 13), dtype=torch.float32, device="cpu")
        v_64_z60ldr06 = torch.maximum(v_59_c6122vlo, v_64_const)
        v_65_p8a8ye7c = torch.tanh(v_63_shbvixls)
        v_66_orgxqjnh = torch.arange(0, 237, dtype=torch.float32, device="cpu")
        v_67_u2sgi8s1 = torch.sum(v_65_p8a8ye7c, dim=-1, keepdim=False)
        v_68_mgb9bq7l = torch.neg(v_65_p8a8ye7c)
        v_69_ahjstg54 = torch.full((58, 57), 0.0, dtype=torch.float32, device="cpu")
        v_70_hbzzv0qp = torch.exp(v_65_p8a8ye7c)
        v_71_ur8rr2n4 = torch.full((14, 13, 24, 12), 0.0, dtype=torch.float32, device="cpu")
        v_72_w3jif0j5 = torch.abs(v_65_p8a8ye7c)
        return (v_0_ke661yvd, v_1_im9x4h3r, v_2_mkc3rqy9, v_3_d1jg8oyv, v_4_8vbbyyel, v_5_ph51o0dz, v_6_xbrd8khr, v_7_at92q8xi, v_9_w9ocw0t3, v_11_l392f3f8, v_12_uz3bnv4t, v_13_noh8izm1, v_15_xd1d3n05, v_18_lbafn7hw, v_19_g7nj23ze, v_20_88gut2i7, v_21_1gdum856, v_22_q1rzt12h, v_23_u8xplqkg, v_24_p8oqa8i8, v_26_05o8zeg0, v_28_c5idaa05, v_29_qvbqgfna, v_32_apf6k8dj, v_34_kdnwresy, v_35_cbwru6vo, v_37_j9matn6m, v_39_hnf56hyr, v_40_jedksvku, v_42_18rqqeyf, v_43_357g2c10, v_44_4qhmr9n4, v_45_1sqqhkcc, v_47_bpnakg6n, v_48_xtclz0w5, v_51_xbtyd8dl, v_52_xri3ex9z, v_53_fud4eoza, v_55_usa0hnig, v_56_9yjk3wnb, v_57_sd5gqsro, v_58_ec9xfq8f, v_60_d7y3pwr6, v_61_48zeqgoj, v_62_5d34075m, v_64_z60ldr06, v_66_orgxqjnh, v_67_u2sgi8s1, v_68_mgb9bq7l, v_69_ahjstg54, v_70_hbzzv0qp, v_71_ur8rr2n4, v_72_w3jif0j5)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_ke661yvd = torch.randn(5, 34, dtype=torch.float32, device="cpu")
v_1_im9x4h3r = torch.randn(22, 3, 12, dtype=torch.float32, device="cpu")
v_2_mkc3rqy9 = torch.randn(22, 43, 22, dtype=torch.float32, device="cpu")
v_3_d1jg8oyv = torch.randn(13, 26, 15, 15, dtype=torch.float32, device="cpu")
v_4_8vbbyyel = torch.randn(30, 63, dtype=torch.float32, device="cpu")
v_5_ph51o0dz = torch.randn(9, 18, dtype=torch.float32, device="cpu")
v_6_xbrd8khr = torch.randn(37, 32, 27, dtype=torch.float32, device="cpu")
v_7_at92q8xi = torch.randn(22, 49, dtype=torch.float32, device="cpu")
v_8_bat8j9ae = torch.randn(2, 26, 37, 40, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_ke661yvd, v_1_im9x4h3r, v_2_mkc3rqy9, v_3_d1jg8oyv, v_4_8vbbyyel, v_5_ph51o0dz, v_6_xbrd8khr, v_7_at92q8xi, v_8_bat8j9ae)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_ke661yvd, v_1_im9x4h3r, v_2_mkc3rqy9, v_3_d1jg8oyv, v_4_8vbbyyel, v_5_ph51o0dz, v_6_xbrd8khr, v_7_at92q8xi, v_8_bat8j9ae)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
