# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_8l9istrc, v_1_gz6egb9v, v_2_4v8ggwan, v_3_1hzes232, v_4_151undmj, v_5_0tao1fce, v_6_z94xghb1):
        v_7_e105lo7w = torch.cumprod(v_6_z94xghb1.float(), dim=-1)
        v_8_8ij77iqy = torch.log(v_6_z94xghb1.float())
        v_9_mrvhrrkm = torch.full((1, 1), 0.0, dtype=torch.float32, device="cpu")
        v_10_dqztwgz4 = torch.triu(v_6_z94xghb1)
        v_11_wppa2z5m = F.interpolate(v_2_4v8ggwan, scale_factor=2.0, mode='nearest')
        v_12_qlk49n8y = torch.rsqrt(v_9_mrvhrrkm.float())
        v_13_yee5tmeu = torch.transpose(v_11_wppa2z5m, 2, 3)
        v_14_76uc4hzc = torch.tanh(v_11_wppa2z5m.float())
        v_15_8u8txhgd = F.log_softmax(v_11_wppa2z5m.float(), dim=-1)
        v_16_mmjrfi07 = torch.full((3, 4, 3, 1), 0.0, dtype=torch.float32, device="cpu")
        v_17_kcfxqisq = F.conv2d(v_11_wppa2z5m, torch.zeros(max(v_16_mmjrfi07.shape[0], 1), v_11_wppa2z5m.shape[1], min(v_16_mmjrfi07.shape[2], v_11_wppa2z5m.shape[2]), min(v_16_mmjrfi07.shape[3], v_11_wppa2z5m.shape[3])), stride=1, padding=0, dilation=1, groups=1)
        v_18_3976w0ih = torch.full((1, 4, 3, 1), 0.0, dtype=torch.float32, device="cpu")
        v_19_2dbxltbs = F.conv2d(v_16_mmjrfi07, torch.zeros(max(v_18_3976w0ih.shape[0], 1), v_16_mmjrfi07.shape[1], min(v_18_3976w0ih.shape[2], v_16_mmjrfi07.shape[2]), min(v_18_3976w0ih.shape[3], v_16_mmjrfi07.shape[3])), stride=1, padding=0, dilation=1, groups=1)
        v_20_eglzyfkr = torch.log(v_18_3976w0ih.float())
        v_21_cp8kiuxq = (v_8_8ij77iqy if v_8_8ij77iqy.ndim >= 4 else torch.unsqueeze(v_8_8ij77iqy, 0))
        v_22_3tncmdpj = torch.abs(v_20_eglzyfkr)
        v_23_xi4yg1t2 = torch.sign(v_20_eglzyfkr)
        v_24_ccyymhtp = (v_3_1hzes232 if v_3_1hzes232.ndim >= 4 else torch.unsqueeze(v_3_1hzes232, 0))
        v_25_1nx2ioud = torch.pow(v_22_3tncmdpj.float(), v_19_2dbxltbs.float())
        v_26_0sh4vvtp = torch.pow(v_22_3tncmdpj.float(), v_12_qlk49n8y.float())
        v_27_tl4yx1oo = torch.div(v_22_3tncmdpj.float(), v_16_mmjrfi07.float())
        v_28_d5wnwch3 = torch.sum(v_26_0sh4vvtp, dim=-1, keepdim=False, dtype=torch.int32).float()
        v_29_x0gxr3xg = torch.triu(v_26_0sh4vvtp)
        v_30_mewtzvil = F.softmax(v_26_0sh4vvtp.float(), dim=-1)
        v_31_bicayolw = torch.full((1, 6, 5), 0.0, dtype=torch.float32, device="cpu")
        v_32_g51ypyoa = F.elu(v_29_x0gxr3xg.float(), alpha=1.06)
        v_33_pzu01uy4 = torch.sqrt(v_29_x0gxr3xg.float())
        v_34_i227vkeh = torch.zeros((6, 6, 2), dtype=torch.float32, device="cpu")
        v_35_4okzcm1b = F.avg_pool2d(v_29_x0gxr3xg, kernel_size=1, stride=1, padding=0)
        v_36_hejnw4ps = torch.full((5, 2, 6), 0.0, dtype=torch.float32, device="cpu")
        v_37_po6i6r40 = torch.tanh(v_34_i227vkeh.float())
        v_38_u7q8djkm = torch.minimum(v_34_i227vkeh.float(), v_12_qlk49n8y.float())
        v_39_09nwxj5v = F.mish(v_37_po6i6r40.float())
        v_40_8vpridqs = torch.ceil(v_37_po6i6r40)
        v_41_k4vcpg53 = torch.sqrt(v_37_po6i6r40.float())
        v_42_wf07d395 = F.relu(v_37_po6i6r40)
        v_43_1iygug8u = torch.log2(v_41_k4vcpg53.float())
        v_44_vtycqs2r = F.leaky_relu(v_42_wf07d395.float(), negative_slope=0.24)
        v_45_h34yzgdd = torch.cumprod(v_42_wf07d395.float(), dim=-1)
        v_46_u85auuci = torch.arange(0, 141, dtype=torch.float32, device="cpu")
        v_47_dqek9ta0 = torch.sign(v_42_wf07d395)
        v_48_5wrq5k3w = torch.tanh(v_42_wf07d395.float())
        v_49_vnuw0pxi = torch.arange(0, 22, dtype=torch.float32, device="cpu")
        v_50_rzqye64u = F.hardtanh(v_48_5wrq5k3w.float(), min_val=-2.0, max_val=1.97)
        v_51_siexeqfd = torch.add(v_49_vnuw0pxi.float(), v_25_1nx2ioud.float())
        v_52_sh1vha4p = F.interpolate(v_22_3tncmdpj, scale_factor=2.0, mode='nearest')
        v_53_c8xb7k5m = (v_49_vnuw0pxi if v_49_vnuw0pxi.ndim >= 4 else torch.unsqueeze(v_49_vnuw0pxi, 0))
        v_54_nackf3tq = (v_53_c8xb7k5m if v_53_c8xb7k5m.ndim >= 4 else torch.unsqueeze(v_53_c8xb7k5m, 0))
        v_55_0y268scm = (v_54_nackf3tq if v_54_nackf3tq.ndim >= 4 else torch.unsqueeze(v_54_nackf3tq, 0))
        v_56_1ucc9jao = torch.zeros((4, 1, 1, 1), dtype=torch.float32, device="cpu")
        v_53_zgcalbu6 = F.conv2d(v_55_0y268scm, torch.zeros(max(v_56_1ucc9jao.shape[0], 1), v_55_0y268scm.shape[1], min(v_56_1ucc9jao.shape[2], v_55_0y268scm.shape[2]), min(v_56_1ucc9jao.shape[3], v_55_0y268scm.shape[3])), stride=1, padding=0, dilation=1, groups=1)
        v_54_z3hckwg5 = F.hardtanh(v_49_vnuw0pxi.float(), min_val=-2.25, max_val=2.33)
        v_55_pasvyu1l = F.gelu(v_49_vnuw0pxi.float())
        v_56_b8xhuj0e = v_49_vnuw0pxi.to(torch.float32)
        v_57_z7i7ugqi = torch.cumsum(v_55_pasvyu1l, dim=-1)
        v_58_6xdnmnfo = torch.round(v_55_pasvyu1l)
        v_59_m60dpxpg = F.interpolate(v_15_8u8txhgd, scale_factor=2.0, mode='nearest')
        v_60_gc0aafue = (v_58_6xdnmnfo if v_58_6xdnmnfo.ndim >= 4 else torch.unsqueeze(v_58_6xdnmnfo, 0))
        v_61_rpap2d6l = torch.mul(v_58_6xdnmnfo.float(), v_55_pasvyu1l.float())
        v_62_vt0wkl6o = F.log_softmax(v_60_gc0aafue.float(), dim=-1)
        v_63_cifq3xwi = torch.clamp(v_60_gc0aafue, min=-0.18, max=1.71)
        v_64_c798tvv0 = F.layer_norm(v_60_gc0aafue.float(), (v_60_gc0aafue.shape[-1],))
        v_65_zdi9exyr = torch.tile(v_60_gc0aafue, [1] * 2)
        v_66_iclgf1ez = F.leaky_relu(v_60_gc0aafue.float(), negative_slope=0.31)
        v_67_25k9ki8z = F.avg_pool2d(v_25_1nx2ioud, kernel_size=1, stride=1, padding=0)
        v_68_k25r52ax = torch.max(v_65_zdi9exyr, dim=-1, keepdim=False).values
        v_69_i2gkkd82 = F.log_softmax(v_67_25k9ki8z.float(), dim=-1)
        v_70_3ygygpyi = torch.tril(v_67_25k9ki8z)
        v_71_t07i2rw8 = F.elu(v_67_25k9ki8z.float(), alpha=1.65)
        v_72_hxksqfva = torch.transpose(v_70_3ygygpyi, 2, 3)
        return (v_0_8l9istrc, v_1_gz6egb9v, v_4_151undmj, v_5_0tao1fce, v_7_e105lo7w, v_10_dqztwgz4, v_13_yee5tmeu, v_14_76uc4hzc, v_17_kcfxqisq, v_21_cp8kiuxq, v_23_xi4yg1t2, v_24_ccyymhtp, v_27_tl4yx1oo, v_28_d5wnwch3, v_30_mewtzvil, v_31_bicayolw, v_32_g51ypyoa, v_33_pzu01uy4, v_35_4okzcm1b, v_36_hejnw4ps, v_38_u7q8djkm, v_39_09nwxj5v, v_40_8vpridqs, v_43_1iygug8u, v_44_vtycqs2r, v_45_h34yzgdd, v_46_u85auuci, v_47_dqek9ta0, v_50_rzqye64u, v_51_siexeqfd, v_52_sh1vha4p, v_53_zgcalbu6, v_54_z3hckwg5, v_56_b8xhuj0e, v_57_z7i7ugqi, v_59_m60dpxpg, v_61_rpap2d6l, v_62_vt0wkl6o, v_63_cifq3xwi, v_64_c798tvv0, v_66_iclgf1ez, v_68_k25r52ax, v_69_i2gkkd82, v_71_t07i2rw8, v_72_hxksqfva)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_8l9istrc = torch.randn(6, 4, 6, 1, dtype=torch.float32, device="cpu")
v_1_gz6egb9v = torch.randn(2, 5, dtype=torch.float32, device="cpu")
v_2_4v8ggwan = torch.randn(2, 4, 2, 3, dtype=torch.float32, device="cpu")
v_3_1hzes232 = torch.randn(6, 4, 3, dtype=torch.float32, device="cpu")
v_4_151undmj = torch.randn(5, 3, 2, dtype=torch.float32, device="cpu")
v_5_0tao1fce = torch.randn(4, 6, 4, 2, dtype=torch.float32, device="cpu")
v_6_z94xghb1 = torch.randn(1, 4, 1, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_8l9istrc, v_1_gz6egb9v, v_2_4v8ggwan, v_3_1hzes232, v_4_151undmj, v_5_0tao1fce, v_6_z94xghb1)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_8l9istrc, v_1_gz6egb9v, v_2_4v8ggwan, v_3_1hzes232, v_4_151undmj, v_5_0tao1fce, v_6_z94xghb1)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise, cast to float for allclose compatibility
    all_match = all(torch.allclose(r.float(), c.float(), atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output.float(), cmp_output.float(), atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
