# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_kdj8e8ea_var = relax.Var("v_0_kdj8e8ea", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3]), dtype="float32"))
    v_1_nakcrlja_var = relax.Var("v_1_nakcrlja", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    with bb.function("graph_0", [v_0_kdj8e8ea_var, v_1_nakcrlja_var]):
        # input: [6, 6]
        # output: [1, 6, 6]
        v_2_xanm0mgu = bb.emit(relax.op.expand_dims(v_1_nakcrlja_var, axis=0))
        assert str(v_2_xanm0mgu.struct_info.shape) == "R.shape([1, 6, 6])", f"Shape mismatch: expected R.shape([1, 6, 6]), got {v_2_xanm0mgu.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_3_z0jh348v = bb.emit(relax.op.where(relax.op.greater_equal(v_1_nakcrlja_var, relax.const(0, dtype="float32")), v_1_nakcrlja_var, relax.op.multiply(relax.const(0.53, dtype="float32"), relax.op.subtract(relax.op.exp(v_1_nakcrlja_var), relax.const(1.0, dtype="float32")))))
        assert str(v_3_z0jh348v.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_3_z0jh348v.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_4_uat265el = bb.emit(relax.op.floor(v_1_nakcrlja_var))
        assert str(v_4_uat265el.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_4_uat265el.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_5_g1h2ncu8 = bb.emit(relax.op.rsqrt(relax.op.astype(v_1_nakcrlja_var, dtype="float32")))
        assert str(v_5_g1h2ncu8.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_5_g1h2ncu8.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_6_0em09y1d = bb.emit(relax.op.sqrt(relax.op.astype(v_1_nakcrlja_var, dtype="float32")))
        assert str(v_6_0em09y1d.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_6_0em09y1d.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_7_yzk2x91n = bb.emit(relax.op.sigmoid(v_5_g1h2ncu8))
        assert str(v_7_yzk2x91n.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_7_yzk2x91n.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_8_22sikq8c = bb.emit(relax.op.nn.gelu(v_6_0em09y1d))
        assert str(v_8_22sikq8c.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_8_22sikq8c.struct_info.shape}"
        # input: [6, 6]
        # output: [6]
        v_9_68vpx57c = bb.emit(relax.op.mean(v_7_yzk2x91n, axis=[-1], keepdims=False))
        assert str(v_9_68vpx57c.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_9_68vpx57c.struct_info.shape}"
        # input: [1, 6, 6]
        # output: [1, 6, 6]
        v_10_pvdnl2zx_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_2_xanm0mgu, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), axis=1))
        v_10_pvdnl2zx = bb.emit(relax.TupleGetItem(v_10_pvdnl2zx_bn_tuple, 0))
        assert str(v_10_pvdnl2zx.struct_info.shape) == "R.shape([1, 6, 6])", f"Shape mismatch: expected R.shape([1, 6, 6]), got {v_10_pvdnl2zx.struct_info.shape}"
        # input: [6]
        # output: []
        v_11_ehuyjkij = bb.emit(relax.op.mean(v_9_68vpx57c, axis=[-1], keepdims=False))
        assert str(v_11_ehuyjkij.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_11_ehuyjkij.struct_info.shape}"
        # input: [6]
        # output: [6]
        v_12_vh7yvfwa = bb.emit(relax.op.multiply(v_9_68vpx57c, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_9_68vpx57c))))))
        assert str(v_12_vh7yvfwa.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_12_vh7yvfwa.struct_info.shape}"
        # input: [6]
        # output: [6]
        v_13_a1c8yz6s = bb.emit(relax.op.rsqrt(relax.op.astype(v_9_68vpx57c, dtype="float32")))
        assert str(v_13_a1c8yz6s.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_13_a1c8yz6s.struct_info.shape}"
        # input: [6], []
        # output: [6]
        v_14_gy1kwaqp = bb.emit(relax.op.divide(relax.op.astype(v_12_vh7yvfwa, dtype="float32"), relax.op.astype(v_11_ehuyjkij, dtype="float32")))
        assert str(v_14_gy1kwaqp.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_14_gy1kwaqp.struct_info.shape}"
        # input: [6]
        # output: []
        v_15_u0cv0p0t = bb.emit(relax.op.min(v_12_vh7yvfwa, axis=[-1], keepdims=False))
        assert str(v_15_u0cv0p0t.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_15_u0cv0p0t.struct_info.shape}"
        # input: [6]
        # output: [1, 6]
        v_16_l568meiu = bb.emit(relax.op.expand_dims(v_14_gy1kwaqp, axis=0))
        assert str(v_16_l568meiu.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_16_l568meiu.struct_info.shape}"
        bb.emit_func_output((v_0_kdj8e8ea_var, v_3_z0jh348v, v_4_uat265el, v_8_22sikq8c, v_10_pvdnl2zx, v_13_a1c8yz6s, v_15_u0cv0p0t, v_16_l568meiu))

    v_0_kdj8e8ea_var = relax.Var("v_0_kdj8e8ea", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3]), dtype="float32"))
    v_3_z0jh348v_var = relax.Var("v_3_z0jh348v", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_4_uat265el_var = relax.Var("v_4_uat265el", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_8_22sikq8c_var = relax.Var("v_8_22sikq8c", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_10_pvdnl2zx_var = relax.Var("v_10_pvdnl2zx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 6]), dtype="float32"))
    v_13_a1c8yz6s_var = relax.Var("v_13_a1c8yz6s", relax.TensorStructInfo(shape=relax.ShapeExpr([6]), dtype="float32"))
    v_15_u0cv0p0t_var = relax.Var("v_15_u0cv0p0t", relax.TensorStructInfo(shape=relax.ShapeExpr([]), dtype="float32"))
    v_16_l568meiu_var = relax.Var("v_16_l568meiu", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    with bb.function("graph_1", [v_0_kdj8e8ea_var, v_3_z0jh348v_var, v_4_uat265el_var, v_8_22sikq8c_var, v_10_pvdnl2zx_var, v_13_a1c8yz6s_var, v_15_u0cv0p0t_var, v_16_l568meiu_var]):
        # input: [1, 6], [1, 6, 6]
        # output: [1, 6, 6]
        v_17_7jusxvkr = bb.emit(relax.op.minimum(relax.op.astype(v_16_l568meiu_var, dtype="float32"), relax.op.astype(v_10_pvdnl2zx_var, dtype="float32")))
        assert str(v_17_7jusxvkr.struct_info.shape) == "R.shape([1, 6, 6])", f"Shape mismatch: expected R.shape([1, 6, 6]), got {v_17_7jusxvkr.struct_info.shape}"
        # input: 
        # output: [249]
        v_18_6e09qtiu = bb.emit(relax.op.arange(0, 249, dtype="float32"))
        assert str(v_18_6e09qtiu.struct_info.shape) == "R.shape([249])", f"Shape mismatch: expected R.shape([249]), got {v_18_6e09qtiu.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_19_0n9dlwm1 = bb.emit(relax.op.nn.relu(v_16_l568meiu_var))
        assert str(v_19_0n9dlwm1.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_19_0n9dlwm1.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_20_z4mjlr9q = bb.emit(relax.op.where(relax.op.greater_equal(v_16_l568meiu_var, relax.const(0, dtype="float32")), v_16_l568meiu_var, relax.op.multiply(relax.const(1.14, dtype="float32"), relax.op.subtract(relax.op.exp(v_16_l568meiu_var), relax.const(1.0, dtype="float32")))))
        assert str(v_20_z4mjlr9q.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_20_z4mjlr9q.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_21_8p2z945f = bb.emit(relax.op.sigmoid(v_16_l568meiu_var))
        assert str(v_21_8p2z945f.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_21_8p2z945f.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_22_0enz1n16 = bb.emit(relax.op.exp(relax.op.astype(v_16_l568meiu_var, dtype="float32")))
        assert str(v_22_0enz1n16.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_22_0enz1n16.struct_info.shape}"
        # input: [1, 6], [6, 6]
        # output: [6, 6]
        v_23_39yandb5 = bb.emit(relax.op.power(relax.op.astype(v_16_l568meiu_var, dtype="float32"), relax.op.astype(v_4_uat265el_var, dtype="float32")))
        assert str(v_23_39yandb5.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_23_39yandb5.struct_info.shape}"
        # input: [1, 6]
        # output: [1, 6]
        v_24_v5fuouug = bb.emit(relax.op.nn.gelu(v_16_l568meiu_var))
        assert str(v_24_v5fuouug.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_24_v5fuouug.struct_info.shape}"
        # input: [6, 6]
        # output: [6]
        v_25_2gw5rruh = bb.emit(relax.op.astype(relax.op.argmax(v_23_39yandb5, axis=-1), dtype="float32"))
        assert str(v_25_2gw5rruh.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_25_2gw5rruh.struct_info.shape}"
        bb.emit_func_output((v_0_kdj8e8ea_var, v_3_z0jh348v_var, v_8_22sikq8c_var, v_13_a1c8yz6s_var, v_15_u0cv0p0t_var, v_17_7jusxvkr, v_18_6e09qtiu, v_19_0n9dlwm1, v_20_z4mjlr9q, v_21_8p2z945f, v_22_0enz1n16, v_24_v5fuouug, v_25_2gw5rruh))

    v_0_kdj8e8ea_var = relax.Var("v_0_kdj8e8ea", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3]), dtype="float32"))
    v_3_z0jh348v_var = relax.Var("v_3_z0jh348v", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_8_22sikq8c_var = relax.Var("v_8_22sikq8c", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_13_a1c8yz6s_var = relax.Var("v_13_a1c8yz6s", relax.TensorStructInfo(shape=relax.ShapeExpr([6]), dtype="float32"))
    v_15_u0cv0p0t_var = relax.Var("v_15_u0cv0p0t", relax.TensorStructInfo(shape=relax.ShapeExpr([]), dtype="float32"))
    v_17_7jusxvkr_var = relax.Var("v_17_7jusxvkr", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 6]), dtype="float32"))
    v_18_6e09qtiu_var = relax.Var("v_18_6e09qtiu", relax.TensorStructInfo(shape=relax.ShapeExpr([249]), dtype="float32"))
    v_19_0n9dlwm1_var = relax.Var("v_19_0n9dlwm1", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_20_z4mjlr9q_var = relax.Var("v_20_z4mjlr9q", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_21_8p2z945f_var = relax.Var("v_21_8p2z945f", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_22_0enz1n16_var = relax.Var("v_22_0enz1n16", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_24_v5fuouug_var = relax.Var("v_24_v5fuouug", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_25_2gw5rruh_var = relax.Var("v_25_2gw5rruh", relax.TensorStructInfo(shape=relax.ShapeExpr([6]), dtype="float32"))
    v_26_618qphbm_var = relax.Var("v_26_618qphbm", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    with bb.function("graph_2", [v_0_kdj8e8ea_var, v_3_z0jh348v_var, v_8_22sikq8c_var, v_13_a1c8yz6s_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_20_z4mjlr9q_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_26_618qphbm_var]):
        # input: [2, 6], [6]
        # output: [2, 6]
        v_27_4w03nmah = bb.emit(relax.op.subtract(relax.op.astype(v_26_618qphbm_var, dtype="float32"), relax.op.astype(v_13_a1c8yz6s_var, dtype="float32")))
        assert str(v_27_4w03nmah.struct_info.shape) == "R.shape([2, 6])", f"Shape mismatch: expected R.shape([2, 6]), got {v_27_4w03nmah.struct_info.shape}"
        # input: [2, 6]
        # output: [2, 6]
        v_28_1y23upxp = bb.emit(relax.op.nn.layer_norm(v_26_618qphbm_var, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), axes=[-1]))
        assert str(v_28_1y23upxp.struct_info.shape) == "R.shape([2, 6])", f"Shape mismatch: expected R.shape([2, 6]), got {v_28_1y23upxp.struct_info.shape}"
        # input: 
        # output: [5, 4]
        v_29_0tgjkba4 = bb.emit(relax.op.ones(relax.ShapeExpr([5, 4]), dtype="float32"))
        assert str(v_29_0tgjkba4.struct_info.shape) == "R.shape([5, 4])", f"Shape mismatch: expected R.shape([5, 4]), got {v_29_0tgjkba4.struct_info.shape}"
        # input: 
        # output: [2, 5, 6, 4]
        v_30_rrv5fv5a = bb.emit(relax.op.full(relax.ShapeExpr([2, 5, 6, 4]), relax.const(0, dtype="float32")))
        assert str(v_30_rrv5fv5a.struct_info.shape) == "R.shape([2, 5, 6, 4])", f"Shape mismatch: expected R.shape([2, 5, 6, 4]), got {v_30_rrv5fv5a.struct_info.shape}"
        # input: [2, 6]
        # output: [2]
        v_31_1pdwv940 = bb.emit(relax.op.astype(relax.op.argmin(v_26_618qphbm_var, axis=-1), dtype="float32"))
        assert str(v_31_1pdwv940.struct_info.shape) == "R.shape([2])", f"Shape mismatch: expected R.shape([2]), got {v_31_1pdwv940.struct_info.shape}"
        # input: [2, 6]
        # output: [2]
        v_32_v3j8nnp3 = bb.emit(relax.op.sum(v_26_618qphbm_var, axis=[-1], keepdims=False))
        assert str(v_32_v3j8nnp3.struct_info.shape) == "R.shape([2])", f"Shape mismatch: expected R.shape([2]), got {v_32_v3j8nnp3.struct_info.shape}"
        # input: [2, 6]
        # output: [2, 6]
        v_33_gc59p0gm = bb.emit(relax.op.nn.layer_norm(v_26_618qphbm_var, gamma=relax.op.ones(relax.ShapeExpr([6]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([6]), dtype="float32"), axes=[-1]))
        assert str(v_33_gc59p0gm.struct_info.shape) == "R.shape([2, 6])", f"Shape mismatch: expected R.shape([2, 6]), got {v_33_gc59p0gm.struct_info.shape}"
        # input: [2, 6], [1, 6]
        # output: [2, 6]
        v_34_zh5hctqt = bb.emit(relax.op.minimum(relax.op.astype(v_26_618qphbm_var, dtype="float32"), relax.op.astype(v_20_z4mjlr9q_var, dtype="float32")))
        assert str(v_34_zh5hctqt.struct_info.shape) == "R.shape([2, 6])", f"Shape mismatch: expected R.shape([2, 6]), got {v_34_zh5hctqt.struct_info.shape}"
        bb.emit_func_output((v_0_kdj8e8ea_var, v_3_z0jh348v_var, v_8_22sikq8c_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_27_4w03nmah, v_28_1y23upxp, v_29_0tgjkba4, v_30_rrv5fv5a, v_31_1pdwv940, v_32_v3j8nnp3, v_33_gc59p0gm, v_34_zh5hctqt))

    v_0_kdj8e8ea_var = relax.Var("v_0_kdj8e8ea", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3]), dtype="float32"))
    v_3_z0jh348v_var = relax.Var("v_3_z0jh348v", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_8_22sikq8c_var = relax.Var("v_8_22sikq8c", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_15_u0cv0p0t_var = relax.Var("v_15_u0cv0p0t", relax.TensorStructInfo(shape=relax.ShapeExpr([]), dtype="float32"))
    v_17_7jusxvkr_var = relax.Var("v_17_7jusxvkr", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 6]), dtype="float32"))
    v_18_6e09qtiu_var = relax.Var("v_18_6e09qtiu", relax.TensorStructInfo(shape=relax.ShapeExpr([249]), dtype="float32"))
    v_19_0n9dlwm1_var = relax.Var("v_19_0n9dlwm1", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_21_8p2z945f_var = relax.Var("v_21_8p2z945f", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_22_0enz1n16_var = relax.Var("v_22_0enz1n16", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_24_v5fuouug_var = relax.Var("v_24_v5fuouug", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_25_2gw5rruh_var = relax.Var("v_25_2gw5rruh", relax.TensorStructInfo(shape=relax.ShapeExpr([6]), dtype="float32"))
    v_27_4w03nmah_var = relax.Var("v_27_4w03nmah", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_28_1y23upxp_var = relax.Var("v_28_1y23upxp", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_29_0tgjkba4_var = relax.Var("v_29_0tgjkba4", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4]), dtype="float32"))
    v_30_rrv5fv5a_var = relax.Var("v_30_rrv5fv5a", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5, 6, 4]), dtype="float32"))
    v_31_1pdwv940_var = relax.Var("v_31_1pdwv940", relax.TensorStructInfo(shape=relax.ShapeExpr([2]), dtype="float32"))
    v_32_v3j8nnp3_var = relax.Var("v_32_v3j8nnp3", relax.TensorStructInfo(shape=relax.ShapeExpr([2]), dtype="float32"))
    v_33_gc59p0gm_var = relax.Var("v_33_gc59p0gm", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_34_zh5hctqt_var = relax.Var("v_34_zh5hctqt", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_35_enxnoufa_var = relax.Var("v_35_enxnoufa", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5]), dtype="float32"))
    with bb.function("graph_3", [v_0_kdj8e8ea_var, v_3_z0jh348v_var, v_8_22sikq8c_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_27_4w03nmah_var, v_28_1y23upxp_var, v_29_0tgjkba4_var, v_30_rrv5fv5a_var, v_31_1pdwv940_var, v_32_v3j8nnp3_var, v_33_gc59p0gm_var, v_34_zh5hctqt_var, v_35_enxnoufa_var]):
        # input: [2, 5]
        # output: [2, 5]
        v_36_ck68sdfr = bb.emit(relax.op.sign(v_35_enxnoufa_var))
        assert str(v_36_ck68sdfr.struct_info.shape) == "R.shape([2, 5])", f"Shape mismatch: expected R.shape([2, 5]), got {v_36_ck68sdfr.struct_info.shape}"
        # input: [2, 5]
        # output: [2, 5]
        v_37_q97bx029 = bb.emit(relax.op.divide(relax.const(1.0, dtype="float32"), relax.op.astype(v_35_enxnoufa_var, dtype="float32")))
        assert str(v_37_q97bx029.struct_info.shape) == "R.shape([2, 5])", f"Shape mismatch: expected R.shape([2, 5]), got {v_37_q97bx029.struct_info.shape}"
        # input: [2, 5]
        # output: [2, 5]
        v_38_tm5k9sck = bb.emit(relax.op.where(relax.op.greater_equal(v_35_enxnoufa_var, relax.const(0, dtype="float32")), v_35_enxnoufa_var, relax.op.multiply(relax.const(1.02, dtype="float32"), relax.op.subtract(relax.op.exp(v_35_enxnoufa_var), relax.const(1.0, dtype="float32")))))
        assert str(v_38_tm5k9sck.struct_info.shape) == "R.shape([2, 5])", f"Shape mismatch: expected R.shape([2, 5]), got {v_38_tm5k9sck.struct_info.shape}"
        # input: [2, 5]
        # output: [5, 2]
        v_39_old3grrc = bb.emit(relax.op.permute_dims(v_35_enxnoufa_var, axes=[1, 0]))
        assert str(v_39_old3grrc.struct_info.shape) == "R.shape([5, 2])", f"Shape mismatch: expected R.shape([5, 2]), got {v_39_old3grrc.struct_info.shape}"
        # input: [2, 5]
        # output: [2, 5]
        v_40_i1l92j5k = bb.emit(relax.op.tile(v_35_enxnoufa_var, [1, 1]))
        assert str(v_40_i1l92j5k.struct_info.shape) == "R.shape([2, 5])", f"Shape mismatch: expected R.shape([2, 5]), got {v_40_i1l92j5k.struct_info.shape}"
        # input: [5, 2]
        # output: [5, 2]
        v_42_cyqe4rlv = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_39_old3grrc, dtype="float32"), axis=-1))
        assert str(v_42_cyqe4rlv.struct_info.shape) == "R.shape([5, 2])", f"Shape mismatch: expected R.shape([5, 2]), got {v_42_cyqe4rlv.struct_info.shape}"
        # input: [5, 2]
        # output: [5, 2]
        v_43_hkx33jv6 = bb.emit(relax.op.nn.relu(v_39_old3grrc))
        assert str(v_43_hkx33jv6.struct_info.shape) == "R.shape([5, 2])", f"Shape mismatch: expected R.shape([5, 2]), got {v_43_hkx33jv6.struct_info.shape}"
        # input: 
        # output: [2, 3]
        v_45_um2iqjxb = bb.emit(relax.op.ones(relax.ShapeExpr([2, 3]), dtype="float32"))
        assert str(v_45_um2iqjxb.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_45_um2iqjxb.struct_info.shape}"
        # input: [5, 2]
        # output: [5, 2]
        v_46_uq8pp870 = bb.emit(relax.op.divide(relax.op.log(relax.op.astype(v_39_old3grrc, dtype="float32")), relax.const(0.6931471805599453, dtype="float32")))
        assert str(v_46_uq8pp870.struct_info.shape) == "R.shape([5, 2])", f"Shape mismatch: expected R.shape([5, 2]), got {v_46_uq8pp870.struct_info.shape}"
        # input: [2, 3], [2, 3]
        # output: [2, 3]
        v_47_30qajn1e = bb.emit(relax.op.divide(relax.op.astype(v_45_um2iqjxb, dtype="float32"), relax.op.astype(v_0_kdj8e8ea_var, dtype="float32")))
        assert str(v_47_30qajn1e.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_47_30qajn1e.struct_info.shape}"
        bb.emit_func_output((v_3_z0jh348v_var, v_8_22sikq8c_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_27_4w03nmah_var, v_28_1y23upxp_var, v_29_0tgjkba4_var, v_30_rrv5fv5a_var, v_31_1pdwv940_var, v_32_v3j8nnp3_var, v_33_gc59p0gm_var, v_34_zh5hctqt_var, v_36_ck68sdfr, v_37_q97bx029, v_38_tm5k9sck, v_40_i1l92j5k, v_42_cyqe4rlv, v_43_hkx33jv6, v_46_uq8pp870, v_47_30qajn1e))

    v_3_z0jh348v_var = relax.Var("v_3_z0jh348v", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_8_22sikq8c_var = relax.Var("v_8_22sikq8c", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    v_15_u0cv0p0t_var = relax.Var("v_15_u0cv0p0t", relax.TensorStructInfo(shape=relax.ShapeExpr([]), dtype="float32"))
    v_17_7jusxvkr_var = relax.Var("v_17_7jusxvkr", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6, 6]), dtype="float32"))
    v_18_6e09qtiu_var = relax.Var("v_18_6e09qtiu", relax.TensorStructInfo(shape=relax.ShapeExpr([249]), dtype="float32"))
    v_19_0n9dlwm1_var = relax.Var("v_19_0n9dlwm1", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_21_8p2z945f_var = relax.Var("v_21_8p2z945f", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_22_0enz1n16_var = relax.Var("v_22_0enz1n16", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_24_v5fuouug_var = relax.Var("v_24_v5fuouug", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 6]), dtype="float32"))
    v_25_2gw5rruh_var = relax.Var("v_25_2gw5rruh", relax.TensorStructInfo(shape=relax.ShapeExpr([6]), dtype="float32"))
    v_27_4w03nmah_var = relax.Var("v_27_4w03nmah", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_28_1y23upxp_var = relax.Var("v_28_1y23upxp", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_29_0tgjkba4_var = relax.Var("v_29_0tgjkba4", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 4]), dtype="float32"))
    v_30_rrv5fv5a_var = relax.Var("v_30_rrv5fv5a", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5, 6, 4]), dtype="float32"))
    v_31_1pdwv940_var = relax.Var("v_31_1pdwv940", relax.TensorStructInfo(shape=relax.ShapeExpr([2]), dtype="float32"))
    v_32_v3j8nnp3_var = relax.Var("v_32_v3j8nnp3", relax.TensorStructInfo(shape=relax.ShapeExpr([2]), dtype="float32"))
    v_33_gc59p0gm_var = relax.Var("v_33_gc59p0gm", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_34_zh5hctqt_var = relax.Var("v_34_zh5hctqt", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 6]), dtype="float32"))
    v_36_ck68sdfr_var = relax.Var("v_36_ck68sdfr", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5]), dtype="float32"))
    v_37_q97bx029_var = relax.Var("v_37_q97bx029", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5]), dtype="float32"))
    v_38_tm5k9sck_var = relax.Var("v_38_tm5k9sck", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5]), dtype="float32"))
    v_40_i1l92j5k_var = relax.Var("v_40_i1l92j5k", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5]), dtype="float32"))
    v_42_cyqe4rlv_var = relax.Var("v_42_cyqe4rlv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2]), dtype="float32"))
    v_43_hkx33jv6_var = relax.Var("v_43_hkx33jv6", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2]), dtype="float32"))
    v_46_uq8pp870_var = relax.Var("v_46_uq8pp870", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2]), dtype="float32"))
    v_47_30qajn1e_var = relax.Var("v_47_30qajn1e", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3]), dtype="float32"))
    with bb.function("graph_4", [v_3_z0jh348v_var, v_8_22sikq8c_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_27_4w03nmah_var, v_28_1y23upxp_var, v_29_0tgjkba4_var, v_30_rrv5fv5a_var, v_31_1pdwv940_var, v_32_v3j8nnp3_var, v_33_gc59p0gm_var, v_34_zh5hctqt_var, v_36_ck68sdfr_var, v_37_q97bx029_var, v_38_tm5k9sck_var, v_40_i1l92j5k_var, v_42_cyqe4rlv_var, v_43_hkx33jv6_var, v_46_uq8pp870_var, v_47_30qajn1e_var]):
        # input: [2, 3]
        # output: [2, 3]
        v_48_3evis58m = bb.emit(relax.op.astype(v_47_30qajn1e_var, dtype="float32"))
        assert str(v_48_3evis58m.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_48_3evis58m.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_49_bn8fvs2g = bb.emit(relax.op.rsqrt(relax.op.astype(v_47_30qajn1e_var, dtype="float32")))
        assert str(v_49_bn8fvs2g.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_49_bn8fvs2g.struct_info.shape}"
        # input: [2, 5, 6, 4]
        # output: [2, 5, 12, 8]
        v_50_9mt1d50l = bb.emit(relax.op.image.resize2d(v_30_rrv5fv5a_var, relax.ShapeExpr([12, 8]), layout="NCHW"))
        assert str(v_50_9mt1d50l.struct_info.shape) == "R.shape([2, 5, 12, 8])", f"Shape mismatch: expected R.shape([2, 5, 12, 8]), got {v_50_9mt1d50l.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_53_lufgpo2x = bb.emit(relax.op.tile(v_47_30qajn1e_var, [1, 1]))
        assert str(v_53_lufgpo2x.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_53_lufgpo2x.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_54_tmhfb37v = bb.emit(relax.op.sqrt(relax.op.astype(v_47_30qajn1e_var, dtype="float32")))
        assert str(v_54_tmhfb37v.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_54_tmhfb37v.struct_info.shape}"
        # input: [2, 5, 6, 4]
        # output: [2, 5, 12, 8]
        v_56_rvtwpbsx = bb.emit(relax.op.image.resize2d(v_30_rrv5fv5a_var, relax.ShapeExpr([12, 8]), layout="NCHW"))
        assert str(v_56_rvtwpbsx.struct_info.shape) == "R.shape([2, 5, 12, 8])", f"Shape mismatch: expected R.shape([2, 5, 12, 8]), got {v_56_rvtwpbsx.struct_info.shape}"
        # input: 
        # output: [4, 5, 3]
        v_57_ockeeg0h = bb.emit(relax.op.full(relax.ShapeExpr([4, 5, 3]), relax.const(0, dtype="float32")))
        assert str(v_57_ockeeg0h.struct_info.shape) == "R.shape([4, 5, 3])", f"Shape mismatch: expected R.shape([4, 5, 3]), got {v_57_ockeeg0h.struct_info.shape}"
        # input: [2, 5, 12, 8]
        # output: [2, 5, 24, 16]
        v_58_2wew8jbx = bb.emit(relax.op.image.resize2d(v_56_rvtwpbsx, relax.ShapeExpr([24, 16]), layout="NCHW"))
        assert str(v_58_2wew8jbx.struct_info.shape) == "R.shape([2, 5, 24, 16])", f"Shape mismatch: expected R.shape([2, 5, 24, 16]), got {v_58_2wew8jbx.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_59_rqlfk2ac = bb.emit(relax.op.exp(relax.op.astype(v_47_30qajn1e_var, dtype="float32")))
        assert str(v_59_rqlfk2ac.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_59_rqlfk2ac.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_60_uijskyjk = bb.emit(relax.op.abs(v_47_30qajn1e_var))
        assert str(v_60_uijskyjk.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_60_uijskyjk.struct_info.shape}"
        # input: [2, 3]
        # output: [1, 3]
        v_61_fymmx32s = bb.emit(relax.op.strided_slice(v_47_30qajn1e_var, axes=[0], begin=[0], end=[1]))
        assert str(v_61_fymmx32s.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_61_fymmx32s.struct_info.shape}"
        # input: [2, 3], [2, 3]
        # output: [2, 3]
        v_62_ifwegm8j = bb.emit(relax.op.power(relax.op.astype(v_47_30qajn1e_var, dtype="float32"), relax.op.astype(v_53_lufgpo2x, dtype="float32")))
        assert str(v_62_ifwegm8j.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_62_ifwegm8j.struct_info.shape}"
        # input: [2, 3]
        # output: [2]
        v_64_9q9wev0y = bb.emit(relax.op.max(v_47_30qajn1e_var, axis=[-1], keepdims=False))
        assert str(v_64_9q9wev0y.struct_info.shape) == "R.shape([2])", f"Shape mismatch: expected R.shape([2]), got {v_64_9q9wev0y.struct_info.shape}"
        # input: [2, 3]
        # output: [2, 3]
        v_66_u69hrjct = bb.emit(relax.op.divide(relax.const(1.0, dtype="float32"), relax.op.astype(v_47_30qajn1e_var, dtype="float32")))
        assert str(v_66_u69hrjct.struct_info.shape) == "R.shape([2, 3])", f"Shape mismatch: expected R.shape([2, 3]), got {v_66_u69hrjct.struct_info.shape}"
        # input: [2, 5, 12, 8]
        # output: [2, 5, 24, 16]
        v_67_j7oo5bv2 = bb.emit(relax.op.image.resize2d(v_56_rvtwpbsx, relax.ShapeExpr([24, 16]), layout="NCHW"))
        assert str(v_67_j7oo5bv2.struct_info.shape) == "R.shape([2, 5, 24, 16])", f"Shape mismatch: expected R.shape([2, 5, 24, 16]), got {v_67_j7oo5bv2.struct_info.shape}"
        bb.emit_func_output((v_3_z0jh348v_var, v_8_22sikq8c_var, v_15_u0cv0p0t_var, v_17_7jusxvkr_var, v_18_6e09qtiu_var, v_19_0n9dlwm1_var, v_21_8p2z945f_var, v_22_0enz1n16_var, v_24_v5fuouug_var, v_25_2gw5rruh_var, v_27_4w03nmah_var, v_28_1y23upxp_var, v_29_0tgjkba4_var, v_31_1pdwv940_var, v_32_v3j8nnp3_var, v_33_gc59p0gm_var, v_34_zh5hctqt_var, v_36_ck68sdfr_var, v_37_q97bx029_var, v_38_tm5k9sck_var, v_40_i1l92j5k_var, v_42_cyqe4rlv_var, v_43_hkx33jv6_var, v_46_uq8pp870_var, v_48_3evis58m, v_49_bn8fvs2g, v_50_9mt1d50l, v_54_tmhfb37v, v_57_ockeeg0h, v_58_2wew8jbx, v_59_rqlfk2ac, v_60_uijskyjk, v_61_fymmx32s, v_62_ifwegm8j, v_64_9q9wev0y, v_66_u69hrjct, v_67_j7oo5bv2))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)

# === Cross-target differential mode: CPU vs GPU ===
ex_cpu = relax.build(mod, target="llvm")
vm_cpu = relax.VirtualMachine(ex_cpu, tvm.cpu())
ex_gpu = relax.build(mod, target="cuda")
vm_gpu = relax.VirtualMachine(ex_gpu, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_kdj8e8ea = np.random.uniform(0.0, 1.0, size=(2, 3)).astype(np.float32)
v_0_kdj8e8ea_cpu = tvm.runtime.tensor(np_v_0_kdj8e8ea)
v_0_kdj8e8ea_gpu = tvm.runtime.tensor(np_v_0_kdj8e8ea, device=tvm.cuda())
np_v_1_nakcrlja = np.random.uniform(0.0, 1.0, size=(6, 6)).astype(np.float32)
v_1_nakcrlja_cpu = tvm.runtime.tensor(np_v_1_nakcrlja)
v_1_nakcrlja_gpu = tvm.runtime.tensor(np_v_1_nakcrlja, device=tvm.cuda())

# CPU execution
tvm_result_cpu_0 = vm_cpu["graph_0"](v_0_kdj8e8ea_cpu, v_1_nakcrlja_cpu)
# GPU execution
tvm_result_gpu_0 = vm_gpu["graph_0"](v_0_kdj8e8ea_gpu, v_1_nakcrlja_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_0
_gpu_val = tvm_result_gpu_0
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_0: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_0: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_0: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_0[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_0[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Chained: graph_0 -> graph_1
_prev_cpu = tvm_result_cpu_0
_prev_gpu = tvm_result_gpu_0
v_0_kdj8e8ea_cpu = _prev_cpu[0]
v_0_kdj8e8ea_gpu = _prev_gpu[0]
v_3_z0jh348v_cpu = _prev_cpu[1]
v_3_z0jh348v_gpu = _prev_gpu[1]
v_4_uat265el_cpu = _prev_cpu[2]
v_4_uat265el_gpu = _prev_gpu[2]
v_8_22sikq8c_cpu = _prev_cpu[3]
v_8_22sikq8c_gpu = _prev_gpu[3]
v_10_pvdnl2zx_cpu = _prev_cpu[4]
v_10_pvdnl2zx_gpu = _prev_gpu[4]
v_13_a1c8yz6s_cpu = _prev_cpu[5]
v_13_a1c8yz6s_gpu = _prev_gpu[5]
v_15_u0cv0p0t_cpu = _prev_cpu[6]
v_15_u0cv0p0t_gpu = _prev_gpu[6]
v_16_l568meiu_cpu = _prev_cpu[7]
v_16_l568meiu_gpu = _prev_gpu[7]

# CPU execution
tvm_result_cpu_1 = vm_cpu["graph_1"](v_0_kdj8e8ea_cpu, v_3_z0jh348v_cpu, v_4_uat265el_cpu, v_8_22sikq8c_cpu, v_10_pvdnl2zx_cpu, v_13_a1c8yz6s_cpu, v_15_u0cv0p0t_cpu, v_16_l568meiu_cpu)
# GPU execution
tvm_result_gpu_1 = vm_gpu["graph_1"](v_0_kdj8e8ea_gpu, v_3_z0jh348v_gpu, v_4_uat265el_gpu, v_8_22sikq8c_gpu, v_10_pvdnl2zx_gpu, v_13_a1c8yz6s_gpu, v_15_u0cv0p0t_gpu, v_16_l568meiu_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_1
_gpu_val = tvm_result_gpu_1
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_1: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_1: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_1: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_1[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_1[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Generate fresh inputs for graph_2
np_v_26_618qphbm = np.random.uniform(0.0, 1.0, size=(2, 6)).astype(np.float32)
v_26_618qphbm_cpu = tvm.runtime.tensor(np_v_26_618qphbm)
v_26_618qphbm_gpu = tvm.runtime.tensor(np_v_26_618qphbm, device=tvm.cuda())

# Chained: graph_1 -> graph_2
_prev_cpu = tvm_result_cpu_1
_prev_gpu = tvm_result_gpu_1
v_0_kdj8e8ea_cpu = _prev_cpu[0]
v_0_kdj8e8ea_gpu = _prev_gpu[0]
v_3_z0jh348v_cpu = _prev_cpu[1]
v_3_z0jh348v_gpu = _prev_gpu[1]
v_8_22sikq8c_cpu = _prev_cpu[2]
v_8_22sikq8c_gpu = _prev_gpu[2]
v_13_a1c8yz6s_cpu = _prev_cpu[3]
v_13_a1c8yz6s_gpu = _prev_gpu[3]
v_15_u0cv0p0t_cpu = _prev_cpu[4]
v_15_u0cv0p0t_gpu = _prev_gpu[4]
v_17_7jusxvkr_cpu = _prev_cpu[5]
v_17_7jusxvkr_gpu = _prev_gpu[5]
v_18_6e09qtiu_cpu = _prev_cpu[6]
v_18_6e09qtiu_gpu = _prev_gpu[6]
v_19_0n9dlwm1_cpu = _prev_cpu[7]
v_19_0n9dlwm1_gpu = _prev_gpu[7]
v_20_z4mjlr9q_cpu = _prev_cpu[8]
v_20_z4mjlr9q_gpu = _prev_gpu[8]
v_21_8p2z945f_cpu = _prev_cpu[9]
v_21_8p2z945f_gpu = _prev_gpu[9]
v_22_0enz1n16_cpu = _prev_cpu[10]
v_22_0enz1n16_gpu = _prev_gpu[10]
v_24_v5fuouug_cpu = _prev_cpu[11]
v_24_v5fuouug_gpu = _prev_gpu[11]
v_25_2gw5rruh_cpu = _prev_cpu[12]
v_25_2gw5rruh_gpu = _prev_gpu[12]

# CPU execution
tvm_result_cpu_2 = vm_cpu["graph_2"](v_0_kdj8e8ea_cpu, v_3_z0jh348v_cpu, v_8_22sikq8c_cpu, v_13_a1c8yz6s_cpu, v_15_u0cv0p0t_cpu, v_17_7jusxvkr_cpu, v_18_6e09qtiu_cpu, v_19_0n9dlwm1_cpu, v_20_z4mjlr9q_cpu, v_21_8p2z945f_cpu, v_22_0enz1n16_cpu, v_24_v5fuouug_cpu, v_25_2gw5rruh_cpu, v_26_618qphbm_cpu)
# GPU execution
tvm_result_gpu_2 = vm_gpu["graph_2"](v_0_kdj8e8ea_gpu, v_3_z0jh348v_gpu, v_8_22sikq8c_gpu, v_13_a1c8yz6s_gpu, v_15_u0cv0p0t_gpu, v_17_7jusxvkr_gpu, v_18_6e09qtiu_gpu, v_19_0n9dlwm1_gpu, v_20_z4mjlr9q_gpu, v_21_8p2z945f_gpu, v_22_0enz1n16_gpu, v_24_v5fuouug_gpu, v_25_2gw5rruh_gpu, v_26_618qphbm_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_2
_gpu_val = tvm_result_gpu_2
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_2: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_2: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_2: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_2[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_2[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Generate fresh inputs for graph_3
np_v_35_enxnoufa = np.random.uniform(0.0, 1.0, size=(2, 5)).astype(np.float32)
v_35_enxnoufa_cpu = tvm.runtime.tensor(np_v_35_enxnoufa)
v_35_enxnoufa_gpu = tvm.runtime.tensor(np_v_35_enxnoufa, device=tvm.cuda())

# Chained: graph_2 -> graph_3
_prev_cpu = tvm_result_cpu_2
_prev_gpu = tvm_result_gpu_2
v_0_kdj8e8ea_cpu = _prev_cpu[0]
v_0_kdj8e8ea_gpu = _prev_gpu[0]
v_3_z0jh348v_cpu = _prev_cpu[1]
v_3_z0jh348v_gpu = _prev_gpu[1]
v_8_22sikq8c_cpu = _prev_cpu[2]
v_8_22sikq8c_gpu = _prev_gpu[2]
v_15_u0cv0p0t_cpu = _prev_cpu[3]
v_15_u0cv0p0t_gpu = _prev_gpu[3]
v_17_7jusxvkr_cpu = _prev_cpu[4]
v_17_7jusxvkr_gpu = _prev_gpu[4]
v_18_6e09qtiu_cpu = _prev_cpu[5]
v_18_6e09qtiu_gpu = _prev_gpu[5]
v_19_0n9dlwm1_cpu = _prev_cpu[6]
v_19_0n9dlwm1_gpu = _prev_gpu[6]
v_21_8p2z945f_cpu = _prev_cpu[7]
v_21_8p2z945f_gpu = _prev_gpu[7]
v_22_0enz1n16_cpu = _prev_cpu[8]
v_22_0enz1n16_gpu = _prev_gpu[8]
v_24_v5fuouug_cpu = _prev_cpu[9]
v_24_v5fuouug_gpu = _prev_gpu[9]
v_25_2gw5rruh_cpu = _prev_cpu[10]
v_25_2gw5rruh_gpu = _prev_gpu[10]
v_27_4w03nmah_cpu = _prev_cpu[11]
v_27_4w03nmah_gpu = _prev_gpu[11]
v_28_1y23upxp_cpu = _prev_cpu[12]
v_28_1y23upxp_gpu = _prev_gpu[12]
v_29_0tgjkba4_cpu = _prev_cpu[13]
v_29_0tgjkba4_gpu = _prev_gpu[13]
v_30_rrv5fv5a_cpu = _prev_cpu[14]
v_30_rrv5fv5a_gpu = _prev_gpu[14]
v_31_1pdwv940_cpu = _prev_cpu[15]
v_31_1pdwv940_gpu = _prev_gpu[15]
v_32_v3j8nnp3_cpu = _prev_cpu[16]
v_32_v3j8nnp3_gpu = _prev_gpu[16]
v_33_gc59p0gm_cpu = _prev_cpu[17]
v_33_gc59p0gm_gpu = _prev_gpu[17]
v_34_zh5hctqt_cpu = _prev_cpu[18]
v_34_zh5hctqt_gpu = _prev_gpu[18]

# CPU execution
tvm_result_cpu_3 = vm_cpu["graph_3"](v_0_kdj8e8ea_cpu, v_3_z0jh348v_cpu, v_8_22sikq8c_cpu, v_15_u0cv0p0t_cpu, v_17_7jusxvkr_cpu, v_18_6e09qtiu_cpu, v_19_0n9dlwm1_cpu, v_21_8p2z945f_cpu, v_22_0enz1n16_cpu, v_24_v5fuouug_cpu, v_25_2gw5rruh_cpu, v_27_4w03nmah_cpu, v_28_1y23upxp_cpu, v_29_0tgjkba4_cpu, v_30_rrv5fv5a_cpu, v_31_1pdwv940_cpu, v_32_v3j8nnp3_cpu, v_33_gc59p0gm_cpu, v_34_zh5hctqt_cpu, v_35_enxnoufa_cpu)
# GPU execution
tvm_result_gpu_3 = vm_gpu["graph_3"](v_0_kdj8e8ea_gpu, v_3_z0jh348v_gpu, v_8_22sikq8c_gpu, v_15_u0cv0p0t_gpu, v_17_7jusxvkr_gpu, v_18_6e09qtiu_gpu, v_19_0n9dlwm1_gpu, v_21_8p2z945f_gpu, v_22_0enz1n16_gpu, v_24_v5fuouug_gpu, v_25_2gw5rruh_gpu, v_27_4w03nmah_gpu, v_28_1y23upxp_gpu, v_29_0tgjkba4_gpu, v_30_rrv5fv5a_gpu, v_31_1pdwv940_gpu, v_32_v3j8nnp3_gpu, v_33_gc59p0gm_gpu, v_34_zh5hctqt_gpu, v_35_enxnoufa_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_3
_gpu_val = tvm_result_gpu_3
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_3: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_3: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_3: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_3[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_3[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Chained: graph_3 -> graph_4
_prev_cpu = tvm_result_cpu_3
_prev_gpu = tvm_result_gpu_3
v_3_z0jh348v_cpu = _prev_cpu[0]
v_3_z0jh348v_gpu = _prev_gpu[0]
v_8_22sikq8c_cpu = _prev_cpu[1]
v_8_22sikq8c_gpu = _prev_gpu[1]
v_15_u0cv0p0t_cpu = _prev_cpu[2]
v_15_u0cv0p0t_gpu = _prev_gpu[2]
v_17_7jusxvkr_cpu = _prev_cpu[3]
v_17_7jusxvkr_gpu = _prev_gpu[3]
v_18_6e09qtiu_cpu = _prev_cpu[4]
v_18_6e09qtiu_gpu = _prev_gpu[4]
v_19_0n9dlwm1_cpu = _prev_cpu[5]
v_19_0n9dlwm1_gpu = _prev_gpu[5]
v_21_8p2z945f_cpu = _prev_cpu[6]
v_21_8p2z945f_gpu = _prev_gpu[6]
v_22_0enz1n16_cpu = _prev_cpu[7]
v_22_0enz1n16_gpu = _prev_gpu[7]
v_24_v5fuouug_cpu = _prev_cpu[8]
v_24_v5fuouug_gpu = _prev_gpu[8]
v_25_2gw5rruh_cpu = _prev_cpu[9]
v_25_2gw5rruh_gpu = _prev_gpu[9]
v_27_4w03nmah_cpu = _prev_cpu[10]
v_27_4w03nmah_gpu = _prev_gpu[10]
v_28_1y23upxp_cpu = _prev_cpu[11]
v_28_1y23upxp_gpu = _prev_gpu[11]
v_29_0tgjkba4_cpu = _prev_cpu[12]
v_29_0tgjkba4_gpu = _prev_gpu[12]
v_30_rrv5fv5a_cpu = _prev_cpu[13]
v_30_rrv5fv5a_gpu = _prev_gpu[13]
v_31_1pdwv940_cpu = _prev_cpu[14]
v_31_1pdwv940_gpu = _prev_gpu[14]
v_32_v3j8nnp3_cpu = _prev_cpu[15]
v_32_v3j8nnp3_gpu = _prev_gpu[15]
v_33_gc59p0gm_cpu = _prev_cpu[16]
v_33_gc59p0gm_gpu = _prev_gpu[16]
v_34_zh5hctqt_cpu = _prev_cpu[17]
v_34_zh5hctqt_gpu = _prev_gpu[17]
v_36_ck68sdfr_cpu = _prev_cpu[18]
v_36_ck68sdfr_gpu = _prev_gpu[18]
v_37_q97bx029_cpu = _prev_cpu[19]
v_37_q97bx029_gpu = _prev_gpu[19]
v_38_tm5k9sck_cpu = _prev_cpu[20]
v_38_tm5k9sck_gpu = _prev_gpu[20]
v_40_i1l92j5k_cpu = _prev_cpu[21]
v_40_i1l92j5k_gpu = _prev_gpu[21]
v_42_cyqe4rlv_cpu = _prev_cpu[22]
v_42_cyqe4rlv_gpu = _prev_gpu[22]
v_43_hkx33jv6_cpu = _prev_cpu[23]
v_43_hkx33jv6_gpu = _prev_gpu[23]
v_46_uq8pp870_cpu = _prev_cpu[24]
v_46_uq8pp870_gpu = _prev_gpu[24]
v_47_30qajn1e_cpu = _prev_cpu[25]
v_47_30qajn1e_gpu = _prev_gpu[25]

# CPU execution
tvm_result_cpu_4 = vm_cpu["graph_4"](v_3_z0jh348v_cpu, v_8_22sikq8c_cpu, v_15_u0cv0p0t_cpu, v_17_7jusxvkr_cpu, v_18_6e09qtiu_cpu, v_19_0n9dlwm1_cpu, v_21_8p2z945f_cpu, v_22_0enz1n16_cpu, v_24_v5fuouug_cpu, v_25_2gw5rruh_cpu, v_27_4w03nmah_cpu, v_28_1y23upxp_cpu, v_29_0tgjkba4_cpu, v_30_rrv5fv5a_cpu, v_31_1pdwv940_cpu, v_32_v3j8nnp3_cpu, v_33_gc59p0gm_cpu, v_34_zh5hctqt_cpu, v_36_ck68sdfr_cpu, v_37_q97bx029_cpu, v_38_tm5k9sck_cpu, v_40_i1l92j5k_cpu, v_42_cyqe4rlv_cpu, v_43_hkx33jv6_cpu, v_46_uq8pp870_cpu, v_47_30qajn1e_cpu)
# GPU execution
tvm_result_gpu_4 = vm_gpu["graph_4"](v_3_z0jh348v_gpu, v_8_22sikq8c_gpu, v_15_u0cv0p0t_gpu, v_17_7jusxvkr_gpu, v_18_6e09qtiu_gpu, v_19_0n9dlwm1_gpu, v_21_8p2z945f_gpu, v_22_0enz1n16_gpu, v_24_v5fuouug_gpu, v_25_2gw5rruh_gpu, v_27_4w03nmah_gpu, v_28_1y23upxp_gpu, v_29_0tgjkba4_gpu, v_30_rrv5fv5a_gpu, v_31_1pdwv940_gpu, v_32_v3j8nnp3_gpu, v_33_gc59p0gm_gpu, v_34_zh5hctqt_gpu, v_36_ck68sdfr_gpu, v_37_q97bx029_gpu, v_38_tm5k9sck_gpu, v_40_i1l92j5k_gpu, v_42_cyqe4rlv_gpu, v_43_hkx33jv6_gpu, v_46_uq8pp870_gpu, v_47_30qajn1e_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_4
_gpu_val = tvm_result_gpu_4
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_4: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_4: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_4: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_4[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_4[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')
print("Execution: OK")
