# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_8gf4onw4_var = relax.Var("v_0_8gf4onw4", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 4]), dtype="float32"))
    with bb.function("graph_0", [v_0_8gf4onw4_var]):
        # input: [1, 4]
        # output: [1, 4]
        v_1_oebzi7vb = bb.emit(relax.op.tril(v_0_8gf4onw4_var))
        assert str(v_1_oebzi7vb.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_1_oebzi7vb.struct_info.shape}"
        # input: [1, 4], [1, 4]
        # output: [1, 4]
        v_2_6trsmmk0 = bb.emit(relax.op.subtract(relax.op.astype(v_0_8gf4onw4_var, dtype="float32"), relax.op.astype(v_1_oebzi7vb, dtype="float32")))
        assert str(v_2_6trsmmk0.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_2_6trsmmk0.struct_info.shape}"
        # input: [1, 4]
        # output: [4, 1]
        v_3_zz23f0fy = bb.emit(relax.op.permute_dims(v_0_8gf4onw4_var, axes=[1, 0]))
        assert str(v_3_zz23f0fy.struct_info.shape) == "R.shape([4, 1])", f"Shape mismatch: expected R.shape([4, 1]), got {v_3_zz23f0fy.struct_info.shape}"
        # input: [1, 4]
        # output: [1, 4]
        v_4_lu6p2e6k = bb.emit(relax.op.sigmoid(v_0_8gf4onw4_var))
        assert str(v_4_lu6p2e6k.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_4_lu6p2e6k.struct_info.shape}"
        # input: [1, 4]
        # output: [1, 4]
        v_5_v15e8hdb = bb.emit(relax.op.nn.leakyrelu(v_0_8gf4onw4_var, alpha=0.15))
        assert str(v_5_v15e8hdb.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_5_v15e8hdb.struct_info.shape}"
        # input: [1, 4]
        # output: [1, 4]
        v_6_0w2vntyn = bb.emit(relax.op.multiply(v_4_lu6p2e6k, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_4_lu6p2e6k))))))
        assert str(v_6_0w2vntyn.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_6_0w2vntyn.struct_info.shape}"
        # input: [1, 4]
        # output: [4]
        v_7_su4nz5p7 = bb.emit(relax.op.take(v_4_lu6p2e6k, relax.const(0, dtype="int64"), axis=0))
        assert str(v_7_su4nz5p7.struct_info.shape) == "R.shape([4])", f"Shape mismatch: expected R.shape([4]), got {v_7_su4nz5p7.struct_info.shape}"
        # input: 
        # output: [4, 2, 5]
        v_8_tgr1ejuw = bb.emit(relax.op.ones(relax.ShapeExpr([4, 2, 5]), dtype="float32"))
        assert str(v_8_tgr1ejuw.struct_info.shape) == "R.shape([4, 2, 5])", f"Shape mismatch: expected R.shape([4, 2, 5]), got {v_8_tgr1ejuw.struct_info.shape}"
        # input: [4]
        # output: []
        v_9_1uzd81rd = bb.emit(relax.op.max(v_7_su4nz5p7, axis=[-1], keepdims=False))
        assert str(v_9_1uzd81rd.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_9_1uzd81rd.struct_info.shape}"
        # input: [4]
        # output: [4]
        v_10_6z7m30u8 = bb.emit(relax.op.nn.layer_norm(v_7_su4nz5p7, gamma=relax.op.ones(relax.ShapeExpr([4]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([4]), dtype="float32"), axes=[-1]))
        assert str(v_10_6z7m30u8.struct_info.shape) == "R.shape([4])", f"Shape mismatch: expected R.shape([4]), got {v_10_6z7m30u8.struct_info.shape}"
        # input: [4], [1, 4]
        # output: [1, 4]
        v_11_qsbhh4se = bb.emit(relax.op.subtract(relax.op.astype(v_7_su4nz5p7, dtype="float32"), relax.op.astype(v_4_lu6p2e6k, dtype="float32")))
        assert str(v_11_qsbhh4se.struct_info.shape) == "R.shape([1, 4])", f"Shape mismatch: expected R.shape([1, 4]), got {v_11_qsbhh4se.struct_info.shape}"
        # input: [4, 1]
        # output: [4, 1]
        v_12_czflrgav = bb.emit(relax.op.triu(v_3_zz23f0fy))
        assert str(v_12_czflrgav.struct_info.shape) == "R.shape([4, 1])", f"Shape mismatch: expected R.shape([4, 1]), got {v_12_czflrgav.struct_info.shape}"
        # input: [4]
        # output: [4]
        v_13_0l04v366 = bb.emit(relax.op.sigmoid(v_10_6z7m30u8))
        assert str(v_13_0l04v366.struct_info.shape) == "R.shape([4])", f"Shape mismatch: expected R.shape([4]), got {v_13_0l04v366.struct_info.shape}"
        # input: [4, 1]
        # output: [4, 1]
        v_14_paqaqsp9 = bb.emit(relax.op.where(relax.op.greater_equal(v_12_czflrgav, relax.const(0, dtype="float32")), v_12_czflrgav, relax.op.multiply(relax.const(1.31, dtype="float32"), relax.op.subtract(relax.op.exp(v_12_czflrgav), relax.const(1.0, dtype="float32")))))
        assert str(v_14_paqaqsp9.struct_info.shape) == "R.shape([4, 1])", f"Shape mismatch: expected R.shape([4, 1]), got {v_14_paqaqsp9.struct_info.shape}"
        # input: [4, 1]
        # output: [4, 1]
        v_15_l1lc2fzg = bb.emit(relax.op.astype(v_12_czflrgav, dtype="float32"))
        assert str(v_15_l1lc2fzg.struct_info.shape) == "R.shape([4, 1])", f"Shape mismatch: expected R.shape([4, 1]), got {v_15_l1lc2fzg.struct_info.shape}"
        bb.emit_func_output((v_2_6trsmmk0, v_5_v15e8hdb, v_6_0w2vntyn, v_8_tgr1ejuw, v_9_1uzd81rd, v_11_qsbhh4se, v_13_0l04v366, v_14_paqaqsp9, v_15_l1lc2fzg))

    v_0_s9liz9bd_var = relax.Var("v_0_s9liz9bd", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 4, 1]), dtype="float32"))
    with bb.function("graph_1", [v_0_s9liz9bd_var]):
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_1_f26jmg40 = bb.emit(relax.op.triu(v_0_s9liz9bd_var))
        assert str(v_1_f26jmg40.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_1_f26jmg40.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_2_us9sf9rc = bb.emit(relax.op.tanh(v_0_s9liz9bd_var))
        assert str(v_2_us9sf9rc.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_2_us9sf9rc.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_3_2fjqtvew = bb.emit(relax.op.nn.silu(v_0_s9liz9bd_var))
        assert str(v_3_2fjqtvew.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_3_2fjqtvew.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_4_6d093hmp = bb.emit(relax.op.clip(v_2_us9sf9rc, -1, 2))
        assert str(v_4_6d093hmp.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_4_6d093hmp.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_5_4nsirdqk = bb.emit(relax.op.clip(v_3_2fjqtvew, -1.87, 1.86))
        assert str(v_5_4nsirdqk.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_5_4nsirdqk.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_6_qv6xd6j0 = bb.emit(relax.op.tile(v_3_2fjqtvew, [1, 1, 1]))
        assert str(v_6_qv6xd6j0.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_6_qv6xd6j0.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_7_6agk19vm = bb.emit(relax.op.tril(v_5_4nsirdqk))
        assert str(v_7_6agk19vm.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_7_6agk19vm.struct_info.shape}"
        # input: 
        # output: [3, 1]
        v_8_bmkgvpq2 = bb.emit(relax.op.ones(relax.ShapeExpr([3, 1]), dtype="float32"))
        assert str(v_8_bmkgvpq2.struct_info.shape) == "R.shape([3, 1])", f"Shape mismatch: expected R.shape([3, 1]), got {v_8_bmkgvpq2.struct_info.shape}"
        # input: 
        # output: [23]
        v_9_7962l75r = bb.emit(relax.op.arange(0, 23, dtype="float32"))
        assert str(v_9_7962l75r.struct_info.shape) == "R.shape([23])", f"Shape mismatch: expected R.shape([23]), got {v_9_7962l75r.struct_info.shape}"
        # input: [3, 1]
        # output: [3, 1]
        v_10_jw7jlrim = bb.emit(relax.op.nn.softmax(relax.op.astype(v_8_bmkgvpq2, dtype="float32"), axis=-1))
        assert str(v_10_jw7jlrim.struct_info.shape) == "R.shape([3, 1])", f"Shape mismatch: expected R.shape([3, 1]), got {v_10_jw7jlrim.struct_info.shape}"
        # input: [3, 1]
        # output: [3, 1]
        v_11_nt4rxpm3 = bb.emit(relax.op.clip(v_8_bmkgvpq2, -1.97, 1.23))
        assert str(v_11_nt4rxpm3.struct_info.shape) == "R.shape([3, 1])", f"Shape mismatch: expected R.shape([3, 1]), got {v_11_nt4rxpm3.struct_info.shape}"
        # input: [3, 1]
        # output: [1, 3]
        v_12_2sfk3gyk = bb.emit(relax.op.permute_dims(v_10_jw7jlrim, axes=[1, 0]))
        assert str(v_12_2sfk3gyk.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_12_2sfk3gyk.struct_info.shape}"
        # input: [1, 4, 1]
        # output: [1, 4, 1]
        v_13_wd4k8wv4_bn_tuple = bb.emit(relax.op.nn.batch_norm(v_2_us9sf9rc, gamma=relax.op.ones(relax.ShapeExpr([4]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([4]), dtype="float32"), moving_mean=relax.op.zeros(relax.ShapeExpr([4]), dtype="float32"), moving_var=relax.op.ones(relax.ShapeExpr([4]), dtype="float32"), axis=1))
        v_13_wd4k8wv4 = bb.emit(relax.TupleGetItem(v_13_wd4k8wv4_bn_tuple, 0))
        assert str(v_13_wd4k8wv4.struct_info.shape) == "R.shape([1, 4, 1])", f"Shape mismatch: expected R.shape([1, 4, 1]), got {v_13_wd4k8wv4.struct_info.shape}"
        # input: [3, 1]
        # output: [3, 1]
        v_14_l851yn15 = bb.emit(relax.op.astype(v_11_nt4rxpm3, dtype="float32"))
        assert str(v_14_l851yn15.struct_info.shape) == "R.shape([3, 1])", f"Shape mismatch: expected R.shape([3, 1]), got {v_14_l851yn15.struct_info.shape}"
        # input: [3, 1]
        # output: [1]
        v_15_132icrtp = bb.emit(relax.op.take(v_11_nt4rxpm3, relax.const(0, dtype="int64"), axis=0))
        assert str(v_15_132icrtp.struct_info.shape) == "R.shape([1])", f"Shape mismatch: expected R.shape([1]), got {v_15_132icrtp.struct_info.shape}"
        # input: [3, 1]
        # output: [1, 1]
        v_16_3oco4mpl = bb.emit(relax.op.strided_slice(v_11_nt4rxpm3, axes=[0], begin=[0], end=[1]))
        assert str(v_16_3oco4mpl.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_16_3oco4mpl.struct_info.shape}"
        bb.emit_func_output((v_1_f26jmg40, v_4_6d093hmp, v_6_qv6xd6j0, v_7_6agk19vm, v_9_7962l75r, v_12_2sfk3gyk, v_13_wd4k8wv4, v_14_l851yn15, v_15_132icrtp, v_16_3oco4mpl))

    v_0_7d3jctwv_var = relax.Var("v_0_7d3jctwv", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 3]), dtype="float32"))
    v_1_xq0j9o6e_var = relax.Var("v_1_xq0j9o6e", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 1, 3]), dtype="float32"))
    with bb.function("graph_2", [v_0_7d3jctwv_var, v_1_xq0j9o6e_var]):
        # input: [6, 1, 3]
        # output: [6, 3, 1]
        v_2_eep0lv5r = bb.emit(relax.op.permute_dims(v_1_xq0j9o6e_var, axes=[0, 2, 1]))
        assert str(v_2_eep0lv5r.struct_info.shape) == "R.shape([6, 3, 1])", f"Shape mismatch: expected R.shape([6, 3, 1]), got {v_2_eep0lv5r.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_3_sis3d0xm = bb.emit(relax.op.clip(v_1_xq0j9o6e_var, -1, 1))
        assert str(v_3_sis3d0xm.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_3_sis3d0xm.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_4_rc9dpsx2 = bb.emit(relax.op.tril(v_1_xq0j9o6e_var))
        assert str(v_4_rc9dpsx2.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_4_rc9dpsx2.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_5_6c1harxo = bb.emit(relax.op.multiply(v_3_sis3d0xm, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_3_sis3d0xm))))))
        assert str(v_5_6c1harxo.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_5_6c1harxo.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_6_4lpbzfqd = bb.emit(relax.op.negative(v_3_sis3d0xm))
        assert str(v_6_4lpbzfqd.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_6_4lpbzfqd.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_7_487dmidc = bb.emit(relax.op.nn.leakyrelu(v_3_sis3d0xm, alpha=0.24))
        assert str(v_7_487dmidc.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_7_487dmidc.struct_info.shape}"
        # input: [6, 1, 3]
        # output: [6, 1, 3]
        v_8_zl0t8v5w = bb.emit(relax.op.tile(v_3_sis3d0xm, [1, 1, 1]))
        assert str(v_8_zl0t8v5w.struct_info.shape) == "R.shape([6, 1, 3])", f"Shape mismatch: expected R.shape([6, 1, 3]), got {v_8_zl0t8v5w.struct_info.shape}"
        bb.emit_func_output((v_0_7d3jctwv_var, v_2_eep0lv5r, v_4_rc9dpsx2, v_5_6c1harxo, v_6_4lpbzfqd, v_7_487dmidc, v_8_zl0t8v5w))

    v_0_1mfyaok7_var = relax.Var("v_0_1mfyaok7", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1]), dtype="float32"))
    with bb.function("graph_3", [v_0_1mfyaok7_var]):
        # input: 
        # output: [5, 2]
        v_1_nuo89a9e = bb.emit(relax.op.ones(relax.ShapeExpr([5, 2]), dtype="float32"))
        assert str(v_1_nuo89a9e.struct_info.shape) == "R.shape([5, 2])", f"Shape mismatch: expected R.shape([5, 2]), got {v_1_nuo89a9e.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_2_pz7v9l5r = bb.emit(relax.op.permute_dims(v_0_1mfyaok7_var, axes=[1, 0]))
        assert str(v_2_pz7v9l5r.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_2_pz7v9l5r.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_3_gpppcwig = bb.emit(relax.op.nn.layer_norm(v_0_1mfyaok7_var, gamma=relax.op.ones(relax.ShapeExpr([1]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"), axes=[-1]))
        assert str(v_3_gpppcwig.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_3_gpppcwig.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_4_r2xxgwmb = bb.emit(relax.op.clip(v_0_1mfyaok7_var, -1, 1))
        assert str(v_4_r2xxgwmb.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_4_r2xxgwmb.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_5_luq6ig6q = bb.emit(relax.op.where(relax.op.greater_equal(v_0_1mfyaok7_var, relax.const(0, dtype="float32")), v_0_1mfyaok7_var, relax.op.multiply(relax.const(1.55, dtype="float32"), relax.op.subtract(relax.op.exp(v_0_1mfyaok7_var), relax.const(1.0, dtype="float32")))))
        assert str(v_5_luq6ig6q.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_5_luq6ig6q.struct_info.shape}"
        # input: [1, 1]
        # output: [1]
        v_6_luif2qeh = bb.emit(relax.op.take(v_0_1mfyaok7_var, relax.const(0, dtype="int64"), axis=0))
        assert str(v_6_luif2qeh.struct_info.shape) == "R.shape([1])", f"Shape mismatch: expected R.shape([1]), got {v_6_luif2qeh.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_7_18m3tvin = bb.emit(relax.op.astype(v_5_luq6ig6q, dtype="float32"))
        assert str(v_7_18m3tvin.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_7_18m3tvin.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_8_qyry1nkd = bb.emit(relax.op.clip(v_5_luq6ig6q, -1, 1))
        assert str(v_8_qyry1nkd.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_8_qyry1nkd.struct_info.shape}"
        # input: [1, 1]
        # output: [1, 1]
        v_9_4nu410kc = bb.emit(relax.op.clip(v_7_18m3tvin, -1, 2))
        assert str(v_9_4nu410kc.struct_info.shape) == "R.shape([1, 1])", f"Shape mismatch: expected R.shape([1, 1]), got {v_9_4nu410kc.struct_info.shape}"
        # input: 
        # output: [2, 4]
        v_10_pke8x3tf = bb.emit(relax.op.full(relax.ShapeExpr([2, 4]), relax.const(0, dtype="float32")))
        assert str(v_10_pke8x3tf.struct_info.shape) == "R.shape([2, 4])", f"Shape mismatch: expected R.shape([2, 4]), got {v_10_pke8x3tf.struct_info.shape}"
        bb.emit_func_output((v_1_nuo89a9e, v_2_pz7v9l5r, v_3_gpppcwig, v_4_r2xxgwmb, v_6_luif2qeh, v_8_qyry1nkd, v_9_4nu410kc, v_10_pke8x3tf))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate inputs for graph_0
np_v_0_8gf4onw4 = np.random.uniform(0.0, 1.0, size=(1, 4)).astype(np.float32)
v_0_8gf4onw4 = tvm.runtime.tensor(np_v_0_8gf4onw4, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_0_8gf4onw4)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Generate inputs for graph_1
np_v_0_s9liz9bd = np.random.uniform(0.0, 1.0, size=(1, 4, 1)).astype(np.float32)
v_0_s9liz9bd = tvm.runtime.tensor(np_v_0_s9liz9bd, device=tvm.cuda())

tvm_result_1 = vm["graph_1"](v_0_s9liz9bd)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Generate inputs for graph_2
np_v_0_7d3jctwv = np.random.uniform(0.0, 1.0, size=(4, 3)).astype(np.float32)
v_0_7d3jctwv = tvm.runtime.tensor(np_v_0_7d3jctwv, device=tvm.cuda())
np_v_1_xq0j9o6e = np.random.uniform(0.0, 1.0, size=(6, 1, 3)).astype(np.float32)
v_1_xq0j9o6e = tvm.runtime.tensor(np_v_1_xq0j9o6e, device=tvm.cuda())

tvm_result_2 = vm["graph_2"](v_0_7d3jctwv, v_1_xq0j9o6e)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")

# Generate inputs for graph_3
np_v_0_1mfyaok7 = np.random.uniform(0.0, 1.0, size=(1, 1)).astype(np.float32)
v_0_1mfyaok7 = tvm.runtime.tensor(np_v_0_1mfyaok7, device=tvm.cuda())

tvm_result_3 = vm["graph_3"](v_0_1mfyaok7)
# Print output
if hasattr(tvm_result_3, 'numpy'):
    _arr = tvm_result_3.numpy()
    print(f"[TVM-OUT] graph_3: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_3)):
        _arr = tvm_result_3[_tvmi].numpy()
        print(f"[TVM-OUT] graph_3[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
