# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_dxyjwqd3_var = relax.Var("v_0_dxyjwqd3", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 3, 1]), dtype="float32"))
    v_1_o4w9jzqa_var = relax.Var("v_1_o4w9jzqa", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_kl62l33q_var = relax.Var("v_2_kl62l33q", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 5, 3]), dtype="float32"))
    v_3_n4kbau62_var = relax.Var("v_3_n4kbau62", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    with bb.function("graph_0", [v_0_dxyjwqd3_var, v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_3_n4kbau62_var]):
        # input: [5, 6, 3]
        # output: [5, 6, 3]
        v_4_bsy2hqwy = bb.emit(relax.op.astype(v_3_n4kbau62_var, dtype="float32"))
        assert str(v_4_bsy2hqwy.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_4_bsy2hqwy.struct_info.shape}"
        # input: [5, 6, 3]
        # output: [5, 6, 3]
        v_5_iqh0rg1z = bb.emit(relax.op.abs(v_3_n4kbau62_var))
        assert str(v_5_iqh0rg1z.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_5_iqh0rg1z.struct_info.shape}"
        # input: [5, 6, 3]
        # output: [5, 6, 3]
        v_6_zw20ujg4 = bb.emit(relax.op.nn.leakyrelu(v_3_n4kbau62_var, alpha=0.19))
        assert str(v_6_zw20ujg4.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_6_zw20ujg4.struct_info.shape}"
        # input: [5, 6, 3]
        # output: [5, 6, 3]
        v_7_knw6s1gz = bb.emit(relax.op.astype(v_3_n4kbau62_var, dtype="float32"))
        assert str(v_7_knw6s1gz.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_7_knw6s1gz.struct_info.shape}"
        # input: [5, 6, 3]
        # output: [5, 6, 3]
        v_8_hb1of550 = bb.emit(relax.op.nn.leakyrelu(v_6_zw20ujg4, alpha=0.1))
        assert str(v_8_hb1of550.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_8_hb1of550.struct_info.shape}"
        # input: [5, 6, 3]
        # output: [5, 3, 6]
        v_9_7zl7nhp9 = bb.emit(relax.op.permute_dims(v_7_knw6s1gz, axes=[0, 2, 1]))
        assert str(v_9_7zl7nhp9.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_9_7zl7nhp9.struct_info.shape}"
        # input: [5, 6, 3], [5, 6, 3]
        # output: [5, 6, 3]
        v_10_4cilz59e = bb.emit(relax.op.multiply(relax.op.astype(v_7_knw6s1gz, dtype="float32"), relax.op.astype(v_3_n4kbau62_var, dtype="float32")))
        assert str(v_10_4cilz59e.struct_info.shape) == "R.shape([5, 6, 3])", f"Shape mismatch: expected R.shape([5, 6, 3]), got {v_10_4cilz59e.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [2, 3, 6]
        v_11_m9biuqp3 = bb.emit(relax.op.strided_slice(v_9_7zl7nhp9, axes=[0], begin=[0], end=[2]))
        assert str(v_11_m9biuqp3.struct_info.shape) == "R.shape([2, 3, 6])", f"Shape mismatch: expected R.shape([2, 3, 6]), got {v_11_m9biuqp3.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_12_27uyzkpv = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_9_7zl7nhp9, dtype="float32"), axis=-1))
        assert str(v_12_27uyzkpv.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_12_27uyzkpv.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [5, 3, 6]
        v_13_xr96w948 = bb.emit(relax.op.nn.selu(v_9_7zl7nhp9))
        assert str(v_13_xr96w948.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_13_xr96w948.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [1, 5, 3, 6]
        v_14_vkllpwxa = bb.emit(relax.op.expand_dims(v_9_7zl7nhp9, axis=0))
        assert str(v_14_vkllpwxa.struct_info.shape) == "R.shape([1, 5, 3, 6])", f"Shape mismatch: expected R.shape([1, 5, 3, 6]), got {v_14_vkllpwxa.struct_info.shape}"
        # input: [5, 3, 6]
        # output: [3, 6]
        v_15_5ie5v3vj = bb.emit(relax.op.take(v_9_7zl7nhp9, relax.const(0, dtype="int64"), axis=0))
        assert str(v_15_5ie5v3vj.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_15_5ie5v3vj.struct_info.shape}"
        # input: [5, 3, 6], [3, 6]
        # output: [5, 3, 6]
        v_16_rec1lelf = bb.emit(relax.op.minimum(relax.op.astype(v_9_7zl7nhp9, dtype="float32"), relax.op.astype(v_15_5ie5v3vj, dtype="float32")))
        assert str(v_16_rec1lelf.struct_info.shape) == "R.shape([5, 3, 6])", f"Shape mismatch: expected R.shape([5, 3, 6]), got {v_16_rec1lelf.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_17_lebd0wpr = bb.emit(relax.op.where(relax.op.greater_equal(v_15_5ie5v3vj, relax.const(0, dtype="float32")), v_15_5ie5v3vj, relax.op.multiply(relax.const(1.06, dtype="float32"), relax.op.subtract(relax.op.exp(v_15_5ie5v3vj), relax.const(1.0, dtype="float32")))))
        assert str(v_17_lebd0wpr.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_17_lebd0wpr.struct_info.shape}"
        bb.emit_func_output((v_0_dxyjwqd3_var, v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_4_bsy2hqwy, v_5_iqh0rg1z, v_8_hb1of550, v_10_4cilz59e, v_11_m9biuqp3, v_12_27uyzkpv, v_13_xr96w948, v_14_vkllpwxa, v_16_rec1lelf, v_17_lebd0wpr))

    v_0_dxyjwqd3_var = relax.Var("v_0_dxyjwqd3", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 3, 1]), dtype="float32"))
    v_1_o4w9jzqa_var = relax.Var("v_1_o4w9jzqa", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_kl62l33q_var = relax.Var("v_2_kl62l33q", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 5, 3]), dtype="float32"))
    v_4_bsy2hqwy_var = relax.Var("v_4_bsy2hqwy", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_5_iqh0rg1z_var = relax.Var("v_5_iqh0rg1z", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_8_hb1of550_var = relax.Var("v_8_hb1of550", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_10_4cilz59e_var = relax.Var("v_10_4cilz59e", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_11_m9biuqp3_var = relax.Var("v_11_m9biuqp3", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3, 6]), dtype="float32"))
    v_12_27uyzkpv_var = relax.Var("v_12_27uyzkpv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_13_xr96w948_var = relax.Var("v_13_xr96w948", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_14_vkllpwxa_var = relax.Var("v_14_vkllpwxa", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 3, 6]), dtype="float32"))
    v_16_rec1lelf_var = relax.Var("v_16_rec1lelf", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_17_lebd0wpr_var = relax.Var("v_17_lebd0wpr", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    with bb.function("graph_1", [v_0_dxyjwqd3_var, v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_4_bsy2hqwy_var, v_5_iqh0rg1z_var, v_8_hb1of550_var, v_10_4cilz59e_var, v_11_m9biuqp3_var, v_12_27uyzkpv_var, v_13_xr96w948_var, v_14_vkllpwxa_var, v_16_rec1lelf_var, v_17_lebd0wpr_var]):
        # input: [3, 6], [4, 5, 3, 1]
        # output: [4, 5, 3, 6]
        v_18_nlyzkg9k = bb.emit(relax.op.add(relax.op.astype(v_17_lebd0wpr_var, dtype="float32"), relax.op.astype(v_0_dxyjwqd3_var, dtype="float32")))
        assert str(v_18_nlyzkg9k.struct_info.shape) == "R.shape([4, 5, 3, 6])", f"Shape mismatch: expected R.shape([4, 5, 3, 6]), got {v_18_nlyzkg9k.struct_info.shape}"
        # input: [3, 6], [1, 5, 3, 6]
        # output: [1, 5, 3, 6]
        v_19_8nrapz2r = bb.emit(relax.op.subtract(relax.op.astype(v_17_lebd0wpr_var, dtype="float32"), relax.op.astype(v_14_vkllpwxa_var, dtype="float32")))
        assert str(v_19_8nrapz2r.struct_info.shape) == "R.shape([1, 5, 3, 6])", f"Shape mismatch: expected R.shape([1, 5, 3, 6]), got {v_19_8nrapz2r.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_20_2us1oje3 = bb.emit(relax.op.tanh(v_17_lebd0wpr_var))
        assert str(v_20_2us1oje3.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_20_2us1oje3.struct_info.shape}"
        # input: 
        # output: [2, 5, 5]
        v_21_qnt8ph3e = bb.emit(relax.op.zeros(relax.ShapeExpr([2, 5, 5]), dtype="float32"))
        assert str(v_21_qnt8ph3e.struct_info.shape) == "R.shape([2, 5, 5])", f"Shape mismatch: expected R.shape([2, 5, 5]), got {v_21_qnt8ph3e.struct_info.shape}"
        # input: [3, 6]
        # output: [3]
        v_22_2ysvasl7 = bb.emit(relax.op.max(v_17_lebd0wpr_var, axis=[-1], keepdims=False))
        assert str(v_22_2ysvasl7.struct_info.shape) == "R.shape([3])", f"Shape mismatch: expected R.shape([3]), got {v_22_2ysvasl7.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_23_emb46t8f = bb.emit(relax.op.clip(v_17_lebd0wpr_var, -1.96, 2.5))
        assert str(v_23_emb46t8f.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_23_emb46t8f.struct_info.shape}"
        # input: [3], [4, 5, 3, 1]
        # output: [4, 5, 3, 3]
        v_24_afgxo06l = bb.emit(relax.op.maximum(relax.op.astype(v_22_2ysvasl7, dtype="float32"), relax.op.astype(v_0_dxyjwqd3_var, dtype="float32")))
        assert str(v_24_afgxo06l.struct_info.shape) == "R.shape([4, 5, 3, 3])", f"Shape mismatch: expected R.shape([4, 5, 3, 3]), got {v_24_afgxo06l.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_25_cotrz1h5 = bb.emit(relax.op.nn.gelu(v_23_emb46t8f))
        assert str(v_25_cotrz1h5.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_25_cotrz1h5.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_26_x4d0i7ei = bb.emit(relax.op.nn.leakyrelu(v_23_emb46t8f, alpha=0.1))
        assert str(v_26_x4d0i7ei.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_26_x4d0i7ei.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_27_3wicvb86 = bb.emit(relax.op.multiply(v_23_emb46t8f, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_23_emb46t8f))))))
        assert str(v_27_3wicvb86.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_27_3wicvb86.struct_info.shape}"
        # input: [3, 6]
        # output: [3, 6]
        v_28_f1iwf6kn = bb.emit(relax.op.sigmoid(v_23_emb46t8f))
        assert str(v_28_f1iwf6kn.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_28_f1iwf6kn.struct_info.shape}"
        # input: 
        # output: [4, 5, 2, 1]
        v_29_inbherzy = bb.emit(relax.op.zeros(relax.ShapeExpr([4, 5, 2, 1]), dtype="float32"))
        assert str(v_29_inbherzy.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_29_inbherzy.struct_info.shape}"
        bb.emit_func_output((v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_4_bsy2hqwy_var, v_5_iqh0rg1z_var, v_8_hb1of550_var, v_10_4cilz59e_var, v_11_m9biuqp3_var, v_12_27uyzkpv_var, v_13_xr96w948_var, v_16_rec1lelf_var, v_18_nlyzkg9k, v_19_8nrapz2r, v_20_2us1oje3, v_21_qnt8ph3e, v_24_afgxo06l, v_25_cotrz1h5, v_26_x4d0i7ei, v_27_3wicvb86, v_28_f1iwf6kn, v_29_inbherzy))

    v_1_o4w9jzqa_var = relax.Var("v_1_o4w9jzqa", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_2_kl62l33q_var = relax.Var("v_2_kl62l33q", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 5, 3]), dtype="float32"))
    v_4_bsy2hqwy_var = relax.Var("v_4_bsy2hqwy", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_5_iqh0rg1z_var = relax.Var("v_5_iqh0rg1z", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_8_hb1of550_var = relax.Var("v_8_hb1of550", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_10_4cilz59e_var = relax.Var("v_10_4cilz59e", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 3]), dtype="float32"))
    v_11_m9biuqp3_var = relax.Var("v_11_m9biuqp3", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3, 6]), dtype="float32"))
    v_12_27uyzkpv_var = relax.Var("v_12_27uyzkpv", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_13_xr96w948_var = relax.Var("v_13_xr96w948", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_16_rec1lelf_var = relax.Var("v_16_rec1lelf", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6]), dtype="float32"))
    v_18_nlyzkg9k_var = relax.Var("v_18_nlyzkg9k", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 3, 6]), dtype="float32"))
    v_19_8nrapz2r_var = relax.Var("v_19_8nrapz2r", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 3, 6]), dtype="float32"))
    v_20_2us1oje3_var = relax.Var("v_20_2us1oje3", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_21_qnt8ph3e_var = relax.Var("v_21_qnt8ph3e", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 5, 5]), dtype="float32"))
    v_24_afgxo06l_var = relax.Var("v_24_afgxo06l", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 3, 3]), dtype="float32"))
    v_25_cotrz1h5_var = relax.Var("v_25_cotrz1h5", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_26_x4d0i7ei_var = relax.Var("v_26_x4d0i7ei", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_27_3wicvb86_var = relax.Var("v_27_3wicvb86", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_28_f1iwf6kn_var = relax.Var("v_28_f1iwf6kn", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_29_inbherzy_var = relax.Var("v_29_inbherzy", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 2, 1]), dtype="float32"))
    with bb.function("graph_2", [v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_4_bsy2hqwy_var, v_5_iqh0rg1z_var, v_8_hb1of550_var, v_10_4cilz59e_var, v_11_m9biuqp3_var, v_12_27uyzkpv_var, v_13_xr96w948_var, v_16_rec1lelf_var, v_18_nlyzkg9k_var, v_19_8nrapz2r_var, v_20_2us1oje3_var, v_21_qnt8ph3e_var, v_24_afgxo06l_var, v_25_cotrz1h5_var, v_26_x4d0i7ei_var, v_27_3wicvb86_var, v_28_f1iwf6kn_var, v_29_inbherzy_var]):
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_30_b25tz2bu = bb.emit(relax.op.negative(v_29_inbherzy_var))
        assert str(v_30_b25tz2bu.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_30_b25tz2bu.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [2, 5, 2, 1]
        v_31_i4pr2ogf = bb.emit(relax.op.strided_slice(v_29_inbherzy_var, axes=[0], begin=[0], end=[2]))
        assert str(v_31_i4pr2ogf.struct_info.shape) == "R.shape([2, 5, 2, 1])", f"Shape mismatch: expected R.shape([2, 5, 2, 1]), got {v_31_i4pr2ogf.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_32_nrjn116z = bb.emit(relax.op.nn.silu(v_29_inbherzy_var))
        assert str(v_32_nrjn116z.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_32_nrjn116z.struct_info.shape}"
        # input: [2, 5, 2, 1]
        # output: [2, 5, 2]
        v_33_wt6xnakd = bb.emit(relax.op.max(v_31_i4pr2ogf, axis=[-1], keepdims=False))
        assert str(v_33_wt6xnakd.struct_info.shape) == "R.shape([2, 5, 2])", f"Shape mismatch: expected R.shape([2, 5, 2]), got {v_33_wt6xnakd.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_34_jc9o01v4 = bb.emit(relax.op.nn.softmax(relax.op.astype(v_32_nrjn116z, dtype="float32"), axis=-1))
        assert str(v_34_jc9o01v4.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_34_jc9o01v4.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_35_br6gpigu = bb.emit(relax.op.clip(v_32_nrjn116z, -0.56, 1.11))
        assert str(v_35_br6gpigu.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_35_br6gpigu.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_36_8qj76hxf = bb.emit(relax.op.nn.leakyrelu(v_32_nrjn116z, alpha=0.01))
        assert str(v_36_8qj76hxf.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_36_8qj76hxf.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_37_nwbezgar = bb.emit(relax.op.nn.relu(v_32_nrjn116z))
        assert str(v_37_nwbezgar.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_37_nwbezgar.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_38_moqbogh3 = bb.emit(relax.op.nn.silu(v_32_nrjn116z))
        assert str(v_38_moqbogh3.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_38_moqbogh3.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_39_mwf33dkh = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_32_nrjn116z, dtype="float32"), axis=-1))
        assert str(v_39_mwf33dkh.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_39_mwf33dkh.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [2, 5, 2, 1]
        v_40_j1r51vfx = bb.emit(relax.op.strided_slice(v_32_nrjn116z, axes=[0], begin=[0], end=[2]))
        assert str(v_40_j1r51vfx.struct_info.shape) == "R.shape([2, 5, 2, 1])", f"Shape mismatch: expected R.shape([2, 5, 2, 1]), got {v_40_j1r51vfx.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_41_qrte9d92 = bb.emit(relax.op.nn.silu(v_32_nrjn116z))
        assert str(v_41_qrte9d92.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_41_qrte9d92.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_42_pckzyf4w = bb.emit(relax.op.nn.gelu(v_32_nrjn116z))
        assert str(v_42_pckzyf4w.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_42_pckzyf4w.struct_info.shape}"
        # input: [4, 5, 2, 1], [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_43_w6zqopi1 = bb.emit(relax.op.minimum(relax.op.astype(v_32_nrjn116z, dtype="float32"), relax.op.astype(v_39_mwf33dkh, dtype="float32")))
        assert str(v_43_w6zqopi1.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_43_w6zqopi1.struct_info.shape}"
        # input: [4, 5, 2, 1]
        # output: [4, 5, 2, 1]
        v_44_ru4yec4c = bb.emit(relax.op.nn.softmax(relax.op.astype(v_32_nrjn116z, dtype="float32"), axis=-1))
        assert str(v_44_ru4yec4c.struct_info.shape) == "R.shape([4, 5, 2, 1])", f"Shape mismatch: expected R.shape([4, 5, 2, 1]), got {v_44_ru4yec4c.struct_info.shape}"
        bb.emit_func_output((v_1_o4w9jzqa_var, v_2_kl62l33q_var, v_4_bsy2hqwy_var, v_5_iqh0rg1z_var, v_8_hb1of550_var, v_10_4cilz59e_var, v_11_m9biuqp3_var, v_12_27uyzkpv_var, v_13_xr96w948_var, v_16_rec1lelf_var, v_18_nlyzkg9k_var, v_19_8nrapz2r_var, v_20_2us1oje3_var, v_21_qnt8ph3e_var, v_24_afgxo06l_var, v_25_cotrz1h5_var, v_26_x4d0i7ei_var, v_27_3wicvb86_var, v_28_f1iwf6kn_var, v_30_b25tz2bu, v_33_wt6xnakd, v_34_jc9o01v4, v_35_br6gpigu, v_36_8qj76hxf, v_37_nwbezgar, v_38_moqbogh3, v_40_j1r51vfx, v_41_qrte9d92, v_42_pckzyf4w, v_43_w6zqopi1, v_44_ru4yec4c))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="llvm")
vm = relax.VirtualMachine(ex, tvm.cpu())

# Generate fresh inputs for graph_0
np_v_0_dxyjwqd3 = np.random.uniform(0.0, 1.0, size=(4, 5, 3, 1)).astype(np.float32)
v_0_dxyjwqd3 = tvm.runtime.tensor(np_v_0_dxyjwqd3)
np_v_1_o4w9jzqa = np.random.uniform(0.0, 1.0, size=(3, 6)).astype(np.float32)
v_1_o4w9jzqa = tvm.runtime.tensor(np_v_1_o4w9jzqa)
np_v_2_kl62l33q = np.random.uniform(0.0, 1.0, size=(5, 5, 3)).astype(np.float32)
v_2_kl62l33q = tvm.runtime.tensor(np_v_2_kl62l33q)
np_v_3_n4kbau62 = np.random.uniform(0.0, 1.0, size=(5, 6, 3)).astype(np.float32)
v_3_n4kbau62 = tvm.runtime.tensor(np_v_3_n4kbau62)

tvm_result_0 = vm["graph_0"](v_0_dxyjwqd3, v_1_o4w9jzqa, v_2_kl62l33q, v_3_n4kbau62)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_0 -> graph_1
_prev_out = tvm_result_0 if not hasattr(tvm_result_0, 'numpy') else [tvm_result_0]
v_0_dxyjwqd3 = _prev_out[0]
v_1_o4w9jzqa = _prev_out[1]
v_2_kl62l33q = _prev_out[2]
v_4_bsy2hqwy = _prev_out[3]
v_5_iqh0rg1z = _prev_out[4]
v_8_hb1of550 = _prev_out[5]
v_10_4cilz59e = _prev_out[6]
v_11_m9biuqp3 = _prev_out[7]
v_12_27uyzkpv = _prev_out[8]
v_13_xr96w948 = _prev_out[9]
v_14_vkllpwxa = _prev_out[10]
v_16_rec1lelf = _prev_out[11]
v_17_lebd0wpr = _prev_out[12]

tvm_result_1 = vm["graph_1"](v_0_dxyjwqd3, v_1_o4w9jzqa, v_2_kl62l33q, v_4_bsy2hqwy, v_5_iqh0rg1z, v_8_hb1of550, v_10_4cilz59e, v_11_m9biuqp3, v_12_27uyzkpv, v_13_xr96w948, v_14_vkllpwxa, v_16_rec1lelf, v_17_lebd0wpr)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_1 -> graph_2
_prev_out = tvm_result_1 if not hasattr(tvm_result_1, 'numpy') else [tvm_result_1]
v_1_o4w9jzqa = _prev_out[0]
v_2_kl62l33q = _prev_out[1]
v_4_bsy2hqwy = _prev_out[2]
v_5_iqh0rg1z = _prev_out[3]
v_8_hb1of550 = _prev_out[4]
v_10_4cilz59e = _prev_out[5]
v_11_m9biuqp3 = _prev_out[6]
v_12_27uyzkpv = _prev_out[7]
v_13_xr96w948 = _prev_out[8]
v_16_rec1lelf = _prev_out[9]
v_18_nlyzkg9k = _prev_out[10]
v_19_8nrapz2r = _prev_out[11]
v_20_2us1oje3 = _prev_out[12]
v_21_qnt8ph3e = _prev_out[13]
v_24_afgxo06l = _prev_out[14]
v_25_cotrz1h5 = _prev_out[15]
v_26_x4d0i7ei = _prev_out[16]
v_27_3wicvb86 = _prev_out[17]
v_28_f1iwf6kn = _prev_out[18]
v_29_inbherzy = _prev_out[19]

tvm_result_2 = vm["graph_2"](v_1_o4w9jzqa, v_2_kl62l33q, v_4_bsy2hqwy, v_5_iqh0rg1z, v_8_hb1of550, v_10_4cilz59e, v_11_m9biuqp3, v_12_27uyzkpv, v_13_xr96w948, v_16_rec1lelf, v_18_nlyzkg9k, v_19_8nrapz2r, v_20_2us1oje3, v_21_qnt8ph3e, v_24_afgxo06l, v_25_cotrz1h5, v_26_x4d0i7ei, v_27_3wicvb86, v_28_f1iwf6kn, v_29_inbherzy)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
