# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_30_90kai4jz_var = relax.Var("v_30_90kai4jz", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    with bb.function("graph_1", [v_30_90kai4jz_var]):
        # input: 
        # output: [1, 1, 1, 2]
        v_32_7rrxmow7 = bb.emit(relax.op.full(relax.ShapeExpr([1, 1, 1, 2]), relax.const(0, dtype="float32")))
        assert str(v_32_7rrxmow7.struct_info.shape) == "R.shape([1, 1, 1, 2])", f"Shape mismatch: expected R.shape([1, 1, 1, 2]), got {v_32_7rrxmow7.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 1, 1, 2]
        # output: [1, 1, 3, 9]
        v_33_843judqx = bb.emit(relax.op.nn.conv2d(v_30_90kai4jz_var, v_32_7rrxmow7, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_33_843judqx.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_33_843judqx.struct_info.shape}"
        bb.emit_func_output(v_33_843judqx)

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_1
np_v_30_90kai4jz = np.random.uniform(0.0, 1.0, size=(1, 1, 3, 10)).astype(np.float32)
v_30_90kai4jz = tvm.runtime.tensor(np_v_30_90kai4jz, device=tvm.cuda())

tvm_result_0 = vm["graph_1"](v_30_90kai4jz)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
