# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_sclpgjx3_var = relax.Var("v_0_sclpgjx3", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 4, 4]), dtype="float32"))
    v_1_drs2ebrm_var = relax.Var("v_1_drs2ebrm", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 4]), dtype="float32"))
    v_2_2fi3nk6u_var = relax.Var("v_2_2fi3nk6u", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2]), dtype="float32"))
    v_3_g7z05ycg_var = relax.Var("v_3_g7z05ycg", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    with bb.function("graph_0", [v_0_sclpgjx3_var, v_1_drs2ebrm_var, v_2_2fi3nk6u_var, v_3_g7z05ycg_var]):
        # input: [3, 6]
        # output: [3, 6]
        v_4_0pb6p2ca = bb.emit(relax.op.nn.softmax(relax.op.astype(v_3_g7z05ycg_var, dtype="float32"), axis=-1))
        assert str(v_4_0pb6p2ca.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_4_0pb6p2ca.struct_info.shape}"
        # input: [2, 2, 4, 4]
        # output: [2, 2, 4, 4]
        v_5_geptsxop = bb.emit(relax.op.nn.avg_pool2d(v_0_sclpgjx3_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_5_geptsxop.struct_info.shape) == "R.shape([2, 2, 4, 4])", f"Shape mismatch: expected R.shape([2, 2, 4, 4]), got {v_5_geptsxop.struct_info.shape}"
        # input: [2, 2, 4, 4]
        # output: [2, 2, 8, 8]
        v_6_kmj1qndj = bb.emit(relax.op.image.resize2d(v_5_geptsxop, relax.ShapeExpr([8, 8]), layout="NCHW"))
        assert str(v_6_kmj1qndj.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_6_kmj1qndj.struct_info.shape}"
        # input: [3, 6], [3, 6]
        # output: [3, 6]
        v_7_9679rs9y = bb.emit(relax.op.add(relax.op.astype(v_3_g7z05ycg_var, dtype="float32"), relax.op.astype(v_4_0pb6p2ca, dtype="float32")))
        assert str(v_7_9679rs9y.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_7_9679rs9y.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8, 8]
        v_8_ptcsddhk = bb.emit(relax.op.nn.avg_pool2d(v_6_kmj1qndj, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_8_ptcsddhk.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_8_ptcsddhk.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8, 8]
        v_9_vs57ghxn = bb.emit(relax.op.clip(v_6_kmj1qndj, 0, 1))
        assert str(v_9_vs57ghxn.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_9_vs57ghxn.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8]
        v_10_o39iynm6 = bb.emit(relax.op.max(v_6_kmj1qndj, axis=[-1], keepdims=False))
        assert str(v_10_o39iynm6.struct_info.shape) == "R.shape([2, 2, 8])", f"Shape mismatch: expected R.shape([2, 2, 8]), got {v_10_o39iynm6.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8, 8]
        v_11_hy90gyap = bb.emit(relax.op.tril(v_9_vs57ghxn))
        assert str(v_11_hy90gyap.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_11_hy90gyap.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8, 8]
        v_12_6cayy0n2 = bb.emit(relax.op.nn.avg_pool2d(v_9_vs57ghxn, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_12_6cayy0n2.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_12_6cayy0n2.struct_info.shape}"
        bb.emit_func_output((v_1_drs2ebrm_var, v_2_2fi3nk6u_var, v_7_9679rs9y, v_8_ptcsddhk, v_10_o39iynm6, v_11_hy90gyap, v_12_6cayy0n2))

    v_1_drs2ebrm_var = relax.Var("v_1_drs2ebrm", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 4]), dtype="float32"))
    v_2_2fi3nk6u_var = relax.Var("v_2_2fi3nk6u", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2]), dtype="float32"))
    v_7_9679rs9y_var = relax.Var("v_7_9679rs9y", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_8_ptcsddhk_var = relax.Var("v_8_ptcsddhk", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_10_o39iynm6_var = relax.Var("v_10_o39iynm6", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8]), dtype="float32"))
    v_11_hy90gyap_var = relax.Var("v_11_hy90gyap", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_12_6cayy0n2_var = relax.Var("v_12_6cayy0n2", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_13_qbxbpfka_var = relax.Var("v_13_qbxbpfka", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 6, 3]), dtype="float32"))
    with bb.function("graph_1", [v_1_drs2ebrm_var, v_2_2fi3nk6u_var, v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_11_hy90gyap_var, v_12_6cayy0n2_var, v_13_qbxbpfka_var]):
        # input: [5, 2, 6, 3]
        # output: [5, 2, 6]
        v_14_tqlx03tt = bb.emit(relax.op.max(v_13_qbxbpfka_var, axis=[-1], keepdims=False))
        assert str(v_14_tqlx03tt.struct_info.shape) == "R.shape([5, 2, 6])", f"Shape mismatch: expected R.shape([5, 2, 6]), got {v_14_tqlx03tt.struct_info.shape}"
        # input: [5, 2, 6, 3]
        # output: [5, 2, 3, 1]
        v_15_jtr9wdtj = bb.emit(relax.op.nn.avg_pool2d(v_13_qbxbpfka_var, pool_size=[2, 2], strides=[2, 2], padding=[0, 0]))
        assert str(v_15_jtr9wdtj.struct_info.shape) == "R.shape([5, 2, 3, 1])", f"Shape mismatch: expected R.shape([5, 2, 3, 1]), got {v_15_jtr9wdtj.struct_info.shape}"
        # input: [5, 2, 6]
        # output: [5, 2, 6]
        v_16_32f5s7mj = bb.emit(relax.op.nn.gelu(v_14_tqlx03tt))
        assert str(v_16_32f5s7mj.struct_info.shape) == "R.shape([5, 2, 6])", f"Shape mismatch: expected R.shape([5, 2, 6]), got {v_16_32f5s7mj.struct_info.shape}"
        # input: [2, 2]
        # output: [1, 2, 2]
        v_17_xxlh71xx = bb.emit(relax.op.expand_dims(v_2_2fi3nk6u_var, axis=0))
        assert str(v_17_xxlh71xx.struct_info.shape) == "R.shape([1, 2, 2])", f"Shape mismatch: expected R.shape([1, 2, 2]), got {v_17_xxlh71xx.struct_info.shape}"
        # input: [5, 2, 3, 1]
        # output: [5, 2, 3, 1]
        v_18_wgsm31fc = bb.emit(relax.op.tril(v_15_jtr9wdtj))
        assert str(v_18_wgsm31fc.struct_info.shape) == "R.shape([5, 2, 3, 1])", f"Shape mismatch: expected R.shape([5, 2, 3, 1]), got {v_18_wgsm31fc.struct_info.shape}"
        # input: [3, 4]
        # output: [1, 3, 4]
        v_19_f503v15s = bb.emit(relax.op.expand_dims(v_1_drs2ebrm_var, axis=0))
        assert str(v_19_f503v15s.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_19_f503v15s.struct_info.shape}"
        # input: [5, 2, 3, 1]
        # output: [5, 2, 3, 1]
        v_20_yww42vqh = bb.emit(relax.op.sigmoid(v_15_jtr9wdtj))
        assert str(v_20_yww42vqh.struct_info.shape) == "R.shape([5, 2, 3, 1])", f"Shape mismatch: expected R.shape([5, 2, 3, 1]), got {v_20_yww42vqh.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_21_cy0odkwt = bb.emit(relax.op.astype(v_19_f503v15s, dtype="float32"))
        assert str(v_21_cy0odkwt.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_21_cy0odkwt.struct_info.shape}"
        # input: [2, 2, 8, 8]
        # output: [2, 2, 8, 8]
        v_22_hkj25rru = bb.emit(relax.op.nn.avg_pool2d(v_11_hy90gyap_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_22_hkj25rru.struct_info.shape) == "R.shape([2, 2, 8, 8])", f"Shape mismatch: expected R.shape([2, 2, 8, 8]), got {v_22_hkj25rru.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_23_ckc5x6hm = bb.emit(relax.op.negative(v_19_f503v15s))
        assert str(v_23_ckc5x6hm.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_23_ckc5x6hm.struct_info.shape}"
        # input: 
        # output: [7, 4, 5, 8]
        v_24_jfx8frh9 = bb.emit(relax.op.full(relax.ShapeExpr([7, 4, 5, 8]), relax.const(0, dtype="float32")))
        assert str(v_24_jfx8frh9.struct_info.shape) == "R.shape([7, 4, 5, 8])", f"Shape mismatch: expected R.shape([7, 4, 5, 8]), got {v_24_jfx8frh9.struct_info.shape}"
        bb.emit_func_output((v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_12_6cayy0n2_var, v_16_32f5s7mj, v_17_xxlh71xx, v_18_wgsm31fc, v_20_yww42vqh, v_21_cy0odkwt, v_22_hkj25rru, v_23_ckc5x6hm, v_24_jfx8frh9))

    v_7_9679rs9y_var = relax.Var("v_7_9679rs9y", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_8_ptcsddhk_var = relax.Var("v_8_ptcsddhk", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_10_o39iynm6_var = relax.Var("v_10_o39iynm6", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8]), dtype="float32"))
    v_12_6cayy0n2_var = relax.Var("v_12_6cayy0n2", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_16_32f5s7mj_var = relax.Var("v_16_32f5s7mj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 6]), dtype="float32"))
    v_17_xxlh71xx_var = relax.Var("v_17_xxlh71xx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 2]), dtype="float32"))
    v_18_wgsm31fc_var = relax.Var("v_18_wgsm31fc", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3, 1]), dtype="float32"))
    v_20_yww42vqh_var = relax.Var("v_20_yww42vqh", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3, 1]), dtype="float32"))
    v_21_cy0odkwt_var = relax.Var("v_21_cy0odkwt", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4]), dtype="float32"))
    v_22_hkj25rru_var = relax.Var("v_22_hkj25rru", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_23_ckc5x6hm_var = relax.Var("v_23_ckc5x6hm", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4]), dtype="float32"))
    v_24_jfx8frh9_var = relax.Var("v_24_jfx8frh9", relax.TensorStructInfo(shape=relax.ShapeExpr([7, 4, 5, 8]), dtype="float32"))
    with bb.function("graph_2", [v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_12_6cayy0n2_var, v_16_32f5s7mj_var, v_17_xxlh71xx_var, v_18_wgsm31fc_var, v_20_yww42vqh_var, v_21_cy0odkwt_var, v_22_hkj25rru_var, v_23_ckc5x6hm_var, v_24_jfx8frh9_var]):
        # input: [1, 3, 4]
        # output: [1, 1, 3, 4]
        v_25_eyf2607f = bb.emit(relax.op.expand_dims(v_23_ckc5x6hm_var, axis=0))
        assert str(v_25_eyf2607f.struct_info.shape) == "R.shape([1, 1, 3, 4])", f"Shape mismatch: expected R.shape([1, 1, 3, 4]), got {v_25_eyf2607f.struct_info.shape}"
        # input: [7, 4, 5, 8]
        # output: [7, 4, 10, 16]
        v_26_vr4fpkpp = bb.emit(relax.op.image.resize2d(v_24_jfx8frh9_var, relax.ShapeExpr([10, 16]), layout="NCHW"))
        assert str(v_26_vr4fpkpp.struct_info.shape) == "R.shape([7, 4, 10, 16])", f"Shape mismatch: expected R.shape([7, 4, 10, 16]), got {v_26_vr4fpkpp.struct_info.shape}"
        # input: [1, 1, 3, 4]
        # output: [1, 1, 6, 8]
        v_27_dr1tdcja = bb.emit(relax.op.image.resize2d(v_25_eyf2607f, relax.ShapeExpr([6, 8]), layout="NCHW"))
        assert str(v_27_dr1tdcja.struct_info.shape) == "R.shape([1, 1, 6, 8])", f"Shape mismatch: expected R.shape([1, 1, 6, 8]), got {v_27_dr1tdcja.struct_info.shape}"
        # input: [7, 4, 10, 16]
        # output: [7, 4, 10, 16]
        v_28_rzaqmnv3 = bb.emit(relax.op.nn.selu(v_26_vr4fpkpp))
        assert str(v_28_rzaqmnv3.struct_info.shape) == "R.shape([7, 4, 10, 16])", f"Shape mismatch: expected R.shape([7, 4, 10, 16]), got {v_28_rzaqmnv3.struct_info.shape}"
        # input: 
        # output: [1, 1, 1, 3]
        v_29_xvzh0ivu = bb.emit(relax.op.full(relax.ShapeExpr([1, 1, 1, 3]), relax.const(0, dtype="float32")))
        assert str(v_29_xvzh0ivu.struct_info.shape) == "R.shape([1, 1, 1, 3])", f"Shape mismatch: expected R.shape([1, 1, 1, 3]), got {v_29_xvzh0ivu.struct_info.shape}"
        # input: [1, 1, 6, 8], [1, 1, 1, 3]
        # output: [1, 1, 6, 6]
        v_30_xmg5tl1s = bb.emit(relax.op.nn.conv2d(v_27_dr1tdcja, v_29_xvzh0ivu, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_30_xmg5tl1s.struct_info.shape) == "R.shape([1, 1, 6, 6])", f"Shape mismatch: expected R.shape([1, 1, 6, 6]), got {v_30_xmg5tl1s.struct_info.shape}"
        bb.emit_func_output((v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_12_6cayy0n2_var, v_16_32f5s7mj_var, v_17_xxlh71xx_var, v_18_wgsm31fc_var, v_20_yww42vqh_var, v_21_cy0odkwt_var, v_22_hkj25rru_var, v_28_rzaqmnv3, v_30_xmg5tl1s))

    v_7_9679rs9y_var = relax.Var("v_7_9679rs9y", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_8_ptcsddhk_var = relax.Var("v_8_ptcsddhk", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_10_o39iynm6_var = relax.Var("v_10_o39iynm6", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8]), dtype="float32"))
    v_12_6cayy0n2_var = relax.Var("v_12_6cayy0n2", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_16_32f5s7mj_var = relax.Var("v_16_32f5s7mj", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 6]), dtype="float32"))
    v_17_xxlh71xx_var = relax.Var("v_17_xxlh71xx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 2, 2]), dtype="float32"))
    v_18_wgsm31fc_var = relax.Var("v_18_wgsm31fc", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3, 1]), dtype="float32"))
    v_20_yww42vqh_var = relax.Var("v_20_yww42vqh", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3, 1]), dtype="float32"))
    v_21_cy0odkwt_var = relax.Var("v_21_cy0odkwt", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4]), dtype="float32"))
    v_22_hkj25rru_var = relax.Var("v_22_hkj25rru", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 2, 8, 8]), dtype="float32"))
    v_28_rzaqmnv3_var = relax.Var("v_28_rzaqmnv3", relax.TensorStructInfo(shape=relax.ShapeExpr([7, 4, 10, 16]), dtype="float32"))
    v_30_xmg5tl1s_var = relax.Var("v_30_xmg5tl1s", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 6, 6]), dtype="float32"))
    v_31_qzg064ky_var = relax.Var("v_31_qzg064ky", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 7, 8]), dtype="float32"))
    with bb.function("graph_3", [v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_12_6cayy0n2_var, v_16_32f5s7mj_var, v_17_xxlh71xx_var, v_18_wgsm31fc_var, v_20_yww42vqh_var, v_21_cy0odkwt_var, v_22_hkj25rru_var, v_28_rzaqmnv3_var, v_30_xmg5tl1s_var, v_31_qzg064ky_var]):
        # input: [3, 7, 8]
        # output: [3, 7, 8]
        v_32_63xyjp7b = bb.emit(relax.op.tanh(v_31_qzg064ky_var))
        assert str(v_32_63xyjp7b.struct_info.shape) == "R.shape([3, 7, 8])", f"Shape mismatch: expected R.shape([3, 7, 8]), got {v_32_63xyjp7b.struct_info.shape}"
        # input: [3, 7, 8]
        # output: [3, 7, 8]
        v_33_4ov2bbyy = bb.emit(relax.op.tanh(v_31_qzg064ky_var))
        assert str(v_33_4ov2bbyy.struct_info.shape) == "R.shape([3, 7, 8])", f"Shape mismatch: expected R.shape([3, 7, 8]), got {v_33_4ov2bbyy.struct_info.shape}"
        # input: [3, 7, 8]
        # output: [7, 8]
        v_34_to9g18rq = bb.emit(relax.op.take(v_32_63xyjp7b, relax.const(0, dtype="int64"), axis=0))
        assert str(v_34_to9g18rq.struct_info.shape) == "R.shape([7, 8])", f"Shape mismatch: expected R.shape([7, 8]), got {v_34_to9g18rq.struct_info.shape}"
        # input: [3, 7, 8]
        # output: [3, 7]
        v_35_ux7ox9j0 = bb.emit(relax.op.min(v_33_4ov2bbyy, axis=[-1], keepdims=False))
        assert str(v_35_ux7ox9j0.struct_info.shape) == "R.shape([3, 7])", f"Shape mismatch: expected R.shape([3, 7]), got {v_35_ux7ox9j0.struct_info.shape}"
        # input: [3, 7, 8]
        # output: [1, 3, 7, 8]
        v_36_icol5mof = bb.emit(relax.op.expand_dims(v_33_4ov2bbyy, axis=0))
        assert str(v_36_icol5mof.struct_info.shape) == "R.shape([1, 3, 7, 8])", f"Shape mismatch: expected R.shape([1, 3, 7, 8]), got {v_36_icol5mof.struct_info.shape}"
        # input: [3, 7, 8]
        # output: [1, 3, 7, 8]
        v_37_eg0g581b = bb.emit(relax.op.expand_dims(v_31_qzg064ky_var, axis=0))
        assert str(v_37_eg0g581b.struct_info.shape) == "R.shape([1, 3, 7, 8])", f"Shape mismatch: expected R.shape([1, 3, 7, 8]), got {v_37_eg0g581b.struct_info.shape}"
        # input: [1, 3, 7, 8], [1, 3, 7, 8]
        # output: [1, 1, 1, 1]
        v_36_zcvggp9z = bb.emit(relax.op.nn.conv2d(v_36_icol5mof, v_37_eg0g581b, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_36_zcvggp9z.struct_info.shape) == "R.shape([1, 1, 1, 1])", f"Shape mismatch: expected R.shape([1, 1, 1, 1]), got {v_36_zcvggp9z.struct_info.shape}"
        bb.emit_func_output((v_7_9679rs9y_var, v_8_ptcsddhk_var, v_10_o39iynm6_var, v_12_6cayy0n2_var, v_16_32f5s7mj_var, v_17_xxlh71xx_var, v_18_wgsm31fc_var, v_20_yww42vqh_var, v_21_cy0odkwt_var, v_22_hkj25rru_var, v_28_rzaqmnv3_var, v_30_xmg5tl1s_var, v_34_to9g18rq, v_35_ux7ox9j0, v_36_zcvggp9z))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_sclpgjx3 = np.random.uniform(0.0, 1.0, size=(2, 2, 4, 4)).astype(np.float32)
v_0_sclpgjx3 = tvm.runtime.tensor(np_v_0_sclpgjx3, device=tvm.cuda())
np_v_1_drs2ebrm = np.random.uniform(0.0, 1.0, size=(3, 4)).astype(np.float32)
v_1_drs2ebrm = tvm.runtime.tensor(np_v_1_drs2ebrm, device=tvm.cuda())
np_v_2_2fi3nk6u = np.random.uniform(0.0, 1.0, size=(2, 2)).astype(np.float32)
v_2_2fi3nk6u = tvm.runtime.tensor(np_v_2_2fi3nk6u, device=tvm.cuda())
np_v_3_g7z05ycg = np.random.uniform(0.0, 1.0, size=(3, 6)).astype(np.float32)
v_3_g7z05ycg = tvm.runtime.tensor(np_v_3_g7z05ycg, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_0_sclpgjx3, v_1_drs2ebrm, v_2_2fi3nk6u, v_3_g7z05ycg)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Generate fresh inputs for graph_1
np_v_13_qbxbpfka = np.random.uniform(0.0, 1.0, size=(5, 2, 6, 3)).astype(np.float32)
v_13_qbxbpfka = tvm.runtime.tensor(np_v_13_qbxbpfka, device=tvm.cuda())

# Chained: graph_0 -> graph_1
_prev_out = tvm_result_0 if not hasattr(tvm_result_0, 'numpy') else [tvm_result_0]
v_1_drs2ebrm = _prev_out[0]
v_2_2fi3nk6u = _prev_out[1]
v_7_9679rs9y = _prev_out[2]
v_8_ptcsddhk = _prev_out[3]
v_10_o39iynm6 = _prev_out[4]
v_11_hy90gyap = _prev_out[5]
v_12_6cayy0n2 = _prev_out[6]

tvm_result_1 = vm["graph_1"](v_1_drs2ebrm, v_2_2fi3nk6u, v_7_9679rs9y, v_8_ptcsddhk, v_10_o39iynm6, v_11_hy90gyap, v_12_6cayy0n2, v_13_qbxbpfka)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_1 -> graph_2
_prev_out = tvm_result_1 if not hasattr(tvm_result_1, 'numpy') else [tvm_result_1]
v_7_9679rs9y = _prev_out[0]
v_8_ptcsddhk = _prev_out[1]
v_10_o39iynm6 = _prev_out[2]
v_12_6cayy0n2 = _prev_out[3]
v_16_32f5s7mj = _prev_out[4]
v_17_xxlh71xx = _prev_out[5]
v_18_wgsm31fc = _prev_out[6]
v_20_yww42vqh = _prev_out[7]
v_21_cy0odkwt = _prev_out[8]
v_22_hkj25rru = _prev_out[9]
v_23_ckc5x6hm = _prev_out[10]
v_24_jfx8frh9 = _prev_out[11]

tvm_result_2 = vm["graph_2"](v_7_9679rs9y, v_8_ptcsddhk, v_10_o39iynm6, v_12_6cayy0n2, v_16_32f5s7mj, v_17_xxlh71xx, v_18_wgsm31fc, v_20_yww42vqh, v_21_cy0odkwt, v_22_hkj25rru, v_23_ckc5x6hm, v_24_jfx8frh9)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")

# Generate fresh inputs for graph_3
np_v_31_qzg064ky = np.random.uniform(0.0, 1.0, size=(3, 7, 8)).astype(np.float32)
v_31_qzg064ky = tvm.runtime.tensor(np_v_31_qzg064ky, device=tvm.cuda())

# Chained: graph_2 -> graph_3
_prev_out = tvm_result_2 if not hasattr(tvm_result_2, 'numpy') else [tvm_result_2]
v_7_9679rs9y = _prev_out[0]
v_8_ptcsddhk = _prev_out[1]
v_10_o39iynm6 = _prev_out[2]
v_12_6cayy0n2 = _prev_out[3]
v_16_32f5s7mj = _prev_out[4]
v_17_xxlh71xx = _prev_out[5]
v_18_wgsm31fc = _prev_out[6]
v_20_yww42vqh = _prev_out[7]
v_21_cy0odkwt = _prev_out[8]
v_22_hkj25rru = _prev_out[9]
v_28_rzaqmnv3 = _prev_out[10]
v_30_xmg5tl1s = _prev_out[11]

tvm_result_3 = vm["graph_3"](v_7_9679rs9y, v_8_ptcsddhk, v_10_o39iynm6, v_12_6cayy0n2, v_16_32f5s7mj, v_17_xxlh71xx, v_18_wgsm31fc, v_20_yww42vqh, v_21_cy0odkwt, v_22_hkj25rru, v_28_rzaqmnv3, v_30_xmg5tl1s, v_31_qzg064ky)
# Print output
if hasattr(tvm_result_3, 'numpy'):
    _arr = tvm_result_3.numpy()
    print(f"[TVM-OUT] graph_3: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_3)):
        _arr = tvm_result_3[_tvmi].numpy()
        print(f"[TVM-OUT] graph_3[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
