# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_ac1ivci1, v_1_pck4yahe, v_2_wlodetal):
        v_3_const = torch.zeros((26, 27), dtype=torch.float32, device="cpu")
        v_3_34cncko0 = torch.add(v_2_wlodetal, v_3_const)
        v_4_kw4btxy4 = torch.unsqueeze(v_2_wlodetal, 0)
        v_5_4ldhhetd = torch.add(v_2_wlodetal, v_4_kw4btxy4)
        v_6_ke8nc9x4 = torch.zeros((36, 54, 20), dtype=torch.float32, device="cpu")
        v_7_2ij1k6y1 = torch.log2(v_5_4ldhhetd)
        v_8_3xcqsxxa = torch.floor(v_5_4ldhhetd)
        v_9_rpexwsu1 = torch.gather(v_5_4ldhhetd, 0, torch.zeros((min(1, 1), min(26, 1), min(27, 1)), dtype=torch.int64, device=v_5_4ldhhetd.device))
        v_10_dqd1id02 = torch.triu(v_5_4ldhhetd)
        v_11_ettq0aun = F.mish(v_5_4ldhhetd)
        v_12_gwi1x2di = torch.sum(v_10_dqd1id02, dim=-1, keepdim=False)
        v_13_n4v5iml3 = v_11_ettq0aun[:max(1, v_11_ettq0aun.shape[0]//2)]
        v_14_9fxj81rx = torch.gather(v_11_ettq0aun, 0, torch.zeros((min(1, 1), min(26, 1), min(27, 1)), dtype=torch.int64, device=v_11_ettq0aun.device))
        v_15_5k6287pb = torch.sub(v_11_ettq0aun, v_5_4ldhhetd)
        v_16_bxr9cz9m = torch.ceil(v_11_ettq0aun)
        v_17_7wfrtyt0 = F.mish(v_11_ettq0aun)
        v_18_arpjuljz = F.selu(v_16_bxr9cz9m)
        v_19_oftvpks9 = torch.gather(v_17_7wfrtyt0, 0, torch.zeros((min(1, 1), min(26, 1), min(27, 1)), dtype=torch.int64, device=v_17_7wfrtyt0.device))
        v_20_b9du8y9w = torch.arange(0, 203, dtype=torch.float32, device="cpu")
        v_21_dlttxxy1 = torch.transpose(v_17_7wfrtyt0, 1, 2)
        v_22_lorsuz4h = torch.max(v_17_7wfrtyt0, dim=-1, keepdim=False).values
        v_23_qwzgzhu1 = torch.div(v_17_7wfrtyt0, v_13_n4v5iml3)
        v_24_wzc9nxhd = torch.reciprocal(v_17_7wfrtyt0)
        v_25_eifexw4x = torch.sign(v_23_qwzgzhu1)
        v_26_jgc4rphe = torch.tril(v_24_wzc9nxhd)
        v_27_fg4c068h = torch.ceil(v_25_eifexw4x)
        v_28_zu2zwzhp = torch.mul(v_26_jgc4rphe, v_7_2ij1k6y1)
        v_29_ldo9syww = torch.unsqueeze(v_26_jgc4rphe, 0)
        v_30_bkkpue04 = torch.clamp(v_28_zu2zwzhp, min=-0.65, max=0.66)
        v_31_j7e01to1 = torch.neg(v_28_zu2zwzhp)
        v_32_qxoeeonz = torch.transpose(v_30_bkkpue04, 1, 2)
        v_33_iq5sbgee = F.mish(v_30_bkkpue04)
        v_34_o8h01qqj = torch.log2(v_30_bkkpue04)
        v_35_const = torch.zeros((1, 26, 27), dtype=torch.float32, device="cpu")
        v_35_kgcdojhv = torch.add(v_30_bkkpue04, v_35_const)
        v_36_0na0gvuj = torch.mul(v_30_bkkpue04, v_31_j7e01to1)
        v_37_const = torch.zeros((1, 26, 27), dtype=torch.float32, device="cpu")
        v_37_se91bc0e = torch.div(v_35_kgcdojhv, v_37_const)
        v_38_sni9bx04 = torch.rsqrt(v_35_kgcdojhv)
        v_39_1kcoztao = torch.tanh(v_35_kgcdojhv)
        v_40_nwej6kf0 = torch.sqrt(v_35_kgcdojhv)
        v_41_0sjoalzu = F.gelu(v_35_kgcdojhv)
        v_42_xv97f2y1 = torch.sqrt(v_40_nwej6kf0)
        v_43_zroseqvw = torch.rsqrt(v_40_nwej6kf0)
        v_44_emyfdcl3 = torch.full((13, 24, 14, 15), 0.0, dtype=torch.float32, device="cpu")
        v_45_ry2k2ml4 = torch.round(v_43_zroseqvw)
        v_46_17u0u97p = torch.gather(v_43_zroseqvw, 0, torch.zeros((min(1, 1), min(26, 1), min(27, 1)), dtype=torch.int64, device=v_43_zroseqvw.device))
        v_47_4xumat03 = torch.log2(v_43_zroseqvw)
        v_48_kuotfqfw = torch.maximum(v_43_zroseqvw, v_46_17u0u97p)
        v_49_m5x905j3 = torch.sum(v_43_zroseqvw, dim=-1, keepdim=False)
        v_50_cnwv0bfv = F.elu(v_43_zroseqvw, alpha=1.73)
        v_51_m60vs45x = F.mish(v_49_m5x905j3)
        v_52_ieyerm5s = torch.arange(0, 55, dtype=torch.float32, device="cpu")
        v_53_hkifhqpj = F.elu(v_50_cnwv0bfv, alpha=1.43)
        return (v_0_ac1ivci1, v_1_pck4yahe, v_3_34cncko0, v_6_ke8nc9x4, v_8_3xcqsxxa, v_9_rpexwsu1, v_12_gwi1x2di, v_14_9fxj81rx, v_15_5k6287pb, v_18_arpjuljz, v_19_oftvpks9, v_20_b9du8y9w, v_21_dlttxxy1, v_22_lorsuz4h, v_27_fg4c068h, v_29_ldo9syww, v_32_qxoeeonz, v_33_iq5sbgee, v_34_o8h01qqj, v_36_0na0gvuj, v_37_se91bc0e, v_38_sni9bx04, v_39_1kcoztao, v_41_0sjoalzu, v_42_xv97f2y1, v_44_emyfdcl3, v_45_ry2k2ml4, v_47_4xumat03, v_48_kuotfqfw, v_51_m60vs45x, v_52_ieyerm5s, v_53_hkifhqpj)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_ac1ivci1 = torch.randn(3, 49, 5, 51, dtype=torch.float32, device="cpu")
v_1_pck4yahe = torch.randn(19, 24, 6, 29, dtype=torch.float32, device="cpu")
v_2_wlodetal = torch.randn(26, 27, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_ac1ivci1, v_1_pck4yahe, v_2_wlodetal)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_ac1ivci1, v_1_pck4yahe, v_2_wlodetal)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
