# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_60wy5drp, v_1_cavnzz1k, v_2_prg9dizg, v_3_co0xcb83, v_4_85v6lz4h):
        v_5_kvscu5f5 = torch.triu(v_4_85v6lz4h)
        v_6_ug2wh3qo = torch.ones((11, 15, 21, 16), dtype=torch.float32, device="cpu")
        v_7_2x4849ig = torch.minimum(v_4_85v6lz4h, v_5_kvscu5f5)
        v_8_l6p9aphf = torch.arange(0, 92, dtype=torch.float32, device="cpu")
        v_9_46icwaki = torch.gather(v_6_ug2wh3qo, 0, torch.zeros((min(11, 1), min(15, 1), min(21, 1), min(16, 1)), dtype=torch.int64, device=v_6_ug2wh3qo.device))
        v_10_const = torch.zeros((11, 15, 21, 16), dtype=torch.float32, device="cpu")
        v_10_xx13irwm = torch.mul(v_6_ug2wh3qo, v_10_const)
        v_11_o1w6zh5f = torch.zeros((28, 50, 43), dtype=torch.float32, device="cpu")
        v_12_const = torch.zeros((11, 15, 21, 16), dtype=torch.float32, device="cpu")
        v_12_ldokrvsf = torch.maximum(v_10_xx13irwm, v_12_const)
        v_13_ctivoguv = torch.log(v_10_xx13irwm)
        v_14_twrluaqw = torch.min(v_10_xx13irwm, dim=-1, keepdim=False).values
        v_15_99hrgmkt = torch.ones((63, 6, 47), dtype=torch.float32, device="cpu")
        v_16_4dgr5vut = torch.mean(v_10_xx13irwm.float(), dim=-1, keepdim=False)
        v_17_zxu7uqms = torch.tril(v_10_xx13irwm)
        v_18_66yy7iw7 = torch.tanh(v_10_xx13irwm)
        v_19_z6mh1iip = torch.div(v_17_zxu7uqms, v_12_ldokrvsf)
        v_20_7uc24qy8 = v_18_66yy7iw7[:max(1, v_18_66yy7iw7.shape[0]//2)]
        v_21_yk8vsyxc = torch.gather(v_19_z6mh1iip, 0, torch.zeros((min(11, 1), min(15, 1), min(21, 1), min(16, 1)), dtype=torch.int64, device=v_19_z6mh1iip.device))
        v_22_z62f5v3y = torch.sigmoid(v_19_z6mh1iip)
        v_23_s3tmvvwb = v_21_yk8vsyxc[:max(1, v_21_yk8vsyxc.shape[0]//2)]
        v_24_jnikllk1 = torch.ceil(v_21_yk8vsyxc)
        v_25_ilp70yyz = torch.maximum(v_21_yk8vsyxc, v_2_prg9dizg)
        v_26_a4em2ucp = torch.gather(v_21_yk8vsyxc, 0, torch.zeros((min(1, 1), min(1, 1), min(1, 1), min(1, 1)), dtype=torch.int64, device=v_21_yk8vsyxc.device))
        v_27_b4irpbjb = torch.add(v_21_yk8vsyxc, v_1_cavnzz1k)
        v_28_jesdmoq6 = torch.neg(v_21_yk8vsyxc)
        v_29_prbxktbd = torch.arange(0, 181, dtype=torch.float32, device="cpu")
        v_30_d126rq98 = F.silu(v_27_b4irpbjb)
        v_31_i6xtonvx = torch.exp(v_29_prbxktbd)
        v_32_kko2dueq = torch.div(v_29_prbxktbd, v_26_a4em2ucp)
        v_33_wrapper = torch.unsqueeze(v_31_i6xtonvx, 0)
        v_33_j0yakr8j = torch.tril(v_33_wrapper)
        v_34_p8ls7zif = v_31_i6xtonvx.to(torch.float32)
        v_35_3f605da4 = torch.sqrt(v_31_i6xtonvx)
        v_36_kxqq7bgp = F.gelu(v_34_p8ls7zif)
        v_37_dqwbeupj = torch.unsqueeze(v_34_p8ls7zif, 0)
        v_38_4xar4tyy = torch.sum(v_34_p8ls7zif, dim=-1, keepdim=False)
        v_39_ovugzi56 = torch.maximum(v_34_p8ls7zif, v_32_kko2dueq)
        v_40_rpzdr66s = torch.min(v_34_p8ls7zif, dim=-1, keepdim=False).values
        v_41_const = torch.zeros((1, 1, 1, 181), dtype=torch.float32, device="cpu")
        v_41_lxybjqde = torch.maximum(v_39_ovugzi56, v_41_const)
        v_42_vrzef66u = torch.neg(v_40_rpzdr66s)
        v_43_13phadvz = torch.zeros((27, 53, 51), dtype=torch.float32, device="cpu")
        v_44_rm35osyn = F.silu(v_40_rpzdr66s)
        v_45_ohduaam8 = torch.unsqueeze(v_40_rpzdr66s, 0)
        v_46_wrapper = torch.unsqueeze(v_40_rpzdr66s, 0)
        v_47_wrapper = torch.unsqueeze(v_46_wrapper, 0)
        v_46_x7l91w34 = torch.triu(v_47_wrapper)
        v_47_2h9t63ga = torch.unsqueeze(v_45_ohduaam8, 0)
        v_48_wrapper = torch.unsqueeze(v_45_ohduaam8, 0)
        v_48_3k94zuma = v_48_wrapper[:max(1, v_48_wrapper.shape[0]//2)]
        v_49_6mp9dp8d = torch.log(v_45_ohduaam8)
        v_50_i3aka8x0 = torch.unsqueeze(v_45_ohduaam8, 0)
        v_51_3x5f8mwb = torch.sum(v_45_ohduaam8, dim=-1, keepdim=False)
        v_52_oqkvrvkv = torch.tanh(v_45_ohduaam8)
        v_53_4g6p8nx8 = torch.sub(v_45_ohduaam8, v_4_85v6lz4h)
        v_54_jz8swkwf = torch.pow(v_45_ohduaam8, v_32_kko2dueq)
        v_55_y2dnw93i = torch.max(v_45_ohduaam8, dim=-1, keepdim=False).values
        v_56_ido8whxl = torch.div(v_45_ohduaam8, v_24_jnikllk1)
        v_57_2g99bpfv = torch.tile(v_45_ohduaam8, [1] * 1)
        v_58_njh3x9gw = torch.exp(v_45_ohduaam8)
        v_59_8jifo2d7 = torch.exp(v_45_ohduaam8)
        v_60_tnw9ywa4 = torch.sub(v_45_ohduaam8, v_19_z6mh1iip)
        v_61_6xnglexy = torch.abs(v_59_8jifo2d7)
        v_62_1dxuw4zg = torch.tile(v_59_8jifo2d7, [1] * 1)
        v_63_wrapper = torch.unsqueeze(v_59_8jifo2d7, 0)
        v_63_r3u45808 = torch.triu(v_63_wrapper)
        v_64_6z3f7o1y = torch.sqrt(v_62_1dxuw4zg)
        v_65_lbqhsw11 = torch.ones((27, 6, 33, 3), dtype=torch.float32, device="cpu")
        v_66_v63fkctn = torch.add(v_63_r3u45808, v_57_2g99bpfv)
        v_67_46mw4kz3 = F.gelu(v_63_r3u45808)
        v_68_g2qbb6bz = torch.sqrt(v_63_r3u45808)
        v_69_v9kio9d6 = torch.neg(v_67_46mw4kz3)
        v_70_jwpd85nj = F.softmax(v_67_46mw4kz3, dim=-1)
        v_71_qtni21i1 = torch.mul(v_67_46mw4kz3, v_33_j0yakr8j)
        v_72_3ffr4381 = torch.gather(v_67_46mw4kz3, 0, torch.zeros((min(1, 1), min(1, 1)), dtype=torch.int64, device=v_67_46mw4kz3.device))
        return (v_0_60wy5drp, v_3_co0xcb83, v_7_2x4849ig, v_8_l6p9aphf, v_9_46icwaki, v_11_o1w6zh5f, v_13_ctivoguv, v_14_twrluaqw, v_15_99hrgmkt, v_16_4dgr5vut, v_20_7uc24qy8, v_22_z62f5v3y, v_23_s3tmvvwb, v_25_ilp70yyz, v_28_jesdmoq6, v_30_d126rq98, v_35_3f605da4, v_36_kxqq7bgp, v_37_dqwbeupj, v_38_4xar4tyy, v_41_lxybjqde, v_42_vrzef66u, v_43_13phadvz, v_44_rm35osyn, v_46_x7l91w34, v_47_2h9t63ga, v_48_3k94zuma, v_49_6mp9dp8d, v_50_i3aka8x0, v_51_3x5f8mwb, v_52_oqkvrvkv, v_53_4g6p8nx8, v_54_jz8swkwf, v_55_y2dnw93i, v_56_ido8whxl, v_58_njh3x9gw, v_60_tnw9ywa4, v_61_6xnglexy, v_64_6z3f7o1y, v_65_lbqhsw11, v_66_v63fkctn, v_68_g2qbb6bz, v_69_v9kio9d6, v_70_jwpd85nj, v_71_qtni21i1, v_72_3ffr4381)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_60wy5drp = torch.randn(17, 31, 20, 6, dtype=torch.float32, device="cpu")
v_1_cavnzz1k = torch.randn(15, 14, 23, 14, dtype=torch.float32, device="cpu")
v_2_prg9dizg = torch.randn(9, 21, 51, dtype=torch.float32, device="cpu")
v_3_co0xcb83 = torch.randn(43, 5, dtype=torch.float32, device="cpu")
v_4_85v6lz4h = torch.randn(7, 63, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_60wy5drp, v_1_cavnzz1k, v_2_prg9dizg, v_3_co0xcb83, v_4_85v6lz4h)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_60wy5drp, v_1_cavnzz1k, v_2_prg9dizg, v_3_co0xcb83, v_4_85v6lz4h)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
