# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_nq4jfi3z, v_1_6nda0puh, v_2_c0wy9aa3, v_3_fu8q5gvt, v_4_3wxff33s, v_5_8xhqox5d, v_6_0v3ngknm, v_7_t1z4r3kf, v_8_ac13makz, v_9_zy4wccbx, v_10_ilifxvld, v_11_hzrs6xwi, v_12_f77ahrd6, v_13_nwqa8f41):
        v_14_const = torch.zeros((48, 45, 34), dtype=torch.float32, device="cpu")
        v_14_1c62v9iv = torch.pow(v_13_nwqa8f41, v_14_const)
        v_15_fj8sxf47 = torch.min(v_13_nwqa8f41, dim=-1, keepdim=False).values
        v_16_2u9rar8t = F.leaky_relu(v_13_nwqa8f41, negative_slope=0.23)
        v_17_uleoi4ir = torch.minimum(v_13_nwqa8f41, v_14_1c62v9iv)
        v_18_const = torch.zeros((48, 45, 34), dtype=torch.float32, device="cpu")
        v_18_mmg2bd80 = torch.minimum(v_13_nwqa8f41, v_18_const)
        v_19_xuatseoy = torch.unsqueeze(v_13_nwqa8f41, 0)
        v_20_const = torch.zeros((48, 45, 34), dtype=torch.float32, device="cpu")
        v_20_cbdexw6p = torch.maximum(v_13_nwqa8f41, v_20_const)
        v_21_k2sj5occ = torch.sum(v_13_nwqa8f41, dim=-1, keepdim=False)
        v_22_bhe4n2qk = torch.gather(v_13_nwqa8f41, 0, torch.zeros((min(48, 1), min(45, 1), min(34, 1)), dtype=torch.int64, device=v_13_nwqa8f41.device))
        v_23_2v8vnl70 = torch.transpose(v_13_nwqa8f41, 1, 2)
        v_24_s70cokas = torch.sub(v_13_nwqa8f41, v_19_xuatseoy)
        v_25_y50x3ahl = torch.zeros((18, 33, 13), dtype=torch.float32, device="cpu")
        v_26_67owr8er = torch.ceil(v_23_2v8vnl70)
        v_27_3dppc1zr = torch.rsqrt(v_25_y50x3ahl)
        v_28_c1k9fleo = torch.mean(v_26_67owr8er.float(), dim=-1, keepdim=False)
        v_29_ppzspot5 = torch.tile(v_26_67owr8er, [1] * 3)
        v_30_9v8n81cq = F.mish(v_26_67owr8er)
        v_31_8gxncbls = F.leaky_relu(v_26_67owr8er, negative_slope=0.21)
        v_32_g1n1r9zo = F.leaky_relu(v_30_9v8n81cq, negative_slope=0.21)
        v_33_40w796rb = torch.sum(v_31_8gxncbls, dim=-1, keepdim=False)
        v_34_zhzr9d8i = torch.transpose(v_31_8gxncbls, 1, 2)
        v_35_const = torch.zeros((48, 34, 45), dtype=torch.float32, device="cpu")
        v_35_apyzfivk = torch.add(v_31_8gxncbls, v_35_const)
        v_36_00q1oezx = torch.abs(v_34_zhzr9d8i)
        v_37_evv84s2l = torch.tanh(v_35_apyzfivk)
        v_38_ahzjc7uw = torch.triu(v_36_00q1oezx)
        v_39_tt29br06 = F.mish(v_37_evv84s2l)
        v_40_jv6xh9kx = torch.sqrt(v_37_evv84s2l)
        v_41_58jx8hex = F.softmax(v_37_evv84s2l, dim=-1)
        v_42_9mvr5s3p = torch.abs(v_37_evv84s2l)
        v_43_79rp4knl = torch.tile(v_37_evv84s2l, [1] * 3)
        v_44_ti9w0esq = torch.reciprocal(v_37_evv84s2l)
        v_45_const = torch.zeros((48, 34, 45), dtype=torch.float32, device="cpu")
        v_45_e7f0c51a = torch.add(v_43_79rp4knl, v_45_const)
        v_46_aikdrm1y = F.selu(v_43_79rp4knl)
        v_47_6kbk5be8 = F.mish(v_45_e7f0c51a)
        v_48_37l216eg = torch.round(v_45_e7f0c51a)
        v_49_60iw46dj = torch.unsqueeze(v_45_e7f0c51a, 0)
        v_50_r33zqsp3 = torch.sub(v_45_e7f0c51a, v_49_60iw46dj)
        v_51_grzncund = F.relu(v_45_e7f0c51a)
        v_52_pu3t1osg = torch.sum(v_45_e7f0c51a, dim=-1, keepdim=False)
        v_53_1g48cbfu = F.elu(v_45_e7f0c51a, alpha=1.79)
        v_54_1h5nh5w3 = torch.tanh(v_45_e7f0c51a)
        v_55_hj1ei3vt = torch.reciprocal(v_45_e7f0c51a)
        v_56_mldxk65i = torch.abs(v_45_e7f0c51a)
        v_57_fsszn4nl = torch.full((34, 29), 0.0, dtype=torch.float32, device="cpu")
        v_58_77yav8q3 = torch.sign(v_56_mldxk65i)
        v_59_fr0ee2ho = torch.tile(v_56_mldxk65i, [1] * 3)
        v_60_lq0qwthh = torch.exp(v_56_mldxk65i)
        v_61_vns2fihr = torch.reciprocal(v_59_fr0ee2ho)
        v_62_v32t1zbl = torch.max(v_60_lq0qwthh, dim=-1, keepdim=False).values
        v_63_6dbcyugg = F.mish(v_61_vns2fihr)
        v_64_x1kekwaa = torch.arange(0, 36, dtype=torch.float32, device="cpu")
        v_65_sfbhqfue = torch.div(v_61_vns2fihr, v_47_6kbk5be8)
        v_66_ee4sc3xx = F.selu(v_64_x1kekwaa)
        v_67_18t133dj = torch.tanh(v_64_x1kekwaa)
        v_68_const = torch.zeros((36), dtype=torch.float32, device="cpu")
        v_68_mo40hkmk = torch.add(v_64_x1kekwaa, v_68_const)
        return (v_0_nq4jfi3z, v_1_6nda0puh, v_2_c0wy9aa3, v_3_fu8q5gvt, v_4_3wxff33s, v_5_8xhqox5d, v_6_0v3ngknm, v_7_t1z4r3kf, v_8_ac13makz, v_9_zy4wccbx, v_10_ilifxvld, v_11_hzrs6xwi, v_12_f77ahrd6, v_15_fj8sxf47, v_16_2u9rar8t, v_17_uleoi4ir, v_18_mmg2bd80, v_20_cbdexw6p, v_21_k2sj5occ, v_22_bhe4n2qk, v_24_s70cokas, v_27_3dppc1zr, v_28_c1k9fleo, v_29_ppzspot5, v_32_g1n1r9zo, v_33_40w796rb, v_38_ahzjc7uw, v_39_tt29br06, v_40_jv6xh9kx, v_41_58jx8hex, v_42_9mvr5s3p, v_44_ti9w0esq, v_46_aikdrm1y, v_48_37l216eg, v_50_r33zqsp3, v_51_grzncund, v_52_pu3t1osg, v_53_1g48cbfu, v_54_1h5nh5w3, v_55_hj1ei3vt, v_57_fsszn4nl, v_58_77yav8q3, v_62_v32t1zbl, v_63_6dbcyugg, v_65_sfbhqfue, v_66_ee4sc3xx, v_67_18t133dj, v_68_mo40hkmk)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_nq4jfi3z = torch.randn(32, 26, 23, dtype=torch.float32, device="cpu")
v_1_6nda0puh = torch.randn(20, 19, 16, 12, dtype=torch.float32, device="cpu")
v_2_c0wy9aa3 = torch.randn(64, 45, 14, dtype=torch.float32, device="cpu")
v_3_fu8q5gvt = torch.randn(31, 52, 29, 2, dtype=torch.float32, device="cpu")
v_4_3wxff33s = torch.randn(22, 21, 6, 27, dtype=torch.float32, device="cpu")
v_5_8xhqox5d = torch.randn(14, 2, dtype=torch.float32, device="cpu")
v_6_0v3ngknm = torch.randn(28, 45, 12, dtype=torch.float32, device="cpu")
v_7_t1z4r3kf = torch.randn(19, 36, 45, dtype=torch.float32, device="cpu")
v_8_ac13makz = torch.randn(52, 21, dtype=torch.float32, device="cpu")
v_9_zy4wccbx = torch.randn(12, 13, 22, 22, dtype=torch.float32, device="cpu")
v_10_ilifxvld = torch.randn(11, 15, 20, 18, dtype=torch.float32, device="cpu")
v_11_hzrs6xwi = torch.randn(63, 47, dtype=torch.float32, device="cpu")
v_12_f77ahrd6 = torch.randn(8, 57, dtype=torch.float32, device="cpu")
v_13_nwqa8f41 = torch.randn(48, 45, 34, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_nq4jfi3z, v_1_6nda0puh, v_2_c0wy9aa3, v_3_fu8q5gvt, v_4_3wxff33s, v_5_8xhqox5d, v_6_0v3ngknm, v_7_t1z4r3kf, v_8_ac13makz, v_9_zy4wccbx, v_10_ilifxvld, v_11_hzrs6xwi, v_12_f77ahrd6, v_13_nwqa8f41)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_nq4jfi3z, v_1_6nda0puh, v_2_c0wy9aa3, v_3_fu8q5gvt, v_4_3wxff33s, v_5_8xhqox5d, v_6_0v3ngknm, v_7_t1z4r3kf, v_8_ac13makz, v_9_zy4wccbx, v_10_ilifxvld, v_11_hzrs6xwi, v_12_f77ahrd6, v_13_nwqa8f41)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
