# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_trbnv6b5, v_1_0dz2ekr4, v_2_me1m5uoh):
        v_3_const = torch.zeros((22, 3, 56), dtype=torch.float32, device="cpu")
        v_3_c3nuv6xs = torch.mul(v_2_me1m5uoh, v_3_const)
        v_4_07bv30sk = torch.unsqueeze(v_2_me1m5uoh, 0)
        v_5_xvf0gojp = torch.ceil(v_2_me1m5uoh)
        v_6_const = torch.zeros((1, 22, 3, 56), dtype=torch.float32, device="cpu")
        v_6_fsy2f6tu = torch.pow(v_4_07bv30sk, v_6_const)
        v_7_hqp2wsmh = F.relu(v_5_xvf0gojp)
        v_8_dp70t49y = torch.tile(v_5_xvf0gojp, [1] * 3)
        v_9_wik6rl85 = torch.add(v_7_hqp2wsmh, v_8_dp70t49y)
        v_10_8zco4cmm = F.hardtanh(v_7_hqp2wsmh, min_val=-1.95, max_val=0.78)
        v_11_2ku8p9rd = torch.abs(v_7_hqp2wsmh)
        v_12_n61de8mm = torch.gather(v_7_hqp2wsmh, 0, torch.zeros((min(22, 1), min(3, 1), min(56, 1)), dtype=torch.int64, device=v_7_hqp2wsmh.device))
        v_13_hwk9o8yk = torch.tril(v_11_2ku8p9rd)
        v_14_my8c27su = torch.mean(v_11_2ku8p9rd.float(), dim=-1, keepdim=False)
        v_15_vse8b8wf = torch.abs(v_11_2ku8p9rd)
        v_16_nxrhl0vl = torch.sub(v_11_2ku8p9rd, v_10_8zco4cmm)
        v_17_u1idwv7a = F.silu(v_15_vse8b8wf)
        v_18_2q68loi5 = torch.pow(v_15_vse8b8wf, v_3_c3nuv6xs)
        v_19_2fj5a4mp = torch.tril(v_15_vse8b8wf)
        v_20_8nsrbhs5 = torch.minimum(v_15_vse8b8wf, v_3_c3nuv6xs)
        v_21_n9jlzo39 = F.softmax(v_15_vse8b8wf, dim=-1)
        v_22_82k6il80 = torch.rsqrt(v_15_vse8b8wf)
        v_23_zfjfjybf = torch.neg(v_15_vse8b8wf)
        v_24_osrzz7w1 = torch.max(v_22_82k6il80, dim=-1, keepdim=False).values
        v_25_ayukqjc1 = torch.clamp(v_22_82k6il80, min=-0.88, max=2.45)
        v_26_drfcs3c6 = torch.neg(v_24_osrzz7w1)
        v_27_ciq59otr = torch.arange(0, 157, dtype=torch.float32, device="cpu")
        v_28_ywhdzb6n = torch.sum(v_26_drfcs3c6, dim=-1, keepdim=False)
        v_29_jldazt0i = F.leaky_relu(v_27_ciq59otr, negative_slope=0.31)
        v_30_4xvwfe59 = F.softmax(v_27_ciq59otr, dim=-1)
        v_31_nuueh4m0 = v_29_jldazt0i.to(torch.float32)
        v_32_const = torch.zeros((157), dtype=torch.float32, device="cpu")
        v_32_x5wmtibp = torch.pow(v_29_jldazt0i, v_32_const)
        v_33_wrapper = torch.unsqueeze(v_29_jldazt0i, 0)
        v_33_4dabmrov = torch.transpose(v_33_wrapper, 0, 1)
        v_34_const = torch.zeros((157), dtype=torch.float32, device="cpu")
        v_34_e2a0rwgb = torch.pow(v_29_jldazt0i, v_34_const)
        v_35_f4z12t1k = F.silu(v_29_jldazt0i)
        v_36_w7tylcdl = torch.ceil(v_34_e2a0rwgb)
        v_37_0x3y06sc = torch.sigmoid(v_34_e2a0rwgb)
        v_38_6vizpg5o = torch.tile(v_34_e2a0rwgb, [1] * 1)
        v_39_9nf37iud = torch.maximum(v_34_e2a0rwgb, v_35_f4z12t1k)
        v_40_8m3zu8i6 = torch.neg(v_34_e2a0rwgb)
        v_41_lanl19jn = F.gelu(v_39_9nf37iud)
        v_42_dgafzq4p = torch.neg(v_39_9nf37iud)
        v_43_1z3sjgs6 = F.log_softmax(v_41_lanl19jn, dim=-1)
        v_44_zk2grm12 = torch.sign(v_41_lanl19jn)
        v_45_tdaq525l = v_41_lanl19jn.to(torch.float32)
        v_46_vwbvtj6x = torch.gather(v_41_lanl19jn, 0, torch.zeros((min(157, 1)), dtype=torch.int64, device=v_41_lanl19jn.device))
        v_47_7ua2k5d5 = torch.rsqrt(v_41_lanl19jn)
        v_48_0575c1dy = torch.neg(v_46_vwbvtj6x)
        v_49_wrapper = torch.unsqueeze(v_46_vwbvtj6x, 0)
        v_49_6v2ue8ag = torch.transpose(v_49_wrapper, 0, 1)
        v_50_v33xhpk7 = torch.sub(v_48_0575c1dy, v_35_f4z12t1k)
        v_51_ubpbbkhh = torch.unsqueeze(v_48_0575c1dy, 0)
        v_52_ch40uir5 = F.silu(v_50_v33xhpk7)
        v_53_ms2gz9ol = torch.mean(v_50_v33xhpk7.float(), dim=-1, keepdim=False)
        v_54_rkko8n7l = torch.arange(0, 117, dtype=torch.float32, device="cpu")
        v_55_wrapper = torch.unsqueeze(v_52_ch40uir5, 0)
        v_55_rwalyh0f = torch.triu(v_55_wrapper)
        v_56_reukyyyt = F.gelu(v_52_ch40uir5)
        v_57_psx73qxx = torch.tile(v_52_ch40uir5, [1] * 1)
        v_58_2w5nchb4 = F.softmax(v_52_ch40uir5, dim=-1)
        v_59_wrapper = torch.unsqueeze(v_52_ch40uir5, 0)
        v_59_ezlpupjl = torch.transpose(v_59_wrapper, 0, 1)
        v_60_bbqxy3kd = torch.sign(v_52_ch40uir5)
        v_61_flobj5tr = F.elu(v_52_ch40uir5, alpha=0.52)
        v_62_nhfgxqfh = torch.clamp(v_52_ch40uir5, min=-0.65, max=0.6)
        v_63_const = torch.zeros((157), dtype=torch.float32, device="cpu")
        v_63_j54su08p = torch.div(v_61_flobj5tr, v_63_const)
        v_64_wrapper = torch.unsqueeze(v_62_nhfgxqfh, 0)
        v_64_u1g5bqsn = torch.tril(v_64_wrapper)
        v_65_1onfv3g3 = torch.clamp(v_62_nhfgxqfh, min=-0.9, max=1.7)
        v_66_be4v2yt0 = F.softmax(v_64_u1g5bqsn, dim=-1)
        v_67_oc6ds0t2 = torch.ones((48, 54), dtype=torch.float32, device="cpu")
        v_68_ehfvol1z = torch.sum(v_64_u1g5bqsn, dim=-1, keepdim=False)
        v_69_04lrah5g = torch.sub(v_64_u1g5bqsn, v_41_lanl19jn)
        v_70_olq323pt = torch.ceil(v_64_u1g5bqsn)
        v_71_9byhn12g = F.gelu(v_69_04lrah5g)
        v_72_c37dtsl9 = torch.zeros((21, 17, 13, 11), dtype=torch.float32, device="cpu")
        v_73_5qkvsn04 = torch.floor(v_69_04lrah5g)
        return (v_0_trbnv6b5, v_1_0dz2ekr4, v_6_fsy2f6tu, v_9_wik6rl85, v_12_n61de8mm, v_13_hwk9o8yk, v_14_my8c27su, v_16_nxrhl0vl, v_17_u1idwv7a, v_18_2q68loi5, v_19_2fj5a4mp, v_20_8nsrbhs5, v_21_n9jlzo39, v_23_zfjfjybf, v_25_ayukqjc1, v_28_ywhdzb6n, v_30_4xvwfe59, v_31_nuueh4m0, v_32_x5wmtibp, v_33_4dabmrov, v_36_w7tylcdl, v_37_0x3y06sc, v_38_6vizpg5o, v_40_8m3zu8i6, v_42_dgafzq4p, v_43_1z3sjgs6, v_44_zk2grm12, v_45_tdaq525l, v_47_7ua2k5d5, v_49_6v2ue8ag, v_51_ubpbbkhh, v_53_ms2gz9ol, v_54_rkko8n7l, v_55_rwalyh0f, v_56_reukyyyt, v_57_psx73qxx, v_58_2w5nchb4, v_59_ezlpupjl, v_60_bbqxy3kd, v_63_j54su08p, v_65_1onfv3g3, v_66_be4v2yt0, v_67_oc6ds0t2, v_68_ehfvol1z, v_70_olq323pt, v_71_9byhn12g, v_72_c37dtsl9, v_73_5qkvsn04)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_trbnv6b5 = torch.randn(20, 49, 3, dtype=torch.float32, device="cpu")
v_1_0dz2ekr4 = torch.randn(53, 27, 53, dtype=torch.float32, device="cpu")
v_2_me1m5uoh = torch.randn(22, 3, 56, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_trbnv6b5, v_1_0dz2ekr4, v_2_me1m5uoh)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_trbnv6b5, v_1_0dz2ekr4, v_2_me1m5uoh)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
