# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_r8qibpvq, v_1_7d6a0m79, v_2_01x057vj, v_3_cesb2l6y, v_4_1eymuh4w, v_5_wmg4lrvb, v_6_31nx150y):
        v_7_const = torch.zeros((33, 57, 32), dtype=torch.float32, device="cpu")
        v_7_u2bob71d = torch.add(v_6_31nx150y, v_7_const)
        v_8_c52g91iq = torch.reciprocal(v_6_31nx150y)
        v_9_so4r2pu1 = torch.add(v_6_31nx150y, v_8_c52g91iq)
        v_10_pghjdlox = torch.pow(v_6_31nx150y, v_7_u2bob71d)
        v_11_7wvov4b9 = torch.floor(v_6_31nx150y)
        v_12_zx95brt8 = torch.rsqrt(v_6_31nx150y)
        v_13_qopgl7ji = torch.sign(v_6_31nx150y)
        v_14_jhlj4yal = F.silu(v_12_zx95brt8)
        v_15_t6esruvg = F.mish(v_13_qopgl7ji)
        v_16_q80oxeu6 = F.relu(v_13_qopgl7ji)
        v_17_xrc9vpg6 = torch.mean(v_13_qopgl7ji.float(), dim=-1, keepdim=False)
        v_18_1bl4mm2c = v_13_qopgl7ji[:max(1, v_13_qopgl7ji.shape[0]//2)]
        v_19_q6pdz652 = torch.neg(v_17_xrc9vpg6)
        v_20_rjynb4yd = torch.ceil(v_17_xrc9vpg6)
        v_21_025g7bab = torch.zeros((11, 24, 7), dtype=torch.float32, device="cpu")
        v_22_pzgf5tfd = torch.mean(v_20_rjynb4yd.float(), dim=-1, keepdim=False)
        v_23_b2emsp5h = F.elu(v_20_rjynb4yd, alpha=1.14)
        v_24_hmui5sw6 = torch.unsqueeze(v_20_rjynb4yd, 0)
        v_25_grpz758b = torch.rsqrt(v_23_b2emsp5h)
        v_26_const = torch.zeros((1, 33, 57), dtype=torch.float32, device="cpu")
        v_26_5mbdlb15 = torch.pow(v_24_hmui5sw6, v_26_const)
        v_27_7hml5qtu = torch.rsqrt(v_24_hmui5sw6)
        v_28_owzonjun = torch.unsqueeze(v_26_5mbdlb15, 0)
        v_29_l2x9lxh6 = torch.tile(v_26_5mbdlb15, [1] * 3)
        v_30_qc6s5ypv = torch.tile(v_26_5mbdlb15, [1] * 3)
        v_31_bu96tuy8 = torch.sum(v_29_l2x9lxh6, dim=-1, keepdim=False)
        v_32_bpkaka86 = torch.max(v_29_l2x9lxh6, dim=-1, keepdim=False).values
        v_33_11nzry3s = torch.triu(v_29_l2x9lxh6)
        v_34_w3bxh2fb = torch.zeros((10, 49), dtype=torch.float32, device="cpu")
        v_35_hnm1st61 = F.silu(v_29_l2x9lxh6)
        v_36_k0858l04 = torch.abs(v_29_l2x9lxh6)
        v_37_48twtr1q = torch.round(v_29_l2x9lxh6)
        v_38_x8qmktvo = torch.neg(v_29_l2x9lxh6)
        v_39_5wchgvs4 = torch.tanh(v_37_48twtr1q)
        v_40_5gh7xqoo = torch.mean(v_38_x8qmktvo.float(), dim=-1, keepdim=False)
        v_41_x7h99q3s = torch.exp(v_38_x8qmktvo)
        v_42_enkh2ygd = torch.min(v_38_x8qmktvo, dim=-1, keepdim=False).values
        v_43_1yjebsp8 = F.mish(v_38_x8qmktvo)
        v_44_vmxz0bcb = torch.tile(v_42_enkh2ygd, [1] * 2)
        v_45_mibrs4w4 = torch.tanh(v_42_enkh2ygd)
        v_46_dhoh591g = torch.log(v_44_vmxz0bcb)
        v_47_x6skflc2 = F.mish(v_44_vmxz0bcb)
        v_48_872r56os = torch.tanh(v_44_vmxz0bcb)
        v_49_11hye5b7 = torch.max(v_44_vmxz0bcb, dim=-1, keepdim=False).values
        v_50_5hw63hls = F.relu(v_44_vmxz0bcb)
        v_51_5z6vdy8a = torch.arange(0, 144, dtype=torch.float32, device="cpu")
        v_52_s24o4i0z = torch.zeros((35, 53, 12), dtype=torch.float32, device="cpu")
        v_53_sukqlxck = torch.sign(v_49_11hye5b7)
        v_54_80v877we = torch.round(v_49_11hye5b7)
        v_55_hpoci3nq = torch.mean(v_49_11hye5b7.float(), dim=-1, keepdim=False)
        v_56_u9urmydr = torch.zeros((21, 15, 14, 13), dtype=torch.float32, device="cpu")
        v_57_wrapper = torch.unsqueeze(v_54_80v877we, 0)
        v_57_8kc9550u = v_57_wrapper[:max(1, v_57_wrapper.shape[0]//2)]
        v_58_sxwg9sha = torch.zeros((10, 36, 33, 6), dtype=torch.float32, device="cpu")
        v_59_r5fqhxw1 = torch.log(v_56_u9urmydr)
        v_60_nadpxo2v = torch.unsqueeze(v_58_sxwg9sha, 0)
        v_61_270u9gja = v_58_sxwg9sha.to(torch.float32)
        v_62_const = torch.zeros((1, 10, 36, 33, 6), dtype=torch.float32, device="cpu")
        v_62_vsy73zmg = torch.pow(v_60_nadpxo2v, v_62_const)
        v_63_vdkn04z3 = torch.floor(v_60_nadpxo2v)
        v_64_taei9s31 = torch.tile(v_60_nadpxo2v, [1] * 5)
        v_65_uz1mok0m = torch.tile(v_60_nadpxo2v, [1] * 5)
        v_66_48bv9e4z = torch.mean(v_60_nadpxo2v.float(), dim=-1, keepdim=False)
        return (v_0_r8qibpvq, v_1_7d6a0m79, v_2_01x057vj, v_3_cesb2l6y, v_4_1eymuh4w, v_5_wmg4lrvb, v_9_so4r2pu1, v_10_pghjdlox, v_11_7wvov4b9, v_14_jhlj4yal, v_15_t6esruvg, v_16_q80oxeu6, v_18_1bl4mm2c, v_19_q6pdz652, v_21_025g7bab, v_22_pzgf5tfd, v_25_grpz758b, v_27_7hml5qtu, v_28_owzonjun, v_30_qc6s5ypv, v_31_bu96tuy8, v_32_bpkaka86, v_33_11nzry3s, v_34_w3bxh2fb, v_35_hnm1st61, v_36_k0858l04, v_39_5wchgvs4, v_40_5gh7xqoo, v_41_x7h99q3s, v_43_1yjebsp8, v_45_mibrs4w4, v_46_dhoh591g, v_47_x6skflc2, v_48_872r56os, v_50_5hw63hls, v_51_5z6vdy8a, v_52_s24o4i0z, v_53_sukqlxck, v_55_hpoci3nq, v_57_8kc9550u, v_59_r5fqhxw1, v_61_270u9gja, v_62_vsy73zmg, v_63_vdkn04z3, v_64_taei9s31, v_65_uz1mok0m, v_66_48bv9e4z)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_r8qibpvq = torch.randn(18, 15, 13, 19, dtype=torch.float32, device="cpu")
v_1_7d6a0m79 = torch.randn(13, 13, 22, 20, dtype=torch.float32, device="cpu")
v_2_01x057vj = torch.randn(39, 34, 26, dtype=torch.float32, device="cpu")
v_3_cesb2l6y = torch.randn(15, 23, dtype=torch.float32, device="cpu")
v_4_1eymuh4w = torch.randn(16, 21, 12, 14, dtype=torch.float32, device="cpu")
v_5_wmg4lrvb = torch.randn(36, 53, dtype=torch.float32, device="cpu")
v_6_31nx150y = torch.randn(33, 57, 32, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_r8qibpvq, v_1_7d6a0m79, v_2_01x057vj, v_3_cesb2l6y, v_4_1eymuh4w, v_5_wmg4lrvb, v_6_31nx150y)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_r8qibpvq, v_1_7d6a0m79, v_2_01x057vj, v_3_cesb2l6y, v_4_1eymuh4w, v_5_wmg4lrvb, v_6_31nx150y)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
