# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_gl4smtoh, v_1_2zomn3ti, v_2_genmp2sk, v_3_cz3nyg1a, v_4_2u7l5jgm, v_5_vlqjf05r, v_6_n007qtwv, v_7_j2vduy3i, v_8_mmh09x2b, v_9_030d0p6v, v_10_0tp4v6me, v_11_3ux8y0fl):
        v_12_4vsdxdud = torch.exp(v_11_3ux8y0fl)
        v_13_rp8isum9 = torch.div(v_11_3ux8y0fl, v_12_4vsdxdud)
        v_14_6bq1fv0h = torch.add(v_11_3ux8y0fl, v_12_4vsdxdud)
        v_15_tkzun9d5 = torch.tril(v_11_3ux8y0fl)
        v_16_01f7m971 = torch.max(v_11_3ux8y0fl, dim=-1, keepdim=False).values
        v_17_mp92zhjf = torch.zeros((63, 35), dtype=torch.float32, device="cpu")
        v_18_xddukoaa = torch.max(v_11_3ux8y0fl, dim=-1, keepdim=False).values
        v_19_6umaxbra = torch.mean(v_11_3ux8y0fl.float(), dim=-1, keepdim=False)
        v_20_const = torch.zeros((50, 46), dtype=torch.float32, device="cpu")
        v_20_jhepfllm = torch.maximum(v_18_xddukoaa, v_20_const)
        v_21_z02ixorm = torch.min(v_18_xddukoaa, dim=-1, keepdim=False).values
        v_22_const = torch.zeros((50, 46), dtype=torch.float32, device="cpu")
        v_22_mkue9g89 = torch.pow(v_18_xddukoaa, v_22_const)
        v_23_7fdthtkk = torch.max(v_21_z02ixorm, dim=-1, keepdim=False).values
        v_24_const = torch.zeros((50, 46), dtype=torch.float32, device="cpu")
        v_24_886z0u0d = torch.minimum(v_22_mkue9g89, v_24_const)
        v_25_gpwraf0n = torch.minimum(v_22_mkue9g89, v_19_6umaxbra)
        v_26_hhl4ww54 = torch.tril(v_22_mkue9g89)
        v_27_0pxrk7ga = torch.unsqueeze(v_22_mkue9g89, 0)
        v_28_h4d2qo9c = F.silu(v_22_mkue9g89)
        v_29_z4pzh70g = torch.arange(0, 221, dtype=torch.float32, device="cpu")
        v_30_2cpwn3dq = torch.sub(v_22_mkue9g89, v_25_gpwraf0n)
        v_31_wrapper = torch.unsqueeze(v_29_z4pzh70g, 0)
        v_31_zm95lfgd = torch.tril(v_31_wrapper)
        v_32_g2jcchdg = torch.min(v_29_z4pzh70g, dim=-1, keepdim=False).values
        v_33_wrapper = torch.unsqueeze(v_29_z4pzh70g, 0)
        v_33_78q6x9ke = torch.tril(v_33_wrapper)
        v_34_hhr0c6m9 = torch.tanh(v_29_z4pzh70g)
        v_35_t8eusmnd = torch.gather(v_29_z4pzh70g, 0, torch.zeros((min(221, 1)), dtype=torch.int64, device=v_29_z4pzh70g.device))
        v_36_wrapper = torch.unsqueeze(v_29_z4pzh70g, 0)
        v_36_635xq2qu = torch.transpose(v_36_wrapper, 0, 1)
        v_37_7dyy69rb = v_29_z4pzh70g.to(torch.float32)
        v_38_juu28ih4 = torch.floor(v_36_635xq2qu)
        v_39_vh5frpo6 = torch.arange(0, 17, dtype=torch.float32, device="cpu")
        v_40_s630pnen = torch.exp(v_38_juu28ih4)
        v_41_9x7pc9gg = torch.neg(v_38_juu28ih4)
        v_42_07l2z9qt = torch.mean(v_40_s630pnen.float(), dim=-1, keepdim=False)
        v_43_fxqci730 = v_41_9x7pc9gg.to(torch.float32)
        v_44_38xgvfvt = torch.log(v_42_07l2z9qt)
        v_45_jkatp96t = torch.maximum(v_42_07l2z9qt, v_35_t8eusmnd)
        v_46_n5mey89r = torch.max(v_44_38xgvfvt, dim=-1, keepdim=False).values
        v_47_6dswumxn = torch.floor(v_44_38xgvfvt)
        v_48_51m34et4 = torch.ceil(v_46_n5mey89r)
        v_49_wrapper = torch.unsqueeze(v_47_6dswumxn, 0)
        v_49_72xbbe0l = v_49_wrapper[:max(1, v_49_wrapper.shape[0]//2)]
        v_50_v1ni0p0v = torch.div(v_47_6dswumxn, v_44_38xgvfvt)
        v_51_j7hl4hw2 = v_47_6dswumxn.to(torch.float32)
        v_52_zb6xtys7 = torch.gather(v_50_v1ni0p0v, 0, torch.zeros((min(221, 1)), dtype=torch.int64, device=v_50_v1ni0p0v.device))
        v_53_yn8cycvj = torch.ones((37, 34), dtype=torch.float32, device="cpu")
        v_54_j1qj3oud = torch.maximum(v_50_v1ni0p0v, v_48_51m34et4)
        v_55_rpaxzakx = torch.abs(v_50_v1ni0p0v)
        v_56_const = torch.zeros((221), dtype=torch.float32, device="cpu")
        v_56_awqmz6qt = torch.mul(v_50_v1ni0p0v, v_56_const)
        v_57_9v85ipl7 = torch.zeros((55, 21, 34), dtype=torch.float32, device="cpu")
        v_58_185fm8zv = torch.arange(0, 32, dtype=torch.float32, device="cpu")
        v_59_36qsx4ko = F.relu(v_56_awqmz6qt)
        v_60_o2l9e985 = torch.tile(v_58_185fm8zv, [1] * 1)
        v_61_hhtv4j87 = F.relu(v_58_185fm8zv)
        v_62_9dugmlso = torch.floor(v_58_185fm8zv)
        v_63_kvvtboew = torch.exp(v_58_185fm8zv)
        v_64_4ymbqshw = torch.floor(v_62_9dugmlso)
        v_65_dq6n38s7 = torch.tile(v_62_9dugmlso, [1] * 1)
        v_66_u0oban5h = torch.neg(v_64_4ymbqshw)
        v_67_45f8fx3g = torch.arange(0, 68, dtype=torch.float32, device="cpu")
        v_68_wrapper = torch.unsqueeze(v_64_4ymbqshw, 0)
        v_68_c3ixnvpc = torch.transpose(v_68_wrapper, 0, 1)
        v_69_xfqr3knx = torch.mul(v_64_4ymbqshw, v_38_juu28ih4)
        v_70_w60xbr6x = torch.exp(v_64_4ymbqshw)
        v_71_rdynrdwx = torch.min(v_64_4ymbqshw, dim=-1, keepdim=False).values
        v_72_275186c6 = torch.tanh(v_64_4ymbqshw)
        v_73_wrapper = torch.unsqueeze(v_71_rdynrdwx, 0)
        v_74_wrapper = torch.unsqueeze(v_73_wrapper, 0)
        v_73_4akj3b2m = torch.triu(v_74_wrapper)
        v_74_fzbd2qjk = torch.log(v_71_rdynrdwx)
        v_75_wrapper = torch.unsqueeze(v_71_rdynrdwx, 0)
        v_75_r0otm8y8 = torch.min(v_75_wrapper, dim=-1, keepdim=False).values
        v_76_3e8xt75d = torch.pow(v_71_rdynrdwx, v_45_jkatp96t)
        v_77_kr4ko554 = torch.pow(v_75_r0otm8y8, v_28_h4d2qo9c)
        v_78_jked5ln2 = torch.arange(0, 239, dtype=torch.float32, device="cpu")
        return (v_0_gl4smtoh, v_1_2zomn3ti, v_2_genmp2sk, v_3_cz3nyg1a, v_4_2u7l5jgm, v_5_vlqjf05r, v_6_n007qtwv, v_7_j2vduy3i, v_8_mmh09x2b, v_9_030d0p6v, v_10_0tp4v6me, v_13_rp8isum9, v_14_6bq1fv0h, v_15_tkzun9d5, v_16_01f7m971, v_17_mp92zhjf, v_20_jhepfllm, v_23_7fdthtkk, v_24_886z0u0d, v_26_hhl4ww54, v_27_0pxrk7ga, v_30_2cpwn3dq, v_31_zm95lfgd, v_32_g2jcchdg, v_33_78q6x9ke, v_34_hhr0c6m9, v_37_7dyy69rb, v_39_vh5frpo6, v_43_fxqci730, v_49_72xbbe0l, v_51_j7hl4hw2, v_52_zb6xtys7, v_53_yn8cycvj, v_54_j1qj3oud, v_55_rpaxzakx, v_57_9v85ipl7, v_59_36qsx4ko, v_60_o2l9e985, v_61_hhtv4j87, v_63_kvvtboew, v_65_dq6n38s7, v_66_u0oban5h, v_67_45f8fx3g, v_68_c3ixnvpc, v_69_xfqr3knx, v_70_w60xbr6x, v_72_275186c6, v_73_4akj3b2m, v_74_fzbd2qjk, v_76_3e8xt75d, v_77_kr4ko554, v_78_jked5ln2)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_gl4smtoh = torch.randn(25, 20, 20, 8, dtype=torch.float32, device="cpu")
v_1_2zomn3ti = torch.randn(5, 8, 37, 21, dtype=torch.float32, device="cpu")
v_2_genmp2sk = torch.randn(10, 53, dtype=torch.float32, device="cpu")
v_3_cz3nyg1a = torch.randn(16, 15, 19, 19, dtype=torch.float32, device="cpu")
v_4_2u7l5jgm = torch.randn(24, 14, 15, 13, dtype=torch.float32, device="cpu")
v_5_vlqjf05r = torch.randn(30, 46, 21, dtype=torch.float32, device="cpu")
v_6_n007qtwv = torch.randn(47, 16, 62, dtype=torch.float32, device="cpu")
v_7_j2vduy3i = torch.randn(15, 14, 20, dtype=torch.float32, device="cpu")
v_8_mmh09x2b = torch.randn(26, 2, 31, 13, dtype=torch.float32, device="cpu")
v_9_030d0p6v = torch.randn(11, 11, dtype=torch.float32, device="cpu")
v_10_0tp4v6me = torch.randn(3, 59, 46, dtype=torch.float32, device="cpu")
v_11_3ux8y0fl = torch.randn(50, 46, 33, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_gl4smtoh, v_1_2zomn3ti, v_2_genmp2sk, v_3_cz3nyg1a, v_4_2u7l5jgm, v_5_vlqjf05r, v_6_n007qtwv, v_7_j2vduy3i, v_8_mmh09x2b, v_9_030d0p6v, v_10_0tp4v6me, v_11_3ux8y0fl)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_gl4smtoh, v_1_2zomn3ti, v_2_genmp2sk, v_3_cz3nyg1a, v_4_2u7l5jgm, v_5_vlqjf05r, v_6_n007qtwv, v_7_j2vduy3i, v_8_mmh09x2b, v_9_030d0p6v, v_10_0tp4v6me, v_11_3ux8y0fl)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
