# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_ef0pseug_var = relax.Var("v_0_ef0pseug", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 5, 3]), dtype="float32"))
    v_1_wbipbwqv_var = relax.Var("v_1_wbipbwqv", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 1]), dtype="float32"))
    v_2_r8euk9bo_var = relax.Var("v_2_r8euk9bo", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4, 5]), dtype="float32"))
    with bb.function("graph_0", [v_0_ef0pseug_var, v_1_wbipbwqv_var, v_2_r8euk9bo_var]):
        # input: [1, 3, 4, 5]
        # output: [1, 3, 4, 5]
        v_3_ses5pulw = bb.emit(relax.op.nn.leakyrelu(v_2_r8euk9bo_var, alpha=0.06))
        assert str(v_3_ses5pulw.struct_info.shape) == "R.shape([1, 3, 4, 5])", f"Shape mismatch: expected R.shape([1, 3, 4, 5]), got {v_3_ses5pulw.struct_info.shape}"
        # input: 
        # output: [5, 2, 3]
        v_4_nu11u34v = bb.emit(relax.op.zeros(relax.ShapeExpr([5, 2, 3]), dtype="float32"))
        assert str(v_4_nu11u34v.struct_info.shape) == "R.shape([5, 2, 3])", f"Shape mismatch: expected R.shape([5, 2, 3]), got {v_4_nu11u34v.struct_info.shape}"
        # input: [1, 3, 4, 5]
        # output: [1, 3, 4, 5]
        v_5_1rmfgxqh = bb.emit(relax.op.abs(v_2_r8euk9bo_var))
        assert str(v_5_1rmfgxqh.struct_info.shape) == "R.shape([1, 3, 4, 5])", f"Shape mismatch: expected R.shape([1, 3, 4, 5]), got {v_5_1rmfgxqh.struct_info.shape}"
        # input: 
        # output: [3, 6]
        v_6_e9wg0ec2 = bb.emit(relax.op.full(relax.ShapeExpr([3, 6]), relax.const(0, dtype="float32")))
        assert str(v_6_e9wg0ec2.struct_info.shape) == "R.shape([3, 6])", f"Shape mismatch: expected R.shape([3, 6]), got {v_6_e9wg0ec2.struct_info.shape}"
        # input: [1, 3, 4, 5]
        # output: [1, 3, 8, 10]
        v_7_n4uuucvi = bb.emit(relax.op.image.resize2d(v_2_r8euk9bo_var, relax.ShapeExpr([8, 10]), layout="NCHW"))
        assert str(v_7_n4uuucvi.struct_info.shape) == "R.shape([1, 3, 8, 10])", f"Shape mismatch: expected R.shape([1, 3, 8, 10]), got {v_7_n4uuucvi.struct_info.shape}"
        # input: [1, 3, 4, 5]
        # output: [1, 3, 8, 10]
        v_8_b9jm2n4g = bb.emit(relax.op.image.resize2d(v_2_r8euk9bo_var, relax.ShapeExpr([8, 10]), layout="NCHW"))
        assert str(v_8_b9jm2n4g.struct_info.shape) == "R.shape([1, 3, 8, 10])", f"Shape mismatch: expected R.shape([1, 3, 8, 10]), got {v_8_b9jm2n4g.struct_info.shape}"
        # input: [1, 3, 8, 10]
        # output: [1, 3, 8, 10]
        v_9_07zzg9bh = bb.emit(relax.op.astype(v_7_n4uuucvi, dtype="float32"))
        assert str(v_9_07zzg9bh.struct_info.shape) == "R.shape([1, 3, 8, 10])", f"Shape mismatch: expected R.shape([1, 3, 8, 10]), got {v_9_07zzg9bh.struct_info.shape}"
        # input: [1, 3, 8, 10]
        # output: [1, 3, 10, 8]
        v_10_cdvmqxcs = bb.emit(relax.op.permute_dims(v_8_b9jm2n4g, axes=[0, 1, 3, 2]))
        assert str(v_10_cdvmqxcs.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_10_cdvmqxcs.struct_info.shape}"
        # input: [1, 3, 8, 10]
        # output: [1, 3, 8, 10]
        v_11_a6wioi1m = bb.emit(relax.op.multiply(v_8_b9jm2n4g, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_8_b9jm2n4g))))))
        assert str(v_11_a6wioi1m.struct_info.shape) == "R.shape([1, 3, 8, 10])", f"Shape mismatch: expected R.shape([1, 3, 8, 10]), got {v_11_a6wioi1m.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_12_dd0fzmr8 = bb.emit(relax.op.nn.leakyrelu(v_10_cdvmqxcs, alpha=0.26))
        assert str(v_12_dd0fzmr8.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_12_dd0fzmr8.struct_info.shape}"
        # input: [1, 3, 10, 8], [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_13_nxv6g0rx = bb.emit(relax.op.multiply(relax.op.astype(v_10_cdvmqxcs, dtype="float32"), relax.op.astype(v_12_dd0fzmr8, dtype="float32")))
        assert str(v_13_nxv6g0rx.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_13_nxv6g0rx.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [3, 10, 8]
        v_14_020iwq73 = bb.emit(relax.op.take(v_10_cdvmqxcs, relax.const(0, dtype="int64"), axis=0))
        assert str(v_14_020iwq73.struct_info.shape) == "R.shape([3, 10, 8])", f"Shape mismatch: expected R.shape([3, 10, 8]), got {v_14_020iwq73.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_15_2a0opf68 = bb.emit(relax.op.abs(v_10_cdvmqxcs))
        assert str(v_15_2a0opf68.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_15_2a0opf68.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_16_3hojzj3g = bb.emit(relax.op.nn.selu(v_10_cdvmqxcs))
        assert str(v_16_3hojzj3g.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_16_3hojzj3g.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_17_6qt5lz07 = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_15_2a0opf68, dtype="float32"), axis=-1))
        assert str(v_17_6qt5lz07.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_17_6qt5lz07.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_18_621b6hvz = bb.emit(relax.op.tile(v_15_2a0opf68, [1, 1, 1, 1]))
        assert str(v_18_621b6hvz.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_18_621b6hvz.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_19_s0hjg44g = bb.emit(relax.op.astype(v_15_2a0opf68, dtype="float32"))
        assert str(v_19_s0hjg44g.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_19_s0hjg44g.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_20_ci2rg2ib = bb.emit(relax.op.clip(v_18_621b6hvz, -1, 0))
        assert str(v_20_ci2rg2ib.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_20_ci2rg2ib.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10, 8]
        v_21_vq8mcvx0 = bb.emit(relax.op.clip(v_18_621b6hvz, -0.76, 1.74))
        assert str(v_21_vq8mcvx0.struct_info.shape) == "R.shape([1, 3, 10, 8])", f"Shape mismatch: expected R.shape([1, 3, 10, 8]), got {v_21_vq8mcvx0.struct_info.shape}"
        # input: [1, 3, 10, 8]
        # output: [1, 3, 10]
        v_22_zx8lmz54 = bb.emit(relax.op.max(v_18_621b6hvz, axis=[-1], keepdims=False))
        assert str(v_22_zx8lmz54.struct_info.shape) == "R.shape([1, 3, 10])", f"Shape mismatch: expected R.shape([1, 3, 10]), got {v_22_zx8lmz54.struct_info.shape}"
        # input: [1, 3, 10]
        # output: [1, 1, 3, 10]
        v_23_eggjtwuo = bb.emit(relax.op.expand_dims(v_22_zx8lmz54, axis=0))
        assert str(v_23_eggjtwuo.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_23_eggjtwuo.struct_info.shape}"
        # input: [1, 3, 10]
        # output: [1, 3, 10]
        v_24_vy09xqyu = bb.emit(relax.op.nn.silu(v_22_zx8lmz54))
        assert str(v_24_vy09xqyu.struct_info.shape) == "R.shape([1, 3, 10])", f"Shape mismatch: expected R.shape([1, 3, 10]), got {v_24_vy09xqyu.struct_info.shape}"
        # input: [1, 3, 10], [1, 3, 10]
        # output: [1, 3, 10]
        v_25_2my78i7q = bb.emit(relax.op.multiply(relax.op.astype(v_22_zx8lmz54, dtype="float32"), relax.op.astype(v_24_vy09xqyu, dtype="float32")))
        assert str(v_25_2my78i7q.struct_info.shape) == "R.shape([1, 3, 10])", f"Shape mismatch: expected R.shape([1, 3, 10]), got {v_25_2my78i7q.struct_info.shape}"
        # input: [1, 3, 10]
        # output: [1, 3, 10]
        v_26_46dlbd1b = bb.emit(relax.op.tril(v_24_vy09xqyu))
        assert str(v_26_46dlbd1b.struct_info.shape) == "R.shape([1, 3, 10])", f"Shape mismatch: expected R.shape([1, 3, 10]), got {v_26_46dlbd1b.struct_info.shape}"
        # input: 
        # output: [6, 4]
        v_27_ujgw2f24 = bb.emit(relax.op.full(relax.ShapeExpr([6, 4]), relax.const(0, dtype="float32")))
        assert str(v_27_ujgw2f24.struct_info.shape) == "R.shape([6, 4])", f"Shape mismatch: expected R.shape([6, 4]), got {v_27_ujgw2f24.struct_info.shape}"
        # input: [1, 3, 10]
        # output: [1, 3, 10]
        v_28_gm09kzyd = bb.emit(relax.op.where(relax.op.greater_equal(v_24_vy09xqyu, relax.const(0, dtype="float32")), v_24_vy09xqyu, relax.op.multiply(relax.const(0.57, dtype="float32"), relax.op.subtract(relax.op.exp(v_24_vy09xqyu), relax.const(1.0, dtype="float32")))))
        assert str(v_28_gm09kzyd.struct_info.shape) == "R.shape([1, 3, 10])", f"Shape mismatch: expected R.shape([1, 3, 10]), got {v_28_gm09kzyd.struct_info.shape}"
        # input: 
        # output: [5, 6, 5, 1]
        v_29_4ee3qgp7 = bb.emit(relax.op.ones(relax.ShapeExpr([5, 6, 5, 1]), dtype="float32"))
        assert str(v_29_4ee3qgp7.struct_info.shape) == "R.shape([5, 6, 5, 1])", f"Shape mismatch: expected R.shape([5, 6, 5, 1]), got {v_29_4ee3qgp7.struct_info.shape}"
        # input: [1, 3, 10]
        # output: [1, 1, 3, 10]
        v_30_90kai4jz = bb.emit(relax.op.expand_dims(v_28_gm09kzyd, axis=0))
        assert str(v_30_90kai4jz.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_30_90kai4jz.struct_info.shape}"
        bb.emit_func_output((v_0_ef0pseug_var, v_1_wbipbwqv_var, v_3_ses5pulw, v_4_nu11u34v, v_5_1rmfgxqh, v_6_e9wg0ec2, v_9_07zzg9bh, v_11_a6wioi1m, v_13_nxv6g0rx, v_14_020iwq73, v_16_3hojzj3g, v_17_6qt5lz07, v_19_s0hjg44g, v_20_ci2rg2ib, v_21_vq8mcvx0, v_23_eggjtwuo, v_25_2my78i7q, v_26_46dlbd1b, v_27_ujgw2f24, v_29_4ee3qgp7, v_30_90kai4jz))

    v_0_ef0pseug_var = relax.Var("v_0_ef0pseug", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 5, 3]), dtype="float32"))
    v_1_wbipbwqv_var = relax.Var("v_1_wbipbwqv", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 1]), dtype="float32"))
    v_3_ses5pulw_var = relax.Var("v_3_ses5pulw", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4, 5]), dtype="float32"))
    v_4_nu11u34v_var = relax.Var("v_4_nu11u34v", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3]), dtype="float32"))
    v_5_1rmfgxqh_var = relax.Var("v_5_1rmfgxqh", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4, 5]), dtype="float32"))
    v_6_e9wg0ec2_var = relax.Var("v_6_e9wg0ec2", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_9_07zzg9bh_var = relax.Var("v_9_07zzg9bh", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 8, 10]), dtype="float32"))
    v_11_a6wioi1m_var = relax.Var("v_11_a6wioi1m", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 8, 10]), dtype="float32"))
    v_13_nxv6g0rx_var = relax.Var("v_13_nxv6g0rx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_14_020iwq73_var = relax.Var("v_14_020iwq73", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 10, 8]), dtype="float32"))
    v_16_3hojzj3g_var = relax.Var("v_16_3hojzj3g", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_17_6qt5lz07_var = relax.Var("v_17_6qt5lz07", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_19_s0hjg44g_var = relax.Var("v_19_s0hjg44g", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_20_ci2rg2ib_var = relax.Var("v_20_ci2rg2ib", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_21_vq8mcvx0_var = relax.Var("v_21_vq8mcvx0", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_23_eggjtwuo_var = relax.Var("v_23_eggjtwuo", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_25_2my78i7q_var = relax.Var("v_25_2my78i7q", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10]), dtype="float32"))
    v_26_46dlbd1b_var = relax.Var("v_26_46dlbd1b", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10]), dtype="float32"))
    v_27_ujgw2f24_var = relax.Var("v_27_ujgw2f24", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 4]), dtype="float32"))
    v_29_4ee3qgp7_var = relax.Var("v_29_4ee3qgp7", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 1]), dtype="float32"))
    v_30_90kai4jz_var = relax.Var("v_30_90kai4jz", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    with bb.function("graph_1", [v_0_ef0pseug_var, v_1_wbipbwqv_var, v_3_ses5pulw_var, v_4_nu11u34v_var, v_5_1rmfgxqh_var, v_6_e9wg0ec2_var, v_9_07zzg9bh_var, v_11_a6wioi1m_var, v_13_nxv6g0rx_var, v_14_020iwq73_var, v_16_3hojzj3g_var, v_17_6qt5lz07_var, v_19_s0hjg44g_var, v_20_ci2rg2ib_var, v_21_vq8mcvx0_var, v_23_eggjtwuo_var, v_25_2my78i7q_var, v_26_46dlbd1b_var, v_27_ujgw2f24_var, v_29_4ee3qgp7_var, v_30_90kai4jz_var]):
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_31_zf31by6p = bb.emit(relax.op.sigmoid(v_30_90kai4jz_var))
        assert str(v_31_zf31by6p.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_31_zf31by6p.struct_info.shape}"
        # input: 
        # output: [1, 1, 1, 2]
        v_32_7rrxmow7 = bb.emit(relax.op.full(relax.ShapeExpr([1, 1, 1, 2]), relax.const(0, dtype="float32")))
        assert str(v_32_7rrxmow7.struct_info.shape) == "R.shape([1, 1, 1, 2])", f"Shape mismatch: expected R.shape([1, 1, 1, 2]), got {v_32_7rrxmow7.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 1, 1, 2]
        # output: [1, 1, 3, 9]
        v_33_843judqx = bb.emit(relax.op.nn.conv2d(v_30_90kai4jz_var, v_32_7rrxmow7, strides=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1))
        assert str(v_33_843judqx.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_33_843judqx.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 3, 10]
        # output: [1, 1, 3, 10]
        v_34_2ckb1zw2 = bb.emit(relax.op.subtract(relax.op.astype(v_30_90kai4jz_var, dtype="float32"), relax.op.astype(v_25_2my78i7q_var, dtype="float32")))
        assert str(v_34_2ckb1zw2.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_34_2ckb1zw2.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_35_bcz8fi9g = bb.emit(relax.op.triu(v_30_90kai4jz_var))
        assert str(v_35_bcz8fi9g.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_35_bcz8fi9g.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_36_y2hqnf6d = bb.emit(relax.op.nn.layer_norm(v_34_2ckb1zw2, gamma=relax.op.ones(relax.ShapeExpr([10]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([10]), dtype="float32"), axes=[-1]))
        assert str(v_36_y2hqnf6d.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_36_y2hqnf6d.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_37_p1x6r8a6 = bb.emit(relax.op.astype(v_34_2ckb1zw2, dtype="float32"))
        assert str(v_37_p1x6r8a6.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_37_p1x6r8a6.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_38_231flc6f = bb.emit(relax.op.nn.gelu(v_34_2ckb1zw2))
        assert str(v_38_231flc6f.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_38_231flc6f.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_39_un2tg4q4 = bb.emit(relax.op.where(relax.op.greater_equal(v_37_p1x6r8a6, relax.const(0, dtype="float32")), v_37_p1x6r8a6, relax.op.multiply(relax.const(1.17, dtype="float32"), relax.op.subtract(relax.op.exp(v_37_p1x6r8a6), relax.const(1.0, dtype="float32")))))
        assert str(v_39_un2tg4q4.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_39_un2tg4q4.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_40_u65k8kvc = bb.emit(relax.op.minimum(relax.op.astype(v_38_231flc6f, dtype="float32"), relax.op.astype(v_39_un2tg4q4, dtype="float32")))
        assert str(v_40_u65k8kvc.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_40_u65k8kvc.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 3, 10]
        # output: [1, 1, 3, 10]
        v_41_fnf6xzhw = bb.emit(relax.op.subtract(relax.op.astype(v_38_231flc6f, dtype="float32"), relax.op.astype(v_25_2my78i7q_var, dtype="float32")))
        assert str(v_41_fnf6xzhw.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_41_fnf6xzhw.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_42_b6gpp1um = bb.emit(relax.op.triu(v_38_231flc6f))
        assert str(v_42_b6gpp1um.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_42_b6gpp1um.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 6, 20]
        v_43_wt5rq7d7 = bb.emit(relax.op.image.resize2d(v_38_231flc6f, relax.ShapeExpr([6, 20]), layout="NCHW"))
        assert str(v_43_wt5rq7d7.struct_info.shape) == "R.shape([1, 1, 6, 20])", f"Shape mismatch: expected R.shape([1, 1, 6, 20]), got {v_43_wt5rq7d7.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_44_dt25mpuw = bb.emit(relax.op.nn.avg_pool2d(v_38_231flc6f, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_44_dt25mpuw.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_44_dt25mpuw.struct_info.shape}"
        # input: [1, 1, 6, 20]
        # output: [1, 1, 6, 20]
        v_45_7rjsjnde = bb.emit(relax.op.where(relax.op.greater_equal(v_43_wt5rq7d7, relax.const(0, dtype="float32")), v_43_wt5rq7d7, relax.op.multiply(relax.const(1.6, dtype="float32"), relax.op.subtract(relax.op.exp(v_43_wt5rq7d7), relax.const(1.0, dtype="float32")))))
        assert str(v_45_7rjsjnde.struct_info.shape) == "R.shape([1, 1, 6, 20])", f"Shape mismatch: expected R.shape([1, 1, 6, 20]), got {v_45_7rjsjnde.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_46_74vwfjxd = bb.emit(relax.op.sigmoid(v_44_dt25mpuw))
        assert str(v_46_74vwfjxd.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_46_74vwfjxd.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_47_5c2xkyvz = bb.emit(relax.op.sigmoid(v_44_dt25mpuw))
        assert str(v_47_5c2xkyvz.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_47_5c2xkyvz.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 6, 20]
        v_48_jrg7uqtk = bb.emit(relax.op.image.resize2d(v_44_dt25mpuw, relax.ShapeExpr([6, 20]), layout="NCHW"))
        assert str(v_48_jrg7uqtk.struct_info.shape) == "R.shape([1, 1, 6, 20])", f"Shape mismatch: expected R.shape([1, 1, 6, 20]), got {v_48_jrg7uqtk.struct_info.shape}"
        # input: [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_49_q5q37zrg = bb.emit(relax.op.nn.relu(v_47_5c2xkyvz))
        assert str(v_49_q5q37zrg.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_49_q5q37zrg.struct_info.shape}"
        # input: [1, 1, 3, 10], [1, 1, 3, 10]
        # output: [1, 1, 3, 10]
        v_50_inpuz0eo = bb.emit(relax.op.add(relax.op.astype(v_47_5c2xkyvz, dtype="float32"), relax.op.astype(v_40_u65k8kvc, dtype="float32")))
        assert str(v_50_inpuz0eo.struct_info.shape) == "R.shape([1, 1, 3, 10])", f"Shape mismatch: expected R.shape([1, 1, 3, 10]), got {v_50_inpuz0eo.struct_info.shape}"
        # input: 
        # output: [1, 3]
        v_51_16s113xs = bb.emit(relax.op.full(relax.ShapeExpr([1, 3]), relax.const(0, dtype="float32")))
        assert str(v_51_16s113xs.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_51_16s113xs.struct_info.shape}"
        bb.emit_func_output((v_0_ef0pseug_var, v_1_wbipbwqv_var, v_3_ses5pulw_var, v_4_nu11u34v_var, v_5_1rmfgxqh_var, v_6_e9wg0ec2_var, v_9_07zzg9bh_var, v_11_a6wioi1m_var, v_13_nxv6g0rx_var, v_14_020iwq73_var, v_16_3hojzj3g_var, v_17_6qt5lz07_var, v_19_s0hjg44g_var, v_20_ci2rg2ib_var, v_21_vq8mcvx0_var, v_23_eggjtwuo_var, v_26_46dlbd1b_var, v_27_ujgw2f24_var, v_29_4ee3qgp7_var, v_31_zf31by6p, v_33_843judqx, v_35_bcz8fi9g, v_36_y2hqnf6d, v_41_fnf6xzhw, v_42_b6gpp1um, v_45_7rjsjnde, v_46_74vwfjxd, v_48_jrg7uqtk, v_49_q5q37zrg, v_50_inpuz0eo, v_51_16s113xs))

    v_0_ef0pseug_var = relax.Var("v_0_ef0pseug", relax.TensorStructInfo(shape=relax.ShapeExpr([4, 5, 5, 3]), dtype="float32"))
    v_1_wbipbwqv_var = relax.Var("v_1_wbipbwqv", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 1]), dtype="float32"))
    v_3_ses5pulw_var = relax.Var("v_3_ses5pulw", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4, 5]), dtype="float32"))
    v_4_nu11u34v_var = relax.Var("v_4_nu11u34v", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 2, 3]), dtype="float32"))
    v_5_1rmfgxqh_var = relax.Var("v_5_1rmfgxqh", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 4, 5]), dtype="float32"))
    v_6_e9wg0ec2_var = relax.Var("v_6_e9wg0ec2", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 6]), dtype="float32"))
    v_9_07zzg9bh_var = relax.Var("v_9_07zzg9bh", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 8, 10]), dtype="float32"))
    v_11_a6wioi1m_var = relax.Var("v_11_a6wioi1m", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 8, 10]), dtype="float32"))
    v_13_nxv6g0rx_var = relax.Var("v_13_nxv6g0rx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_14_020iwq73_var = relax.Var("v_14_020iwq73", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 10, 8]), dtype="float32"))
    v_16_3hojzj3g_var = relax.Var("v_16_3hojzj3g", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_17_6qt5lz07_var = relax.Var("v_17_6qt5lz07", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_19_s0hjg44g_var = relax.Var("v_19_s0hjg44g", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_20_ci2rg2ib_var = relax.Var("v_20_ci2rg2ib", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_21_vq8mcvx0_var = relax.Var("v_21_vq8mcvx0", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10, 8]), dtype="float32"))
    v_23_eggjtwuo_var = relax.Var("v_23_eggjtwuo", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_26_46dlbd1b_var = relax.Var("v_26_46dlbd1b", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3, 10]), dtype="float32"))
    v_27_ujgw2f24_var = relax.Var("v_27_ujgw2f24", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 4]), dtype="float32"))
    v_29_4ee3qgp7_var = relax.Var("v_29_4ee3qgp7", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 6, 5, 1]), dtype="float32"))
    v_31_zf31by6p_var = relax.Var("v_31_zf31by6p", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_33_843judqx_var = relax.Var("v_33_843judqx", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 9]), dtype="float32"))
    v_35_bcz8fi9g_var = relax.Var("v_35_bcz8fi9g", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_36_y2hqnf6d_var = relax.Var("v_36_y2hqnf6d", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_41_fnf6xzhw_var = relax.Var("v_41_fnf6xzhw", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_42_b6gpp1um_var = relax.Var("v_42_b6gpp1um", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_45_7rjsjnde_var = relax.Var("v_45_7rjsjnde", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 6, 20]), dtype="float32"))
    v_46_74vwfjxd_var = relax.Var("v_46_74vwfjxd", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_48_jrg7uqtk_var = relax.Var("v_48_jrg7uqtk", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 6, 20]), dtype="float32"))
    v_49_q5q37zrg_var = relax.Var("v_49_q5q37zrg", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_50_inpuz0eo_var = relax.Var("v_50_inpuz0eo", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 1, 3, 10]), dtype="float32"))
    v_51_16s113xs_var = relax.Var("v_51_16s113xs", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 3]), dtype="float32"))
    with bb.function("graph_2", [v_0_ef0pseug_var, v_1_wbipbwqv_var, v_3_ses5pulw_var, v_4_nu11u34v_var, v_5_1rmfgxqh_var, v_6_e9wg0ec2_var, v_9_07zzg9bh_var, v_11_a6wioi1m_var, v_13_nxv6g0rx_var, v_14_020iwq73_var, v_16_3hojzj3g_var, v_17_6qt5lz07_var, v_19_s0hjg44g_var, v_20_ci2rg2ib_var, v_21_vq8mcvx0_var, v_23_eggjtwuo_var, v_26_46dlbd1b_var, v_27_ujgw2f24_var, v_29_4ee3qgp7_var, v_31_zf31by6p_var, v_33_843judqx_var, v_35_bcz8fi9g_var, v_36_y2hqnf6d_var, v_41_fnf6xzhw_var, v_42_b6gpp1um_var, v_45_7rjsjnde_var, v_46_74vwfjxd_var, v_48_jrg7uqtk_var, v_49_q5q37zrg_var, v_50_inpuz0eo_var, v_51_16s113xs_var]):
        # input: [1, 3]
        # output: [1, 3]
        v_52_tmql7ojb = bb.emit(relax.op.nn.relu(v_51_16s113xs_var))
        assert str(v_52_tmql7ojb.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_52_tmql7ojb.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_53_75nqf6ak = bb.emit(relax.op.triu(v_51_16s113xs_var))
        assert str(v_53_75nqf6ak.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_53_75nqf6ak.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_54_rx3n7cze = bb.emit(relax.op.nn.silu(v_52_tmql7ojb))
        assert str(v_54_rx3n7cze.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_54_rx3n7cze.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_55_3fgh4dmx = bb.emit(relax.op.nn.selu(v_53_75nqf6ak))
        assert str(v_55_3fgh4dmx.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_55_3fgh4dmx.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_56_h9chswzo = bb.emit(relax.op.nn.avg_pool2d(v_33_843judqx_var, pool_size=[1, 1], strides=[1, 1], padding=[0, 0]))
        assert str(v_56_h9chswzo.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_56_h9chswzo.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_57_34ekf62j = bb.emit(relax.op.nn.relu(v_54_rx3n7cze))
        assert str(v_57_34ekf62j.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_57_34ekf62j.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_58_vtiof4r1 = bb.emit(relax.op.astype(v_56_h9chswzo, dtype="float32"))
        assert str(v_58_vtiof4r1.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_58_vtiof4r1.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 1, 3]
        v_59_fbuv2ybq = bb.emit(relax.op.expand_dims(v_57_34ekf62j, axis=0))
        assert str(v_59_fbuv2ybq.struct_info.shape) == "R.shape([1, 1, 3])", f"Shape mismatch: expected R.shape([1, 1, 3]), got {v_59_fbuv2ybq.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_60_sa432pi7 = bb.emit(relax.op.astype(v_58_vtiof4r1, dtype="float32"))
        assert str(v_60_sa432pi7.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_60_sa432pi7.struct_info.shape}"
        # input: 
        # output: [21]
        v_61_j05z554j = bb.emit(relax.op.arange(0, 21, dtype="float32"))
        assert str(v_61_j05z554j.struct_info.shape) == "R.shape([21])", f"Shape mismatch: expected R.shape([21]), got {v_61_j05z554j.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_62_adilow8d = bb.emit(relax.op.clip(v_60_sa432pi7, 0, 0))
        assert str(v_62_adilow8d.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_62_adilow8d.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_63_ltesv37s = bb.emit(relax.op.nn.gelu(v_60_sa432pi7))
        assert str(v_63_ltesv37s.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_63_ltesv37s.struct_info.shape}"
        # input: [1, 1, 3, 9], [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_64_synhnn22 = bb.emit(relax.op.add(relax.op.astype(v_60_sa432pi7, dtype="float32"), relax.op.astype(v_62_adilow8d, dtype="float32")))
        assert str(v_64_synhnn22.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_64_synhnn22.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 6, 18]
        v_65_9hptyfnu = bb.emit(relax.op.image.resize2d(v_60_sa432pi7, relax.ShapeExpr([6, 18]), layout="NCHW"))
        assert str(v_65_9hptyfnu.struct_info.shape) == "R.shape([1, 1, 6, 18])", f"Shape mismatch: expected R.shape([1, 1, 6, 18]), got {v_65_9hptyfnu.struct_info.shape}"
        # input: 
        # output: [5, 4, 4]
        v_66_z5loumbg = bb.emit(relax.op.zeros(relax.ShapeExpr([5, 4, 4]), dtype="float32"))
        assert str(v_66_z5loumbg.struct_info.shape) == "R.shape([5, 4, 4])", f"Shape mismatch: expected R.shape([5, 4, 4]), got {v_66_z5loumbg.struct_info.shape}"
        # input: 
        # output: [6, 4, 6]
        v_67_06w2akbz = bb.emit(relax.op.ones(relax.ShapeExpr([6, 4, 6]), dtype="float32"))
        assert str(v_67_06w2akbz.struct_info.shape) == "R.shape([6, 4, 6])", f"Shape mismatch: expected R.shape([6, 4, 6]), got {v_67_06w2akbz.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_68_c295gjta = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_64_synhnn22, dtype="float32"), axis=-1))
        assert str(v_68_c295gjta.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_68_c295gjta.struct_info.shape}"
        # input: 
        # output: [2, 1, 2, 2]
        v_69_74mbrvq4 = bb.emit(relax.op.ones(relax.ShapeExpr([2, 1, 2, 2]), dtype="float32"))
        assert str(v_69_74mbrvq4.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_69_74mbrvq4.struct_info.shape}"
        # input: [1, 1, 3, 9]
        # output: [1, 1, 3, 9]
        v_70_lvpuhdvh = bb.emit(relax.op.nn.relu(v_64_synhnn22))
        assert str(v_70_lvpuhdvh.struct_info.shape) == "R.shape([1, 1, 3, 9])", f"Shape mismatch: expected R.shape([1, 1, 3, 9]), got {v_70_lvpuhdvh.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_71_kq9b4jf2 = bb.emit(relax.op.nn.silu(v_69_74mbrvq4))
        assert str(v_71_kq9b4jf2.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_71_kq9b4jf2.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_72_d2ygg8eh = bb.emit(relax.op.multiply(v_69_74mbrvq4, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_69_74mbrvq4))))))
        assert str(v_72_d2ygg8eh.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_72_d2ygg8eh.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_73_4nbeye89 = bb.emit(relax.op.nn.silu(v_69_74mbrvq4))
        assert str(v_73_4nbeye89.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_73_4nbeye89.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_74_x0h2arat = bb.emit(relax.op.astype(v_72_d2ygg8eh, dtype="float32"))
        assert str(v_74_x0h2arat.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_74_x0h2arat.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_75_n5c6zeh9 = bb.emit(relax.op.nn.gelu(v_72_d2ygg8eh))
        assert str(v_75_n5c6zeh9.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_75_n5c6zeh9.struct_info.shape}"
        # input: [2, 1, 2, 2], [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_76_8yqmc5b4 = bb.emit(relax.op.multiply(relax.op.astype(v_74_x0h2arat, dtype="float32"), relax.op.astype(v_72_d2ygg8eh, dtype="float32")))
        assert str(v_76_8yqmc5b4.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_76_8yqmc5b4.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_77_cles744h = bb.emit(relax.op.nn.selu(v_75_n5c6zeh9))
        assert str(v_77_cles744h.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_77_cles744h.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_78_lbwuzuoa = bb.emit(relax.op.where(relax.op.greater_equal(v_75_n5c6zeh9, relax.const(0, dtype="float32")), v_75_n5c6zeh9, relax.op.multiply(relax.const(1.63, dtype="float32"), relax.op.subtract(relax.op.exp(v_75_n5c6zeh9), relax.const(1.0, dtype="float32")))))
        assert str(v_78_lbwuzuoa.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_78_lbwuzuoa.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2]
        v_79_qymxkbq9 = bb.emit(relax.op.max(v_75_n5c6zeh9, axis=[-1], keepdims=False))
        assert str(v_79_qymxkbq9.struct_info.shape) == "R.shape([2, 1, 2])", f"Shape mismatch: expected R.shape([2, 1, 2]), got {v_79_qymxkbq9.struct_info.shape}"
        # input: [2, 1, 2, 2]
        # output: [2, 1, 2, 2]
        v_80_9s21kb5m = bb.emit(relax.op.multiply(v_75_n5c6zeh9, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_75_n5c6zeh9))))))
        assert str(v_80_9s21kb5m.struct_info.shape) == "R.shape([2, 1, 2, 2])", f"Shape mismatch: expected R.shape([2, 1, 2, 2]), got {v_80_9s21kb5m.struct_info.shape}"
        # input: [2, 1, 2]
        # output: [2, 1, 2]
        v_81_ci4ggehw = bb.emit(relax.op.astype(v_79_qymxkbq9, dtype="float32"))
        assert str(v_81_ci4ggehw.struct_info.shape) == "R.shape([2, 1, 2])", f"Shape mismatch: expected R.shape([2, 1, 2]), got {v_81_ci4ggehw.struct_info.shape}"
        # input: [2, 1, 2], [2, 1, 2, 2]
        # output: [2, 2, 2, 2]
        v_82_xf53hlr6 = bb.emit(relax.op.multiply(relax.op.astype(v_79_qymxkbq9, dtype="float32"), relax.op.astype(v_71_kq9b4jf2, dtype="float32")))
        assert str(v_82_xf53hlr6.struct_info.shape) == "R.shape([2, 2, 2, 2])", f"Shape mismatch: expected R.shape([2, 2, 2, 2]), got {v_82_xf53hlr6.struct_info.shape}"
        bb.emit_func_output((v_0_ef0pseug_var, v_1_wbipbwqv_var, v_3_ses5pulw_var, v_4_nu11u34v_var, v_5_1rmfgxqh_var, v_6_e9wg0ec2_var, v_9_07zzg9bh_var, v_11_a6wioi1m_var, v_13_nxv6g0rx_var, v_14_020iwq73_var, v_16_3hojzj3g_var, v_17_6qt5lz07_var, v_19_s0hjg44g_var, v_20_ci2rg2ib_var, v_21_vq8mcvx0_var, v_23_eggjtwuo_var, v_26_46dlbd1b_var, v_27_ujgw2f24_var, v_29_4ee3qgp7_var, v_31_zf31by6p_var, v_35_bcz8fi9g_var, v_36_y2hqnf6d_var, v_41_fnf6xzhw_var, v_42_b6gpp1um_var, v_45_7rjsjnde_var, v_46_74vwfjxd_var, v_48_jrg7uqtk_var, v_49_q5q37zrg_var, v_50_inpuz0eo_var, v_55_3fgh4dmx, v_59_fbuv2ybq, v_61_j05z554j, v_63_ltesv37s, v_65_9hptyfnu, v_66_z5loumbg, v_67_06w2akbz, v_68_c295gjta, v_70_lvpuhdvh, v_73_4nbeye89, v_76_8yqmc5b4, v_77_cles744h, v_78_lbwuzuoa, v_80_9s21kb5m, v_81_ci4ggehw, v_82_xf53hlr6))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_ef0pseug = np.random.uniform(0.0, 1.0, size=(4, 5, 5, 3)).astype(np.float32)
v_0_ef0pseug = tvm.runtime.tensor(np_v_0_ef0pseug, device=tvm.cuda())
np_v_1_wbipbwqv = np.random.uniform(0.0, 1.0, size=(6, 1)).astype(np.float32)
v_1_wbipbwqv = tvm.runtime.tensor(np_v_1_wbipbwqv, device=tvm.cuda())
np_v_2_r8euk9bo = np.random.uniform(0.0, 1.0, size=(1, 3, 4, 5)).astype(np.float32)
v_2_r8euk9bo = tvm.runtime.tensor(np_v_2_r8euk9bo, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_0_ef0pseug, v_1_wbipbwqv, v_2_r8euk9bo)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_0 -> graph_1
_prev_out = tvm_result_0 if not hasattr(tvm_result_0, 'numpy') else [tvm_result_0]
v_0_ef0pseug = _prev_out[0]
v_1_wbipbwqv = _prev_out[1]
v_3_ses5pulw = _prev_out[2]
v_4_nu11u34v = _prev_out[3]
v_5_1rmfgxqh = _prev_out[4]
v_6_e9wg0ec2 = _prev_out[5]
v_9_07zzg9bh = _prev_out[6]
v_11_a6wioi1m = _prev_out[7]
v_13_nxv6g0rx = _prev_out[8]
v_14_020iwq73 = _prev_out[9]
v_16_3hojzj3g = _prev_out[10]
v_17_6qt5lz07 = _prev_out[11]
v_19_s0hjg44g = _prev_out[12]
v_20_ci2rg2ib = _prev_out[13]
v_21_vq8mcvx0 = _prev_out[14]
v_23_eggjtwuo = _prev_out[15]
v_25_2my78i7q = _prev_out[16]
v_26_46dlbd1b = _prev_out[17]
v_27_ujgw2f24 = _prev_out[18]
v_29_4ee3qgp7 = _prev_out[19]
v_30_90kai4jz = _prev_out[20]

tvm_result_1 = vm["graph_1"](v_0_ef0pseug, v_1_wbipbwqv, v_3_ses5pulw, v_4_nu11u34v, v_5_1rmfgxqh, v_6_e9wg0ec2, v_9_07zzg9bh, v_11_a6wioi1m, v_13_nxv6g0rx, v_14_020iwq73, v_16_3hojzj3g, v_17_6qt5lz07, v_19_s0hjg44g, v_20_ci2rg2ib, v_21_vq8mcvx0, v_23_eggjtwuo, v_25_2my78i7q, v_26_46dlbd1b, v_27_ujgw2f24, v_29_4ee3qgp7, v_30_90kai4jz)
# Print output
if hasattr(tvm_result_1, 'numpy'):
    _arr = tvm_result_1.numpy()
    print(f"[TVM-OUT] graph_1: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_1)):
        _arr = tvm_result_1[_tvmi].numpy()
        print(f"[TVM-OUT] graph_1[{_tvmi}]: shape={list(_arr.shape)}")

# Chained: graph_1 -> graph_2
_prev_out = tvm_result_1 if not hasattr(tvm_result_1, 'numpy') else [tvm_result_1]
v_0_ef0pseug = _prev_out[0]
v_1_wbipbwqv = _prev_out[1]
v_3_ses5pulw = _prev_out[2]
v_4_nu11u34v = _prev_out[3]
v_5_1rmfgxqh = _prev_out[4]
v_6_e9wg0ec2 = _prev_out[5]
v_9_07zzg9bh = _prev_out[6]
v_11_a6wioi1m = _prev_out[7]
v_13_nxv6g0rx = _prev_out[8]
v_14_020iwq73 = _prev_out[9]
v_16_3hojzj3g = _prev_out[10]
v_17_6qt5lz07 = _prev_out[11]
v_19_s0hjg44g = _prev_out[12]
v_20_ci2rg2ib = _prev_out[13]
v_21_vq8mcvx0 = _prev_out[14]
v_23_eggjtwuo = _prev_out[15]
v_26_46dlbd1b = _prev_out[16]
v_27_ujgw2f24 = _prev_out[17]
v_29_4ee3qgp7 = _prev_out[18]
v_31_zf31by6p = _prev_out[19]
v_33_843judqx = _prev_out[20]
v_35_bcz8fi9g = _prev_out[21]
v_36_y2hqnf6d = _prev_out[22]
v_41_fnf6xzhw = _prev_out[23]
v_42_b6gpp1um = _prev_out[24]
v_45_7rjsjnde = _prev_out[25]
v_46_74vwfjxd = _prev_out[26]
v_48_jrg7uqtk = _prev_out[27]
v_49_q5q37zrg = _prev_out[28]
v_50_inpuz0eo = _prev_out[29]
v_51_16s113xs = _prev_out[30]

tvm_result_2 = vm["graph_2"](v_0_ef0pseug, v_1_wbipbwqv, v_3_ses5pulw, v_4_nu11u34v, v_5_1rmfgxqh, v_6_e9wg0ec2, v_9_07zzg9bh, v_11_a6wioi1m, v_13_nxv6g0rx, v_14_020iwq73, v_16_3hojzj3g, v_17_6qt5lz07, v_19_s0hjg44g, v_20_ci2rg2ib, v_21_vq8mcvx0, v_23_eggjtwuo, v_26_46dlbd1b, v_27_ujgw2f24, v_29_4ee3qgp7, v_31_zf31by6p, v_33_843judqx, v_35_bcz8fi9g, v_36_y2hqnf6d, v_41_fnf6xzhw, v_42_b6gpp1um, v_45_7rjsjnde, v_46_74vwfjxd, v_48_jrg7uqtk, v_49_q5q37zrg, v_50_inpuz0eo, v_51_16s113xs)
# Print output
if hasattr(tvm_result_2, 'numpy'):
    _arr = tvm_result_2.numpy()
    print(f"[TVM-OUT] graph_2: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_2)):
        _arr = tvm_result_2[_tvmi].numpy()
        print(f"[TVM-OUT] graph_2[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
