# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, ):
        v_18_3976w0ih = torch.full((1, 4, 3, 1), 0.0, dtype=torch.float32, device="cpu")
        v_20_eglzyfkr = torch.log(v_18_3976w0ih.float())
        v_28_d5wnwch3 = torch.sum(v_20_eglzyfkr, dim=-1, keepdim=False, dtype=torch.int32).float()
        return v_28_d5wnwch3

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model()

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled()

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise, cast to float for allclose compatibility
    all_match = all(torch.allclose(r.float(), c.float(), atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output.float(), cmp_output.float(), atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
