# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_sr4lagz7, v_1_yblwj6hk, v_2_nejm6td4, v_3_kk7jai5r, v_4_kq84hi2u, v_5_h6qxt7gk, v_6_k5zs9tuu, v_7_ai1skj4p, v_8_ahtw56mq, v_9_jhljefm7, v_10_svadp7vz, v_11_hze9za5b, v_12_3oybcvv5, v_13_ey2vb89w):
        v_14_ftx0iqqf = torch.tanh(v_13_ey2vb89w)
        v_15_hlfq01rl = v_13_ey2vb89w[:max(1, v_13_ey2vb89w.shape[0]//2)]
        v_16_d244sqd3 = torch.tanh(v_13_ey2vb89w)
        v_17_const = torch.zeros((14, 60), dtype=torch.float32, device="cpu")
        v_17_yydbrkoz = torch.div(v_15_hlfq01rl, v_17_const)
        v_18_q3vc6b1s = torch.sum(v_16_d244sqd3, dim=-1, keepdim=False)
        v_19_1ooy6vf0 = F.gelu(v_17_yydbrkoz)
        v_20_const = torch.zeros((14, 60), dtype=torch.float32, device="cpu")
        v_20_w10x1frd = torch.mul(v_17_yydbrkoz, v_20_const)
        v_21_aebyyxzs = torch.zeros((60, 51, 31), dtype=torch.float32, device="cpu")
        v_22_7riyhyoy = torch.sum(v_17_yydbrkoz, dim=-1, keepdim=False)
        v_23_const = torch.zeros((14, 60), dtype=torch.float32, device="cpu")
        v_23_8nq7s20k = torch.sub(v_17_yydbrkoz, v_23_const)
        v_24_ick7dcck = torch.transpose(v_17_yydbrkoz, 0, 1)
        v_25_const = torch.zeros((14, 60), dtype=torch.float32, device="cpu")
        v_25_lt8r51kp = torch.sub(v_17_yydbrkoz, v_25_const)
        v_26_n132xn1y = torch.gather(v_24_ick7dcck, 0, torch.zeros((min(60, 1), min(14, 1)), dtype=torch.int64, device=v_24_ick7dcck.device))
        v_27_q1ixy9rz = F.relu(v_24_ick7dcck)
        v_28_const = torch.zeros((60, 14), dtype=torch.float32, device="cpu")
        v_28_4wrtcnjc = torch.mul(v_24_ick7dcck, v_28_const)
        v_29_zdf0y7it = torch.unsqueeze(v_24_ick7dcck, 0)
        v_30_sfvcvx6b = torch.full((10, 3, 32), 0.0, dtype=torch.float32, device="cpu")
        v_31_cn9b55tv = torch.tile(v_24_ick7dcck, [1] * 2)
        v_32_k9g30rxi = torch.transpose(v_24_ick7dcck, 0, 1)
        v_33_k6o3mgxr = torch.triu(v_24_ick7dcck)
        v_34_const = torch.zeros((60, 14), dtype=torch.float32, device="cpu")
        v_34_x6agrwn3 = torch.pow(v_24_ick7dcck, v_34_const)
        v_35_3fczvc6r = torch.pow(v_24_ick7dcck, v_29_zdf0y7it)
        v_36_n2w9k2rq = torch.exp(v_24_ick7dcck)
        v_37_an2blwbv = v_35_3fczvc6r.to(torch.float32)
        v_38_0bf48ulu = torch.sum(v_35_3fczvc6r, dim=-1, keepdim=False)
        v_39_b4iqge0t = torch.tril(v_37_an2blwbv)
        v_40_const = torch.zeros((1, 60, 14), dtype=torch.float32, device="cpu")
        v_40_vgdshd7y = torch.sub(v_37_an2blwbv, v_40_const)
        v_41_2t303f3z = F.softmax(v_37_an2blwbv, dim=-1)
        v_42_hcm5yn2t = torch.triu(v_37_an2blwbv)
        v_43_4utmeylq = F.silu(v_41_2t303f3z)
        v_44_5w4f2d2k = torch.tanh(v_42_hcm5yn2t)
        v_45_const = torch.zeros((1, 60, 14), dtype=torch.float32, device="cpu")
        v_45_vximw53g = torch.sub(v_42_hcm5yn2t, v_45_const)
        v_46_mosz6ci6 = torch.tril(v_42_hcm5yn2t)
        v_47_const = torch.zeros((1, 60, 14), dtype=torch.float32, device="cpu")
        v_47_v5vpifh8 = torch.pow(v_42_hcm5yn2t, v_47_const)
        v_48_c4rybcgw = torch.min(v_42_hcm5yn2t, dim=-1, keepdim=False).values
        v_49_75gi1vyx = torch.min(v_47_v5vpifh8, dim=-1, keepdim=False).values
        v_50_j1qcsnyx = v_48_c4rybcgw.to(torch.float32)
        v_51_dztj0imt = torch.log(v_48_c4rybcgw)
        v_52_hbvlgxez = torch.zeros((24, 15, 13, 17), dtype=torch.float32, device="cpu")
        v_53_const = torch.zeros((1, 60), dtype=torch.float32, device="cpu")
        v_53_0wyaewkx = torch.mul(v_48_c4rybcgw, v_53_const)
        v_54_490ki4fn = torch.ones((47, 3, 35, 15), dtype=torch.float32, device="cpu")
        v_55_amnhzds2 = torch.max(v_48_c4rybcgw, dim=-1, keepdim=False).values
        v_56_sbq9j9pj = torch.full((14, 37), 0.0, dtype=torch.float32, device="cpu")
        return (v_0_sr4lagz7, v_1_yblwj6hk, v_2_nejm6td4, v_3_kk7jai5r, v_4_kq84hi2u, v_5_h6qxt7gk, v_6_k5zs9tuu, v_7_ai1skj4p, v_8_ahtw56mq, v_9_jhljefm7, v_10_svadp7vz, v_11_hze9za5b, v_12_3oybcvv5, v_14_ftx0iqqf, v_18_q3vc6b1s, v_19_1ooy6vf0, v_20_w10x1frd, v_21_aebyyxzs, v_22_7riyhyoy, v_23_8nq7s20k, v_25_lt8r51kp, v_26_n132xn1y, v_27_q1ixy9rz, v_28_4wrtcnjc, v_30_sfvcvx6b, v_31_cn9b55tv, v_32_k9g30rxi, v_33_k6o3mgxr, v_34_x6agrwn3, v_36_n2w9k2rq, v_38_0bf48ulu, v_39_b4iqge0t, v_40_vgdshd7y, v_43_4utmeylq, v_44_5w4f2d2k, v_45_vximw53g, v_46_mosz6ci6, v_49_75gi1vyx, v_50_j1qcsnyx, v_51_dztj0imt, v_52_hbvlgxez, v_53_0wyaewkx, v_54_490ki4fn, v_55_amnhzds2, v_56_sbq9j9pj)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_sr4lagz7 = torch.randn(5, 4, 37, dtype=torch.float32, device="cpu")
v_1_yblwj6hk = torch.randn(18, 12, 58, dtype=torch.float32, device="cpu")
v_2_nejm6td4 = torch.randn(8, 32, dtype=torch.float32, device="cpu")
v_3_kk7jai5r = torch.randn(4, 11, 15, 40, dtype=torch.float32, device="cpu")
v_4_kq84hi2u = torch.randn(28, 48, 58, dtype=torch.float32, device="cpu")
v_5_h6qxt7gk = torch.randn(17, 19, 22, 13, dtype=torch.float32, device="cpu")
v_6_k5zs9tuu = torch.randn(63, 57, 2, dtype=torch.float32, device="cpu")
v_7_ai1skj4p = torch.randn(62, 32, dtype=torch.float32, device="cpu")
v_8_ahtw56mq = torch.randn(40, 3, dtype=torch.float32, device="cpu")
v_9_jhljefm7 = torch.randn(53, 10, 63, dtype=torch.float32, device="cpu")
v_10_svadp7vz = torch.randn(20, 16, 16, 19, dtype=torch.float32, device="cpu")
v_11_hze9za5b = torch.randn(55, 48, dtype=torch.float32, device="cpu")
v_12_3oybcvv5 = torch.randn(19, 9, 14, 24, dtype=torch.float32, device="cpu")
v_13_ey2vb89w = torch.randn(28, 60, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_sr4lagz7, v_1_yblwj6hk, v_2_nejm6td4, v_3_kk7jai5r, v_4_kq84hi2u, v_5_h6qxt7gk, v_6_k5zs9tuu, v_7_ai1skj4p, v_8_ahtw56mq, v_9_jhljefm7, v_10_svadp7vz, v_11_hze9za5b, v_12_3oybcvv5, v_13_ey2vb89w)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_sr4lagz7, v_1_yblwj6hk, v_2_nejm6td4, v_3_kk7jai5r, v_4_kq84hi2u, v_5_h6qxt7gk, v_6_k5zs9tuu, v_7_ai1skj4p, v_8_ahtw56mq, v_9_jhljefm7, v_10_svadp7vz, v_11_hze9za5b, v_12_3oybcvv5, v_13_ey2vb89w)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
