# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_0_8qubescz_var = relax.Var("v_0_8qubescz", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4, 6]), dtype="float32"))
    with bb.function("graph_0", [v_0_8qubescz_var]):
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_1_htx8j8ll = bb.emit(relax.op.clip(v_0_8qubescz_var, -2.0, 1.49))
        assert str(v_1_htx8j8ll.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_1_htx8j8ll.struct_info.shape}"
        # input: [5, 3, 4, 6], [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_2_ru4un76n = bb.emit(relax.op.divide(relax.op.astype(v_0_8qubescz_var, dtype="float32"), relax.op.astype(v_1_htx8j8ll, dtype="float32")))
        assert str(v_2_ru4un76n.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_2_ru4un76n.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_3_8mqo4h0c = bb.emit(relax.op.multiply(v_1_htx8j8ll, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_1_htx8j8ll))))))
        assert str(v_3_8mqo4h0c.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_3_8mqo4h0c.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4]
        v_4_66w68z2p = bb.emit(relax.op.astype(relax.op.argmax(v_1_htx8j8ll, axis=-1), dtype="float32"))
        assert str(v_4_66w68z2p.struct_info.shape) == "R.shape([5, 3, 4])", f"Shape mismatch: expected R.shape([5, 3, 4]), got {v_4_66w68z2p.struct_info.shape}"
        # input: [5, 3, 4, 6], [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_5_ltthoyld = bb.emit(relax.op.maximum(relax.op.astype(v_3_8mqo4h0c, dtype="float32"), relax.op.astype(v_1_htx8j8ll, dtype="float32")))
        assert str(v_5_ltthoyld.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_5_ltthoyld.struct_info.shape}"
        # input: [5, 3, 4, 6], [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_6_ra9gjtqx = bb.emit(relax.op.multiply(relax.op.astype(v_3_8mqo4h0c, dtype="float32"), relax.op.astype(v_2_ru4un76n, dtype="float32")))
        assert str(v_6_ra9gjtqx.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_6_ra9gjtqx.struct_info.shape}"
        bb.emit_func_output((v_4_66w68z2p, v_5_ltthoyld, v_6_ra9gjtqx))

    v_4_66w68z2p_var = relax.Var("v_4_66w68z2p", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4]), dtype="float32"))
    v_5_ltthoyld_var = relax.Var("v_5_ltthoyld", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4, 6]), dtype="float32"))
    v_6_ra9gjtqx_var = relax.Var("v_6_ra9gjtqx", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4, 6]), dtype="float32"))
    with bb.function("graph_1", [v_4_66w68z2p_var, v_5_ltthoyld_var, v_6_ra9gjtqx_var]):
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4]
        v_7_w5juoeev = bb.emit(relax.op.sum(v_6_ra9gjtqx_var, axis=[-1], keepdims=False))
        assert str(v_7_w5juoeev.struct_info.shape) == "R.shape([5, 3, 4])", f"Shape mismatch: expected R.shape([5, 3, 4]), got {v_7_w5juoeev.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_8_idpfvc6b = bb.emit(relax.op.nn.gelu(v_6_ra9gjtqx_var))
        assert str(v_8_idpfvc6b.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_8_idpfvc6b.struct_info.shape}"
        # input: [5, 3, 4]
        # output: [5, 3, 4]
        v_9_2j2nwr61 = bb.emit(relax.op.tile(v_7_w5juoeev, [1, 1, 1]))
        assert str(v_9_2j2nwr61.struct_info.shape) == "R.shape([5, 3, 4])", f"Shape mismatch: expected R.shape([5, 3, 4]), got {v_9_2j2nwr61.struct_info.shape}"
        # input: 
        # output: [92]
        v_10_scgna6cb = bb.emit(relax.op.arange(0, 92, dtype="float32"))
        assert str(v_10_scgna6cb.struct_info.shape) == "R.shape([92])", f"Shape mismatch: expected R.shape([92]), got {v_10_scgna6cb.struct_info.shape}"
        # input: [5, 3, 4]
        # output: [1, 5, 3, 4]
        v_12_mzuds2dl = bb.emit(relax.op.expand_dims(v_9_2j2nwr61, axis=0))
        assert str(v_12_mzuds2dl.struct_info.shape) == "R.shape([1, 5, 3, 4])", f"Shape mismatch: expected R.shape([1, 5, 3, 4]), got {v_12_mzuds2dl.struct_info.shape}"
        # input: 
        # output: [1]
        v_13_ehdon66x = bb.emit(relax.op.zeros(relax.ShapeExpr([1]), dtype="float32"))
        assert str(v_13_ehdon66x.struct_info.shape) == "R.shape([1])", f"Shape mismatch: expected R.shape([1]), got {v_13_ehdon66x.struct_info.shape}"
        # input: [92], [1]
        # output: [92]
        v_14_ylszo2cb = bb.emit(relax.op.maximum(relax.op.astype(v_10_scgna6cb, dtype="float32"), relax.op.astype(v_13_ehdon66x, dtype="float32")))
        assert str(v_14_ylszo2cb.struct_info.shape) == "R.shape([92])", f"Shape mismatch: expected R.shape([92]), got {v_14_ylszo2cb.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_15_9gul18fs = bb.emit(relax.op.tril(v_5_ltthoyld_var))
        assert str(v_15_9gul18fs.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_15_9gul18fs.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 8, 12]
        v_16_r85i09tr = bb.emit(relax.op.image.resize2d(v_15_9gul18fs, relax.ShapeExpr([8, 12]), layout="NCHW"))
        assert str(v_16_r85i09tr.struct_info.shape) == "R.shape([5, 3, 8, 12])", f"Shape mismatch: expected R.shape([5, 3, 8, 12]), got {v_16_r85i09tr.struct_info.shape}"
        # input: [1]
        # output: [1]
        v_17_it2n9tx2 = bb.emit(relax.op.rsqrt(relax.op.astype(v_13_ehdon66x, dtype="float32")))
        assert str(v_17_it2n9tx2.struct_info.shape) == "R.shape([1])", f"Shape mismatch: expected R.shape([1]), got {v_17_it2n9tx2.struct_info.shape}"
        bb.emit_func_output((v_4_66w68z2p_var, v_8_idpfvc6b, v_12_mzuds2dl, v_14_ylszo2cb, v_16_r85i09tr, v_17_it2n9tx2))

    v_4_66w68z2p_var = relax.Var("v_4_66w68z2p", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4]), dtype="float32"))
    v_8_idpfvc6b_var = relax.Var("v_8_idpfvc6b", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4, 6]), dtype="float32"))
    v_12_mzuds2dl_var = relax.Var("v_12_mzuds2dl", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 3, 4]), dtype="float32"))
    v_14_ylszo2cb_var = relax.Var("v_14_ylszo2cb", relax.TensorStructInfo(shape=relax.ShapeExpr([92]), dtype="float32"))
    v_16_r85i09tr_var = relax.Var("v_16_r85i09tr", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 8, 12]), dtype="float32"))
    v_17_it2n9tx2_var = relax.Var("v_17_it2n9tx2", relax.TensorStructInfo(shape=relax.ShapeExpr([1]), dtype="float32"))
    with bb.function("graph_2", [v_4_66w68z2p_var, v_8_idpfvc6b_var, v_12_mzuds2dl_var, v_14_ylszo2cb_var, v_16_r85i09tr_var, v_17_it2n9tx2_var]):
        # input: [1]
        # output: []
        v_18_b6lcx44f = bb.emit(relax.op.astype(relax.op.argmin(v_17_it2n9tx2_var, axis=-1), dtype="float32"))
        assert str(v_18_b6lcx44f.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_18_b6lcx44f.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 6, 4]
        v_19_svi5n0eo = bb.emit(relax.op.permute_dims(v_8_idpfvc6b_var, axes=[0, 1, 3, 2]))
        assert str(v_19_svi5n0eo.struct_info.shape) == "R.shape([5, 3, 6, 4])", f"Shape mismatch: expected R.shape([5, 3, 6, 4]), got {v_19_svi5n0eo.struct_info.shape}"
        # input: [1]
        # output: [1]
        v_20_u5nd9kuh = bb.emit(relax.op.clip(v_17_it2n9tx2_var, -0.75, 1.19))
        assert str(v_20_u5nd9kuh.struct_info.shape) == "R.shape([1])", f"Shape mismatch: expected R.shape([1]), got {v_20_u5nd9kuh.struct_info.shape}"
        # input: [5, 3, 8, 12]
        # output: [5, 3, 8, 12]
        v_21_jsu6wqko = bb.emit(relax.op.tril(v_16_r85i09tr_var))
        assert str(v_21_jsu6wqko.struct_info.shape) == "R.shape([5, 3, 8, 12])", f"Shape mismatch: expected R.shape([5, 3, 8, 12]), got {v_21_jsu6wqko.struct_info.shape}"
        # input: [5, 3, 4, 6]
        # output: [5, 3, 4, 6]
        v_22_ai15t5l6 = bb.emit(relax.op.tril(v_8_idpfvc6b_var))
        assert str(v_22_ai15t5l6.struct_info.shape) == "R.shape([5, 3, 4, 6])", f"Shape mismatch: expected R.shape([5, 3, 4, 6]), got {v_22_ai15t5l6.struct_info.shape}"
        # input: [5, 3, 8, 12]
        # output: [5, 3, 8, 12]
        v_24_eba53j5f = bb.emit(relax.op.where(relax.op.greater_equal(v_21_jsu6wqko, relax.const(0, dtype="float32")), v_21_jsu6wqko, relax.op.multiply(relax.const(1.25, dtype="float32"), relax.op.subtract(relax.op.exp(v_21_jsu6wqko), relax.const(1.0, dtype="float32")))))
        assert str(v_24_eba53j5f.struct_info.shape) == "R.shape([5, 3, 8, 12])", f"Shape mismatch: expected R.shape([5, 3, 8, 12]), got {v_24_eba53j5f.struct_info.shape}"
        # input: [5, 3, 8, 12]
        # output: [5, 3, 8, 12]
        v_26_clw87c7l = bb.emit(relax.op.sqrt(relax.op.astype(v_21_jsu6wqko, dtype="float32")))
        assert str(v_26_clw87c7l.struct_info.shape) == "R.shape([5, 3, 8, 12])", f"Shape mismatch: expected R.shape([5, 3, 8, 12]), got {v_26_clw87c7l.struct_info.shape}"
        # input: [5, 3, 8, 12]
        # output: [2, 3, 8, 12]
        v_27_mwcz13wh = bb.emit(relax.op.strided_slice(v_21_jsu6wqko, axes=[0], begin=[0], end=[2]))
        assert str(v_27_mwcz13wh.struct_info.shape) == "R.shape([2, 3, 8, 12])", f"Shape mismatch: expected R.shape([2, 3, 8, 12]), got {v_27_mwcz13wh.struct_info.shape}"
        bb.emit_func_output((v_4_66w68z2p_var, v_12_mzuds2dl_var, v_14_ylszo2cb_var, v_18_b6lcx44f, v_19_svi5n0eo, v_20_u5nd9kuh, v_22_ai15t5l6, v_24_eba53j5f, v_26_clw87c7l, v_27_mwcz13wh))

    v_4_66w68z2p_var = relax.Var("v_4_66w68z2p", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4]), dtype="float32"))
    v_12_mzuds2dl_var = relax.Var("v_12_mzuds2dl", relax.TensorStructInfo(shape=relax.ShapeExpr([1, 5, 3, 4]), dtype="float32"))
    v_14_ylszo2cb_var = relax.Var("v_14_ylszo2cb", relax.TensorStructInfo(shape=relax.ShapeExpr([92]), dtype="float32"))
    v_18_b6lcx44f_var = relax.Var("v_18_b6lcx44f", relax.TensorStructInfo(shape=relax.ShapeExpr([]), dtype="float32"))
    v_19_svi5n0eo_var = relax.Var("v_19_svi5n0eo", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 6, 4]), dtype="float32"))
    v_20_u5nd9kuh_var = relax.Var("v_20_u5nd9kuh", relax.TensorStructInfo(shape=relax.ShapeExpr([1]), dtype="float32"))
    v_22_ai15t5l6_var = relax.Var("v_22_ai15t5l6", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 4, 6]), dtype="float32"))
    v_24_eba53j5f_var = relax.Var("v_24_eba53j5f", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 8, 12]), dtype="float32"))
    v_26_clw87c7l_var = relax.Var("v_26_clw87c7l", relax.TensorStructInfo(shape=relax.ShapeExpr([5, 3, 8, 12]), dtype="float32"))
    v_27_mwcz13wh_var = relax.Var("v_27_mwcz13wh", relax.TensorStructInfo(shape=relax.ShapeExpr([2, 3, 8, 12]), dtype="float32"))
    v_28_k44at8af_var = relax.Var("v_28_k44at8af", relax.TensorStructInfo(shape=relax.ShapeExpr([3, 4]), dtype="float32"))
    with bb.function("graph_3", [v_4_66w68z2p_var, v_12_mzuds2dl_var, v_14_ylszo2cb_var, v_18_b6lcx44f_var, v_19_svi5n0eo_var, v_20_u5nd9kuh_var, v_22_ai15t5l6_var, v_24_eba53j5f_var, v_26_clw87c7l_var, v_27_mwcz13wh_var, v_28_k44at8af_var]):
        # input: [3, 4]
        # output: [1, 3, 4]
        v_29_ees4adsv = bb.emit(relax.op.expand_dims(v_28_k44at8af_var, axis=0))
        assert str(v_29_ees4adsv.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_29_ees4adsv.struct_info.shape}"
        # input: [3, 4]
        # output: [3, 4]
        v_30_jju2b8hb = bb.emit(relax.op.where(relax.op.greater_equal(v_28_k44at8af_var, relax.const(0, dtype="float32")), v_28_k44at8af_var, relax.op.multiply(relax.const(1.5, dtype="float32"), relax.op.subtract(relax.op.exp(v_28_k44at8af_var), relax.const(1.0, dtype="float32")))))
        assert str(v_30_jju2b8hb.struct_info.shape) == "R.shape([3, 4])", f"Shape mismatch: expected R.shape([3, 4]), got {v_30_jju2b8hb.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_31_iyv15tip = bb.emit(relax.op.tril(v_29_ees4adsv))
        assert str(v_31_iyv15tip.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_31_iyv15tip.struct_info.shape}"
        # input: [3, 4]
        # output: [3, 4]
        v_32_x1am8ppa = bb.emit(relax.op.nn.layer_norm(v_30_jju2b8hb, gamma=relax.op.ones(relax.ShapeExpr([4]), dtype="float32"), beta=relax.op.zeros(relax.ShapeExpr([4]), dtype="float32"), axes=[-1]))
        assert str(v_32_x1am8ppa.struct_info.shape) == "R.shape([3, 4])", f"Shape mismatch: expected R.shape([3, 4]), got {v_32_x1am8ppa.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_33_fg1fadp8 = bb.emit(relax.op.strided_slice(v_31_iyv15tip, axes=[0], begin=[0], end=[1]))
        assert str(v_33_fg1fadp8.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_33_fg1fadp8.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3]
        v_34_4a1ym4pe = bb.emit(relax.op.sum(v_31_iyv15tip, axis=[-1], keepdims=False))
        assert str(v_34_4a1ym4pe.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_34_4a1ym4pe.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_35_51ct2o0o = bb.emit(relax.op.clip(v_31_iyv15tip, -0.88, 0.66))
        assert str(v_35_51ct2o0o.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_35_51ct2o0o.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_36_ygwlone7 = bb.emit(relax.op.exp(relax.op.astype(v_34_4a1ym4pe, dtype="float32")))
        assert str(v_36_ygwlone7.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_36_ygwlone7.struct_info.shape}"
        # input: [1, 3, 4]
        # output: [1, 3, 4]
        v_37_67miy28s = bb.emit(relax.op.cumsum(v_35_51ct2o0o, axis=-1))
        assert str(v_37_67miy28s.struct_info.shape) == "R.shape([1, 3, 4])", f"Shape mismatch: expected R.shape([1, 3, 4]), got {v_37_67miy28s.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_38_bbtp59i3 = bb.emit(relax.op.round(v_36_ygwlone7))
        assert str(v_38_bbtp59i3.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_38_bbtp59i3.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_39_6scmxpb3 = bb.emit(relax.op.rsqrt(relax.op.astype(v_36_ygwlone7, dtype="float32")))
        assert str(v_39_6scmxpb3.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_39_6scmxpb3.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_40_3gy7m54c = bb.emit(relax.op.nn.log_softmax(relax.op.astype(v_38_bbtp59i3, dtype="float32"), axis=-1))
        assert str(v_40_3gy7m54c.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_40_3gy7m54c.struct_info.shape}"
        # input: [1, 3]
        # output: [1, 3]
        v_41_aroldbsn = bb.emit(relax.op.nn.gelu(v_38_bbtp59i3))
        assert str(v_41_aroldbsn.struct_info.shape) == "R.shape([1, 3])", f"Shape mismatch: expected R.shape([1, 3]), got {v_41_aroldbsn.struct_info.shape}"
        bb.emit_func_output((v_4_66w68z2p_var, v_12_mzuds2dl_var, v_14_ylszo2cb_var, v_18_b6lcx44f_var, v_19_svi5n0eo_var, v_20_u5nd9kuh_var, v_22_ai15t5l6_var, v_24_eba53j5f_var, v_26_clw87c7l_var, v_27_mwcz13wh_var, v_32_x1am8ppa, v_33_fg1fadp8, v_37_67miy28s, v_39_6scmxpb3, v_40_3gy7m54c, v_41_aroldbsn))

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)

# === Cross-target differential mode: CPU vs GPU ===
ex_cpu = relax.build(mod, target="llvm")
vm_cpu = relax.VirtualMachine(ex_cpu, tvm.cpu())
ex_gpu = relax.build(mod, target="cuda")
vm_gpu = relax.VirtualMachine(ex_gpu, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_0_8qubescz = np.random.uniform(0.0, 1.0, size=(5, 3, 4, 6)).astype(np.float32)
v_0_8qubescz_cpu = tvm.runtime.tensor(np_v_0_8qubescz)
v_0_8qubescz_gpu = tvm.runtime.tensor(np_v_0_8qubescz, device=tvm.cuda())

# CPU execution
tvm_result_cpu_0 = vm_cpu["graph_0"](v_0_8qubescz_cpu)
# GPU execution
tvm_result_gpu_0 = vm_gpu["graph_0"](v_0_8qubescz_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_0
_gpu_val = tvm_result_gpu_0
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_0: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_0: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_0: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_0[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_0[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Chained: graph_0 -> graph_1
_prev_cpu = tvm_result_cpu_0
_prev_gpu = tvm_result_gpu_0
v_4_66w68z2p_cpu = _prev_cpu[0]
v_4_66w68z2p_gpu = _prev_gpu[0]
v_5_ltthoyld_cpu = _prev_cpu[1]
v_5_ltthoyld_gpu = _prev_gpu[1]
v_6_ra9gjtqx_cpu = _prev_cpu[2]
v_6_ra9gjtqx_gpu = _prev_gpu[2]

# CPU execution
tvm_result_cpu_1 = vm_cpu["graph_1"](v_4_66w68z2p_cpu, v_5_ltthoyld_cpu, v_6_ra9gjtqx_cpu)
# GPU execution
tvm_result_gpu_1 = vm_gpu["graph_1"](v_4_66w68z2p_gpu, v_5_ltthoyld_gpu, v_6_ra9gjtqx_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_1
_gpu_val = tvm_result_gpu_1
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_1: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_1: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_1: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_1[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_1[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Chained: graph_1 -> graph_2
_prev_cpu = tvm_result_cpu_1
_prev_gpu = tvm_result_gpu_1
v_4_66w68z2p_cpu = _prev_cpu[0]
v_4_66w68z2p_gpu = _prev_gpu[0]
v_8_idpfvc6b_cpu = _prev_cpu[1]
v_8_idpfvc6b_gpu = _prev_gpu[1]
v_12_mzuds2dl_cpu = _prev_cpu[2]
v_12_mzuds2dl_gpu = _prev_gpu[2]
v_14_ylszo2cb_cpu = _prev_cpu[3]
v_14_ylszo2cb_gpu = _prev_gpu[3]
v_16_r85i09tr_cpu = _prev_cpu[4]
v_16_r85i09tr_gpu = _prev_gpu[4]
v_17_it2n9tx2_cpu = _prev_cpu[5]
v_17_it2n9tx2_gpu = _prev_gpu[5]

# CPU execution
tvm_result_cpu_2 = vm_cpu["graph_2"](v_4_66w68z2p_cpu, v_8_idpfvc6b_cpu, v_12_mzuds2dl_cpu, v_14_ylszo2cb_cpu, v_16_r85i09tr_cpu, v_17_it2n9tx2_cpu)
# GPU execution
tvm_result_gpu_2 = vm_gpu["graph_2"](v_4_66w68z2p_gpu, v_8_idpfvc6b_gpu, v_12_mzuds2dl_gpu, v_14_ylszo2cb_gpu, v_16_r85i09tr_gpu, v_17_it2n9tx2_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_2
_gpu_val = tvm_result_gpu_2
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_2: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_2: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_2: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_2[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_2[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')

# Generate fresh inputs for graph_3
np_v_28_k44at8af = np.random.uniform(0.0, 1.0, size=(3, 4)).astype(np.float32)
v_28_k44at8af_cpu = tvm.runtime.tensor(np_v_28_k44at8af)
v_28_k44at8af_gpu = tvm.runtime.tensor(np_v_28_k44at8af, device=tvm.cuda())

# Chained: graph_2 -> graph_3
_prev_cpu = tvm_result_cpu_2
_prev_gpu = tvm_result_gpu_2
v_4_66w68z2p_cpu = _prev_cpu[0]
v_4_66w68z2p_gpu = _prev_gpu[0]
v_12_mzuds2dl_cpu = _prev_cpu[1]
v_12_mzuds2dl_gpu = _prev_gpu[1]
v_14_ylszo2cb_cpu = _prev_cpu[2]
v_14_ylszo2cb_gpu = _prev_gpu[2]
v_18_b6lcx44f_cpu = _prev_cpu[3]
v_18_b6lcx44f_gpu = _prev_gpu[3]
v_19_svi5n0eo_cpu = _prev_cpu[4]
v_19_svi5n0eo_gpu = _prev_gpu[4]
v_20_u5nd9kuh_cpu = _prev_cpu[5]
v_20_u5nd9kuh_gpu = _prev_gpu[5]
v_22_ai15t5l6_cpu = _prev_cpu[6]
v_22_ai15t5l6_gpu = _prev_gpu[6]
v_24_eba53j5f_cpu = _prev_cpu[7]
v_24_eba53j5f_gpu = _prev_gpu[7]
v_26_clw87c7l_cpu = _prev_cpu[8]
v_26_clw87c7l_gpu = _prev_gpu[8]
v_27_mwcz13wh_cpu = _prev_cpu[9]
v_27_mwcz13wh_gpu = _prev_gpu[9]

# CPU execution
tvm_result_cpu_3 = vm_cpu["graph_3"](v_4_66w68z2p_cpu, v_12_mzuds2dl_cpu, v_14_ylszo2cb_cpu, v_18_b6lcx44f_cpu, v_19_svi5n0eo_cpu, v_20_u5nd9kuh_cpu, v_22_ai15t5l6_cpu, v_24_eba53j5f_cpu, v_26_clw87c7l_cpu, v_27_mwcz13wh_cpu, v_28_k44at8af_cpu)
# GPU execution
tvm_result_gpu_3 = vm_gpu["graph_3"](v_4_66w68z2p_gpu, v_12_mzuds2dl_gpu, v_14_ylszo2cb_gpu, v_18_b6lcx44f_gpu, v_19_svi5n0eo_gpu, v_20_u5nd9kuh_gpu, v_22_ai15t5l6_gpu, v_24_eba53j5f_gpu, v_26_clw87c7l_gpu, v_27_mwcz13wh_gpu, v_28_k44at8af_gpu)
# Compare CPU vs GPU outputs
_cpu_val = tvm_result_cpu_3
_gpu_val = tvm_result_gpu_3
if hasattr(_cpu_val, 'numpy'):
    _cpu_arr = _cpu_val.numpy()
    _gpu_arr = _gpu_val.numpy()
    if _cpu_arr.shape != _gpu_arr.shape:
        print(f'[DIFF-MISMATCH] graph_3: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
    else:
        _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
        if _max_diff > 1e-3:
            print(f'[DIFF-MISMATCH] graph_3: CPU vs GPU mismatch, max_diff={_max_diff}')
        else:
            print(f'[TVM-OUT] graph_3: shape={list(_cpu_arr.shape)} (CPU=GPU match)')
else:
    # tvm.runtime.Array (multi-output container)
    for _ci in range(len(_cpu_val)):
        _cpu_arr = _cpu_val[_ci].numpy()
        _gpu_arr = _gpu_val[_ci].numpy()
        if _cpu_arr.shape != _gpu_arr.shape:
            print(f'[DIFF-MISMATCH] graph_3[{_ci}]: shape mismatch CPU={list(_cpu_arr.shape)} GPU={list(_gpu_arr.shape)}')
        else:
            _max_diff = float(np.max(np.abs(_cpu_arr.astype(np.float64) - _gpu_arr.astype(np.float64))))
            if _max_diff > 1e-3:
                print(f'[DIFF-MISMATCH] graph_3[{_ci}]: CPU vs GPU mismatch, max_diff={_max_diff}')
print("Execution: OK")
