# Auto-generated by aiFuzzer

import tvm
from tvm import relax
from tvm.ir.module import IRModule
import numpy as np

def build_mod():
    bb = relax.BlockBuilder()

    v_1_nakcrlja_var = relax.Var("v_1_nakcrlja", relax.TensorStructInfo(shape=relax.ShapeExpr([6, 6]), dtype="float32"))
    with bb.function("graph_0", [v_1_nakcrlja_var]):
        # input: [6, 6]
        # output: [6, 6]
        v_5_g1h2ncu8 = bb.emit(relax.op.rsqrt(relax.op.astype(v_1_nakcrlja_var, dtype="float32")))
        assert str(v_5_g1h2ncu8.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_5_g1h2ncu8.struct_info.shape}"
        # input: [6, 6]
        # output: [6, 6]
        v_7_yzk2x91n = bb.emit(relax.op.sigmoid(v_5_g1h2ncu8))
        assert str(v_7_yzk2x91n.struct_info.shape) == "R.shape([6, 6])", f"Shape mismatch: expected R.shape([6, 6]), got {v_7_yzk2x91n.struct_info.shape}"
        # input: [6, 6]
        # output: [6]
        v_9_68vpx57c = bb.emit(relax.op.mean(v_7_yzk2x91n, axis=[-1], keepdims=False))
        assert str(v_9_68vpx57c.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_9_68vpx57c.struct_info.shape}"
        # input: [6]
        # output: []
        v_11_ehuyjkij = bb.emit(relax.op.mean(v_9_68vpx57c, axis=[-1], keepdims=False))
        assert str(v_11_ehuyjkij.struct_info.shape) == "R.shape([])", f"Shape mismatch: expected R.shape([]), got {v_11_ehuyjkij.struct_info.shape}"
        # input: [6]
        # output: [6]
        v_12_vh7yvfwa = bb.emit(relax.op.multiply(v_9_68vpx57c, relax.op.tanh(relax.op.log(relax.op.add(relax.const(1.0, dtype="float32"), relax.op.exp(v_9_68vpx57c))))))
        assert str(v_12_vh7yvfwa.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_12_vh7yvfwa.struct_info.shape}"
        # input: [6], []
        # output: [6]
        v_14_gy1kwaqp = bb.emit(relax.op.divide(relax.op.astype(v_12_vh7yvfwa, dtype="float32"), relax.op.astype(v_11_ehuyjkij, dtype="float32")))
        assert str(v_14_gy1kwaqp.struct_info.shape) == "R.shape([6])", f"Shape mismatch: expected R.shape([6]), got {v_14_gy1kwaqp.struct_info.shape}"
        # input: [6]
        # output: [1, 6]
        v_16_l568meiu = bb.emit(relax.op.expand_dims(v_14_gy1kwaqp, axis=0))
        assert str(v_16_l568meiu.struct_info.shape) == "R.shape([1, 6])", f"Shape mismatch: expected R.shape([1, 6]), got {v_16_l568meiu.struct_info.shape}"
        bb.emit_func_output(v_16_l568meiu)

    mod = bb.get()
    return mod


mod = build_mod()
print('Module built successfully')
# print(mod)


# === Execute compiled module (chained graphs) ===
np.random.seed(42)
ex = relax.build(mod, target="cuda")
vm = relax.VirtualMachine(ex, tvm.cuda())

# Generate fresh inputs for graph_0
np_v_1_nakcrlja = np.random.uniform(0.0, 1.0, size=(6, 6)).astype(np.float32)
v_1_nakcrlja = tvm.runtime.tensor(np_v_1_nakcrlja, device=tvm.cuda())

tvm_result_0 = vm["graph_0"](v_1_nakcrlja)
# Print output
if hasattr(tvm_result_0, 'numpy'):
    _arr = tvm_result_0.numpy()
    print(f"[TVM-OUT] graph_0: shape={list(_arr.shape)}")
else:
    for _tvmi in range(len(tvm_result_0)):
        _arr = tvm_result_0[_tvmi].numpy()
        print(f"[TVM-OUT] graph_0[{_tvmi}]: shape={list(_arr.shape)}")
print("Execution: OK")
