# Auto-generated by aiFuzzer PyTorch translator

import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule_0(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, v_0_rpy14hq3, v_1_f8faldik, v_2_14d11tye, v_3_gznrxlw1, v_4_y9m9u02d, v_5_l4owroqm, v_6_gmy608cq):
        v_7_v3yqxjom = torch.transpose(v_6_gmy608cq, 1, 2)
        v_8_308siqkn = torch.log2(v_6_gmy608cq)
        v_9_3w5ei8af = F.softmax(v_6_gmy608cq, dim=-1)
        v_10_twflf1tt = torch.reciprocal(v_6_gmy608cq)
        v_11_vrv10d4t = torch.mean(v_6_gmy608cq.float(), dim=-1, keepdim=False)
        v_12_mrhifmnv = torch.log2(v_6_gmy608cq)
        v_13_const = torch.zeros((23, 64), dtype=torch.float32, device="cpu")
        v_13_8m6vacli = torch.mul(v_11_vrv10d4t, v_13_const)
        v_14_r5wk8p2y = torch.round(v_12_mrhifmnv)
        v_15_ptpmtgte = torch.reciprocal(v_12_mrhifmnv)
        v_16_xwdpbqkt = torch.log2(v_12_mrhifmnv)
        v_17_const = torch.zeros((23, 64, 62), dtype=torch.float32, device="cpu")
        v_17_ggd7uyz3 = torch.sub(v_12_mrhifmnv, v_17_const)
        v_18_mfyn7p89 = torch.div(v_12_mrhifmnv, v_16_xwdpbqkt)
        v_19_v1qk3wse = torch.min(v_17_ggd7uyz3, dim=-1, keepdim=False).values
        v_20_zt2grtqu = F.gelu(v_18_mfyn7p89)
        v_21_bcdr4mbl = torch.sum(v_19_v1qk3wse, dim=-1, keepdim=False)
        v_22_lzr41zty = torch.sign(v_20_zt2grtqu)
        v_23_72nv70ab = torch.minimum(v_20_zt2grtqu, v_14_r5wk8p2y)
        v_24_ll9yfvqp = torch.sigmoid(v_22_lzr41zty)
        v_25_azsv0qk9 = torch.sigmoid(v_23_72nv70ab)
        v_26_idj9omsn = F.mish(v_23_72nv70ab)
        v_27_cudcqg3h = torch.sigmoid(v_23_72nv70ab)
        v_28_63db36e9 = torch.gather(v_23_72nv70ab, 0, torch.zeros((min(23, 1), min(64, 1), min(62, 1)), dtype=torch.int64, device=v_23_72nv70ab.device))
        v_29_mhsjl0cy = torch.sign(v_23_72nv70ab)
        v_30_g8oc2kj9 = F.selu(v_23_72nv70ab)
        v_31_mv8r3aam = torch.exp(v_23_72nv70ab)
        v_32_13b282qg = torch.sigmoid(v_23_72nv70ab)
        v_33_ab99nd4v = torch.transpose(v_31_mv8r3aam, 1, 2)
        v_34_s5jn8amr = torch.mul(v_32_13b282qg, v_12_mrhifmnv)
        v_35_xm88lg9x = torch.floor(v_33_ab99nd4v)
        v_36_ro8i2vay = torch.transpose(v_33_ab99nd4v, 1, 2)
        v_37_23cvz2fk = torch.floor(v_33_ab99nd4v)
        v_38_8mwnxfd2 = torch.gather(v_36_ro8i2vay, 0, torch.zeros((min(23, 1), min(64, 1), min(62, 1)), dtype=torch.int64, device=v_36_ro8i2vay.device))
        v_39_svrpznbu = torch.sqrt(v_36_ro8i2vay)
        v_40_f53vnxzg = torch.clamp(v_38_8mwnxfd2, min=-0.2, max=0.79)
        v_41_skua8ziy = torch.log2(v_38_8mwnxfd2)
        v_42_j5bgl78r = F.relu(v_38_8mwnxfd2)
        v_43_ys5uicgh = torch.mul(v_41_skua8ziy, v_29_mhsjl0cy)
        v_44_ggybgxcg = torch.zeros((27, 28), dtype=torch.float32, device="cpu")
        v_45_4jzl23tw = torch.tanh(v_42_j5bgl78r)
        v_46_x9q5vnp3 = F.relu(v_44_ggybgxcg)
        v_47_pwz9hnbl = torch.round(v_44_ggybgxcg)
        v_48_zl510n7q = torch.log2(v_44_ggybgxcg)
        v_49_hodfkap4 = torch.sigmoid(v_44_ggybgxcg)
        v_50_lltenz5m = torch.arange(0, 163, dtype=torch.float32, device="cpu")
        v_51_mguiwg7v = torch.maximum(v_44_ggybgxcg, v_46_x9q5vnp3)
        v_52_m05pjab4 = torch.full((17, 2, 45, 49), 0.0, dtype=torch.float32, device="cpu")
        v_53_iv325cie = torch.tril(v_44_ggybgxcg)
        v_54_eczbug4j = torch.sigmoid(v_44_ggybgxcg)
        v_55_bxlvorbw = torch.round(v_53_iv325cie)
        v_56_q8rvhxbp = F.relu(v_54_eczbug4j)
        v_57_gijvf3e4 = F.mish(v_54_eczbug4j)
        v_58_8s45t9v5 = torch.max(v_56_q8rvhxbp, dim=-1, keepdim=False).values
        v_59_6o0kzwel = F.elu(v_57_gijvf3e4, alpha=1.1)
        v_60_3ifd3e1c = torch.arange(0, 98, dtype=torch.float32, device="cpu")
        v_61_const = torch.zeros((27), dtype=torch.float32, device="cpu")
        v_61_7lpah3ul = torch.minimum(v_58_8s45t9v5, v_61_const)
        v_62_0thwlfik = torch.log2(v_60_3ifd3e1c)
        v_63_1bnp54mg = torch.ceil(v_60_3ifd3e1c)
        v_64_q1xa9e6g = torch.exp(v_60_3ifd3e1c)
        v_65_ti19gf2z = torch.gather(v_60_3ifd3e1c, 0, torch.zeros((min(98, 1)), dtype=torch.int64, device=v_60_3ifd3e1c.device))
        v_66_xkxgrk32 = torch.reciprocal(v_60_3ifd3e1c)
        v_67_tl60etah = F.softmax(v_60_3ifd3e1c, dim=-1)
        v_68_4o056i6t = torch.neg(v_60_3ifd3e1c)
        v_69_lv8w66cb = F.leaky_relu(v_67_tl60etah, negative_slope=0.06)
        v_70_u15507v6 = torch.zeros((56, 28), dtype=torch.float32, device="cpu")
        v_71_c4rtkjir = torch.sigmoid(v_69_lv8w66cb)
        v_72_const = torch.zeros((98), dtype=torch.float32, device="cpu")
        v_72_9574115m = torch.div(v_69_lv8w66cb, v_72_const)
        return (v_0_rpy14hq3, v_1_f8faldik, v_2_14d11tye, v_3_gznrxlw1, v_4_y9m9u02d, v_5_l4owroqm, v_7_v3yqxjom, v_8_308siqkn, v_9_3w5ei8af, v_10_twflf1tt, v_13_8m6vacli, v_15_ptpmtgte, v_21_bcdr4mbl, v_24_ll9yfvqp, v_25_azsv0qk9, v_26_idj9omsn, v_27_cudcqg3h, v_28_63db36e9, v_30_g8oc2kj9, v_34_s5jn8amr, v_35_xm88lg9x, v_37_23cvz2fk, v_39_svrpznbu, v_40_f53vnxzg, v_43_ys5uicgh, v_45_4jzl23tw, v_47_pwz9hnbl, v_48_zl510n7q, v_49_hodfkap4, v_50_lltenz5m, v_51_mguiwg7v, v_52_m05pjab4, v_55_bxlvorbw, v_59_6o0kzwel, v_61_7lpah3ul, v_62_0thwlfik, v_63_1bnp54mg, v_64_q1xa9e6g, v_65_ti19gf2z, v_66_xkxgrk32, v_68_4o056i6t, v_70_u15507v6, v_71_c4rtkjir, v_72_9574115m)

# Main execution
model = TestModule_0()

# Generate random inputs for verification
torch.manual_seed(42)
v_0_rpy14hq3 = torch.randn(35, 12, 54, dtype=torch.float32, device="cpu")
v_1_f8faldik = torch.randn(27, 24, 5, dtype=torch.float32, device="cpu")
v_2_14d11tye = torch.randn(16, 17, 11, 21, dtype=torch.float32, device="cpu")
v_3_gznrxlw1 = torch.randn(20, 41, dtype=torch.float32, device="cpu")
v_4_y9m9u02d = torch.randn(31, 15, dtype=torch.float32, device="cpu")
v_5_l4owroqm = torch.randn(7, 32, 12, dtype=torch.float32, device="cpu")
v_6_gmy608cq = torch.randn(23, 64, 62, dtype=torch.float32, device="cpu")

# Eager execution (ground truth)
with torch.no_grad():
    ref_output = model(v_0_rpy14hq3, v_1_f8faldik, v_2_14d11tye, v_3_gznrxlw1, v_4_y9m9u02d, v_5_l4owroqm, v_6_gmy608cq)

# Compiled execution
try:
    compiled = torch.compile(model, mode="default")
except Exception as e:
    print(f'torch.compile failed: {e}')
    raise

with torch.no_grad():
    cmp_output = compiled(v_0_rpy14hq3, v_1_f8faldik, v_2_14d11tye, v_3_gznrxlw1, v_4_y9m9u02d, v_5_l4owroqm, v_6_gmy608cq)

# Differential testing: eager vs compile
if isinstance(ref_output, tuple):
    # Multi-output: compare element-wise
    all_match = all(torch.allclose(r, c, atol=1e-3, rtol=1e-3, equal_nan=True)
                    for r, c in zip(ref_output, cmp_output))
else:
    all_match = torch.allclose(ref_output, cmp_output, atol=1e-3, rtol=1e-3, equal_nan=True)

if all_match:
    print('VERIFY: PASS')
else:
    raise RuntimeError('VERIFY: FAIL')


print('Module built successfully')
